### ISSUE TITLE
[playable] Risk of Rain

### ISSUE THREAD

**Issue by voltagex** [ptitSeb/box86#100]
Risk of Rain from GOG works just fine on a Pi 4 with 9422039

Thought I better log some playable games - if you give me access to label issues I could start marking things as playable etc @ptitSeb

**Comment by ptitSeb** [comment]
I don't know how to give access to Labels. So created the label Working...

**Comment by voltagex** [comment]
Looks like I need write access - https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests
