### ISSUE TITLE
Error loading needed lib: "libstdc++.so.6"

### ISSUE THREAD

**Issue by forcie** [ptitSeb/box86#101]
Hi,

Trying to run utorrent server for Debian 7 32-bit (https://www.utorrent.com/downloads/linux).
I get the following output. I'm not sure what to do from here.

> ./box86 utorrent-server-alpha-v3_3/utserver
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 27 Env var
Looking for utorrent-server-alpha-v3_3/utserver
Using native(wrapped) libssl.so.1
Using native(wrapped) libcrypto.so.1
Using native(wrapped) libresolv.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Error loading needed lib: "libstdc++.so.6"
Error: loading needed libs in elf utorrent-server-alpha-v3_3/utserver

Thanks in advance for any pointer to make progress.

**Comment by ptitSeb** [comment]
you can install box86 int the system with `sudo make install`: that way, box86 is launched itself and the libstdc++ as well as libgcc_s are installed too.
If you prefer not to, that lib is `x86lib` folder from box86 repo, so use `BOX86_LD_LIBRARY_PATH=/PATH/TO/box86/x86lib`

**Comment by ptitSeb** [comment]
Is this solved? Can the ticket be closed?

**Comment by Andryshik345** [comment]
custom var is worked for me
