### ISSUE TITLE
"home/user/Desktop/example.86_64 is not an executable file"

### ISSUE THREAD

**Issue by GalaxiumNation** [ptitSeb/box86#1017]
(Raspberry Pi OS (Legacy, 64-bit) Full on a Raspberry Pi 3b v1.2)

I compiled it without a hitch, cd' to desktop and run `box86 example.86_64` but i get this error: `home/cancer/Desktop/example.86_64 is not an executable file`

It runs fine on my Ubuntu 24.04.1 laptop.

**Comment by ptitSeb** [comment]
From the name of the file, it seems to be a 64bits executable. You need box64 to run it, not box86.

**Comment by GalaxiumNation** [comment]
i forgot to change file perms 🤦
