### ISSUE TITLE
TeamSpeak 3 Server crashes after a few hours, CPU usage goes to 400% on RPi 4

### ISSUE THREAD

**Issue by Tiger7539** [ptitSeb/box86#103]
Server runs fine at first, really great performance with several connected clients usually for ~2-4 hours. Then the server suddenly crashes, box86 process still runs though and CPU usage starts creeping up  slowly (after the server already crashed) until reaching 400% after several more hours.

System is 4GB Raspberry Pi 4b running Raspbian Buster. This is my first Linux project so mistake might absolutely be on my side.

**Comment by ptitSeb** [comment]
Ok, I'll check if I see something.
(I suspect there are some issue with thread not quitting correctly with box86, but still unsure what could be the issue really)

**Comment by Tiger7539** [comment]
Cool, thanks! Let me know if you want me to provide any additional information, will do my best.

**Comment by Tiger7539** [comment]
Today, the server ran for 8 hours before anyone connected. When people started using it, it crashed after the usual ~4 hours. I will close the port so no one can connect and let it run for a day or two.

**Comment by Jack477** [comment]
Same situation here, after 2 hours of great working with 3 connected users server crashed, CPU overload. Log show nothing. I attach a screen how start is looks.
![Przechwytywanie](https://user-images.githubusercontent.com/47400151/80547055-857fff00-89b7-11ea-9062-34133f3959c8.PNG)

**Comment by Tiger7539** [comment]
The server has now been up for 40 hours and running. I think at this point it is safe to assume the crashes only occur with active clients connected.

**Comment by Jack477** [comment]
My server is working for 8 hours and still running. I set there 10 passive users and sometimes I talk with my friend and I dont see any problems.I create ts3server.ini file and set logappend=1

**Comment by Tiger7539** [comment]
After creating the ts3server.ini file, how do you start the server so that the .ini is passed to it?

**Comment by Jack477** [comment]
./ts3server createinifile=1
Actually Im testing with live users, 30-40min and freeze, CPU overload soo it need restart..

**Comment by Tiger7539** [comment]
So no difference in behavior whatsoever?

**Comment by Jack477** [comment]
There is a difference beacuse with 10 afk users it works for 10hours but with active users crash after ~30min. I wrote a script which look after CPU usage by ts3 and restart him automaticly after freeze

**Comment by Tiger7539** [comment]
As I wrote, crashes only occur when active clients are connected. I also had a few inactive clients connected for a few hours at a time, never caused anything.

> I wrote a script which look after CPU usage by ts3 and restart him automaticly after freeze
Automatically restarting is good I guess, but such frequent crashes are not worth running the server for me.

**Comment by HairMetalMadness** [comment]
I got the same Problem. TS3 server runs without issues until clients connect to it. At seemingly random times it crashes and CPU usage goes up to 300% + in the "top" screen. Longest time it ran so far was 2+ hours. I also didnt find anything suspicious in the TS3 log files.

**Comment by Jack477** [comment]
Be patient, maybe in future its gonna works fine beacuse ts3 its large app, at the moment I'm sure there is a problem with threads. You can use my script which I made exactly for this issue. https://github.com/Jack477/TeamSpeak3-AntiCrash

**Comment by ptitSeb** [comment]
Is this ticket still relevent? So much things have changed in box86 since last ticket entry.
