### ISSUE TITLE
[playable] Uplink: Hacker Elite

### ISSUE THREAD

**Issue by talraash** [ptitSeb/box86#104]
Game: Uplink: Hacker Elite
Version: 2.0.0.4
Status: Full playable 
1080p: 30 fps windowed/ 35 -40 fps full screen
Host : Rpi 4 
Dynarec: +
gl4es: -
![2020-04-27-013002_1920x1080_scrot](https://user-images.githubusercontent.com/22260439/80321583-dad8d680-8826-11ea-81ca-35652dd3e349.png)
P.S. If this is useful, I’m ready to test and make a list of playable games. It might be worth creating a wiki page on github and doing it there.

**Comment by ptitSeb** [comment]
Yes, it's very usefull.
I have just created a new repo for the compatibility list
Can you go there: https://github.com/ptitSeb/box86-compatibility-list/issues and fill in your tests result. I have created a template and some tags to help keep things organise. Feel free to comment if things are unclear / wrong / missing...

**Comment by talraash** [comment]
Ok, all fine. But i can't add tags on that repo, So close this issue and move to box86-compatibility-list
