### ISSUE TITLE
Issues with YoYo games using runner v0.1

### ISSUE THREAD

**Issue by farox1** [ptitSeb/box86#106]
When i run one of this games (tested with Donkey Me and Verminian Trap) i get some errors and an undefined symbol _XGetRequest (from libXxf86vm.so.1)

Here is the complete log:
[errorbox86.txt](https://github.com/ptitSeb/box86/files/4568211/errorbox86.txt)

This on Pandora.
Thanks

**Comment by ptitSeb** [comment]
I think I have updated that libXxf86vm.so.1 lib. Try to use one from my latest Locomalito PND release, and it should work (I have already run Verminian Trap on the Pandora IIRC).

**Comment by farox1** [comment]
Thanks
just tested (estracted the libs and box86 from issyos.pnd the latest release), but it's the same error.

**Comment by ptitSeb** [comment]
Still, this look like a system error, not a box86 error.

Can you try with `LD_DEBUG=libs`, maybe that will clarify things?

**Comment by farox1** [comment]
ok how can i save this to a logfile ? (it's too long for the terminal).

**Comment by ptitSeb** [comment]
I think it goes to stderr, so `2> log.txt` should work (or `> log.txt 2>&1` to redirect everything)

**Comment by farox1** [comment]
Yes this command worked. 
here is both 
[log.txt](https://github.com/ptitSeb/box86/files/4568762/log.txt)
[log2.txt](https://github.com/ptitSeb/box86/files/4568764/log2.txt)

**Comment by farox1** [comment]
You are right..it's a system error and not a Box86 error. I forgot to copy over libXext.so.6 and libX11.so.6 from your issyos.pnd. Now the error is gone but the game have other problems (shaders error i think).
Thanks a lot for your time and help.
Closing this issue
