### ISSUE TITLE
ccmake unable to configure after merge #108

### ISSUE THREAD

**Issue by shahidali55** [ptitSeb/box86#110]
Unable to compile after merge https://github.com/ptitSeb/box86/pull/108.
Error is as below:
```
CMake Error at CMakeLists.txt:29 (if):
   if given arguments:

     "LESS" "3"

   Unknown arguments specified
```

**Comment by ptitSeb** [comment]
What version of cmake and python3 do you have on your system?

**Comment by shahidali55** [comment]
Had to make python3 the default python version (was python 2.7 by default) by running below commands:
```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
sudo update-alternatives --config python
```

**Comment by ptitSeb** [comment]
It should be fixed now, even without python3 as default.

**Comment by rajdakin** [comment]
I believe that using `-DPYTHON_EXECUTABLE=/usr/bin/python3` on the command line avoids changing the alternative (I did test this on my CMake 3.10.2, and I did get the correct Python binary).
Although, now you shouldn't have this issue anymore since CMake will (hopefully) automatically exclude any Python2 executable (and I recommend to @shahidali55 undoing his modification then re-configuring using `cmake .. -U PYTHON_EXECUTABLE` to force a re-scan, that way there should be no problem from things that expect the default Python to be Python2).

**Comment by shahidali55** [comment]
Unfortunately, undoing the set alternatives action breaks cmake:
```
CMake Error at CMakeLists.txt:27 (message):
   You need a Python interpretor, CMake will exit.

```
```
cmake --version
cmake version 3.5.1
```
```
python --version
Python 2.7.12
```
OS: Ubuntu 16.04.6 LTS

**Comment by rajdakin** [comment]
Strange... Did you try a bare `cmake ..`? I don't really know how CMake works, maybe unsetting an option on the command line forces it to be undefined, so removing the `-U PYTHON_EXECUTABLE` will make it re-search the Python executable? If it searched Python, it should show something containing `PythonInterp`...

I am using a Linux Mint 19.3 with the system-installed cmake (3.10.2) and `Python 2.7.17` as `/usr/bin/python` (though I have Python 3 as `/usr/local/bin/python`). However I cannot manage to reproduce your issue...

**Comment by shahidali55** [comment]
bare cmake gives a more detailed error:
```
cmake ..
-- Could NOT find PythonInterp: Found unsuitable version "2.7.12", but required is at least "3" (found /usr/bin/python)
CMake Error at CMakeLists.txt:27 (message):
  You need a Python interpretor, CMake will exit.


-- Configuring incomplete, errors occurred!
```

**Comment by rajdakin** [comment]
So it looks like using the `-U` option on CMake 3.5.1 indeed forces the removal of the variable...

So now you should be able to do `cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 ..` to make it work (just to be sure in case it still doesn't, you do have a valid python3 executable there right?).

**Comment by shahidali55** [comment]
```
cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ali/box86/build
```
