### ISSUE TITLE
Game: Septerra Core

### ISSUE THREAD

**Issue by Juli199696** [ptitSeb/box86#113]
Well i got a Linux Version of the game which seems almost to be compatible. I just get the following problem.

System Raspberry Pi 4 ARM
Raspbian Buster

I build libSDL2 and used the "Fake KMS" driver in raspi-config. I tried like everything. Im clueless pls help.

pi@raspberrypi:~/Desktop/dos/SR/SRW-games/Septerra Core/SRW $ sh Septerra.sh 
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for ./SR-Septerra
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libm.so.6
Using native(wrapped) librt.so.1
Using native(wrapped) libpthread.so.0
Using emulated libmpg123.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using emulated libquicktime.so.2
Using native(wrapped) libz.so.1
Error: Symbol SDL_UnlockTexture not found, cannot apply R_386_JMP_SLOT @0x80b3214 (0x804a526)
Error: Symbol SDL_UpdateYUVTexture not found, cannot apply R_386_JMP_SLOT @0x80b3278 (0x804a6b6)
PltResolver: Ofs=0x8050e49, Id=464 (IP=(nil), ESP+4=0x1d0)

So the game wont start / crash instant.
Any idea how to fix that?

**Comment by meveric** [comment]
From what I remember Septerra Core "Linux version" uses Wine.
So it's not a native Linux version.

**Comment by Juli199696** [comment]
https://github.com/M-HT/SR/releases/tag/septerra_v1.04.0.4

This is a custom version where the exe gets decompiled and recompiled for linux. So its a native x86 version.

**Comment by ptitSeb** [comment]
That's the OpenSource static decompilation project of M-HT. You should build a native version, that should be efficient.

Also, be sure to use latest box86, as most of the symbol you listed are already supported. Only 2 were missing, and I've just added them with latest commit.

**Comment by Juli199696** [comment]
Awesome that worked!! Thank you. I can play my favorite game on the Pi now :D

**Comment by Juli199696** [comment]
Oh shit.. i get seg fault after i switch to the second room ingame. So it start. I can start a "new game" and get to the first plot of the story. After that when i try to leave the room in game and it starts to load the next one it will crash with seg fault.

**Comment by ptitSeb** [comment]
I don't own the game for now, so I'll not be able to debug it myself.

Can you get a gdb backtrace of the segfault?

**Comment by Juli199696** [comment]
How do i do this? I mean i just got the Linux executable file. I didnt compiled it. Im not that advanced sry.

**Comment by ptitSeb** [comment]
It looks like you are missing the plugins for libquicktime2. There in the form of `lqt_ffmpeg.so` and more name starting with lqt_XXXX.so
Put them (the x86 version) in folder and start the game with `export LIBQUICKTIME_PLUGIN_DIR=/PATH/TO/PLUGINS` and see if it helps.

In the mean time, I'll see if I can wrap this lib...

**Comment by Juli199696** [comment]
Well you dont need to fix it anymore if you dont want to. I got the native ARM version compiled now. As i have written there is a demo version of the game so if you want you can try to get it running with the "linux" version of the MHT project :) Thank you anyway.
