### ISSUE TITLE
Spotify woes

### ISSUE THREAD

**Issue by pinilpypinilpy** [ptitSeb/box86#114]
After spending an hour or so painfully installing missing packages and their dependencies, I end up with this, and I'm fairly sure no amount of package wizardry will fix it :(
output:
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for ./spotify
Using native(wrapped) libasound.so.2
Using native(wrapped) libresolv.so.2
Using native(wrapped) libcurl.so.4
Using native(wrapped) libdl.so.2
Using emulated libcef.so
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libm.so.6
Using emulated /usr/lib/i386-linux-gnu/libgcc_s.so.1
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using emulated /usr/lib/i386-linux-gnu/libnss3.so
Using emulated /usr/lib/i386-linux-gnu/libnssutil3.so
Using emulated /usr/lib/i386-linux-gnu/libplc4.so
Using emulated /usr/lib/i386-linux-gnu/libnspr4.so
Using emulated /usr/lib/i386-linux-gnu/libplds4.so
Using emulated /usr/lib/i386-linux-gnu/libsmime3.so
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libcairo.so.2
Using emulated /lib/i386-linux-gnu/libexpat.so.1
Using native(wrapped) libX11.so.6
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXdamage.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXtst.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXss.so.1
Using emulated /usr/lib/i386-linux-gnu/libgconf-2.so.4
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgthread-2.0.so.0
Using native(wrapped) libdbus-glib-1.so.2
Using native(wrapped) libdbus-1.so.3
Using emulated /usr/lib/i386-linux-gnu/libcups.so.2
Using emulated /usr/lib/i386-linux-gnu/libgssapi_krb5.so.2
Using emulated /usr/lib/i386-linux-gnu/libkrb5.so.3
Using emulated /usr/lib/i386-linux-gnu/libk5crypto.so.3
Using emulated /usr/lib/i386-linux-gnu/libkrb5support.so.0
Using emulated /lib/i386-linux-gnu/libkeyutils.so.1
Using emulated /lib/i386-linux-gnu/libcom_err.so.2
Using emulated /usr/lib/i386-linux-gnu/libgnutls.so.30
Using emulated /usr/lib/i386-linux-gnu/libp11-kit.so.0
Using emulated /usr/lib/i386-linux-gnu/libffi.so.6
Using emulated /usr/lib/i386-linux-gnu/libidn2.so.0
Using emulated /usr/lib/i386-linux-gnu/libunistring.so.2
Using emulated /usr/lib/i386-linux-gnu/libtasn1.so.6
Using emulated /usr/lib/i386-linux-gnu/libnettle.so.6
Using emulated /usr/lib/i386-linux-gnu/libhogweed.so.4
Using emulated /usr/lib/i386-linux-gnu/libgmp.so.10
Using emulated /usr/lib/i386-linux-gnu/libavahi-common.so.3
Using emulated /usr/lib/i386-linux-gnu/libavahi-client.so.3
Using native(wrapped) libz.so.1
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libgtk-x11-2.0.so.0
Using native(wrapped) libgdk-x11-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using emulated /usr/lib/i386-linux-gnu/libatomic.so.1
Using native(wrapped) libpangoft2-1.0.so.0
Using native(wrapped) libfreetype.so.6
Using emulated /usr/lib/i386-linux-gnu/libstdc++.so.6
Error: Symbol g_node_insert_before not found, cannot apply R_386_JMP_SLOT @0x746cc0d4 (0x7366)
Error: Symbol g_list_foreach not found, cannot apply R_386_JMP_SLOT @0x746cc0e0 (0x7396)
Error: Symbol g_slist_sort not found, cannot apply R_386_JMP_SLOT @0x746cc298 (0x7a76)
Error: Symbol g_node_traverse not found, cannot apply R_386_JMP_SLOT @0x746cc350 (0x7d56)
Error: Symbol g_node_new not found, cannot apply R_386_JMP_SLOT @0x746cc4c4 (0x8326)
Error: Symbol g_node_destroy not found, cannot apply R_386_JMP_SLOT @0x746cc548 (0x8536)
Error: Symbol dbus_watch_get_flags not found, cannot apply R_386_JMP_SLOT @0x6617e054 (0x3166)
Error: Symbol dbus_watch_get_data not found, cannot apply R_386_JMP_SLOT @0x6617e074 (0x31e6)
Error: Symbol dbus_watch_get_unix_fd not found, cannot apply R_386_JMP_SLOT @0x6617e0a0 (0x3296)
Error: Symbol dbus_watch_get_enabled not found, cannot apply R_386_JMP_SLOT @0x6617e0b0 (0x32d6)
Error: Symbol dbus_watch_handle not found, cannot apply R_386_JMP_SLOT @0x6617e11c (0x3486)
Error: Symbol dbus_connection_set_dispatch_status_function not found, cannot apply R_386_JMP_SLOT @0x6617e158 (0x3576)
Error: Symbol dbus_watch_set_data not found, cannot apply R_386_JMP_SLOT @0x6617e170 (0x35d6)
Error: Symbol dbus_connection_set_watch_functions not found, cannot apply R_386_JMP_SLOT @0x6617e180 (0x3616)
Error: Global Symbol in6addr_loopback not found, cannot apply R_386_GLOB_DAT @0x6e0f0b40 ((nil))
Error: Symbol snd_mixer_elem_get_callback_private not found, cannot apply R_386_JMP_SLOT @0x6e0f1054 (0x3a8266)
Error: Symbol snd_mixer_elem_set_callback not found, cannot apply R_386_JMP_SLOT @0x6e0f1058 (0x3a8276)
Error: Symbol snd_mixer_elem_set_callback_private not found, cannot apply R_386_JMP_SLOT @0x6e0f105c (0x3a8286)
Error: Symbol g_log_set_handler not found, cannot apply R_386_JMP_SLOT @0x6e0f1154 (0x3a8666)
Error: Symbol pango_cairo_font_map_get_default not found, cannot apply R_386_JMP_SLOT @0x6e0f11b4 (0x3a87e6)
Error: Symbol atk_state_set_contains_state not found, cannot apply R_386_JMP_SLOT @0x6e0f11ec (0x3a88c6)
Error: Symbol atk_state_type_get_name not found, cannot apply R_386_JMP_SLOT @0x6e0f11f0 (0x3a88d6)
Error: Symbol atk_image_get_type not found, cannot apply R_386_JMP_SLOT @0x6e0f11f4 (0x3a88e6)
Error: Symbol atk_value_get_type not found, cannot apply R_386_JMP_SLOT @0x6e0f1220 (0x3a8996)
Error: Symbol atk_document_get_type not found, cannot apply R_386_JMP_SLOT @0x6e0f1238 (0x3a89f6)
Error: Symbol atk_state_set_add_state not found, cannot apply R_386_JMP_SLOT @0x6e0f1248 (0x3a8a36)
Error: Symbol clone not found, cannot apply R_386_JMP_SLOT @0x6e0f14e8 (0x3a94b6)
Error: Symbol __libc_malloc not found, cannot apply R_386_JMP_SLOT @0x6e0f1580 (0x3a9716)
Error: Symbol __libc_calloc not found, cannot apply R_386_JMP_SLOT @0x6e0f1584 (0x3a9726)
Error: Symbol __libc_memalign not found, cannot apply R_386_JMP_SLOT @0x6e0f1588 (0x3a9736)
Error: Symbol __libc_realloc not found, cannot apply R_386_JMP_SLOT @0x6e0f158c (0x3a9746)
Error: Symbol __libc_free not found, cannot apply R_386_JMP_SLOT @0x6e0f1590 (0x3a9756)
Error: Symbol FcGetVersion not found, cannot apply R_386_JMP_SLOT @0x6e0f1620 (0x3a9996)
Error: Symbol FcPatternDuplicate not found, cannot apply R_386_JMP_SLOT @0x6e0f171c (0x3a9d86)
Error: Symbol FcConfigSubstituteWithPat not found, cannot apply R_386_JMP_SLOT @0x6e0f1720 (0x3a9d96)
Error: Symbol xcb_discard_reply not found, cannot apply R_386_JMP_SLOT @0x6e0f17d0 (0x3aa056)
Error: Symbol __res_state not found, cannot apply R_386_JMP_SLOT @0x6e0f19a4 (0x3aa7a6)
Error: Symbol llroundf not found, cannot apply R_386_JMP_SLOT @0x6e0f19f8 (0x3aa8f6)
Error: Symbol llround not found, cannot apply R_386_JMP_SLOT @0x6e0f19fc (0x3aa906)
Error: Symbol dbus_threads_init_default not found, cannot apply R_386_JMP_SLOT @0x6e0f1bcc (0x3ab046)
Error: Symbol dbus_connection_set_watch_functions not found, cannot apply R_386_JMP_SLOT @0x6e0f1c04 (0x3ab126)
Error: Symbol dbus_connection_set_dispatch_status_function not found, cannot apply R_386_JMP_SLOT @0x6e0f1c0c (0x3ab146)
Error: Symbol dbus_watch_set_data not found, cannot apply R_386_JMP_SLOT @0x6e0f1c10 (0x3ab156)
Error: Symbol dbus_watch_get_enabled not found, cannot apply R_386_JMP_SLOT @0x6e0f1c14 (0x3ab166)
Error: Symbol dbus_connection_try_register_object_path not found, cannot apply R_386_JMP_SLOT @0x6e0f1c40 (0x3ab216)
Error: Symbol dbus_watch_get_unix_fd not found, cannot apply R_386_JMP_SLOT @0x6e0f1c48 (0x3ab236)
Error: Symbol dbus_watch_get_flags not found, cannot apply R_386_JMP_SLOT @0x6e0f1c4c (0x3ab246)
Error: Symbol dbus_watch_get_data not found, cannot apply R_386_JMP_SLOT @0x6e0f1c50 (0x3ab256)
Error: Symbol dbus_watch_handle not found, cannot apply R_386_JMP_SLOT @0x6e0f1c5c (0x3ab286)
Error: Symbol dbus_get_version not found, cannot apply R_386_JMP_SLOT @0x6e0f1c80 (0x3ab316)
Error: Symbol nan not found, cannot apply R_386_JMP_SLOT @0x6e0f1e24 (0x3ab9a6)
Error: Symbol nanf not found, cannot apply R_386_JMP_SLOT @0x6e0f1fc8 (0x3ac036)
Error: Symbol __atomic_load_8 not found, cannot apply R_386_JMP_SLOT @0x73dea014 (0x2056)
Error: Symbol __atomic_exchange_8 not found, cannot apply R_386_JMP_SLOT @0x73dea01c (0x2076)
Error: Symbol __atomic_store_8 not found, cannot apply R_386_JMP_SLOT @0x73dea020 (0x2086)
Error: Symbol __atomic_compare_exchange_8 not found, cannot apply R_386_JMP_SLOT @0x73dea024 (0x2096)
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT @0x65c9519c (0x6b506)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_386_JMP_SLOT @0x65c95478 (0x6c076)
Error: Symbol g_dbus_error_quark not found, cannot apply R_386_JMP_SLOT @0xa62511c (0x81ead66)
Error: Symbol g_type_add_instance_private not found, cannot apply R_386_JMP_SLOT @0xa6251a0 (0x81eaf76)
Error: Symbol g_dbus_interface_skeleton_get_type not found, cannot apply R_386_JMP_SLOT @0xa6251b8 (0x81eafd6)
Error: Symbol g_unix_fd_list_get_type not found, cannot apply R_386_JMP_SLOT @0xa625248 (0x81eb216)
Error: Symbol g_dbus_interface_skeleton_get_connections not found, cannot apply R_386_JMP_SLOT @0xa62525c (0x81eb266)
Error: Symbol g_dbus_interface_skeleton_get_object_path not found, cannot apply R_386_JMP_SLOT @0xa625264 (0x81eb286)
Error: Symbol g_dbus_interface_skeleton_get_connection not found, cannot apply R_386_JMP_SLOT @0xa6252c0 (0x81eb3f6)
Error: Symbol __atomic_store_8 not found, cannot apply R_386_JMP_SLOT @0xa6259c4 (0x81ed006)
Error: Symbol __atomic_exchange_8 not found, cannot apply R_386_JMP_SLOT @0xa6259c8 (0x81ed016)
Error: Symbol __atomic_load_8 not found, cannot apply R_386_JMP_SLOT @0xa6259cc (0x81ed026)
Error: Symbol gtk_show_uri not found, cannot apply R_386_JMP_SLOT @0xa625b60 (0x81ed676)
Segmentation fault

**Comment by ptitSeb** [comment]
A lot have changed since last ticket, both for box86 and probably Spotify.

Is this ticket still relevent?

**Comment by pinilpypinilpy** [comment]
Probably not, I'll close the issue. 
Sorry, should have done it a long time ago
