### ISSUE TITLE
Build fails for ARM linux with disabled dynarec

### ISSUE THREAD

**Issue by jochenjagers** [ptitSeb/box86#116]
Hello,
i try to build box86 for an arm platform without NEON support so I disabled dynarec by -DARM_DYNAREC=OFF but it does not work.

~~~
| /git/src/dynarec/dynarec.c: In function 'resettable':
| /git/src/dynarec/dynarec.c:43:17: error: 'arm_linker' undeclared (first use in this function)
|      tableupdate(arm_linker, (uintptr_t)p, table);
|                  ^~~~~~~~~~
~~~

Greetings
Jochen

**Comment by ptitSeb** [comment]
Ok, sorry. It should be fixed now.

**Comment by jochenjagers** [comment]
Thanks. I use it for some old development tools for NVIDIA Tegra2. So performance is not so important.

**Comment by ptitSeb** [comment]
Build on non-dynarec is tested on CI now (Dynarec build too), closing  the ticket.
