### ISSUE TITLE
OSS Sound

### ISSUE THREAD

**Issue by The-El-Jonesy** [ptitSeb/box86#122]
Trying to run Eschalon Book I, which runs fine but with no sound.

It uses the (included from GOG) aoss wrapper for sound but it doesn't work. Keep getting a "libaoss.so failed to preload" error. When I point it to the alsa-oss libraries on my system it says "not an i386 ELF binary".

Is there a solution for this?

**Comment by The-El-Jonesy** [comment]
Still can't get the sound to work. If I try to use aoss from my system with `aoss ./Eschalon\ Book\ I` I get:
```BOX86 try to Preload /usr/lib/arm-linux-gnueabihf/libaoss.so 
Looking for ./Eschalon Book I
Not an i386 ELF (40)
Error: reading elf header of /usr/lib/arm-linux-gnueabihf/libaoss.so
Warning, cannot pre-load lib: "/usr/lib/arm-linux-gnueabihf/libaoss.so"
```
And using `padsp ./Eschalon\ Book\ I` gives me basically the same:
```BOX86 try to Preload /usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsedsp.so 
Looking for ./Eschalon Book I
Not an i386 ELF (40)
Error: reading elf header of /usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsedsp.so
Warning, cannot pre-load lib: "/usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsedsp.so"
```
Using LD_PRELOAD is the same.

Am I doing it wrong? Anything else I can try?

**Comment by ptitSeb** [comment]
The messages
```
Not an i386 ELF (40)
Error: reading elf header of /usr/lib/arm-linux-gnueabihf/libaoss.so
Warning, cannot pre-load lib: "/usr/lib/arm-linux-gnueabihf/libaoss.so"
```
and 
```
Not an i386 ELF (40)
Error: reading elf header of /usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsedsp.so
Warning, cannot pre-load lib: "/usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsedsp.so"
```
are normal. Box85 also try to use LD_PRELOAD, in case it's an x86 library that is asked to be preload, and fail because it only find an ARM library.
That doesn't mean the library hasn't been preloaded (and I guess it has been preload)

I think there was some issue with bitrates here, check that the game use the same bitrate as the default one for the system (not sure if it's 44100 or 48000)

**Comment by phoenixbyrd** [comment]
I believe the bitrate is 44100. 

I also notice the two methods you posted were both preloads, did you try downloading the three things I mentioned? I had this exact issue and downloading those three resolved it right away for me. You shouldn't need to preload anything for sound.

**Comment by The-El-Jonesy** [comment]
Yes, I did install all three packages. Don't remember if I actually tried just running it without preloading anything last night. I can give that a try later (fingers crossed).

**Comment by The-El-Jonesy** [comment]
Sorry, but still no luck. @phoenixbyrd are you using the GOG version? If so, how are you launching it (what command / from where)?

**Comment by phoenixbyrd** [comment]
Sorry for the late reply! I was using the GOG version and just went to go run it from my sd card I stuck it on and now it's not working. I use the start.sh script. 

I get a totally different error though

support/gog_com.shlib: line 134: 29893 Segmentation fault      ./aoss ./"${bin_32}"

**Comment by The-El-Jonesy** [comment]
No problem. It's good to know I'm not alone, I thought it might just be some issue with my particular setup.

Yeah, if I try to run it using start.sh I get a few Symbol errors and the game won't even launch. The last line from the console is the error you mentioned.

If I bypass the included sound libraries by renaming the "lib" folder to "lib nope" the game loads but with no sound (as you'd expect).

Which is why I landed on trying to use my system's libraries instead, but those aren't i386 so they don't work either. I'm stuck.

Here are the symbol errors when trying to use the included libraries:
```
Error: Symbol snd_mixer_elem_get_callback_private not found, cannot apply R_386_JMP_SLOT @0xb6fc50a4 (0x1fc6) in /home/pi/Box86/Eschalon Book I/game/../lib/libalsatoss.so.0
Error: Symbol snd_mixer_set_callback not found, cannot apply R_386_JMP_SLOT @0xb6fc50ac (0x1fe6) in /home/pi/Box86/Eschalon Book I/game/../lib/libalsatoss.so.0
Error: Symbol snd_mixer_elem_set_callback_private not found, cannot apply R_386_JMP_SLOT @0xb6fc50c4 (0x2046) in /home/pi/Box86/Eschalon Book I/game/../lib/libalsatoss.so.0
Error: Symbol snd_mixer_elem_set_callback not found, cannot apply R_386_JMP_SLOT @0xb6fc5160 (0x22b6) in /home/pi/Box86/Eschalon Book I/game/../lib/libalsatoss.so.0
Error: Symbol snd_mixer_get_callback_private not found, cannot apply R_386_JMP_SLOT @0xb6fc51a4 (0x23c6) in /home/pi/Box86/Eschalon Book I/game/../lib/libalsatoss.so.0
Error: Symbol snd_mixer_set_callback_private not found, cannot apply R_386_JMP_SLOT @0xb6fc51b4 (0x2406) in /home/pi/Box86/Eschalon Book I/game/../lib/libalsatoss.so.0
Error: Symbol dlsym not found, cannot apply R_386_JMP_SLOT @0xb6ff1058 (0xdb6) in /home/pi/Box86/Eschalon Book I/game/../lib/libaoss.so
```

Then everything looks fine until the segmentation error at line 134 of gog_com.shlib, which is the call to load the game using aoss.

**Comment by ptitSeb** [comment]
Eschalion Book I works fine with box86, closing the ticket.

(aoss is not relevent to box86)
