### ISSUE TITLE
Starting Games from Steam freezes

### ISSUE THREAD

**Issue by DaVinciJunior** [ptitSeb/box86#134]
Hi,

I tried starting games from the Steam ("small mode") window and sometimes when I start a game (also when games download updates) steam just freezes. I used the "top" command in the terminal and saw that the CPU usage of steam is constant at 100%. I tried "kill" with the PID and tried "killall" via the process name but still it just freezes and after approximately 2-3 minutes the steam window closes without any explanation and the process got killed too (maybe it'd be interesting investigating why it automatically closes and why the CPU usage is at constant 100%).

I am using a Raspberry Pi 4 B (4 GB RAM) and the Twister OS 1.2, so everything necessary should be preinstalled I assume.

Thank you for your great work pitSeb!!!

**Comment by ptitSeb** [comment]
Is it allows happening for the same hames or is it random?

**Comment by DaVinciJunior** [comment]
I am not sure if it happens randomly or not to be honest. Now that all games installed are up to date it seems to run more stable, but before when I was downloading the games (or their updates) it was crashing all the time after approximately 10-20 seconds.

**Comment by ptitSeb** [comment]
Ah I see. Yeah, I have also niticed some instabilities when steam goes online. I don't know what cause them yet.

**Comment by DaVinciJunior** [comment]
Thanks for looking into it. I am really impressed by your work! Sending you all the good vibes!

**Comment by ptitSeb** [comment]
Compatibility have improved with Steam, I'm closing the ticket, but feel free to re-open it if needed.
