### ISSUE TITLE
RimWorld unable to run

### ISSUE THREAD

**Issue by DaVinciJunior** [ptitSeb/box86#135]
Hi,

I tried running RimWorld (running on Linux x86 - note it is however a Unity Project and as there are already a mentioning about problems with mono maybe this is the issue) however I am not managing to get it working. I tried so far:
- starting it from Steam: Next to the game in the "Small Mode" of Steam you can see the status of the game. It is really short in the "Running" state and after that directly in "Syncing" (as it crashed as I supposed and "updates the save files to the cloud")
- starting it in a terminal: after downloading there are two different shell files one can try to either "start_RimWorld.sh" or "start_RimWorld_openglfix.sh". I tried both and even tried to print the exitvalue (=126). The game crashes with following message:
cannot execute binary file: Exec format error

This lead me to the assumption that the box86 somehow is not working at all for this?

My setup is:
- Raspberry Pi 4 (4GB RAM) with Twister OS (v1.2)
- As some stated in the RimWorld forums that the localization might be a problem I tried it with en-US and en-UK both
- I tried forcing OpenGL but as I already stated prior I think this seems to be a problem of not being able to read the instructions (aka somehow the emulator is not triggered I guess?)

Any insights and feedback would be appreciated. Thanks in advance

**Comment by ptitSeb** [comment]
How do you start? with `./start_RimWorld.sh` ?

**Comment by DaVinciJunior** [comment]
I tried all of the above mentioned. I even tried a manually modified version of the ./start_RimWorld_openglfix.sh where I printed the exit value. The exit value is 126 but I have no idea what this might be indicating.

**Comment by rajdakin** [comment]
What does this script do? When you directly launch the executable do you still get the error?

**Comment by DaVinciJunior** [comment]
I tried directly executing the executable to no avail :(

The start_RimWorld_openglfix.sh starts it basically just with "-force-opengl" tag (as suggested by the developer himself in here[1]). I think I tried all of the mentioned options in the forum linked but that also did not do the trick. Maybe I did something wrong not sure though... I also tried accessing the logs but there were no logs at all as the game immediately crashes before even launching.

[1] - https://ludeon.com/forums/index.php?topic=4805.0

**Comment by rajdakin** [comment]
What happens when you execute the executable directly? Any log? If so, can you copy-paste them here?

Also, what are the results of `file <executable-here>` and `ls -l <executable-here>`? (The first one is to check if the file is an x86 executable, the second to check if the executable is indeed executable, the file should start with `-rwxr-xr-x` or something like that.)

**Comment by DaVinciJunior** [comment]
![Screenshot_2020-06-25_17-56-43](https://user-images.githubusercontent.com/37219126/85754341-44813e00-b70d-11ea-87aa-bb653fc41bb0.png)
I executed everything once so you can have a detailed look at it. Thanks for the help. Appreciate it!!

**Comment by rajdakin** [comment]
This is a **64-bit** executable (`ELF 64-bit LSB executable`), box86 can only run **32-bit** executables.

**Comment by DaVinciJunior** [comment]
Oh ... now that you pointed that out... but it should most definitely be 32-bit also. I think Steam grabbed the wrong version for me. I'll try some tinkering and will update it if I got a 32-bit version. Thanks!!

**Comment by KweezyPlay** [comment]
i started it fine, but only latest alpha release, 15-20 fps maximum, sometimes crashes at start if you focused on game window

**Comment by DaVinciJunior** [comment]
@KweezyPlay - It is most likely just my incompetence but how did you grab the 32-bit version instead of the 64-bit? Did you manually download it beforehand on a linux 32 bit OS or did you try it with even Twister OS? Would really appreciate a tip because I didn't manage to grab the right version. Thank you for your feedback though it is much appreciated!

**Comment by KweezyPlay** [comment]
since 1.1 there is only 64bit version

**Comment by KweezyPlay** [comment]
and 1.0 won't run on rpi for no reason

**Comment by DaVinciJunior** [comment]
Oh I overread the "latest alpha" part. Thank you very much for your reply!

**Comment by ptitSeb** [comment]
RimWorld is a 64bits now, and it works with box64. Closing this ticket.
