### ISSUE TITLE
Armhf to aarch64 Box86

### ISSUE THREAD

**Issue by slimsam4u** [ptitSeb/box86#139]
Hey, I am samar, last I used box86 on my arm32 debian. When I shifted to arm64 Debian, while making cmake file, I got this error
```
0%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o                                               cc: error: unrecognized command line option '-marm'; did you mean '-fasm'?                                                  cc: error: unrecognized command line option '-mfpu=neon-fp-armv8'                                                           cc: error: unrecognized command line option '-mfloat-abi=hard'
cc: error: unrecognized command line option '-marm'; did you mean '-fasm'?
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:63: CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/dynarec_arm.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
I think it's error cakes because of aarch64, I think box86 should create a version for aarch64 otherwise it can be end of box86 (because aarch is popularly using in upcoming arm based devices)

# help me

**Comment by SamarJi** [comment]
I also added armhf support, same error

**Comment by ptitSeb** [comment]
you need a toolchain for aarch32 to build box86.
Also, you need to understand that this is a design choice: x86 lib calls are translated directely to native lib calls, so bitness NEED to be the same on both side (and I'm getting a bit tired of justifing my design choices)

A "box86" (probably called "box64") running on aarch64 is a new software, that would target x86_64, and need writing mostly from scratch.

**Comment by SamarJi** [comment]
Thanks, can it will work on adding new arch or on croll compiling in arm64 debian

**Comment by ptitSeb** [comment]
It does work with a 32bits chroot yes. Look at this video: https://www.youtube.com/watch?v=a1NFvm22wFI this is what PILab did (using a box86 built on a pi4).

**Comment by SamarJi** [comment]
Can there will a day came when box86 supports aarch64.

**Comment by ptitSeb** [comment]
Even if that come, that will not help you run what is currently supported by box86 for most part.

For example, Unreal Tournament 99 works well with box86 on armhf. But it wont run with box64 on aarch64, because ut99 is only a 32bits application.

**Comment by SamarJi** [comment]
Ok, I am trying to install armhf chroot , not installing, some alternative for it.

**Comment by SamarJi** [comment]
```
samar@localhost:~$ make
[  0%] Built target WRAPPERS                               [ 11%] Built target arm_pass0
[ 15%] Built target dynarec_arm                            [ 25%] Built target arm_pass3
[ 35%] Built target arm_pass2                              [ 45%] Built target arm_pass1
[ 45%] Built target dynarec                                [ 45%] Built target PRINTER
[ 46%] Linking C executable box86
/usr/bin/ld: cannot open output file box86: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/box86.dir/build.make:2069: box86] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/box86.dir/all] Error 2                                              make: *** [Makefile:141: all] Error 2
samar@localhost:~$
```
Finally, it is installing, but i got this error

**Comment by ptitSeb** [comment]
well, it say it: you seeems to hve a `box86` folder where the `box86` file should be outputed. Why do you have that folder?

**Comment by SamarJi** [comment]
I got that folder from git clone , instead on making in build , i used box86 dfolder, but i got this error, some idea to solve it. 
**If it solved , box86 cam be run able easily on aarch64**

**Comment by SamarJi** [comment]
OMG!
Installed, yes

**Comment by SamarJi** [comment]
Some idea to contact you privately like discord, i gonna show the data .

**Comment by ptitSeb** [comment]
I'm on discord yes. You can probably find me on that channel: https://discord.gg/Y7WFeC5﻿

**Comment by SamarJi** [comment]
Ha , i think i banned (but for what). Anyway, how do i can install x86 apps from .deb .

**Comment by SamarJi** [comment]
Samar #2104 ,please add me

**Comment by phoenixbyrd** [comment]
Digital panhandling was the reason for the ban.

**Comment by SamarJi** [comment]
Oh! Thats my fault, but not begging, i just telling about my project and status, 
** I don't need anything, that's just project bad status which makes not reason for any conflicts.**

Sorry, I want to contact box86 dev privately because i have some success that i can't show here.

**Comment by SamarJi** [comment]
I am opposite of that such cyber-crimes, i think that's some conflict created accidently, i just want to show my project current status and you thinked i am panhandling 😭😭, please i had never do it and i will never do it in future

**Comment by phoenixbyrd** [comment]
I'm sorry if you feel you weren't panhandling but let's look at the discussion that transpired to see why others might think otherwise.

-  I'm looking for a sponsor
-  Are you looking for money?
-  Yes

Prior to that you were talking about how you did not have a pi4 and weren't planning on buying one for at least a year but had this project you were working on that would make use of one. 

This is very suspiciously looking like digital panhandling. 

I think the best route for you to seek financial aide for your project would be a kickstarter campaign. It sure does sound like an interesting project and if this is truly a legit project the community would probably fund something like this if you are looking to market it. There is definitely interest out there for products like what you described, but please have a better plan on how to fund things other than trying to ask people to buy the parts for you.

**Comment by SamarJi** [comment]
I think, i main problem is that conflict , that's my dream project, i will never take money from others to work on it . This project is fully standalone for me, I think
I am something and you understand something which created something new, forget all. Now how can I came back.

**Comment by SamarJi** [comment]
###### I don't need financial aid, it's a pure project, and I don't need that . My aim is to build this project on myself without taking other's help. So, why I need it.

**Comment by SamarJi** [comment]
So, project completed, but i cant show you in discord. Anyways, i create a new way suitable for future for arm64

**Comment by SamarJi** [comment]
When you will unban me

**Comment by chrishancox** [comment]
Is there a guide on how to set up the chroot please? I have never set up a chroot before, and it is like pulling hen's teeth. I am using Ubuntu 20.04.1 ARM64 build. I have found a few guides around the internet, but I always get stuck, if someone can assist that would be amazing!

**Comment by ptitSeb** [comment]
I haven't tried myself yet, but on PILab discord ( https://discord.gg/Y7WFeC5﻿ ), I have seen some success on box86 running an aarch64. Come there to get some help.

**Comment by SamarJi** [comment]
I tried chroot for proot, and it didn't worked.

**Comment by SamarJi** [comment]
> I haven't tried myself yet, but on PILab discord ( https://discord.gg/Y7WFeC5﻿ ), I have seen some success on box86 running an aarch64. Come there to get some help.

I had been banned from here for no reason, installing 32but libraries and compilers inside 64bit Ubuntu as multi-arch would work.

**Comment by rnadesignlab** [comment]
To succesfully Compile Box86 on Arm64, look at this:
https://forum.armbian.com/topic/16584-install-box86-on-arm64/

**Comment by GxmerSam** [comment]
Oh great!
I got some success too,
https://youtu.be/-i33Nj63q40

Just trying to build all required dependencies, how've wine works well on android with box86 (explorer and winecfg only).

**Comment by ptitSeb** [comment]
Closing this ticket.

Building box86 on 64bits OS is well documented now.
