### ISSUE TITLE
Unimplemented Opcode, missing symbols

### ISSUE THREAD

**Issue by Nmzik** [ptitSeb/box86#14]
Log
```
BOX86_LD_LIBRARY_PATH: /home/user/Downloads/racer/:/usr/lib32/
Using default BOX86_PATH: ./:bin/
Counted 57 Env var
Looking for /home/user/Downloads/racer/racer
Using native(wrapped) libX11.so.6
Using native(wrapped) libGLU.so.1
Using native(wrapped) libGL.so.1
Using emulated /home/user/Downloads/racer/libfmodex.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using emulated /usr/lib32/libstdc++.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /usr/lib32/libgcc_s.so.1
Using native(wrapped) libXxf86vm.so.1

```
```
0xf7b4fe64: Unimplemented Opcode D0 67 B3 F7 80 67 B3 F7
0xf7b4fe68: Unimplemented Opcode 80 67 B3 F7 01 00 00 00
0xf74011d4: Unimplemented Opcode 10 4A 2F F7 A0 4A 2F F7
0xf74011d8: Unimplemented Opcode A0 4A 2F F7 D0 4A 2F F7
0xf74011dc: Unimplemented Opcode D0 4A 2F F7 50 4B 2F F7
0xf74011e0: Unimplemented Opcode 50 4B 2F F7 60 4C 2F F7
0xf74011e4: Unimplemented Opcode 60 4C 2F F7 B0 4F 2F F7
0xf74011e8: Unimplemented Opcode B0 4F 2F F7 00 50 2F F7
0xf74011ec: Unimplemented Opcode 00 50 2F F7 80 50 2F F7
0xf74011f0: Unimplemented Opcode 80 50 2F F7 00 51 2F F7
0xf74011f4: Unimplemented Opcode 00 51 2F F7 C0 51 2F F7
0xf74011f8: Unimplemented Opcode C0 51 2F F7 20 53 2F F7
0xf74011fc: Unimplemented Opcode 20 53 2F F7 74 00 00 00
0xf72f9830: Unimplemented Opcode F3 0F 1E FB 56 B8 01 00
```
Also some symbols cannot be applied
```
Error: Global Symbol _ZGTtnaj not found, cannot apply R_386_GLOB_DAT @0xf7405d00 ((nil))
Error: Global Symbol _ZGTtdlPv not found, cannot apply R_386_GLOB_DAT @0xf7406168 ((nil))
Error: Symbol FMOD_DSP_Connection_Mix5_1To5_1_SIMD not found, cannot apply R_386_JMP_SLOT @0xf75a6d18 (0x3942a)
Error: Symbol FMOD_DSP_Connection_Mix7_1To7_1_SIMD not found, cannot apply R_386_JMP_SLOT @0xf75a6ee0 (0x39b4a)
Error: Symbol FMOD_OS_SupportsSSE not found, cannot apply R_386_JMP_SLOT @0xf75a6f4c (0x39cfa)
Error: Symbol FMOD_DSP_Convert_FloatToPCM16 not found, cannot apply R_386_JMP_SLOT @0xf75a7068 (0x3a16a)
Error: Symbol FMOD_DSP_Distortion_SIMD not found, cannot apply R_386_JMP_SLOT @0xf75a7214 (0x3a81a)
Error: Symbol FMOD_DSP_Connection_MixStereoToStereo_SIMD not found, cannot apply R_386_JMP_SLOT @0xf75a7608 (0x3b7ea)
Error: Symbol FMOD_Resampler_Linear_PCM16_Stereo not found, cannot apply R_386_JMP_SLOT @0xf75a78f0 (0x3c38a)
Error: Symbol FMOD_Resampler_Linear_PCM16_Mono not found, cannot apply R_386_JMP_SLOT @0xf75a7aac (0x3ca7a)
Error: Symbol FMOD_DSP_Connection_MixMonoTo7_1_SIMD not found, cannot apply R_386_JMP_SLOT @0xf75a7e18 (0x3d82a)
Error: Symbol FMOD_DSP_Connection_MixMonoToStereo_SIMD not found, cannot apply R_386_JMP_SLOT @0xf75a81ac (0x3e67a)
Error: Symbol FMOD_DSP_Connection_MixMonoTo5_1_SIMD not found, cannot apply R_386_JMP_SLOT @0xf75a85c0 (0x3f6ca)
Error: Symbol XSetNormalHints not found, cannot apply R_386_JMP_SLOT @0x826a36c (0x804cefa)
Error: Symbol XAllocNamedColor not found, cannot apply R_386_JMP_SLOT @0x826a50c (0x804d57a)
Error: Symbol gamma not found, cannot apply R_386_JMP_SLOT @0x826a588 (0x804d76a)
Error: Symbol bcopy not found, cannot apply R_386_JMP_SLOT @0x826a5c0 (0x804d84a)
```
The game can be downloaded on http://www.racer.nl/
I think it uses OpenGL >= 3.0 so it won't work via GL4ES

**UPDATE:**
WorldOfGoo Demo doesn't work either
box86 Log
```
Error: Global Symbol _ZGTtnaj not found, cannot apply R_386_GLOB_DAT @0xf754bd00 ((nil))
Error: Global Symbol _ZGTtdlPv not found, cannot apply R_386_GLOB_DAT @0xf754c168 ((nil))
0xf7f97e64: Unimplemented Opcode D0 E7 F7 F7 80 E7 F7 F7
0xf7f97e68: Unimplemented Opcode 80 E7 F7 F7 01 00 00 00
0xf75471d4: Unimplemented Opcode 10 AA 43 F7 A0 AA 43 F7
0xf75471d8: Unimplemented Opcode A0 AA 43 F7 D0 AA 43 F7
0xf75471dc: Unimplemented Opcode D0 AA 43 F7 50 AB 43 F7
0xf75471e0: Unimplemented Opcode 50 AB 43 F7 60 AC 43 F7
0xf75471e4: Unimplemented Opcode 60 AC 43 F7 B0 AF 43 F7
0xf75471e8: Unimplemented Opcode B0 AF 43 F7 00 B0 43 F7
0xf75471ec: Unimplemented Opcode 00 B0 43 F7 80 B0 43 F7
0xf75471f0: Unimplemented Opcode 80 B0 43 F7 00 B1 43 F7
0xf75471f4: Unimplemented Opcode 00 B1 43 F7 C0 B1 43 F7
0xf75471f8: Unimplemented Opcode C0 B1 43 F7 20 B3 43 F7
0xf75471fc: Unimplemented Opcode 20 B3 43 F7 74 00 00 00
```
Is there something wrong with my setup? Is it because i run it on x64? The box86's libs directory points to 32bit system libs

**Comment by meveric** [comment]
Box86 is mainly meant for ARM boards where x86 needs to be emulated, why are you trying to run it on an x64 CPU that can run x86 code perfectly fine?

**Comment by Nmzik** [comment]
It's not about x64 CPU that can execute x86 code. I'm just testing box86. box86 doesn't contain any ARM specific code so it's fairly okay to run on any platform to detect bugs.

**Comment by ptitSeb** [comment]
You can run it on 64bits system, but you need to build box86 as a 32bts apps with `-m32`. Box86 will not work if build as 64bits.
The OpCode listed exists in Box86 (I haven't checked all of them, but `D0 XX` for example is implemented), so I guess the main issue is 64bits build here.

**Comment by Nmzik** [comment]
I use 32bit version. Box86 compiled with -m32 flag
64bit of box86 doesn’t even compile.

**Comment by ptitSeb** [comment]
Ok good.
Also, don't forgot to use `LD80BITS` and `NOALIGN`.

Now, what I don't understand is why you have all those Unimplemented Opcode. Thoses opcodes are implemented, I use an x86 build myself from time to time to debug, it works (I launched WorldOfGoo, the full game, not the demo, already using Box86 on a x86 and an x86__64 linux already).

**Comment by ptitSeb** [comment]
And last question, what does `make test` gives you?

**Comment by Nmzik** [comment]
UPDATE:
With both LD80BITS and NOALIGN options selected all tests get passed (Test 7 failed without those flags)
With all latest commits i still cannot get WorldOfGoo to work.
**FTL doesn't work**. I get same errors (I basically get the same unimplemented opcodes).

> 5510|0xf7615e64: Unimplemented Opcode D0 C7 5F F7 80 C7 5F F7
> 5510|0xf7615e68: Unimplemented Opcode 80 C7 5F F7 01 00 00 00
> 5510|0xf752d1d4: Unimplemented Opcode 10 0A 42 F7 A0 0A 42 F7
> 5510|0xf752d1d8: Unimplemented Opcode A0 0A 42 F7 D0 0A 42 F7
> 5510|0xf752d1dc: Unimplemented Opcode D0 0A 42 F7 50 0B 42 F7
> 5510|0xf752d1e0: Unimplemented Opcode 50 0B 42 F7 60 0C 42 F7
> 5510|0xf752d1e4: Unimplemented Opcode 60 0C 42 F7 B0 0F 42 F7
> 5510|0xf752d1e8: Unimplemented Opcode B0 0F 42 F7 00 10 42 F7
> 5510|0xf752d1ec: Unimplemented Opcode 00 10 42 F7 80 10 42 F7
> 5510|0xf752d1f0: Unimplemented Opcode 80 10 42 F7 00 11 42 F7
> 5510|0xf752d1f4: Unimplemented Opcode 00 11 42 F7 C0 11 42 F7
> 5510|0xf752d1f8: Unimplemented Opcode C0 11 42 F7 20 13 42 F7
> 5510|0xf752d1fc: Unimplemented Opcode 20 13 42 F7 74 00 00 00
> 5510|0xf7436510: Unimplemented Opcode F3 0F 1E FB 55 89 E5 57

Not very much familiar with gdb but i'll try to debug in near time

**Comment by ptitSeb** [comment]
There seem to be something wrong and the "Unimplemented Opcode" gets trigger even if the opcode is know. What's your gcc version?
But test are ok? Interresting, so, the cpu emu does work enough for the tests to be ok.
Are you building with TRACE enabled or not?

**Comment by ptitSeb** [comment]
I don't think this ticket is still relevent. It will be closed soon unless stated otherwise.
