### ISSUE TITLE
error compiling on rpi

### ISSUE THREAD

**Issue by Pokojwy** [ptitSeb/box86#147]
hi, i have problem when i try to compile box86 on rpi3.  When i try download and compile it was happening 

```
pi @ raspberrypi: ~ / Desktop / box86 $ git clone https://github.com/ptitSeb/box86.git
Cloning into 'box86' ...
remote: Enumerating objects: 516, done.
remote: Counting objects: 100% (516/516), done.
remote: Compressing objects: 100% (325/325), done.
remote: Total 15253 (delta 354), reused 316 (delta 191), pack-reused 14737
Receiving objects: 100% (15253/15253), 5.36 MiB | 3.13 MiB / s, done.
Resolving deltas: 100% (12067/12067), done.
pi @ raspberrypi: ~ / Desktop / box86 $ cd box86
pi @ raspberrypi: ~ / Desktop / box86 / box86 $ mkdir build; cd build; cmake .. -DRPI3 = 1 -DCMAKE_BUILD_TYPE = RelWithDebInfo; make
bash: cmake: command not found
make: *** No objects specified and no makefile found. Stop.
pi @ raspberrypi: ~ / Desktop / box86 / box86 / build $
```
rasbpian is from 14th VII (noobs), and only thing what i did on that is install minecraft using that guide https://www.raspberrypi.org/forums/viewtopic.php?t=243946
can anybody help me with compile this? 
please as simple as possible, because i'm just starting to learn rpi

sorry for my not very good english but i can't use it very well

**Comment by ptitSeb** [comment]
run this: `sudo apt install build-essential cmake cmake-curses-gui git`
That should do it.

**Comment by Pokojwy** [comment]
thanks, now it works
