### ISSUE TITLE
Using wine to run the game

### ISSUE THREAD

**Issue by aini3225** [ptitSeb/box86#149]
Using the（wine）   run  War3  Ra2......Error will appear below  , Repetitive code appear constantly
![11](https://user-images.githubusercontent.com/68221567/87852678-9eed7300-c936-11ea-9aca-608f5bc3e1c9.jpg)

**Comment by ptitSeb** [comment]
Wine is still experimental, crash happens. Not a lot of things are running for now. Plus the D3D driver may crash also.

I'm not sure what you expect me to do with that?

**Comment by aini3225** [comment]
Box86 wine on the raspberry pie won't appear this problem
But I use chroot running on android box86 wine will appear above the error    
I hope can fix it

**Comment by aini3225** [comment]
I use equipment is samsung S5

**Comment by ptitSeb** [comment]
I can't do anything with that log. Try to get a picture of the 1st time that line appear. I need the line before.

If you cannot (like it's going too fast), change box86: in `src/libtools/signals.c` line 326 from
`if(old_code==info->si_code && old_pc==pc && old_addr==addr) {`
to
`if(1/*old_code==info->si_code && old_pc==pc && old_addr==addr*/) {`
So it should stop at 1st segfault.

**Comment by aini3225** [comment]
![QQ图片20200718233111](https://user-images.githubusercontent.com/68221567/87856033-ca7c5780-c94e-11ea-98f4-62d17835f68a.jpg)

**Comment by aini3225** [comment]
![QQ图片20200718233256](https://user-images.githubusercontent.com/68221567/87856078-0a433f00-c94f-11ea-9b7d-0fb2e2838a4b.jpg)

**Comment by ptitSeb** [comment]
There seems to be something wrong with libgnutls.so.30 on the first picture, resulting with a corrupted stack. This is not good, and doesn't happens on my Pandora or on PI4. I don't know if you can update/downgrade your version. You can also try to use an x86 version using `BOX86_EMULATED_LIBS=libgnutls.so.30` but it will probably required some other libs as dependancies.

The second screenshot looks fine, those Warning are ok, I have more or less the same.

**Comment by aini3225** [comment]
This also needs to be repair
![QQ图片20200718234407](https://user-images.githubusercontent.com/68221567/87856318-fc8eb900-c950-11ea-8d7a-703d69ddba6f.jpg)

**Comment by aini3225** [comment]
hope Give priority  repair This problem

**Comment by ptitSeb** [comment]
There is a segfault after the load of "librt.so", apparently durring "wineboot::start_services_process". I don't think anythink can work until wineboot start correctly.
Unfortunalty, again, I don't see what I can do with that screenshot.

What you can try is use "BOX86_TRACE_FILE=/SOME/PATH/trace-%pid.txt" along with "BOX86_LOG=2", to have more logs, and logs redirected to some file, 1 file per process spawned.

Also, just to be sure, you are using latest box86 sources right?

**Comment by aini3225** [comment]
YES

**Comment by aini3225** [comment]
i am using latest source

**Comment by aini3225** [comment]
i am using latest box86 source

**Comment by aini3225** [comment]
[trace.zip](https://github.com/ptitSeb/box86/files/4941962/trace.zip)

**Comment by aini3225** [comment]
Raspberry pi error message
![QQ图片20200719011705](https://user-images.githubusercontent.com/68221567/87857999-98bebd00-c95d-11ea-85ee-f69f6d4a506f.jpg)

**Comment by ptitSeb** [comment]
so it's Android on a pi4?
For now, I have done all my testing using wine 5.11 that I built for x86. I haven't tested other wine version.
Also, on the PI (but using Raspbian), I noticed I needed very recent mesa driver (20.x), older will fail with similar message.

**Comment by aini3225** [comment]
NO

**Comment by aini3225** [comment]
I use equipment is samsung S5

**Comment by aini3225** [comment]
[box86-trace.zip](https://github.com/ptitSeb/box86/files/4942149/box86-trace.zip)

**Comment by aini3225** [comment]
pi4. Prompt error message
![QQ图片20200719014041](https://user-images.githubusercontent.com/68221567/87858495-dec95000-c960-11ea-9bc7-45dacc068d0b.jpg)

**Comment by aini3225** [comment]
Two devices have error message

**Comment by ptitSeb** [comment]
This seems to be a crash in box86, according to the address, but I don't know where or why. The log was also nut usefull unfortunatly.
Not much I can do now with this data.
Hopefully, I'll be able to improve the debug log later, but for now, I'm sorry but there isn't much I can do.
