### ISSUE TITLE
Run Warcraft 3 with wine

### ISSUE THREAD

**Issue by pmtip** [ptitSeb/box86#151]
5809|SIGSEGV @0xb6f60a8c (???) (x86pc=(nil)/"???"), for accessing 0x8e0a7b8 (code=1)
Segmentation fault
![Screenshot_20200719_233728](https://user-images.githubusercontent.com/67471944/87878846-78eccf00-ca19-11ea-854c-749e2ef95cd7.jpg)

**Comment by pmtip** [comment]
My device is Raspberry Pi

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
gl4es with GLES2 backend is not yet compatible with Wine. I'm working on it...

**Comment by pmtip** [comment]
Now i am not using gl4es
![Uploading Screenshot_20200720_001023.jpg…]()

**Comment by pmtip** [comment]
Now i am not using gl4es
![Screenshot_20200720_001023](https://user-images.githubusercontent.com/67471944/87879487-ae93b700-ca1d-11ea-9eff-fb5688beb003.jpg)

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
Ok, Warcraft 3 is not working, I'm aware. wine support on box86 is still experimental, and there are more things not working than working.
That will take time.

**Comment by pmtip** [comment]
Diablo 2 Error Message
![Screenshot_20200720_131304](https://user-images.githubusercontent.com/67471944/87901900-d10fe980-ca8a-11ea-9a47-8ea8c9a09b01.jpg)

**Comment by pmtip** [comment]
@ptitSeb

**Comment by pmtip** [comment]
Diablo 2 Error Message
![Screenshot_20200720_134540](https://user-images.githubusercontent.com/67471944/87903912-bdb34d00-ca8f-11ea-8b06-69e62cf997d1.jpg)

**Comment by pmtip** [comment]
@ptitSeb

**Comment by pmtip** [comment]
Ok, It worked.

**Comment by ptitSeb** [comment]
I guess it's latest changes I pushed, especily the XCHG change in the dynarec, that may fix the recursive segfault you had at the beggining yes.

**Comment by pmtip** [comment]
Is box86 faster than exagear? @ptitSeb

**Comment by pmtip** [comment]
Which is faster, box86 or exagear

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
I don't know, I never exagear.
My guess is exagear will be faster on cpu only stuff, but box86 will probably better on complex game that use many wrapped lib.
But point is: I don't know.

**Comment by pmtip** [comment]
Can box86 run on Android?

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
no, not dirrectly. It may run on linux chroot it's 32bits.

**Comment by pmtip** [comment]
Can it be run with proot?

**Comment by pmtip** [comment]
@ptitSeb

**Comment by pmtip** [comment]
I try to run box86 in proot.
Cannot run wine.
![Screenshot_20200723_040929](https://user-images.githubusercontent.com/67471944/88223603-50bfd300-cc9a-11ea-8772-f8f5d9f3e690.jpg)

**Comment by pmtip** [comment]
If I use chroot, what linux rootfs should I use? @ptitSeb

**Comment by ptitSeb** [comment]
I don't know, I'm now an Android specialist. Some armhf rootfs will be fine.
BUt not you'll have any 3D Driver in that configuration.

Just to note, are you aware of the boxedwine project here: http://www.boxedwine.org/ this emulator seems slower than box86, 
 but target Android, so you have more luck with it.

**Comment by pmtip** [comment]
I use box86 to run Red Alert 2.
It works when I turn off dynarec.

**Comment by pmtip** [comment]
But when I turn on dynarec, it won't work.

**Comment by pmtip** [comment]
But when I turn on dynarec, it won't work.
![Screenshot_20200723_180335](https://user-images.githubusercontent.com/67471944/88274793-d8472980-cd0e-11ea-96e6-17d8b6a2d955.jpg)

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
Yes, I have notice there seems to be some instabilities with dynarec on. At first I thought it was some buggy opcode translation, but unfortunatly, it seems more complicated then that. I'm still trying to understand what's going on, but debuggibg wine stuff is very tricky.

**Comment by pmtip** [comment]
I try to run box86 on Android without chroot or proot.
Bad system call.
![Screenshot_20200723_194529](https://user-images.githubusercontent.com/67471944/88282933-13e8f000-cd1d-11ea-8db1-251efe085b1d.jpg)

**Comment by ptitSeb** [comment]
wont work, syscall seems slighty different and some linux libs will be missing (or have a different name). Plus Google is phasing out 32bits architectures.

**Comment by pmtip** [comment]
Can you make an Android version of box86?

**Comment by ptitSeb** [comment]
Not me, but I gladly work with someone. Be again, with Goggle phasing out 32bits arch, I'm not sure there is a point in doing it.

**Comment by pmtip** [comment]
@ptitSeb  why don't you wrap libstdc++ and libgcc_s

**Comment by ptitSeb** [comment]
I cannot wrap C++ library easily. The Virtual Table mecanism would be tricky so it wasn't in short-term roadmap.

**Comment by pmtip** [comment]
Will box86 be faster than exagear in the future?

**Comment by pmtip** [comment]
@ptitSeb

**Comment by ptitSeb** [comment]
I don(t even know if it slower or faster now, and by what percentage...
Do I plan more dynarec optim in the future: yes, but priority is to stabilize wine program for now.

**Comment by pmtip** [comment]
How long does it take to run wine stably on box86?

**Comment by ptitSeb** [comment]
I don't know what the problem is, so I really have no idea.

Do you have performances issue?

**Comment by pmtip** [comment]
Can you solve the problem of Bad system call?
@ptitSeb

**Comment by pmtip** [comment]
Can you solve the Bad system call.
@ptitSeb

**Comment by pmtip** [comment]
This problem occurs when running linux programs on Android 8 and above

**Comment by rajdakin** [comment]
You do know he literally answered this just 12 comments sooner right? (The answer was no, or at least not by himself.) https://github.com/ptitSeb/box86/issues/151#issuecomment-662969595

**Comment by pmtip** [comment]
@rajdakin 
My problem now is different.
I mean how to solve the bad system call when running linux programs on Android 8 and above.

**Comment by pmtip** [comment]
I'm sorry.

**Comment by pmtip** [comment]
@ptitSeb Is wine stable now?

**Comment by ptitSeb** [comment]
nope

**Comment by pmtip** [comment]
opengl does not work.
Diablo2 works when I don’t use opengl.
But I can't run Diablo2 with opengl.

**Comment by pmtip** [comment]
can you fix?

**Comment by ptitSeb** [comment]
I don't know, I have to check it. Maybe later.

**Comment by pmtip** [comment]
![Screenshot_20200814_031922](https://user-images.githubusercontent.com/67471944/90177625-65950f80-dddd-11ea-9d89-e5182fed713f.jpg)

**Comment by pmtip** [comment]
This is the output of running diablo2 with opengl.

**Comment by pmtip** [comment]
![Screenshot_20200814_032603](https://user-images.githubusercontent.com/67471944/90178098-fec42600-dddd-11ea-9fc2-ba5997f2cbc6.jpg)

**Comment by pmtip** [comment]
Now I don't use opengl, it can run.

**Comment by pmtip** [comment]
![Screenshot_20200814_032603](https://user-images.githubusercontent.com/67471944/90178496-91fd5b80-ddde-11ea-8bd3-983576806c75.jpg)

**Comment by pmtip** [comment]
Warcraft3 still cannot run.
![Screenshot_20200814_034341](https://user-images.githubusercontent.com/67471944/90179962-e0abf500-dde0-11ea-816c-4dbae6875804.jpg)

**Comment by ptitSeb** [comment]
I want to make some changes in box86 dynarec internals first. After it's done, I'll look at Warcraft 3

In the mean time, can you try with `BOX86_DYNAREC=0` to check if it's an issue specific to Dynarec or a general issue?

**Comment by pmtip** [comment]
I turned off dynarec, it still doesn't work.But the error message has changed.

**Comment by ptitSeb** [comment]
Also, on Warcraft 3, are you using "-opengl" option?

**Comment by pmtip** [comment]
I did not use the "-opengl" option, my mesa version is 19.3.2.

**Comment by ptitSeb** [comment]
Mesa 19.3.2 on PI4 is not advised: S3TC is not enabled there, and that's a hard requirement for most Windows games. Try to get latest 20.2 or 20.3 ersion of mesa (build it yourself or look for pre-built binary). Use "LD_LIBRARY_PATH=/PATH/MESA/LIB" kind of env. var. to use the new mesa.

Also, prefer opengl renderer over d3d if possible, to avoid d3d->opengl translation that can be tricky.

**Comment by ptitSeb** [comment]
Alternatively, you can try "TwisterOS", as it include box86, wine and latest mesa by default (it's a mod of RaspberryPIOS).

**Comment by pmtip** [comment]
I compiled and installed mesa 20.1.5.Warcraft3 still cannot run.

**Comment by pmtip** [comment]
what should I do.

**Comment by ptitSeb** [comment]
Are you sure 20.1.5 have S3TC extension? check with glxinfo, look for exampel for GL_EXT_texture_compression_dxt1 in the extension string.

**Comment by ptitSeb** [comment]
also, use "-opengl" option when launching warcraft3

**Comment by pmtip** [comment]
Without S3TC extension, what should I do?

**Comment by ptitSeb** [comment]
Try to build 20.2, the extension was add during 20.1 cycle.
gl4es still have issue with Wine, so I don't advised to use it (maybe it works with -opengl switch, but I don't know)

**Comment by pmtip** [comment]
I cannot compile mesa20.2, the meson version of raspberrypi os is too low.

**Comment by pmtip** [comment]
Can you give me a link to the compiled mesa?

**Comment by ptitSeb** [comment]
remove the repo meson  with `sudo apt remove meson` and install a fresh new one with pip3 with `pip3 install meson` or `pip3 install --user meson` if you have permission issues

**Comment by ptitSeb** [comment]
You can also check on PILabs Youtube channel. In the "Community" part, you'll find an invite for a discord channel, there there some mesa build shared I think

**Comment by pmtip** [comment]
I didn't find it.
Can you give me a link?

**Comment by ptitSeb** [comment]
This https://www.youtube.com/channel/UCgfQjdc5RceRlTGfuthBs7g/community ?

**Comment by pmtip** [comment]
Can I use mesa of ubuntu 20.04?

**Comment by ptitSeb** [comment]
I don't know. I would see it may not work because compiler / dependancy will be different.

**Comment by pmtip** [comment]
"MESA_20_V3D_RPI4_PILAB.zip"
Is it this one?

**Comment by ptitSeb** [comment]
I guess so yes.

**Comment by pmtip** [comment]
It still does not have the S3TC extension.Please give me the download link of mesa.

**Comment by Askmewho** [comment]
Use this one for preload https://drive.google.com/file/d/1lO7GsfUQ3mToLT5QjDM5oRhx9hBLzZX6/view?usp=drivesdk

**Comment by pmtip** [comment]
ok,thank you.

**Comment by pmtip** [comment]
does not work.
LD_LIBRARY_PATH=/home/pi/mesa/lib/arm-linux-gnueabihf/ LIBGL_DRIVERS_PATH=/home/pi/mesa/lib/arm-linux-gnueabihf/dri GBM_DRIVERS_PATH=/home/pi/mesa/lib/arm-linux-gnueabihf/ wine War3.exe -opengl
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 27 Env var
Looking for /usr/bin/wine
argv[1]="War3.exe"
argv[2]="-opengl"
Using emulated /opt/wine-devel/bin/../lib/libwine.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /opt/wine-devel/bin/../lib/wine/ntdll.so
Using native(wrapped) libm.so.6
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 28 Env var
Looking for /opt/wine-devel/bin/wine
argv[1]="War3.exe"
argv[2]="-opengl"
Using emulated /opt/wine-devel/bin/../lib/libwine.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /opt/wine-devel/bin/../lib/wine/ntdll.so
Using native(wrapped) libm.so.6
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 28 Env var
Looking for /opt/wine-devel/bin/wineserver
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
0050:err:vulkan:wine_vk_init Failed to load libvulkan.so.1.
008c:err:seh:segv_handler Got unexpected trap 0
003c:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1053
Using emulated /opt/wine-devel/lib/wine/kernel32.dll.so
Using emulated /opt/wine-devel/lib/wine/advapi32.dll.so
Using emulated /opt/wine-devel/lib/wine/ucrtbase.dll.so
Using emulated /opt/wine-devel/lib/wine/gdi32.dll.so
Using emulated /opt/wine-devel/lib/wine/user32.dll.so
Using emulated /opt/wine-devel/lib/wine/shell32.dll.so
Using emulated /opt/wine-devel/lib/wine/winspool.drv.so
Using emulated /opt/wine-devel/lib/wine/msvcr80.dll.so
Using emulated /opt/wine-devel/lib/wine/ws2_32.dll.so
Using emulated /opt/wine-devel/lib/wine/iphlpapi.dll.so
Using native(wrapped) libresolv.so.2
Using native(wrapped) libncurses.so.6
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated /opt/wine-devel/lib/wine/winex11.drv.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
Warning: Cannot dlopen("libcups.so.2"/0x7e1cb299, 2)
Using emulated /opt/wine-devel/lib/wine/msvcrt.dll.so
Using emulated /opt/wine-devel/lib/wine/secur32.dll.so
Using emulated /opt/wine-devel/lib/wine/netapi32.dll.so
Using emulated /opt/wine-devel/lib/wine/dnsapi.dll.so
Using emulated /opt/wine-devel/lib/wine/crypt32.dll.so
Using emulated /opt/wine-devel/lib/wine/bcrypt.dll.so
Using native(wrapped) libgnutls.so.30
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
Using emulated /opt/wine-devel/lib/wine/kerberos.dll.so
Warning: Cannot dlopen("libkrb5.so.3"/0x7b383272, 2)
Warning: Cannot dlopen("libgssapi_krb5.so.2"/0x7b383129, 2)
0024:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
Using native(wrapped) libpng16.so.16
0024:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits)").
0024:err:winediag:wined3d_adapter_gl_init You are using the backbuffer for offscreen rendering. This is unsupported, and will be removed in a future version.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
0024:fixme:d3d:wined3d_adapter_find_polyoffset_scale No FBOs, assuming polyoffset scale of 2^23.
Warning: Cannot dlopen("libvulkan.so.1"/0x7d38b266, 2)
0024:err:vulkan:wine_vk_init Failed to load libvulkan.so.1.
1288|SIGSEGV @0x2842840 (???) (x86pc=0xffffffff/"???"), for accessing 0x35800000 (code=1), db=(nil)((nil)/???)
Segmentation fault

**Comment by pmtip** [comment]
This mesa does not work on rpi4.
@ptitSeb

**Comment by Askmewho** [comment]
It's the one I use on rpi4.

**Comment by pmtip** [comment]
OK,I will try.

**Comment by pmtip** [comment]
It worked, thanks.

**Comment by Askmewho** [comment]
It will crash eventually, WIP

**Comment by pmtip** [comment]
what?

**Comment by pmtip** [comment]
Diablo2 also worked!

**Comment by Askmewho** [comment]
Yes, than some games will crash ingame. It's expected

**Comment by pmtip** [comment]
Yes, this mesa is easy to get stuck.

**Comment by pmtip** [comment]
@ptitSeb 
There are many "Not an ELF file" errors when running wine 3.0, because wine 3.0 does not have a wine-preloader, can you fix it?

**Comment by pmtip** [comment]
Box86 will detect wine-preloader, but wine3.0 does not have wine-preloader.

**Comment by ptitSeb** [comment]
Even if there is no preloader, it should still work. be sure to call wine and not the exe directly.

**Comment by pmtip** [comment]
But I hope you can fix this error, I don't want to see the error.

**Comment by pmtip** [comment]
Can you fix it? I don't want to see this error.

**Comment by pmtip** [comment]
I use wine3.0-eltechs because it is faster than wine5.14.

**Comment by ptitSeb** [comment]
So it's the wine from exagear? I don't know if they modify it or not. But it should work (unless there is a specific change). Can you copy/paste the log?

**Comment by pmtip** [comment]
yes,wine-eltechs is faster than normal wine.
It works, but there are many "Not an ELF file".

**Comment by ptitSeb** [comment]
I don't understand where this error comes from. Can you paste an example of it?

**Comment by pmtip** [comment]
I use box86 on Android, how should I make box86 use GPU?

**Comment by ptitSeb** [comment]
I don't know.
I assume you have a linux armhf chroot. You need to check how to get EGL/GLES driver running on your chroot. Once it's done, use gl4es to get an OpenGL driver from EGL/GLES. You will then be abble to use that with box86 (but be warned, gl4es still have trouble with wine  for now, so not everything run, I'm aware of the issues).

**Comment by pmtip** [comment]
Do I need to use framebuffer?

**Comment by ptitSeb** [comment]
maybe.
Again, never tried this kind of things, so I don't have all the answers.

**Comment by pmtip** [comment]
PlantsVsZombies does not work, but it works when I turn off dynarec.

**Comment by ptitSeb** [comment]
Interresting. You could open a new ticket for this one, it's interresting.

**Comment by pmtip** [comment]
OK.

**Comment by pmtip** [comment]
Red Alert 2 does not work, it is stuck here.
![Screenshot_20200820_222649](https://user-images.githubusercontent.com/67471944/90785271-bd2f0000-e334-11ea-828b-ab7e2db1bdb9.jpg)

**Comment by pmtip** [comment]
@ptitSeb

**Comment by pmtip** [comment]
@ptitSeb Red Alert 2 is not working properly.

**Comment by ptitSeb** [comment]
Yes, I have seen your previous message. I don"t need to respond within 2h you now. Also, "pinging" me as no special effect (it's the same as a regular entry, because I own the repo I receive a notification for every new entry / new ticket)

Also, please open a new ticket and let this one close, as this is a different issue.

**Comment by pmtip** [comment]
OK.
