### ISSUE TITLE
undertale don't work

### ISSUE THREAD

**Issue by Pokojwy** [ptitSeb/box86#152]
Hi, I have a problem trying to run Undertale installer
do you know what i have to do to make it work
`pi @ raspberrypi: ~ / Desktop $ ./undertale_en_1_08_18328.sh
Archive integrity verification ... Everything is fine.
Undertale decompress (GOG.com) 100%
Collecting information for this system ...
Warning: Binaries not found for "armv7l", default is x86 ...
Operating system: linux
CPU Arch: x86
trying mojosetup in bin / linux / x86
USING en_PL.UTF-8
./startmojo.sh: 55: ./startmojo.sh: / tmp / selfgz11346 / bin / linux / x86 / mojosetup: Exec format error
Error: Could not start mojosetup
`

maybe it matters: 

`pi@raspberrypi:~/Desktop/programs/box86/build $ ctest 
Test project /home/pi/Desktop/programs/box86/build
      Start  1: test01
 1/15 Test  #1: test01 ...........................   Passed    0.18 sec
      Start  2: test02
 2/15 Test  #2: test02 ...........................   Passed    0.17 sec
      Start  3: test03
 3/15 Test  #3: test03 ...........................   Passed    0.17 sec
      Start  4: test04
 4/15 Test  #4: test04 ...........................   Passed    0.17 sec
      Start  5: test05
 5/15 Test  #5: test05 ...........................   Passed    0.17 sec
      Start  6: test06
 6/15 Test  #6: test06 ...........................   Passed    0.18 sec
      Start  7: test07
 7/15 Test  #7: test07 ...........................   Passed    0.17 sec
      Start  8: test08
 8/15 Test  #8: test08 ...........................   Passed    0.25 sec
      Start  9: test09
 9/15 Test  #9: test09 ...........................   Passed    0.20 sec
      Start 10: test10
10/15 Test #10: test10 ...........................***Failed    0.12 sec
      Start 11: test11
11/15 Test #11: test11 ...........................   Passed    0.18 sec
      Start 12: test12
12/15 Test #12: test12 ...........................   Passed    0.19 sec
      Start 13: test13
13/15 Test #13: test13 ...........................   Passed    0.21 sec
      Start 14: test14
14/15 Test #14: test14 ...........................   Passed    0.18 sec
      Start 15: mmx
15/15 Test #15: mmx ..............................   Passed    0.19 sec

93% tests passed, 1 tests failed out of 15

Total Test time (real) =   2.76 sec

The following tests FAILED:
	 10 - test10 (Failed)
Errors while running CTest`

test 10 failed
what should do to pass this test?

sorry if my english is not very good but i can't use it very well

**Comment by ptitSeb** [comment]
Does the ctest always fail on test10? because many later test use thread, and some can give a slightly different output from time to time?
did you "make install" after the the make. And with at least 1 reboot of the pi to make sure the binfmt stuff is registered?

**Comment by Pokojwy** [comment]
test 10: I tried 4 times and it never worked
the only thing I did with box86 was: `mkdir build; cd compilation; cmake .. -DRPI3 = 1 -DCMAKE_BUILD_TYPE = RelWithDebInfo; do '
should i do something more?
(and yes, i was reboot pi after make this)

**Comment by Pokojwy** [comment]
[LastTest.log](https://github.com/ptitSeb/box86/files/4964271/LastTest.log)
i think here can be something...
maybe that help

**Comment by ptitSeb** [comment]
test 10: strange. Try to run it independantly to see the outpu with "./box86 ../test/test10`

The reboot is useless if you don't `sudo make install` first (Note: after a first reboot, you don't need to reboot fter each `sudo make install`)

**Comment by Pokojwy** [comment]
how can i run only test 10?

**Comment by Pokojwy** [comment]
and where should i `sudo make install` ?

**Comment by ptitSeb** [comment]
from `build` folder, the `sudo make install` will install box86 in the system, and after that and a reboot, from that same `build` folder, a simple `../test/test10` will launch test10 (wich is an x86 binary).

**Comment by Pokojwy** [comment]
i install and reboot, but when i try run test 10 i have that: 
`pi @ raspberrypi: ~ / Desktop / programs / box86 / build $ ../test/test10
bash: ../test/test10: There is no such file or directory`

**Comment by Pokojwy** [comment]
but now on `ctest` test 10 pass

**Comment by Pokojwy** [comment]
installer work like shuld
thanks @ptitSeb

**Comment by Pokojwy** [comment]
and i have ask: can stem run on rpi 3 B?

**Comment by ptitSeb** [comment]
Yeah it should work.

**Comment by Pokojwy** [comment]
ok, thanks
