### ISSUE TITLE
wine: could not exec wineserver error when using Wine through Box86

### ISSUE THREAD

**Issue by mathewthill** [ptitSeb/box86#154]
Downloaded wine through the website and extracted the .deb succesfully using the ar x command.

Any 32bit exe files that I run all end with wine: could not exec wineserver.

Box86 is recognising that wine is in use through this line: BOX86: Wine detected, WINEPRELOADRESERVE=""

Running my exe files through this command: ./box86 winefolder/wine exefolder/program.exe

Not sure what could be causing this issue.

**Comment by ptitSeb** [comment]
Yes, I also have reproduced that on my side and I'm investigating. Still unclear to me what triggers this (path legth?)

**Comment by mathewthill** [comment]
I have moved all my folders so the have shorter path lengths and this is still occurring. I will make the paths even shorter and see if this is still occurring.

I will also try to find other executables and see if that works.

Let me know if there is anything else that might cause this and I will try any fixes on my end.

**Comment by ptitSeb** [comment]
I'm unsure where you got your wine binary set, but I notice that there are some hardcoded path, especially in all schell wine wrappers, that can interfeare with loading process.
You may need to adjust thoses path

Another workaround is to launch wineserver independantly. No ideal, but should works.

**Comment by mathewthill** [comment]
Downloaded the binaries from https://dl.winehq.org/wine-builds/debian/ and extracted the .deb package. Is this correct?

Downloading through sudo apt install --install-recommends winehq-stable didnt work for me.

It might be that the wineserver binary was never in the .deb file and the wine install isn't setup correctly due to that.

If you could say how your wine setup was done I would appropriate it.

**Comment by ptitSeb** [comment]
Ok, but then, the folder containing wine is different then the one hardcoded.
I guess it"s supposed to be in `/usr/wine` ? I have no idea in fact, but you probably put it elsewhere. Check with the notepad shell script.

**Comment by mathewthill** [comment]
I have now moved all the wine folders to /usr/wine and have made sure the other binaries are in the /usr/wine/bin folder and this has partially fixed the issue. Every time I want to run a windows x86 binary I need to run wineserver before which is annoying but fine as a workaround for now.

**Comment by mathewthill** [comment]
After building again with your fix I now get this error while using the openarena.exe through wine

> Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
> BOX86: Wine detected, WINEPRELOADRESERVE=""
> Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
> Using default BOX86_PATH: ./:bin/
> Counted 43 Env var
> Looking for /usr/wine/bin/wine
> argv[1]="/home/pi/Downloads/openarena-0.8.8/openarena.exe"
> Using emulated /usr/wine/bin/../lib/libwine.so.1
> Using native(wrapped) libdl.so.2
> Using native(wrapped) libc.so.6
> Using native(wrapped) ld-linux.so.2
> Using native(wrapped) libpthread.so.0
> Using native(wrapped) librt.so.1
> Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
> BOX86: Wine detected, WINEPRELOADRESERVE=""
> Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
> Using default BOX86_PATH: ./:bin/
> Counted 44 Env var
> Looking for /usr/wine/bin/wine
> argv[1]="/home/pi/Downloads/openarena-0.8.8/openarena.exe"
> Using emulated /usr/wine/bin/../lib/libwine.so.1
> Using native(wrapped) libdl.so.2
> Using native(wrapped) libc.so.6
> Using native(wrapped) ld-linux.so.2
> Using native(wrapped) libpthread.so.0
> Using native(wrapped) librt.so.1
> Using emulated /usr/wine/bin/../lib/wine/ntdll.dll.so
> Using native(wrapped) libm.so.6
> 000b:err:wineboot:start_services_process Couldn't start services.exe: error 1359
> wine: failed to update L"\\??\\Z:\\home\\pi\\.wine" with L"\\\\?\\Z:\\usr\\wine\\bin\\..\\share\\wine\\wine.inf": No such file or directory
> 000b:err:seh:segv_handler Got unexpected trap 0
> Using emulated /usr/wine/bin/../lib/wine/kernel32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/advapi32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/msvcrt.dll.so
> Using emulated /usr/wine/bin/../lib/wine/opengl32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/gdi32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/user32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/ws2_32.dll.so
> Using native(wrapped) libncurses.so.6
> Using native(wrapped) libfreetype.so.6
> Using native(wrapped) libfontconfig.so.1
> Using emulated /usr/wine/bin/../lib/wine/wined3d.dll.so
> Using native(wrapped) libpng16.so.16
> Using emulated /usr/wine/bin/../lib/wine/shell32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/dinput.dll.so
> 3793|SIGSEGV @0x42387790 (???) (x86pc=0x19f4f410/"???"), for accessing (nil) (code=1)
> Segmentation fault

**Comment by ptitSeb** [comment]
Ok, but that is a different error. You can open a new one for this error, for better traking, and maybe this one can be closed (you didn't need to "prelaunch" wineserver right?)

**Comment by mathewthill** [comment]
Still needed to prelaunch wineserver for this to work. Opening this first will result in the same error.

> wine: could not exec wineserver

**Comment by ptitSeb** [comment]
with latest box86 version? That's strange, I don't have the issue any more.

Can you try to lanch again with `BOX86_LOG=2`  that will splitou a lot of log, but should still fail to load wineserver. I'm interrested in the last par on the log, start with the "execv" line where it tried to launch wineserver.

**Comment by mathewthill** [comment]
How do you run box86 with the env variables changed? I use the env command and couldn't find any of the environment variables listed here: https://github.com/ptitSeb/box86/blob/master/USAGE.md

**Comment by ptitSeb** [comment]
you just insert the `ENV=val` in front of your command, separated by a space.

**Comment by mathewthill** [comment]
Here is the log:

> 15316|0xb62f76f4: Calling execv (02D4CFF8, B6CA4C34, 0000000D...) =>execv("/usr/wine/bin/wineserver", 0xb6ca4c34) is x86=1
>  => execv("./box86", 0x2d4bce8 ["./box86", "/usr/wine/bin/wineserver", ""...:1])
>  return 0xFFFFFFFF
> 15316|0xb62f80be: Calling free (02D4CFF8, B6300105, B6CA4C18...) => return 0xFFFFFFFF
> 15316|0xb62f80e1: Calling getenv("PATH") => return 0xBECBFED6(/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:
> 15316|0xb62f80f7: Calling strlen(0xbecbfed6("/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games")) => return 0x0000006C
> 15316|0xb62f8102: Calling strlen(0x7be9b50b("wineserver")) => return 0x0000000A
> 15316|0xb62f7196: Calling malloc (00000078, 00000004, 000003E8...) => return 0x02D4D0B0
> 15316|0xb62f8135: Calling strchr (BECBFED6, 0000003A, B6CA4C18...) => return 0xBECBFEE9
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFED6, 00000013...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0C3, 7BE9B50B, 00000013...) => return 0x02D4D0C3
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/home/pi/.local/bin/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f8135: Calling strchr (BECBFEEA, 0000003A, 00000013...) => return 0xBECBFEF9
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFEEA, 0000000F...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0BF, 7BE9B50B, 0000000F...) => return 0x02D4D0BF
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/usr/local/sbin/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f8135: Calling strchr (BECBFEFA, 0000003A, 0000000F...) => return 0xBECBFF08
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFEFA, 0000000E...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0BE, 7BE9B50B, 0000000E...) => return 0x02D4D0BE
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/usr/local/bin/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f8135: Calling strchr (BECBFF09, 0000003A, 0000000E...) => return 0xBECBFF12
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFF09, 00000009...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0B9, 7BE9B50B, 00000009...) => return 0x02D4D0B9
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/usr/sbin/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f8135: Calling strchr (BECBFF13, 0000003A, 00000009...) => return 0xBECBFF1B
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFF13, 00000008...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0B8, 7BE9B50B, 00000008...) => return 0x02D4D0B8
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/usr/bin/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f8135: Calling strchr (BECBFF1C, 0000003A, 00000008...) => return 0xBECBFF21
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFF1C, 00000005...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0B5, 7BE9B50B, 00000005...) => return 0x02D4D0B5
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/sbin/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f8135: Calling strchr (BECBFF22, 0000003A, 00000005...) => return 0xBECBFF26
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFF22, 00000004...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0B4, 7BE9B50B, 00000004...) => return 0x02D4D0B4
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/bin/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f8135: Calling strchr (BECBFF27, 0000003A, 00000004...) => return 0xBECBFF37
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFF27, 00000010...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0C0, 7BE9B50B, 00000010...) => return 0x02D4D0C0
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/usr/local/games/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f8135: Calling strchr (BECBFF38, 0000003A, 00000010...) => return 0x00000000
> 15316|0xb62f8199: Calling strlen(0xbecbff38("/usr/games")) => return 0x0000000A
> 15316|0xb62f8153: Calling memcpy (02D4D0B0, BECBFF38, 0000000A...) => return 0x02D4D0B0
> 15316|0xb62f816c: Calling strcat (02D4D0BA, 7BE9B50B, 0000000A...) => return 0x02D4D0BA
> 15316|0xb62f76f4: Calling execv (02D4D0B0, B6CA4C34, 00000000...) =>execv("/usr/games/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0xb62f81b3: Calling free (02D4D0B0, 7BE9B50B, 0000000A...) => return 0x00000000
> 15316|0xb62f73e4: Calling strlen(0xb6300129("/opt/wine-stable/bin")) => return 0x00000014
> 15316|0xb62f73ee: Calling strlen(0x7be9b50b("wineserver")) => return 0x0000000A
> 15316|0xb62f7196: Calling malloc (00000020, B6CA4C34, 00000000...) => return 0x02D4D130
> 15316|0xb62f740a: Calling memcpy (02D4D130, B6300129, 00000014...) => return 0x02D4D130
> 15316|0xb62f742e: Calling strcpy (02D4D145, 7BE9B50B, 00000014...) => return 0x02D4D145
> 15316|0xb62f76f4: Calling execv (02D4D130, B6CA4C34, 00000014...) =>execv("/opt/wine-stable/bin/wineserver", 0xb6ca4c34) is x86=0
>  return 0xFFFFFFFF
> 15316|0x7bcac5fe: Calling free (02D4D130, B6CA4C34, 00000000...) => return 0x02D4D130
> 15316|0x7bcac52e: Calling fwrite (7BCE8136, 00000001, 00000006...) =>wine:  return 0x00000006
> 15316|0x7bcac540: Calling vfprintf(B6E32CF0, "could not exec wineserver
> ", ...) =>could not exec wineserver
>  return 0x0000001A
> 15316|0x7bcac54c: Calling exit (00000001, 7BCE814D, B6CA4C24...) =>Calling atexit registered functions

**Comment by ptitSeb** [comment]
Do you have this `/usr/wine/bin/wineserver`?
My guess is you installed wine in  different folder then were this build is supposed to go, and this is a sideeffect os this.

**Comment by ptitSeb** [comment]
no wait, I see in execv line that `./box86` id called.
this is supposed to be fixed. You are sure you are up-to-date?

**Comment by mathewthill** [comment]
My wine files are all in /usr/wine/bin/. I have just cloned and compiled box86 again and it still is happening. Must be my install of wine causing issues. I will try install wine through the commands on the winehq site and see if that fixes it.

**Comment by mathewthill** [comment]
Using the https://wiki.winehq.org/Debian guide wine just refuses to install due to dependency issues (buster 5.0.1).

How did you manage to install wine on the RPI4 through apt-get?

**Comment by ptitSeb** [comment]
I didn't. I built one for the occasion. But you can grab thoses fromplayonlinux it seems.

**Comment by Icenowy** [comment]
By the way I think an wineserver can be patched to run natively on ARM but accept connection from x86 wine programs.

**Comment by ptitSeb** [comment]
Wine works fine with box86, I close this ticket, feel free to re-open it if needed.
