### ISSUE TITLE
wine: Segmentation Fault when running openarena windows binary

### ISSUE THREAD

**Issue by mathewthill** [ptitSeb/box86#155]
After building again with your fix I now get this error while using the openarena.exe through wine

> Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
> BOX86: Wine detected, WINEPRELOADRESERVE=""
> Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
> Using default BOX86_PATH: ./:bin/
> Counted 43 Env var
> Looking for /usr/wine/bin/wine
> argv[1]="/home/pi/Downloads/openarena-0.8.8/openarena.exe"
> Using emulated /usr/wine/bin/../lib/libwine.so.1
> Using native(wrapped) libdl.so.2
> Using native(wrapped) libc.so.6
> Using native(wrapped) ld-linux.so.2
> Using native(wrapped) libpthread.so.0
> Using native(wrapped) librt.so.1
> Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
> BOX86: Wine detected, WINEPRELOADRESERVE=""
> Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
> Using default BOX86_PATH: ./:bin/
> Counted 44 Env var
> Looking for /usr/wine/bin/wine
> argv[1]="/home/pi/Downloads/openarena-0.8.8/openarena.exe"
> Using emulated /usr/wine/bin/../lib/libwine.so.1
> Using native(wrapped) libdl.so.2
> Using native(wrapped) libc.so.6
> Using native(wrapped) ld-linux.so.2
> Using native(wrapped) libpthread.so.0
> Using native(wrapped) librt.so.1
> Using emulated /usr/wine/bin/../lib/wine/ntdll.dll.so
> Using native(wrapped) libm.so.6
> 000b:err:wineboot:start_services_process Couldn't start services.exe: error 1359
> wine: failed to update L"\??\Z:\home\pi\.wine" with L"\\?\Z:\usr\wine\bin\..\share\wine\wine.inf": No such file or directory
> 000b:err:seh:segv_handler Got unexpected trap 0
> Using emulated /usr/wine/bin/../lib/wine/kernel32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/advapi32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/msvcrt.dll.so
> Using emulated /usr/wine/bin/../lib/wine/opengl32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/gdi32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/user32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/ws2_32.dll.so
> Using native(wrapped) libncurses.so.6
> Using native(wrapped) libfreetype.so.6
> Using native(wrapped) libfontconfig.so.1
> Using emulated /usr/wine/bin/../lib/wine/wined3d.dll.so
> Using native(wrapped) libpng16.so.16
> Using emulated /usr/wine/bin/../lib/wine/shell32.dll.so
> Using emulated /usr/wine/bin/../lib/wine/dinput.dll.so
> 3793|SIGSEGV @0x42387790 (???) (x86pc=0x19f4f410/"???"), for accessing (nil) (code=1)
> Segmentation fault

**Comment by ptitSeb** [comment]
I can run OpenArena windows version with wine with no issue now. Closing the ticket but feel free to re-open it if needed.
