### ISSUE TITLE
Missing _obstack_begin wrapping (in libc.so.6)

### ISSUE THREAD

**Issue by Icenowy** [ptitSeb/box86#160]

**Comment by ptitSeb** [comment]
That function have 2 callbacks, I'll wrap it tomorrow.

**Comment by Icenowy** [comment]
@ptitSeb Do all functions with callback need manually wrapping?

**Comment by ptitSeb** [comment]
Yes they does.

The wrapped is semi automatic, but if there is a callback, you cannot use the automatic wrapping (function is is ARM world, but callback my be in x86 world, so some bridge is needed)

**Comment by Icenowy** [comment]
Now it says
```
Warning, function my__obstack_begin not found
```

**Comment by Icenowy** [comment]
Verified to work, thanks!

**Comment by Icenowy** [comment]
Maybe we should drop all obstack wrappers now, because it seems more complex than we expected.
Although the struct's member is not meant to be accessed in user code, there're many macros in obstack.h that directly access struct's member. And the two callback functions are stored in the struct.

**Comment by Icenowy** [comment]
For this kind of complex operation, maybe have some way to wake up the i386 implementation of them will work?

**Comment by Icenowy** [comment]
GCC still fails, and I have totally no idea.

I will close this issue, and open another one if I find anything.
