### ISSUE TITLE
libexpat.so.1 missing when loading DROD 1 and DROD 3

### ISSUE THREAD

**Issue by dult** [ptitSeb/box86#161]
Hey,
I'm not the most technical savvy person so sorry in advance for any noobishness.

I've managed to get Drod 2 running on my RPI3B by placing the compiled box86 binary and placing libgcc_s.so.1, libstdc++.so.5 and libstdc++.so.6 on the its x86 folder and running:
`sudo startx /home/pi/RetroPie-GOG/DROD2jtrh/game/drod2-jtrh/Bin/linux-x86/box86 /home/pi/RetroPie-GOG/DROD2jtrh/game/drod2-jtrh/Bin/linux-x86/drod-jtrh`
Works like a charm.
For Drod 1 and Drod 3 when doing the same they complaint of this: 
`Error loading needed lib: "libexpat.so.1"
Error: loading needed libs in elf /home/pi/RetroPie-GOG/DROD3tcb/game/drod3-tcb/`
Which is a lib placed on its own folder.
What should I do to try solve this?
Thanks

**Comment by ptitSeb** [comment]
grab an x86 version of libexpat.so.1 and put it in DROD folder. That should makes the trick, unless that lib requires some other libs (than you have to do the same, grab an x86 version of the missing lib and but it in the same place)

**Comment by dult** [comment]
The game is x86 only, and that lib is already included with the game folder. I didn't change it.

**Comment by ptitSeb** [comment]
Oh, ok. But isn't there some line before where it fail to load some other lib? Can you copy/paster the whole log?

**Comment by dult** [comment]
`pi@retropie:~ $ sudo startx /home/pi/RetroPie-GOG/DROD3tcb/game/drod3-tcb/Bin/linux-x86/box86 /home/pi/RetroPie-GOG/DROD3tcb/game/drod3-tcb/Bin/linux-x86/drod-tcb


X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.9.41-v7+ armv7l Raspbian
Current Operating System: Linux retropie 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l
Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=1366 bcm2708_fb.fbheight=768 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait loglevel=3 consoleblank=0 plymouth.enable=0
Build Date: 18 October 2017  04:55:30PM
xorg-server 2:1.19.2-1+rpt1+deb9u2 (https://www.debian.org/support)
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Fri Jul 31 10:30:15 2020
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
modprobe: FATAL: Module g2d_23 not found in directory /lib/modules/4.14.98-v7+
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 19 Env var
Looking for /home/pi/RetroPie-GOG/DROD3tcb/game/drod3-tcb/Bin/linux-x86/drod-tcb
Error loading needed lib: "libexpat.so.1"
Error: loading needed libs in elf /home/pi/RetroPie-GOG/DROD3tcb/game/drod3-tcb/Bin/linux-x86/drod-tcb
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.
`

**Comment by dult** [comment]
If I send you the binaries will that help?
Thanks

**Comment by ptitSeb** [comment]
Do you still have issues with thoses games or are they running now. If they run, please close the ticket.

**Comment by dult** [comment]
DROD 1 I managed to get working.
I'll try to recompile to check if there are any changes to DROD 3.
Thanks

**Comment by dult** [comment]
I've compiled Box86 more recently, and the only bugs it's showing now are relative to x-server.
Thanks.
