### ISSUE TITLE
DDLC runing error

### ISSUE THREAD

**Issue by Pokojwy** [ptitSeb/box86#162]
hi, i have problem when i try to run DDLC. when i try to run `DDLC.sh`, i have that error
```
pi@raspberrypi:~/Desktop/DDLC-1.1.1-pc $ ./DDLC.sh 
Ren'Py could not detect that platform it's running on. Please set
the RENPY_PLATFORM environment variable to one of "linux-i686" or
"linux-x86_64", or "darwin-x86_64" and run this command again.
```
and when i try to run it using `box86 ./DDLC.sh`
```
pi@raspberrypi:~/Desktop/DDLC-1.1.1-pc $ box86 ./DDLC.sh 
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 44 Env var
Looking for ./DDLC.sh
Not an ELF file (sign=#!/b)
Error: reading elf header of ./DDLC.sh
pi@raspberrypi:~/Desktop/DDLC-1.1.1-pc $ 
```
i think that should run on rpi 3, i seen program from GitHub to launch it, but i'd like to run it using box86
what should i do to it work can work, and if i should change `RENPY_PLATFORM`, where and how i can set it?

sorry about my English, i can't use it very well

edit: I'm using a different language version that works on x86 windows (sorry, i can't send files, because zip is bigger than 10 MB)

edit 2: i just change some files on translated

**Comment by ptitSeb** [comment]
Try like this: `RENPY_PLATFORM=linux-i686 ./DDLC.sh`

**Comment by Pokojwy** [comment]
```
pi@raspberrypi:~/Desktop/ddlc-win/DDLC-1.1.1-pc $ sudo RENPY_PLATFORM=linux-i686 ./DDLC.sh
./DDLC.sh: 77: exec: /home/pi/Desktop/ddlc-win/DDLC-1.1.1-pc/lib/linux-i686/DDLC: Permission denied
pi@raspberrypi:~/Desktop/ddlc-win/DDLC-1.1.1-pc $ RENPY_PLATFORM=linux-i686 ./DDLC.sh
./DDLC.sh: 77: exec: /home/pi/Desktop/ddlc-win/DDLC-1.1.1-pc/lib/linux-i686/DDLC: Permission denied
pi@raspberrypi:~/Desktop/ddlc-win/DDLC-1.1.1-pc $ ./DDLC.sh
Ren'Py could not detect that platform it's running on. Please set
the RENPY_PLATFORM environment variable to one of "linux-i686" or
"linux-x86_64", or "darwin-x86_64" and run this command again.
```
i don't know why, but that don't work...

**Comment by rajdakin** [comment]
1. What do you mean it can run on Windows? Do you need to use Wine to run it on Linux?
2. Can you tell us the result of `ls -l lib/*/DDLC`? (Also, it seems strange that it tries to execute a library... Is there a `bin` folder where `DDLC.sh` is?)

**Comment by Pokojwy** [comment]
1. ddlc version is the same on linux and on windows, folder look that
![2020-08-01-165136_800x480_scrot](https://user-images.githubusercontent.com/68324219/89104141-52fefb80-d417-11ea-887c-a60c76e839f8.png)
here is 2 files, one on windows and one on linux

2. when i use `ls -l lib/*/DDLC` when `DDLC.sh` is i have that
```
pi@raspberrypi:~/Desktop/ddlc-win/DDLC-1.1.1-pc $ s -l lib/*/DDLC
bash: s: nie znaleziono polecenia

```

**Comment by Pokojwy** [comment]
sorry i copied command wrong
```
i@raspberrypi:~/Desktop/ddlc-win/DDLC-1.1.1-pc $ ls -l lib/*/DDLC
-rw-r--r-- 1 pi pi 10591 kwi  9  2018 lib/linux-i686/DDLC
-rw-r--r-- 1 pi pi 11754 kwi  9  2018 lib/linux-x86_64/DDLC
```

**Comment by rajdakin** [comment]
Can you copy-paste the content of `DDLC.sh` or is too big? And what is inside the `game` folder? (Also, as I thought, the `DDLC` inside `lib` isn't meant to be executed unless the permissions are messed up after being in the package, there is no `x` on the left.)

**Comment by Pokojwy** [comment]
DDLC.sh look taht
#!/bin/sh

```
SCRIPT="$0"

# Resolve the chain of symlinks leading to this script.
while [ -L "$SCRIPT" ] ; do
    LINK=$(readlink "$SCRIPT")

    case "$LINK" in
        /*)
            SCRIPT="$LINK"
            ;;
        *)
            SCRIPT="$(dirname "$SCRIPT")/$LINK"
            ;;
    esac
done

# The directory containing this shell script - an absolute path.
ROOT=$(dirname "$SCRIPT")
ROOT=$(cd "$ROOT"; pwd)

# The name of this shell script without the .sh on the end.
BASEFILE=$(basename "$SCRIPT" .sh)

if [ -z "$RENPY_PLATFORM" ] ; then
    case "$(uname -s)-$(uname -m)" in
        Darwin-*)
            RENPY_PLATFORM="darwin-x86_64"
            ROOT1="$ROOT/../Resources/autorun"
            ROOT2="$ROOT/../../.."
                        ;;
        *-x86_64|amd64)
            RENPY_PLATFORM="linux-x86_64"
            ROOT1="$ROOT"
            ROOT2="$ROOT"
                        ;;
        *-i*86)
            RENPY_PLATFORM="linux-i686"
            ROOT1="$ROOT"
            ROOT2="$ROOT"
            ;;
        *)
            echo "Ren'Py could not detect that platform it's running on. Please set"
            echo "the RENPY_PLATFORM environment variable to one of \"linux-i686\" or"
            echo "\"linux-x86_64\", or \"darwin-x86_64\" and run this command again."
            exit 1
            ;;
    esac
fi


for BASE in "$ROOT" "$ROOT1" "$ROOT2"; do
    LIB="$BASE/lib/$RENPY_PLATFORM"
    if test -d "$LIB"; then
        break
    fi
done

for BASE in "$ROOT" "$ROOT1" "$ROOT2"; do
    if test -e "$BASE/$BASEFILE.py"; then
        break
    fi
done

if ! test -d "$LIB"; then
    echo "Ren'Py platform files not found in any of $ROOT, $ROOT1 or $ROOT2!"
    echo "Please compile the platform files using the instructions in README.md"
    echo "or point them to an existing installation using ./after_checkout.sh <path>."
    exit 1
fi

if test -n "$LD_LIBRARY_PATH"; then
    export LD_LIBRARY_PATH="$LIB:$LD_LIBRARY_PATH"
fi

exec $RENPY_GDB "$LIB/$BASEFILE" $RENPY_PYARGS -EO "$BASE/$BASEFILE.py" "$@"

```
and in game i have 
```
pi@raspberrypi:~/Desktop/ddlc-win/DDLC-1.1.1-pc/game $ ls
audio.rpa         poems_special.rpyc  script-ch4.rpyc
cgs.rpyc          poemwords.txt       script-ch5.rpyc
console.rpyc      python-packages     script-exclusives2-natsuki.rpyc
credits.rpyc      screens.rpyc        script-exclusives2-yuri.rpyc
definitions.rpyc  script-ch0.rpyc     script-exclusives-natsuki.rpyc
effects.rpyc      script-ch10.rpyc    script-exclusives-sayori.rpyc
firstrun          script-ch1.rpyc     script-exclusives-yuri.rpyc
fonts.rpa         script-ch20.rpyc    script-poemgame.rpyc
glitchtext.rpyc   script-ch21.rpyc    script-poemresponses2.rpyc
gui               script-ch22.rpyc    script-poemresponses.rpyc
gui.rpyc          script-ch23.rpyc    script.rpyc
images            script-ch2.rpyc     scripts.rpa
images.rpa        script-ch30.rpyc    splash.rpyc
options.rpyc      script-ch3.rpyc     transforms.rpyc
poems.rpyc        script-ch40.rpyc
```

**Comment by Pokojwy** [comment]
but `gui` `images` and `python-packages` is folders

**Comment by rajdakin** [comment]
Well, I think you need to download [Run'Py](https://www.renpy.org/latest.html) and then use it to start the game. There is no real executable, apart from that bash script (and a `.exe` which I am pretty sure does the same thing), and to start the game using that bash script you need to set environments variables like `RENPY_GDB` which I am pretty sure shouldn't be touched by the user...

**Comment by Pokojwy** [comment]
ok, but i have ask:
how to use that, if i have `renpy-7.3.5-raspi.tar.bz2` (what should do with that file to it work?)
that rpi version of that

**Comment by Pokojwy** [comment]
hi @rajdakin can you tell me how to install ren'py?

**Comment by rajdakin** [comment]
Well, I don't know but if there is an ARM (raspberry Pi) version of it you should be able to execute the game natively (no need to use box86).
[Quoting the Quickstart in the documentation:](https://www.renpy.org/doc/html/quickstart.html)
> On Linux, unpack the tarball, change into the renpy-<version> directory, and then run renpy.sh.
> After running this, the Ren'Py launcher should run.
> 
> The Ren'Py launcher has been translated to multiple languages. To change the language, choose "preferences" at the bottom right, and then select the language.
> 
> **Choosing and Launching a Project.** You should first see what the completed The Question game looks like. To do this, start the Ren'Py launcher, and choose "The Question" from the first screen. Choose "Launch Project" to start The Question.
I guess you have to extract the tarball, and inside should be a folder named `projects` or something like that (and don't ask me the details, I don't know...). You should move your DDLC folder in there, then start the launcher (or hit refresh if it was already started). (Do note that I don't known anything about Ren'Py, so if it doesn't work, search on the Web...)

**Comment by Pokojwy** [comment]
ok thanks
i will try
