### ISSUE TITLE
Steam, the binding of isaac afterbirth+

### ISSUE THREAD

**Issue by jk101290** [ptitSeb/box86#164]
I'm not sure if this is the right place to ask about this so please forgive me if its isn't

I started using twister os on Rpi 4 and noticed it comes with steam, and I started reading up on this box86 thing. Well I'd love to get "the binding of issac afterbirth+" working but the game will not launch. Ive done some searching and ive seen a couple videos of people demonstrating "the binding of isaac: rebirth" in box86. 

I have the DLC (called afterbirth+) and I cant get it to launch, steam will show running... then close. 

I can see that box86 is still in early development so if there's a chance that this could be looked into and possibly fixed, thatd be awesome!

Also I'm no expert but I looked into the steam directory where the game is stored (steamapps/common) and saw that theres a launcher for i386 and one for x64. I tried launching them both manually in the terminal but neither worked. 

Thanks for any help and thanks for making awesome software 🤘

**Comment by ptitSeb** [comment]
I don't have this game on my steam collection (only regular Binding of Isaac). Is the problem still happening?

(sorry for the long delay in response :( )

**Comment by jk101290** [comment]
> I don't have this game on my steam collection (only regular Binding of Isaac). Is the problem still happening?
> 
> (sorry for the long delay in response :( )

Hi, I never got it to work and ended up sticking with my PC for this game.
