### ISSUE TITLE
question about wine

### ISSUE THREAD

**Issue by Pokojwy** [ptitSeb/box86#181]
hi, i have a question
i'd like to run exe on raspberry pi using wine, but i don't know

* how to compile it
* from where should i take it (is that `sudo apt-get install wine`?)
* how to use it with box86 

can anyone help me?

and, i have another question: is there any file like `cmake_install.cmake` to update?
because when  some time i need to update, i have to uninstall, remove box86 and install again, so i think its will be easier, if i can do it like `sudo make update`

_sorry if i made mistakes, i can't use english very well_

**Comment by ptitSeb** [comment]
Wine needs to be compile on linux x86. You cannot apt install it for this reason (unless you have setup proprer multiarch with x86, which is not trivial at all). box86, once compiled and `sudo make install` is done, just work magicaly, you don't need to call it.

To update "box86", go into the folder where you clone box86, and type `git pull`: it will update the sources. Then do again the `sudo make install` and it will build the update and install it. No need to unstall redo everything.

I suggest you take a look at TwisterOS ( https://twisteros.com/ ), it's a mod of RaspberryPI OS with everything installed. Well, if you have a RPi4.

**Comment by Pokojwy** [comment]
ok, thanks for information about upadate, but i still no sure what should i do to have working wine on mi pi
i heard about TwisterOS, but i haven't RPi 4 (yet, i'd like to buy, but i can't now)

**Comment by ptitSeb** [comment]
The easier would be for you to grab the WINE version that is inside twisteros. Grab the image, and extract the "/home/pi/wine" folder. It contains a wine x86 version built to be in "/home/pi/wine"

**Comment by Pokojwy** [comment]
ok, thanks
if i throw this `folder into home / pi`
and reboot it will work?

**Comment by ptitSeb** [comment]
No need to reboot. You'll be able tu use wine. After extracting try `~/wine/bin/wine winecfg` to launch wine config dialog... You can also `~/wine/bin/wine winemine` for minesweeper...

**Comment by Pokojwy** [comment]
ok, i'l try
i must download it, what can take some time

**Comment by Pokojwy** [comment]
can i do all of that on raspberry pi?
(i thing about extracting file)

**Comment by ptitSeb** [comment]
Probably yes. But maybe it will be easier if you take the "TwisterOS 1.3 to 1.41 patch" zip. It should contains full Wine binary, and is just a zip...

**Comment by ptitSeb** [comment]
Yeah, I checked, and it's much easier with the zip. wine folder is inside "patch" folder...

**Comment by Pokojwy** [comment]
i think zip will be easier

**Comment by Pokojwy** [comment]
ok i have it
should i now move folder `home/pi/Downloads/TwisterOSv1-4-1Patch/patch/wine` to `home/pi/`?

**Comment by ptitSeb** [comment]
yes

**Comment by Pokojwy** [comment]
after move `wine` to `/home/pi` and using `~/wine/bin/wine winecfg` i have
```
pi@raspberrypi:~/wine $ ~/wine/bin/wine winecfg
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 44 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="winecfg"
Using emulated /home/pi/wine/bin/../lib/libwine.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/ntdll.so
Using native(wrapped) libm.so.6
err:module:check_vmsplit Warning: memory above 0x80000000 doesn't seem to be accessible.
Wine requires a 3G/1G user/kernel memory split to work properly.
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="winecfg"
Using emulated /home/pi/wine/bin/../lib/libwine.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /home/pi/wine/lib/wine/ntdll.dll.so
err:virtual:virtual_alloc_first_teb wine: failed to map the shared user data: c0000018
```

**Comment by Pokojwy** [comment]
then i have `err:virtual:virtual_alloc_first_teb wine: failed to map the shared user data: c0000018`
if i good think i have error in user data (or that can't read it)

**Comment by ptitSeb** [comment]
try with `setarch linux32 -L ~/wine/bin/wine winecfg`

**Comment by Pokojwy** [comment]
stil error on end is the same
```
pi@raspberrypi:~/wine $ setarch linux32 -L ~/wine/bin/wine winecfg
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 44 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="winecfg"
Using emulated /home/pi/wine/bin/../lib/libwine.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/ntdll.so
Using native(wrapped) libm.so.6
err:module:check_vmsplit Warning: memory above 0x80000000 doesn't seem to be accessible.
Wine requires a 3G/1G user/kernel memory split to work properly.
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="winecfg"
Using emulated /home/pi/wine/bin/../lib/libwine.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /home/pi/wine/lib/wine/ntdll.dll.so
err:virtual:virtual_alloc_first_teb wine: failed to map the shared user data: c0000018

```

**Comment by ptitSeb** [comment]
Are you using latest box86? Also, on what hardware are you running exactly?

**Comment by ptitSeb** [comment]
Oh, wait
I see that on your log: `err:module:check_vmsplit Warning: memory above 0x80000000 doesn't seem to be accessible.`

Your Kernel is configure 2G/2G (2GB for userspace, 2GB for Kernel). Wine cannot run on this configuration. You need a kernel configure as 3G/1G.
There is nothing I can do there, you need to fix that.

**Comment by Pokojwy** [comment]
ok, how can i do this?
(heh, undertale work)

**Comment by ptitSeb** [comment]
Yeah, Linux x86 app/games will work, but not Wine.

I don't know how to do this. Maybe just upgrade your distribution with `sudo apt dist-upgrade`? Reconfiguring a kernel can be tricky, and I'm not the specialist here.

**Comment by Pokojwy** [comment]
ok, i will try to do it, but i can't  `sudo apt dist-upgrade` today after my country 20.00 i have veery bad internet, and i must reboot it all hour
if i can do it any another way, i do this
if no, i do this tomorrow

**Comment by Pokojwy** [comment]
ok, i have idea what i need
i'l take 3G/1G kernel and take it in `/boot`
after that, i need only make 2 file: 3G/1G and 2G/2G. in that file if i have
```
cd /boot
echo " (file config.txt content with set appropriate kernel)" > config.txt
reboot
```
ok, now i must find kernel 3G/1G (or configure but i can't)

**Comment by Pokojwy** [comment]
is kernel using [here](https://www.raspberrypi.org/forums/viewtopic.php?t=226376) can work on raspbian? (that makes for debian scretch i have raspbian)

**Comment by Pokojwy** [comment]
i think that didn't work

**Comment by Pokojwy** [comment]
i must find difrend

**Comment by Pokojwy** [comment]
ok, i'l try configure kernel

**Comment by Pokojwy** [comment]
i have that:
![2020-08-15-111727_800x480_scrot](https://user-images.githubusercontent.com/68324219/90309441-fad0fa80-dee8-11ea-8ac5-7c234dc88384.png)

any idea where that 3G/1G can be?

**Comment by ptitSeb** [comment]
I don't know.
Here is the relevent thread in the PI forum about that issue: https://www.raspberrypi.org/forums/viewtopic.php?t=226376
But not sure there is the answer to your question there.

**Comment by Pokojwy** [comment]
ok, what should i set (here is 2 3G/1G)
![2020-08-15-112902_800x480_scrot](https://user-images.githubusercontent.com/68324219/90309648-9f077100-deea-11ea-8aa0-acec14a99d3d.png)

**Comment by Pokojwy** [comment]
i found it, but i'm not sure which one should i use

**Comment by ptitSeb** [comment]
Yes, it should be the 1st one.

**Comment by Pokojwy** [comment]
ok, that now making and installing
that... take some time
i hope that work like should

**Comment by Pokojwy** [comment]
ok, i have it, but what should i do in vine config?

**Comment by ptitSeb** [comment]
nothing, it's just to test everything loadup correctly.

**Comment by Pokojwy** [comment]
on `~/wine/bin/wine winecfg` i have configuration window
here is choise: windows 7 etc.
can i set here windows 10?

**Comment by ptitSeb** [comment]
Yes, if you want. Try other stuff now. Like the Skyfree.exe that was also on that zipped patch. That's a true x86 Windows game (a simple one, but still).

**Comment by Pokojwy** [comment]
ok, something no work
```
pi@raspberrypi:~/Desktop/SkiFree $ ls
ski32.exe  skifree.desktop  SkiFree.png
pi@raspberrypi:~/Desktop/SkiFree $ ./ski32.exe 
bash: ./ski32.exe: Failed to start binary: Wrong executable format
```

**Comment by ptitSeb** [comment]
no, it's a windows binary, you need to launch it with wine (it's not automagic like x86 linux binary). So use `~/wine/bin/wine ./ski32.exe`

**Comment by Pokojwy** [comment]
umm, ok (that's why i ask how to use that)

**Comment by Pokojwy** [comment]
ok, doesn't work
again
```
pi@raspberrypi:~/wine $ ~/wine/bin/wine ./ski32.exe
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 44 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="./ski32.exe"
Using emulated /home/pi/wine/bin/../lib/libwine.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/ntdll.so
Using native(wrapped) libm.so.6
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="./ski32.exe"
Using emulated /home/pi/wine/bin/../lib/libwine.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /home/pi/wine/lib/wine/ntdll.dll.so
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for /home/pi/wine/bin/wineserver
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
wine: cannot find L"./ski32.exe"
```

**Comment by Pokojwy** [comment]
i added that in wine

**Comment by ptitSeb** [comment]
why did you cd in wine???

stay in skyfree folder, and will work.

**Comment by Pokojwy** [comment]
.... i don't know, i think that should be in wine
ok, sorry, i'm stupid some time

**Comment by ptitSeb** [comment]
Don't worry about wine... Just go in the folder of the app you want to run and launch it (with wine). and that's all.

**Comment by Pokojwy** [comment]
ok, thanks for all.
should i now close the issue?

**Comment by Pokojwy** [comment]
last ask. can i use `-f4` to use all CPU cores on maximum?
because when i make kernel, that was useful.

**Comment by ptitSeb** [comment]
`-f4` ? Do you mean `-j4` witch on `make`?
Anyway, the windows app will use the number of cpu it's designed for. You cannot force it to use more CPU (or thread) it's supposed to use. And it will use all 4 cpu if it can.

Also, yeah, I think you can close the ticket. Open a new one if you have new issues (just check for existing ticket before).

**Comment by Pokojwy** [comment]
ok, thanks
right, i have mistake in that `-j4`
