### ISSUE TITLE
PortableApps installers crash when dynarec is enabled

### ISSUE THREAD

**Issue by icecream95** [ptitSeb/box86#182]
PortableApps.com installers (for example, the one for [Chromium B.S.U.](https://portableapps.com/apps/games/chromium_bsu_portable)) crash when dynarec is enabled, but work with `BOX86_DYNAREC=0`.

**Comment by ptitSeb** [comment]
I'll check with Chromium B.S.U.
But I just tied with PortableSudoku and it installed (and ran) without issue with current box86.

**Comment by ptitSeb** [comment]
Just checked Chromium B.S.U. Portable and it was also working for me, with Dynarec. (I guess I have fixed it with some previous opcode adjustement in the Dynarec).
Can you check it's working on your side too?

**Comment by ptitSeb** [comment]
I assume this ticket can be closed now @icecream95
