### ISSUE TITLE
PlantsVsZombies does not work when dynarec is enabled.

### ISSUE THREAD

**Issue by pmtip** [ptitSeb/box86#183]
But when I turn off dynarec, it works.
@ptitSeb can you fix?

**Comment by ptitSeb** [comment]
I now reproduce the issue. I'll see what I can do.

**Comment by pmtip** [comment]
Still can't run.

**Comment by pmtip** [comment]
It still does not work when dynarec is enabled.

**Comment by pmtip** [comment]
The gog game installer also does not work when dynarec is enabled.

**Comment by ptitSeb** [comment]
I know, I haven't fixed it yet. And I'm aware for GOG Setup not working (with an EAbstract exception) on dynarec. It seems Sega Rally and a few other also have issue with Dynarec.

**Comment by ptitSeb** [comment]
It should be fixed now (and GOG Setup too).

**Comment by pmtip** [comment]
OK,thank you.
