### ISSUE TITLE
Diablo2 cannot run with "-d3d" option.

### ISSUE THREAD

**Issue by pmtip** [ptitSeb/box86#184]
@ptitSeb

**Comment by ptitSeb** [comment]
It's probably some d3d -> opengl that doesn't work because of some missing opengl function in the mesa driver. I don't think Box86 is at foult here.

**Comment by pmtip** [comment]
So what should I do.

**Comment by pmtip** [comment]
So no way?

**Comment by ptitSeb** [comment]
why not using opengl instead?

**Comment by pmtip** [comment]
OK.
