### ISSUE TITLE
Stack corruption while initialising dri3 with Gallium Nine 

### ISSUE THREAD

**Issue by icecream95** [ptitSeb/box86#185]
When trying to run the [Gallium Nine Standalone](https://github.com/iXit/wine-nine-standalone) configuration tool (ninewinecfg.exe), it crashes in [dri3_create](https://github.com/iXit/wine-nine-standalone/blob/b1f4581b8b329987877d69b5f4c8001dd514749a/d3d9-nine/dri3.c#L26) due to stack corruption.

To have Gallium Nine support, Mesa will need to be compiled with `-Dgallium-nine=true` and the error about needing a "non-swrast gallium driver" might need to be commented out from meson.build.

I'm using the [Arch package](https://www.archlinux.org/packages/multilib/x86_64/wine-nine/download/) for the wine part of Gallium Nine, which requires `d3dadapter9.so.1` from Mesa to be at `/usr/lib32/d3d/d3dadapter9.so.1`.

`d3d9-nine.dll.so` from `usr/lib32/wine` in the package will need to be copied to `d3d9-nine.dll` in `wine winepath -u 'c:\windows\system32'`.

```
7668|0xb52b12f4: Calling XGetXCBConnection (05F92D80, B52B9F64, B52B9F3C...) => return 0x05F936D8
 ...  =>PltResolver: Addr=0x5f5bc58, Slot=336 Return=0xb52b1312: elf is /home/ixn/.wine/dosdevices/c:/windows/system32/d3d9-nine.dll
PltReolver: Apply Global R_386_JMP_SLOT @0xb52ca0b4 with sym=xcb_dri3_open (0xb52a92e6 -> 0xb6f75310 / /files/lib/libxcb-dri3.so.0)
 return 0x05F92548
7668|0xb6f75375: Calling xcb_send_request (05F936D8, 00000009, 1021E6E8...) => return 0x0000000B
 ...  =>PltResolver: Addr=0x5f5bc58, Slot=48 Return=0xb52b1320: elf is /home/ixn/.wine/dosdevices/c:/windows/system32/d3d9-nine.dll
PltReolver: Apply Global R_386_JMP_SLOT @0xb52ca024 with sym=xcb_dri3_open_reply (0xb52a90a6 -> 0xb6f75430 / /files/lib/libxcb-dri3.so.0)
 return 0x0000039C
7668|0xb6f75450: Calling xcb_wait_for_reply (05F936D8, 0000000B, 00000000...) => return 0x05F8BC58
 ...  =>PltResolver: Addr=0x5f5bc58, Slot=536 Return=0xb52b133f: elf is /home/ixn/.wine/dosdevices/c:/windows/system32/d3d9-nine.dll
PltReolver: Apply Global R_386_JMP_SLOT @0xb52ca118 with sym=xcb_dri3_open_reply_fds (0xb52a9476 -> 0xb6f75460 / /files/lib/libxcb-dri3.so.0)
 return 0x05F8BC58
 ...  =>PltResolver: Addr=0x5f6d2c0, Slot=48 Return=0xb6f75488: elf is /files/lib/libxcb-dri3.so.0
PltReolver: Apply Global R_386_JMP_SLOT @0xb6f79024 with sym=xcb_get_reply_fds (0xb6f75096 -> 0x582c964 / (noelf))
 return 0x05F8BC58
7668|0xb6f75488: Calling xcb_get_reply_fds (05F936D8, 05F8BC58, 00000020...) => return 0x05F8BC78
7668|0xb52b134e: Calling fcntl64 (00000010, 00000002, 00000001...) =>Trying to Get "libc.so.6" to maplib
 return 0x00000000
7668|0xb52b135a: Calling free (05F8BC58, 00000002, 00000001...) => return 0x00000000
7668|0x7bc6fc0a: Calling memset (103F99C0, 00000000, 0000000C...) => return 0x103F99C0
 ...  =>PltResolver: Addr=0x5f5bc58, Slot=640 Return=0xb52b129c: elf is /home/ixn/.wine/dosdevices/c:/windows/system32/d3d9-nine.dll
PltReolver: Apply Global R_386_JMP_SLOT @0xb52ca14c with sym=close (0xb52a9546 -> 0x48d0f70 / (noelf))
 return 0x00000001
7668|0xb52b129c: Calling close (00000010, 00000008, 00000000...) => return 0x00000000
 ...  =>PltResolver: Addr=0x5f5bc58, Slot=168 Return=0xb52b8ce8: elf is /home/ixn/.wine/dosdevices/c:/windows/system32/d3d9-nine.dll
PltReolver: Apply Global R_386_JMP_SLOT @0xb52ca060 with sym=__stack_chk_fail (0xb52a9196 -> 0x489bc50 / (noelf))
 return 0x93FA68ED
7668|0xb52b8ce8: Calling __stack_chk_fail (05F92D80, 00000001, B52CA000...) =>0x48dd818: Stack is corrupted, aborting
CPU Regs=EAX=93fa68ed ECX=1021e74c EDX=10000064 EBX=b52ca000 FLAGS=--PA--
ESP=1021e7b8 EBP=b52cb258 ESI=00000001 EDI=05f92d80 EIP=0489bc5b
 return 0x93FA68ED
 return 0x00000000
Emulation finished, EAX=0
```

**Comment by ptitSeb** [comment]
Interesting.

I guess the d3dadapter9.so.1 would need wrapping to get better performances (I haven't looked at how many function that would represent).

Now, for the stack corruption, a x86 trace would be needed, but building Zydis library can be a bit tricky to build... Maybe at least a "BOX86_DYNAREC_DUMP=2" can help (but again, with wine launching many process, it's not trivial to get traces).

I will look at Gallium-nine, but just not yet.

**Comment by icecream95** [comment]
For wrapping, so far I have this patch to box86:

[box86-nine.patch.txt](https://github.com/ptitSeb/box86/files/5080650/box86-nine.patch.txt)

Maybe more will be needed, but for now it's enough to get it to start initialisation.

**Comment by ptitSeb** [comment]
For d3dadapter.so.1 wrapping, `D3DAdapter9GetProc(...)` function return function pointer, so like `glGetProcAddress(...)` it will need special care and cannot just return unwrapped pointers.

For the cxb_* function, also, I'm afraid it's not that simple. All xcb_* function return `xcb_get_property_cookie_t` structure. So you need to wrap them. Look at source, I have set some macro for that in the .c source. Also, using GOS(...) will fix the stack curruption message (as return a Struct in x86 make the return a `RETN 2`, instead of a simple `RET`).

**Comment by icecream95** [comment]
Wrapping `D3DAdapter9GetProc` (but not doing anything special in it) allows it to get further, and it crashes when trying to call the function `D3DAdapter9GetProc` returns, as expected.

That wrapping the function without making any changes to what happens fixed the stack corruption doesn't inspire much confidence that it was a real fix, but at least I can get on to properly wrapping stuff now...

**Comment by icecream95** [comment]
All of the functions for Gallium Nine are stdcall, so the stack needed to be popped by the callee.
