### ISSUE TITLE
Red Alert 2 is not working properly.

### ISSUE THREAD

**Issue by pmtip** [ptitSeb/box86#190]

**Comment by pmtip** [comment]
And I can't quit.

**Comment by ptitSeb** [comment]
Why are you closing it? It's working now?

**Comment by pmtip** [comment]
I don't know. I'll try.

**Comment by pmtip** [comment]
Oh,It's working now.

**Comment by pmtip** [comment]
It is work on wine3.0,but did not work on wine5.15.

**Comment by pmtip** [comment]
@ptitSeb Is wine fault?

**Comment by pmtip** [comment]
@ptitSeb If you wrapped the c++ library, will box86 be much faster than before?

**Comment by pmtip** [comment]
Now box86 is slower than exagear.

**Comment by ptitSeb** [comment]
It works with wine3.0 from exagear?

Also, what c++ library? (for now, wrapping of C++ library is not on the Roadmap)
How much slower is box86 than exagear, and how do you test that?

**Comment by pmtip** [comment]
Yes, it can work on wine eltechs. The c++ library is libstdc++. I tested Diablo2 and it is slower than exagear without opengl, but it is faster with opengl.

**Comment by pmtip** [comment]
Will you wrap libstdc++ in the future?

**Comment by pmtip** [comment]
And, do you think box86 will be faster than exagear in the future?

**Comment by ptitSeb** [comment]
> Yes, it can work on wine eltechs. The c++ library is libstdc++. I tested Diablo2 and it is slower than exagear without opengl, but it is faster with opengl.

Ah ok. Well, from what I understood, box86 dynarec is faster than Qemu but slower than Exagear (only counting pure CPU emulation).



> Will you wrap libstdc++ in the future?

Not in the near future. Wrapping c++ library is more complicated than C libraary becasue of the concept of VTable. Maybe one day I'll have a look. Also libstdc++ contains thousands of symbol, so an automated way need to be found.



> And, do you think box86 will be faster than exagear in the future?

I don't know. Probably a bit. But more dynarec speedup will require some refactoring, and some more inter-opcode optimisations...

**Comment by pmtip** [comment]
How should I compile the gl4es Android version, I will only compile the static link library.

**Comment by pmtip** [comment]
How compile a dynamic link library.

**Comment by rajdakin** [comment]
Set STATICLIB to OFF when `cmake`-ing (aka, something lke `cmake .. -DSTATICLIB=OFF`), then compile (note that this is specific to gl4es and not a general rule).

**Comment by pmtip** [comment]
But I use ndk to compile gl4es.

**Comment by pmtip** [comment]
@ptitSeb  I am running box86 in android chroot,wine does not work when dynarec is enabled.It will loop this error.
000e:err:seh:segv_handler Got unexpected trap 0
