### ISSUE TITLE
Run wine in the android chroot.

### ISSUE THREAD

**Issue by pmtip** [ptitSeb/box86#192]
Loop this error.
0010:err:seh:segv_handler Got unexpected trap 0

**Comment by pmtip** [comment]
@ptitSeb I added RPI4=1 after cmake, it worked.Can you tell me why?

**Comment by pmtip** [comment]
I tried DGAMESHELL=1, it also works.

**Comment by ptitSeb** [comment]
those are mainly some optimized CFLAGS for the targetted hardware. Why shouldn't it work?

**Comment by pmtip** [comment]
Can you tell me how best to solve this error?

**Comment by pmtip** [comment]
It also crashed in my other phone.

**Comment by pmtip** [comment]
Box86 seems to let the fopen function get a fake /proc/cpuinfo, but it doesn't seem to work in the stdc++ library.
I tested the fstream of the stdc++ library to open /proc/cpuinfo, and the output, it is no different from the real cpuinfo, and /proc/self/exe is also box86 itself.
i don't know if this is a bug of box86.

**Comment by ptitSeb** [comment]
Could be considered as a bug yes. Do you know wich C function is called for fstream?

**Comment by pmtip** [comment]
Does fstream call fopen... in libc to open the file?

**Comment by pmtip** [comment]
Can you tell me why fstream read the real /proc/cpuinfo?

**Comment by ptitSeb** [comment]
I cannot tell you (unless I dig into libstdc++ sources, and I prefer not to do that), that was my question. But you can: iy seems you have a sample c++ program that simply open and read /proc/cpuinfo right?. Then launch it using "BOX86_LOG=2" to see all wrapped function used, so that way you'll see wich libc function is used for fstream.

**Comment by pmtip** [comment]
How should I get your sample program?

**Comment by ptitSeb** [comment]
I don't have a sample. I thought you had one.

How do you know fstream doesn't work???

**Comment by pmtip** [comment]
I used some functions in fstream to open and output /proc/cpuinfo.
So I can use my program?

**Comment by ptitSeb** [comment]
Yes.
Your program is built on a x86 system? The yes, use that one.

**Comment by pmtip** [comment]
Yes,Is built on x86 linux.

**Comment by pmtip** [comment]
stdc++ used fopen64 to open /proc/cpuinfo.
27034|0xb5fc107e: Calling fopen64("/proc/cpuinfo", "r") => return 0x031DFC38

**Comment by pmtip** [comment]
Can you solve this problem now?

**Comment by pmtip** [comment]
I think you should make fopen64 return fake cpuinfo when use fopen64 to open /proc/cpuinfo.

**Comment by ptitSeb** [comment]
Yeah, I'll fix that, and make fopen64 use the fake cpuinfo.

**Comment by pmtip** [comment]
I have a question, will you modify wine in the future to improve the speed of wine on box86?

**Comment by pmtip** [comment]
Now, wine eltechs is much faster than ordinary wine in box86.

**Comment by pmtip** [comment]
In exagear, it may be faster than in box86.

**Comment by ptitSeb** [comment]
I don't have plans to modify wine for now. I'm not even sure what should be modify in fact for now.

**Comment by ptitSeb** [comment]
I pushed the change so `fopen64(...)` should behave like `fopen(...)` now. Can you build latest box86 and test that?

**Comment by pmtip** [comment]
It's fixed.

**Comment by pmtip** [comment]
Is box86 can not run statically linked program?

**Comment by pmtip** [comment]
I compiled my program into statically linked.

**Comment by pmtip** [comment]
It did not output any.

**Comment by pmtip** [comment]
pi@raspberrypi:~ $ file cat
cat: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=6ba4c964c23cf5460fefad1ba2de8fada5254f13, not stripped
pi@raspberrypi:~ $ BOX86_LD_LIBRARY_PATH=box86/x86lib/ ./box86/box86 ./cat /proc/cpuinfoDynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86_LD_LIBRARY_PATH: box86/x86lib/
Using default BOX86_PATH: ./:bin/
Counted 24 Env var
Looking for ./cat
argv[1]="/proc/cpuinfo"
pi@raspberrypi:~ $

**Comment by pmtip** [comment]
Cannot execute /proc/self/exe with execl in box86.
And the file opened with fopen/fopen64 is box86 itself.

**Comment by pmtip** [comment]
Can you fix these?

**Comment by pmtip** [comment]
You can make fopen/fopen64 return fopen(64)(emu->context->fullpath, mode) when use fopen/fopen64 open /proc/self/exe.

**Comment by ptitSeb** [comment]
I can put some workaround yes, but it would be better to open new ticket for this kind of thing, it's easier to track.

**Comment by pmtip** [comment]
...
I don't know how to name the ticket.

**Comment by pmtip** [comment]
My English is not good.

**Comment by ptitSeb** [comment]
It doesn't mater if the sentence is not correct.
You need to create 2 tickets here:
One for "handling /proc/self/exe in fopen/fopen64 function"  and one for "handling /proc/self/exe in execv function"
