### ISSUE TITLE
Can not pass qemu i386 test

### ISSUE THREAD

**Issue by hmilyyang** [ptitSeb/box86#194]
I found some mismatches when running qemu i386 test.
According my analysise, there is a bug in function shld16 (line 894 in x86primop.c):
	} else {
                res = (fill << (cnt)) | (fill >> (16 - cnt));
should change to :
	} else {
		res = (fill << (cnt)) | (d >> (16 - cnt));
And the bug exist in function shrd16 too.

**Comment by ptitSeb** [comment]
Oh, nice catch!

I'll look into this, thanks :)

**Comment by ptitSeb** [comment]
Is it better now?

**Comment by hmilyyang** [comment]
👍 ,Thanks!
