### ISSUE TITLE
Steam ELF error

### ISSUE THREAD

**Issue by Smorekat** [ptitSeb/box86#197]
On Raspbian, most recent version, on Raspberry Pi 3 B.
Tried typing “`sudo Box86 steam`” and came with 
“`Error: reading elf header of /usr/lib/steam/bin_steam.sh`” after printing “`steam detected, forcing emulated libudev, disabling SSE3, faking 64bits OS`”

**Comment by pmtip** [comment]
When I compile with "cmake .. -DARM_DYNAREC", 
0010:err:seh:segv_handler Got unexpected trap 0

**Comment by ptitSeb** [comment]
why `sudo` ? and also, did you `sudo make install` box86 already?
If yes, just `steam` to launch steam. You cannot use box86 to launch a shell script (and I think your "steam" is a symlink to that "/usr/lib/steam/bin_steam.sh" shell script).

**Comment by JoeSchr** [comment]
Hi, thanks for that information nugget. I also tried it like @Smorekat because running `steam` directly gave me this error:
```
Package xterm needs to be installed
Package zenity needs to be installed
Package libgl1-mesa-dri:i386 needs to be installed
Package libgl1:i386 needs to be installed
Package libc6:i386 needs to be installed
Running Steam on raspbian 10 32-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
Error:
You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
Press enter to continue:
Can't find 'steam-runtime-check-requirements', continuing anyway
/home/pi/.local/share/Steam/ubuntu12_32/steam
/lib/ld-linux.so.2: No such file or directory
```

How do i get this libraries? Do I need to get the x86 version of them?

**Comment by ptitSeb** [comment]
Steam is not always working, for an unknown reason for now (porbably some gtk issue).

The libc error is "normal". Run steam as `STEAMOS=1 STEAM_RUNTIME=1 steam` to avoid that message.

**Comment by JoeSchr** [comment]
@ptitSeb thanks for the hint. sadly the same results. maybe it just won't work on raspbian...

**Comment by ptitSeb** [comment]
I'm trying to debug steam issue on TwisterOS. Hopefully I'll find something eventually.

**Comment by moddedmcplayer** [comment]
same error 
for me, except without:

> Error: You are missing the following 32-bit libraries, and Steam may not run:
>libc.so.6
>Error:
>You are missing the following 32-bit libraries, and Steam may not run:
>libc.so.6
>Press enter to continue:

**Comment by moddedmcplayer** [comment]
Same thing for me

> Hi, thanks for that information nugget. I also tried it like @Smorekat because running `steam` directly gave me this error:
> 
> ```
> Package xterm needs to be installed
> Package zenity needs to be installed
> Package libgl1-mesa-dri:i386 needs to be installed
> Package libgl1:i386 needs to be installed
> Package libc6:i386 needs to be installed
> Running Steam on raspbian 10 32-bit
> STEAM_RUNTIME is enabled automatically
> Pins up-to-date!
> Error: You are missing the following 32-bit libraries, and Steam may not run:
> libc.so.6
> Error:
> You are missing the following 32-bit libraries, and Steam may not run:
> libc.so.6
> Press enter to continue:
> Can't find 'steam-runtime-check-requirements', continuing anyway
> /home/pi/.local/share/Steam/ubuntu12_32/steam
> /lib/ld-linux.so.2: No such file or directory
> ```
> 
> How do i get this libraries? Do I need to get the x86 version of them?

**Comment by ptitSeb** [comment]
Steam launch on my side, but it's really unstable. Consider it experimental support. Read the docs, join the discord for more help.
I'll close this ticket, there will be not "fix" for this ticket as the error is way too vague.
