### ISSUE TITLE
May be a bug for BTS instruction

### ISSUE THREAD

**Issue by hmilyyang** [ptitSeb/box86#198]
According to ident, there may be missing { } for instruction "BTS Ed, Ib" (line 841, run0f.h)
                    if(ED->dword[0] & (1<<tmp8u)) {
                        SET_FLAG(F_CF);
                    } else
                        ED->dword[0] ^= (1<<tmp8u);
                        CLEAR_FLAG(F_CF);
should be
                    if(ED->dword[0] & (1<<tmp8u)) {
                        SET_FLAG(F_CF);
                    } else {
                        ED->dword[0] ^= (1<<tmp8u);
                        CLEAR_FLAG(F_CF);
                    } 

And it seems that the instruction "BTS" and "BTC" is missing in dynarec. It should be easy to implement like instruction "BTR", but I am not sure I can submit a commit without bug.

**Comment by ptitSeb** [comment]
I have pushed a fix, thnx.

Indeed, BTS and BTC can be implemented in dynarec using BTR as template. Feel free to try a PR :) (and don't worry about the bugs, I submit plenty of them already)

**Comment by hmilyyang** [comment]
Thanks :)
