### ISSUE TITLE
HumanRessourceMachine: No music

### ISSUE THREAD

**Issue by ptitSeb** [ptitSeb/box86#2]
Humand ressource Machine start, but on the Intro there should be some music playing. A short burst of currupted sound can be heard, but that's all.
Other sounds play fine.
![box86_43](https://user-images.githubusercontent.com/3250792/53682474-51974400-3cf6-11e9-99b8-170ad764e495.png)

(not sure it's related to #1 because HRM use OpenAL and FTL use Alsa. Ogg decompression is done by FTL, not sure how the music is uncompressed on HRM).

**Comment by ITotalJustice** [comment]
I managed to play this game fine a few weeks ago, I didn’t notice any missing sounds or graphical errors. Guessing this can be closed? 😄

**Comment by ptitSeb** [comment]
I'll close it end of weekd end (I want to run a last test, but wont be able to do it before sunday night).

**Comment by ptitSeb** [comment]
I still have no music in the intro on the Pandora. But I guess this is due to the slowyness of the CPU mixed with the lack of Dynarec.
