### ISSUE TITLE
I need some help!

### ISSUE THREAD

**Issue by revoxhere** [ptitSeb/box86#20]
Hey!
Firstly, I don't know if I posted this in the right place but anyways, is this masterpiece available for  Raspbian on Raspberry Pi? I successfully compiled the repo as stated in compiling readme, but I don't know how to use the program. I'm not an experienced linux user and couldn't find any related  topics. 
Thanks for help!

**Comment by ptitSeb** [comment]
Hey.

Yes, this is a good place.


To my knowledge, this is not available in Raspbian.

Now that you have built it, is it to call some game. If you had built it in `~/box86/build/box86`
Let's say you have decompressed a game, for example, Undertale, in some place (like `~/undertale`), you will `cd ~/undertale` then call  `~/box86/build/box86 runner` to launch the game.
Note that the game may need some i386 libs. Either install the i386 version of libstc++ using apt command, or either copy one (from some i386 distibution) in the game folder, so box86 pick it up automaticaly.

I hope this is clear enough.

**Comment by revoxhere** [comment]
Ok, thanks for the clarification! I'll try running something and tell the results.

**Comment by revoxhere** [comment]
So I tried running a notepad.exe (from windows) for the test using this command: $ ~/box86/build/box86 notepad.exe, but i get memory protection violation error. So that propably means it won't run on the Pi?

**Comment by ptitSeb** [comment]
You cannot run windows program for now. Only Linux x86 programs.

**Comment by revoxhere** [comment]
Ahh, okay! Let me check.

**Comment by revoxhere** [comment]
> Ahh, okay! Let me check.

Still the same error if I use for example wine 32bit deb file. 
Even if I call the program with no "parameter".

**Comment by ptitSeb** [comment]
Yes, wine will not work for now. It's not in current target of box86.

**Comment by ptitSeb** [comment]
Here you have some example of what can run with Box86: https://magazine.odroid.com/article/linux-gaming-box86-a-new-x86-emulator-for-odroids/
And here some other examples: https://www.giantpockets.com/box86-run-x86-code-and-games-on-arm/
