### ISSUE TITLE
Steam UI not working

### ISSUE THREAD

**Issue by dragan2k6** [ptitSeb/box86#206]
I use a Raspberry Pi 3b+ and I tried to startup Steam but the ui won't show up. Steam is still running, I can see it in the Task Manager but I can't login. When I startup Steam it does show that it's starting up but after that nothing. Maybe I shoud use SteamCMD but I want to know if I can use normal Steam first before moving on to SteamCMD.

**Comment by ptitSeb** [comment]
I haven't encounter this behavour.
For me, either steam just work, or, on other config, it load, let you login (with steam guard if needed), but then crash before showing the GUI.
I don't remember having seen it not crashing but not showing the gui.

**Comment by dragan2k6** [comment]
Could you show any of those configs

**Comment by ptitSeb** [comment]
I fixed some pending issue with Steam today. Is it still not working?

Also, you can mybe try to launch steam using `steam +open steam://open/minigameslist -no-browser` to directly get the mini view mode.

**Comment by ptitSeb** [comment]
Too many steam ticket open. Closing.
