### ISSUE TITLE
Fez not working

### ISSUE THREAD

**Issue by gercapo** [ptitSeb/box86#207]
I've running fez a gog game and I've got an error.
pi@retropie:~/GOG Games/FEZ/game $ box86 FEZ.bin.x86
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 43 Env var
Looking for FEZ.bin.x86
Using native(wrapped) libm.so.6
Using native(wrapped) librt.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Warning, don't know of to handle rel #58 type: 0x25 (unknown) (0x83ab178)
Warning, don't know of to handle rel #151 type: 0x25 (unknown) (0x83ab2f4)
Warning: Cannot dlopen("/home/pi/GOG Games/FEZ/game/mscorlib.dll.so"/0x3710518, 101)
Warning: Cannot dlopen("/usr/local/lib/mono/aot-cache/x86/mscorlib.dll.so"/0x36a8578, 101)
3065|SIGSEGV @0x740dddc0 (???) (x86pc=0x815a930/"/home/pi/GOG Games/FEZ/game/FEZ.bin.x86/mono_gc_alloc_obj"), for accessing 0xf0 (code=1), db=0x3883088(0x815a930//home/pi/GOG Games/FEZ/game/FEZ.bin.x86/mono_gc_alloc_obj)

Native stacktrace:

	box86() [0x288bd88]
	box86() [0x287e15c]
	box86() [0x284d904]
	box86() [0x2848d94]
	box86() [0x2884da4]
	box86() [0x2884fd8]
	box86() [0x28852b0]
	/lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0x76cfc130]

Debug info from gdb:

Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for /usr/bin/gdb
argv[1]="-ex"
argv[2]="attach 3065"
argv[3]="--ex"
argv[4]="info threads"
argv[5]="--ex"
argv[6]="thread apply all bt"
argv[7]="--batch"
Not an i386 ELF (40)
Error: reading elf header of /usr/bin/gdb

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Abortado

**Comment by ptitSeb** [comment]
FEZ is an FNA game. YOu can use the "FNA Trick" to run it without box86 (basicaly remove System.dll and Mono*.dll and use `mono FEZ.exe` to launch it).

**Comment by gercapo** [comment]
I have deleted Mono.Posix.dll, Mono.Security.dll and System.dll but the command "mono FEZ.exe" does nothing
![Captura de pantalla de 2020-09-24 04-50-45](https://user-images.githubusercontent.com/28670116/94116774-d3dbe180-fe21-11ea-9bda-230637b74ee7.png)

**Comment by ptitSeb** [comment]
You probably need "monolibs" package also, with mojoshader lib and a few other.  My outdated guide for ODROID is here: https://magazine.odroid.com/article/playing-modern-fna-games-on-the-odroid-platform/
You can probably find some youtube channels taht offers pre-built libs for RPi4 too (look for Celeste on RPi4 by djazz for example).

**Comment by gercapo** [comment]
i can't make mojoshaders libraries. I follow your guide from this page https://magazine.odroid.com/article/playing-modern-fna-games-on-the-odroid-platform/ and I'm stuck on this part

pi@raspberrypi:~/mojoshader $ make -j4
Scanning dependencies of target lemon
Scanning dependencies of target glcaps
[  2%] Building C object CMakeFiles/lemon.dir/misc/lemon.c.o
[  5%] Building C object CMakeFiles/glcaps.dir/utils/glcaps.c.o
[  7%] Linking C executable glcaps
[  7%] Built target glcaps
[ 10%] Linking C executable lemon
[ 10%] Built target lemon
[ 13%] Generating mojoshader_parser_hlsl.h
make[2]: *** [CMakeFiles/mojoshader.dir/build.make:64: mojoshader_parser_hlsl.h] Violación de segmento
make[2]: *** Se borra el archivo 'mojoshader_parser_hlsl.h'
make[1]: *** [CMakeFiles/Makefile2:363: CMakeFiles/mojoshader.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Im on raspberry pi 3.

**Comment by ptitSeb** [comment]
That's probably a `yacc` or `bison` version problem, leading to an incorrectly built "lemon" program. Try to switch version or install yacc instead of bison (or the contrary).

**Comment by gercapo** [comment]
I have tried several versions of bison but none works. Do you have the libmojoshader.so file?
Maybe it should be done by cross compilation.

**Comment by ptitSeb** [comment]
Try this guide: https://hackmd.io/@djazz/HyMRXfreS
And here the "monolibs" package for Pi4 (hopefully should works on Pi3) https://drive.google.com/file/d/1B49wkWVBvFwAlGfBtbvTJF4L_owXUQ3G/view?usp=drivesdk

**Comment by gercapo** [comment]
copy and paste everything into monolibs from the compressed file and now I have this error.

pi@raspberrypi:~/GOG Games/FEZ/game $ LC_ALL="C" LIBGL_ES=2 LIBGL_GL=21 LIBGL_DEFAULTWRAP=2 LIBGL_FBOFORCETEX=1 LD_LIBRARY_PATH=~/monolibs mono FEZ.exe
LIBGL: Initialising gl4es
LIBGL: v1.1.3 built on Apr 30 2020 17:13:13
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: loaded: libEGL.so
LIBGL: Using GLES 2.0 backend
libEGL warning: DRI2: failed to authenticate
LIBGL: No alpha channel in PBuffer context, disabling EGL Alpha channel...
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: Extension GL_EXT_draw_buffers  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_multi_draw_arrays  detected
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_OES_texture_stencil8  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: Extension GL_OES_texture_half_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Max texture size: 8192
LIBGL: Max Varying Vector: 32
LIBGL: Texture Units: 16/16 (hardware: 32), Max lights: 8, Max planes: 6
LIBGL: Max Color Attachments: 8 / Draw buffers: 8
LIBGL: Hardware vendor is VMware, Inc.
LIBGL: GLSL 300 es supported
LIBGL: GLSL 310 es supported and used
LIBGL: sRGB surface supported
LIBGL: Targeting OpenGL 2.1
LIBGL: NPOT texture handled in hardware
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: Force texture for Attachment color0 on FBO
LIBGL: Default wrap mode is GL_CLAMP_TO_EDGE, enforced
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/home/pi/GOG Games/FEZ/game
libEGL warning: DRI2: failed to authenticate
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
  at FezEngine.Structure.Mesh.Dispose (System.Boolean disposeEffect) [0x00084] in <5a056033aeeb4741b32c426029866964>:0 
  at FezEngine.Structure.Mesh.Dispose () [0x00000] in <5a056033aeeb4741b32c426029866964>:0 
  at FezGame.Components.Intro.Dispose (System.Boolean disposing) [0x000de] in <17c795b28e00420dbe494c0ec426f378>:0 
  at Microsoft.Xna.Framework.GameComponent.Dispose () [0x00000] in <a3a5dd65b0c14b009d31bf2acc9f8da8>:0 
  at Microsoft.Xna.Framework.Game.Dispose (System.Boolean disposing) [0x00030] in <a3a5dd65b0c14b009d31bf2acc9f8da8>:0 
  at FezGame.Fez.Dispose (System.Boolean disposing) [0x00000] in <17c795b28e00420dbe494c0ec426f378>:0 
  at Microsoft.Xna.Framework.Game.Dispose () [0x00000] in <a3a5dd65b0c14b009d31bf2acc9f8da8>:0 
  at FezGame.Program.Main (System.String[] args) [0x00380] in <17c795b28e00420dbe494c0ec426f378>:0 
LIBGL: Shuting down

**Comment by ptitSeb** [comment]
not related to box86 (but box86 should run it now).

Closing the ticket.
