### ISSUE TITLE
Fix aarch64 build

### ISSUE THREAD

**Issue by Google61** [ptitSeb/box86#213]
A workaround to build box86 on aarch64 (termux) is to fix CMakeLists.txt, after presets, in ARM_DYNAREC section, change `-marm` to `-m32`, then after cmake it will build.
I could do a pr, but I'm not so familiar with cmake lists ¯\_(ツ)_/¯

**Comment by ptitSeb** [comment]
I need to detect the bitness of the platform in the CMake then first, because -m32 doesn't work on armhf.

**Comment by ptitSeb** [comment]
Are you sure that works on your side?
It seems -m32 is an x86/x86_64 only option

(look https://gcc.gnu.org/onlinedocs/gcc-8.4.0/gcc/x86-Options.html and https://gcc.gnu.org/onlinedocs/gcc-8.4.0/gcc/AArch64-Options.html )

**Comment by Google61** [comment]
See here https://github.com/termux/termux-packages/issues/1258
Not sure, maybe only termux clang feature?
Without fix it gives warnings like -marm is unused, and some fatal error, don't remember now.
Also other fatal errors while building, will open another issue.

**Comment by ptitSeb** [comment]
I think it's limited to clang, gcc doesn't seems to handle that (it's a shame it doesn't, that would be handy to have).

I'll see if I can add a detection of 64bits platform and clang, to see if I can have more autosettings of build parameters

**Comment by ptitSeb** [comment]
Fatal error when building as a 64bits app is normal, don't bother open a ticket for that. box86 cannot be build as a 64bits app.

**Comment by woachk** [comment]
Note with clang on Ubuntu 20.04 multiarch: it directs to armel when you use -m32 instead of armhf.

You have to use -target arm-linux-gnueabihf instead.

**Comment by Google61** [comment]
#214
