### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Google61** [ptitSeb/box86#214]
Errors while building
[box86.txt](https://github.com/ptitSeb/box86/files/5312320/box86.txt)

**Comment by ptitSeb** [comment]
So, it's clang? can you add `-std=c11` to CFLAGS?

**Comment by ptitSeb** [comment]
Thoses are regular macro from linux header... On what system are trying to build?

**Comment by Google61** [comment]
Termux aarch64
Maybe I'm missing some required packages, or need to fix include paths?

**Comment by ptitSeb** [comment]
I think you are missing 32bits elf header, but I don't know what package they came from.

**Comment by Google61** [comment]
elf.h is a part of libc6-dev...
🤦‍♂️ I've completely forgot, android have it's bionic instead of libc...

**Comment by ptitSeb** [comment]
if you want, you can find precompiled version there: https://archive.org/details/box86.7z_20200928

**Comment by Google61** [comment]
Ok, thanks, I will close both issues for now, without solution
