### ISSUE TITLE
box86 fatal error while compiling

### ISSUE THREAD

**Issue by Pythonic456** [ptitSeb/box86#220]
I am trying to compile box86 to a .deb file on the RPi 4B.
While compiling with this command:
`mkdir build; cd build; cmake .. -DRPI4=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo; make
`
I get this error:
```Scanning dependencies of target box86
[ 42%] Building C object CMakeFiles/box86.dir/src/main.c.o
[ 43%] Building C object CMakeFiles/box86.dir/src/box86context.c.o
[ 43%] Building C object CMakeFiles/box86.dir/src/build_info.c.o
/home/pi/Downloads/box86 build/box86-master/src/build_info.c:4:10: fatal error: git_head.h: No such file or directory
 #include "git_head.h"
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/box86.dir/build.make:240: CMakeFiles/box86.dir/src/build_info.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/box86.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Thanks for help in advance.

**Comment by ptitSeb** [comment]
you don't have git installed?

**Comment by Pythonic456** [comment]
I'm pretty sure I have git installed:
`root@RaspberryPi4B:/home/pi# apt install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.20.1-2+deb10u3).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
root@RaspberryPi4B:/home/pi# 
`

So is it just me? Or am I missing something?


Thanks in advance.

**Comment by ptitSeb** [comment]
And you are building from a sources that come from a git clone?

**Comment by Pythonic456** [comment]
I downloaded the .zip file on the home page of box86, this: https://github.com/ptitSeb/box86/archive/master.zip

Thanks in advance.

**Comment by ptitSeb** [comment]
Ah ok, so there is no git information... I probably need to had a workround when not build from a git repo (note that it's not advise for now as box86 is evolving fast, but I'll add something)

**Comment by Pythonic456** [comment]
okay thanks a lot :+1:

**Comment by Pythonic456** [comment]
Welp I tried using git clone for this and compiling it again, still fails, exact same error.
I'm not sure, should I try downloading the .zip and try that way?

**Comment by ptitSeb** [comment]
the file is generated, so it should find it. Try to clean your workspace and try again.

Also, I have added the NOGIT option anyway.

**Comment by Pythonic456** [comment]
Okay I'll try...

**Comment by Pythonic456** [comment]
Nope, still fails. CLI output is:
`Scanning dependencies of target dynarec
[ 42%] Linking C static library libdynarec.a
[ 42%] Built target dynarec
[ 42%] Generating ../src/git_head.h
Scanning dependencies of target box86
[ 42%] Building C object CMakeFiles/box86.dir/src/main.c.o
[ 43%] Building C object CMakeFiles/box86.dir/src/box86context.c.o
[ 43%] Building C object CMakeFiles/box86.dir/src/build_info.c.o
/home/pi/Downloads/box86 build/box86/src/build_info.c:7:10: fatal error: git_head.h: No such file or directory
 #include "git_head.h"
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/box86.dir/build.make:240: CMakeFiles/box86.dir/src/build_info.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/box86.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
pi@RaspberryPi4B:~/Downloads/box86 build/box86/build $ 
`
Thanks in advance.

**Comment by ptitSeb** [comment]
Why all you copy/paste of command line have no return to line? Make things difficult to read.

You build attempts is from what folder and using what config? Can you detail a bit more the command you use.

**Comment by Pythonic456** [comment]
Sorry, I don't know how to make new lines with markdown.

The command I use is the one linked on this project for Raspberry Pi 4.
`pi@RaspberryPi4B:~/Downloads/box86 build/box86/build $ mkdir build; cd build; cmake .. -DRPI4=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo; make
`

**Comment by ptitSeb** [comment]
> Sorry, I don't know how to make new lines with markdown.
> 
Use triple back quote instead of single. I edited your post with that.

> The command I use is the one linked on this project for Raspberry Pi 4.
> `pi@RaspberryPi4B:~/Downloads/box86 build/box86 $ mkdir build; cd build; cmake .. -DRPI4=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo; make `
> 
> (Edit: That build shouldn't have been there, but I was running it in the box86 dir.)

Your folder is "~/Downloads/box86 build/box86"? with a space in the name right?

**Comment by Pythonic456** [comment]
Yep.

**Comment by ptitSeb** [comment]
Well, that certainly is the source of the issue. Space in folder names are evil!

**Comment by Pythonic456** [comment]
Just trying it now...

**Comment by Pythonic456** [comment]
Just trying it now...

**Comment by Pythonic456** [comment]
Okay, it has got past that error. I haven't encountered any errors so far in compiling, so I reckon that fixed it.
Thanks so much for your time!

**Comment by Pythonic456** [comment]
Oh yeah, a quick question: How to compile it for a .deb file? I've only
just started compiling things and would appreciate your help greatly.

**Comment by ptitSeb** [comment]
I don't know.  I haven't checked that, and if I add, there would be an option to build box86 as a .deb

**Comment by Pythonic456** [comment]
Okay. Thanks anyway!
