### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by BenNottelling** [ptitSeb/box86#223]
I've been watching this for a while, and I've noticed a lot of people are having issues with steam, and that you seem to have 
 some workarounds / tests for it, so I was thinking perhaps it may be a good idea to document this? Steam is something a lot of people will try to use.

So maybe some info on the readme, or a wiki entry, or a comment here with a link to it?
Just thinking outloud.

**Comment by ptitSeb** [comment]
That would be a good occasion the learn how to use github wiki entry...

In the mean time, yeah, you're right, I have to add something in the README.md about steam.
