### ISSUE TITLE
ZOOM client cannot see camera and speakers don't work

### ISSUE THREAD

**Issue by coolerw** [ptitSeb/box86#225]
Hi,
I have compiled box86 on RPI4 purposely for zoom client but when zoom was installed and run (no issues, crashes) I discovered that a dedicated mmal camera is not seen by zoom and I cannot switch output sound to headphones. I also tested HDMI sound (which is the default in zoom as I cannot switch to headphone output) but it also does not work.
Strangely the USB microphone  works fine, zoom is establishing meetings, everything works except for mmal video (a dedicated camera is not seen - USB camera works fine) and output sound. 
Could be great to investigate this as it would be a really great achievement to have a zoom conference working under RPI4 Raspberry OS 32bits thanks to box86. This is a very popular computer and a lot of people have mmal camera and HDMI/headphone sound.
Regards,
Tomasz

**Comment by ptitSeb** [comment]
I don't have mmal camera, so it's difficult for me to test that. Does the mmal camera is accessible on `/dev/video0` ?
About sound, zoom is pulseaudio based, I don't why it wouldn't see the headphone out, but I have seen that one to be problematic on certai OS.

What OS are you using?

**Comment by coolerw** [comment]
The Camera module (conected via ribbon cable to a dedicated port on RPI4) is accessible on /ded/video0 and Zoom can't see it, while /dev/video1 is UDB cam and zoom can see it.
I'm using Raspberry Pi OS (previously called Raspbian)  32 bit - the one which is officially available on raspberrypi.org. As far as I understand it - Audio is based on Alsa - so maybe this is the part of the problem, but it works for every USB device connected, including: USB Video Cam, USB Microphone (with issues) and USB headphones (Sound Blaster Jam).

**Comment by ptitSeb** [comment]
What id the resolution of that camera? Maybe it doesn't fullfill some minimum requirement?

Maybe adding pulseaudio might still help for the headphone connector.

**Comment by coolerw** [comment]
Camera is full HD AFAIK. 
Will try with pulse audio installed, previously I tested pulse audio but apparently Raspbian works better with Alsa, I was unable to get A2DP profile on my BT headphones, while under Alsa works as a charm. 

Dnia 11 października 2020 14:16:58 CEST, ptitSeb <notifications@github.com> napisał(a):

**Comment by coolerw** [comment]
Maybe zoom startup/shutdown messages may be helpful:

./zoom
Box86 with Dynarec v0.1.3 a9d87a93 built on Oct 11 2020 06:19:30
sh: 1: pactl: not found
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
sh: 1: pactl: not found
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: DC:A6:32:01:4A:4F][client: Linux][OS: Raspbian GNU/Linux 10 (buster)][Hardware: CPU Core:4 Frenquency:2 G Memory size:1815MB CPU Brand:              Intel(R) Pentium(R) 4 CPU 2000MHz GPU Brand:][Req ID: ]
Linux Client Version is 5.3.469451.0927
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = LXDE;   GDMSESSION = lightdm-xsession
Graphics Card Info:: 
Zoom package arch is 32bit, runing OS arch is i386
AppIconMgr::systemDesktopName log Desktop Name: LXDE-pi 
sh: 1: pactl: not found
link image0 hasn't been detected!
Could not resolve property : pattern0
qrc:/qml/ZoomMenu.qml:64:5: QML ZoomListView: Binding loop detected for property "height"
qrc:/qml/ZoomMenu.qml:64:5: QML ZoomListView: Binding loop detected for property "height"
qrc:/qml/ZoomMenu.qml:64:5: QML ZoomListView: Binding loop detected for property "height"
qrc:/qml/ZoomMenu.qml:64:5: QML ZoomListView: Binding loop detected for property "height"
qrc:/qml/ZoomMenu.qml:64:5: QML ZoomListView: Binding loop detected for property "height"
qrc:/qml/ZoomMenu.qml:64:5: QML ZoomListView: Binding loop detected for property "height"
qrc:/qml/ZoomMenu.qml:64:5: QML ZoomListView: Binding loop detected for property "height"
qrc:/qml/ZoomMenu.qml:64:5: QML ZoomListView: Binding loop detected for property "height"
WorkerBase::loop() normal exit, fds[0].revents & POLLIN = true
WorkerBase::loop() normal exit, fds[0].revents & POLLIN = true
qrc:/qml/SettingItemDelegate.qml:52: TypeError: Cannot read property 'isEnabled' of undefined
WorkerBase::loop() normal exit, fds[0].revents & POLLIN = true
WorkerBase::loop() normal exit, fds[0].revents & POLLIN = true
WorkerBase::loop() normal exit, fds[0].revents & POLLIN = true
WorkerBase::loop() normal exit, fds[0].revents & POLLIN = true
sh: 1: pactl: not found
6757|Double SIGSEGV!
Naruszenie ochrony pamięci

---------
Last 2 lines were right after choosing exit from the taskbar menu (last line is memory protection error).
The line about image0 is maybe about the RPI cam?
And definitely zoom searches for pactl which is in the pulseaudio packages. But when I connected USB headphones - zoom switched to them and the output sound worked.

Next step I'm going to install (temporarely) pulseaudio and check if this helps.
Anyway, I'm impressed that x86 zoom starts and almost works :)

**Comment by ptitSeb** [comment]
I just added an option to box86 to not load pulse audio libs. Zoom support ALSA, so it should falback to it. I notice it still wants to use pactl even if no pulse lib is loaded. So not sure it works. To be tested: the parameter is `BOX86_NOPULSE=1`

**Comment by coolerw** [comment]
I'm assuming that I should again git clone and recompile? Should I uninstall somehow the old version?

Dnia 14 października 2020 09:31:36 CEST, ptitSeb <notifications@github.com> napisał(a):

**Comment by ptitSeb** [comment]
> I'm assuming that I should again git clone and recompile? Should I uninstall somehow the old version? 
>
Yes, clone or update your actual copy (with `git pull`) and rebuild & install.

**Comment by Botspot** [comment]
@coolerw For the camera module, somebody figured out you can do a v4loopback device: https://github.com/ptitSeb/box86/issues/193#issuecomment-710045656

**Comment by ptitSeb** [comment]
Can this ticket be closed now?

**Comment by coolerw** [comment]
Sorry, I was busy some other things, just give me a week or two so I can test this and confirm the solution works just fine. 
Regards,
Tomasz

Dnia 31 grudnia 2020 16:47:38 CET, ptitSeb <notifications@github.com> napisał(a):

**Comment by coolerw** [comment]
Hi there!
I have updated box86 and started zoom app v 5.3.469451.0927 and no progress with zoom. Still cannot change to native RPI4 camera and also cannot change output sound to the Analog (HDMI1 is as default, changing to headphones does not have any effect).
Will update zoom to the most recent version and test it again
Cheers!

**Comment by coolerw** [comment]
I have some other issue woth the 5.4.2 version:
/zoom $ zoom/zoom 
Box86 with Dynarec v0.2.1 6a498c37 built on Feb  2 2021 23:30:11
No PulseAudio daemon running, or not running as session daemon.
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.

This is something new, previous version just worked...

**Comment by langme** [comment]
How to access pi Camera with zoom ?
i tried a lot of things. Zoom app lists only bcmxxxx device.

**Comment by ptitSeb** [comment]
I don't think the onboard camera can be used with Zoom.
It's not box86 issue, and some other camera can be used, but I suppose the Pi one doesn't fulfill some requirement.

I close this issue, but feel free to re*open it if needed.
