### ISSUE TITLE
There already exists a project known as 86Box since 2017. Please change your name to avoid confusion.

### ISSUE THREAD

**Issue by qeeg** [ptitSeb/box86#232]
We came first, we had our name before you had yours, please respect this and change your project's name. We've already gotten two different people coming to our Discord server thinking it was for box86, and then becoming annoyed when we obviously can't help them.

**Comment by ptitSeb** [comment]
I understand but that seems difficult. I can add a note in the Readme to explain these are 2 different projects.

**Comment by qeeg** [comment]
Well, people claim that they're Googling box86, and getting our Discord somehow, so I'm not sure that's going to quite be effective.

**Comment by ptitSeb** [comment]
Ah, ok, I'll add a box86 discord to the readme also, so google will stop confusing maybe.

**Comment by qeeg** [comment]
Fair enough. Thanks for understanding.

**Comment by qeeg** [comment]
The URL for 86Box is actually https://github.com/86Box/86Box, but other than that, that should work! Thanks.

**Comment by ptitSeb** [comment]
Ah oops, sorry. It's fixed now.
