### ISSUE TITLE
Compile error on Pandora

### ISSUE THREAD

**Issue by farox1** [ptitSeb/box86#233]
Hi
just received this error trying to compile your latest sources:

---------------------------------------------------------------
Building C object CMakeFiles/box86.dir/src/wrapped/wrappedlibc.c.o
/media/toshi32/code/box86-dynarec/src/wrapped/wrappedlibc.c: In function ���my_recvmmsg���:
/media/toshi32/code/box86-dynarec/src/wrapped/wrappedlibc.c:1891:20: error: ���__NR_recvmmsg��� 
undeclared (first use in this function); 
did you mean ���my_recvmmsg���?
return syscall(__NR_recvmmsg, fd, msgvec, vlen, flags, timeout);
                    ^~~~~~~~~~~~~
                    my_recvmmsg
/media/toshi32/code/box86-dynarec/src/wrapped/wrappedlibc.c:1891:20: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/box86.dir/build.make:724: CMakeFiles/box86.dir/src/wrapped/wrappedlibc.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/box86.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
-----------------------------------

I'm building with:
-DPANDORA=1 -DARM_DYNAREC=1 -DNOGIT=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo

Thanks

**Comment by ptitSeb** [comment]
Works for me on my codeblock (should be similar to latest beta PND). But ok, I'll add the definition of those syscall in Pandora case.

**Comment by farox1** [comment]
Thanks
i was looking at line 53
#ifdef PANDORA
#ifndef __NR_preadv
#define __NR_preadv                     (__NR_SYSCALL_BASE+361)
#endif
#ifndef __NR_pwritev
#define __NR_pwritev                    (__NR_SYSCALL_BASE+362)
#endif
#ifndef __NR_accept4
#define __NR_accept4                    (__NR_SYSCALL_BASE+366)
#endif
#ifndef __NR_sendmmsg
#define __NR_sendmmsg			        (__NR_SYSCALL_BASE+374)
#endif
#ifndef __NR_prlimit64
#define __NR_prlimit64                  (__NR_SYSCALL_BASE+369)
#endif
#endif

and maybe __NR_sendmmsg is already defined?

**Comment by farox1** [comment]
Ok but i think NR_sendmmsg is already defined...

**Comment by farox1** [comment]
Thanks fixed
