### ISSUE TITLE
Zoom Recording in Meeting

### ISSUE THREAD

**Issue by Pythonic456** [ptitSeb/box86#236]
Whenever I'm using Zoom with box86 and I join a meeting, it starts to record the meeting on Zoom.
Is this a bug with box86? Because I don't have this issue on any other devices, or it might just be me
with a weird setting.

Thanks in advance.

**Comment by ptitSeb** [comment]
I'm not aware of a bug like that. That's strange. I haven't used Zoom enough myself for now to say if it's a bug or not.

**Comment by Pythonic456** [comment]
I don't know, it could just be me. I'm going to look through
all the Zoom settings to try and find out if it's just me.

Thanks :-)

**Comment by Pythonic456** [comment]
Okay, I checked my Zoom settings and I don't have Auto record enabled.
I'm not sure it's Zoom, I reckon it's box86.

**Comment by ptitSeb** [comment]
Do you still have this issue, because I don't have this behaviour on my side. If the issue is gone, please close the ticket.

**Comment by Pythonic456** [comment]
Yes, it still does this. Every time. And I've been having issues with the new i686 version from zoom.us, sometimes it segfaults,
sometimes it doesn't, but it works.

**Comment by Itai-Nelken** [comment]
>  And I've been having issues with the new i686 version from zoom.us

@Pythonic456 here is  mirror that has a older version: https://github.com/Botspot/zoom_686_mirror

**Comment by Pythonic456** [comment]
@Itai-Nelken it _works_, but not reliably. Thanks though :+1:

**Comment by Pythonic456** [comment]
In case anyone finds this issue, if you want to run Zoom reliably and easily on ARM, I recommend checking out [Pi-Apps](https://pi-apps.io/). It downloads Box86/Box64 and Zoom, sets it all up, and it runs really well, rarely crashes.
