### ISSUE TITLE
Error initializing native ld-linux.so.2 

### ISSUE THREAD

**Issue by baptistebeaumes** [ptitSeb/box86#24]
Hi,
I found your project and it sounds very interesting.
I have an X86 project and I need to make him works on ARM.

I have this error :
Error initializing native ld-linux.so.2 (last dlerror is ld-linux.so.2: cannot open ...)

But the file is here, i probably missed something.

Anyway, i would also have another commercial question, may i have your mail address ?

Best regards,
Baptiste

**Comment by ptitSeb** [comment]
Hi.

For your issue at init, it's strange, because ld-linux.so.2 (or ld-linux.so.3) is a critical part and should load. Can you run with the export `BOX86_LOG=DEBUG` to have more detailles log?

About my email, it's: sebastien.chev@gmail.com

**Comment by baptistebeaumes** [comment]
A screenshot
![image](https://user-images.githubusercontent.com/52062745/59901453-95c06880-93fb-11e9-9049-2770ad12d1f8.png)

**Comment by ptitSeb** [comment]
Ok.
Now, on your system, how is named your ld-linux.so? It should be in `/lib`. common version are `ld-linux.so.2` and `ld-linux.so.3`

**Comment by baptistebeaumes** [comment]
I have a link to the x86 version, shame on me
![image](https://user-images.githubusercontent.com/52062745/59901840-d40a5780-93fc-11e9-82f7-bb7f5c13fc9e.png)

**Comment by ptitSeb** [comment]
ah ok.
I can add "ld-linux-armhf.so.3" to the list of tried name, that should do the trick.
If you want to try on your side, in `src/wrappedldlinux.c` change line 25 from
`#define ALTNAME "ld-linux.so.2"`
to
`#define ALTNAME "ld-linux-armhf.so.3"`

**Comment by ptitSeb** [comment]
Anyway, I have just pushed a change, it should work for you now.

**Comment by baptistebeaumes** [comment]
I have recompile, it works. I will continue, thanks. You can close this issue.
