### ISSUE TITLE
Running wine  and missing x86 library file. Error SIGSEGV is reported after adding.

### ISSUE THREAD

**Issue by Mr-HappyLI** [ptitSeb/box86#246]
Hi,I am a beginner.
Now,I've run some programs.But when I run WeChat,there are some problems.

0009:err:module:load_so_dll failed to load .so lib "/opt/wine/usr/local/bin/../lib/wine/wldap32.dll.so": Cannot dlopen("/opt/wine/usr/local/bin/../lib/wine/wldap32.dll.so"/0x7dd71e58, 2)

0009:err:module:import_dll Loading library WLDAP32.dll (which is needed by L"Z:\\home\\tony\\WeChat\\WeChatWin.dll") failed (error c000007a).

By looking at the log, I know that the library file is missing(x86 i386) like libldap_r-2.4.so.2 and more.
When I'm done adding all the library files,new problems have arisen.
Log :
Box86 with Dynarec v0.1.4 0edc0374 built on Oct 28 2020 09:03:49
Box86 with Dynarec v0.1.4 0edc0374 built on Oct 28 2020 09:03:49
Box86 with Dynarec v0.1.4 0edc0374 built on Oct 28 2020 09:03:49
002a:fixme:ver:GetCurrentPackageId (0x7298ff0c (nil)): stub
21804|SIGSEGV @0x628a85cc (???) (x86pc=0x10e8876e/???:"???", esp=0x7298feac), for accessing 0x26b7ecc3 (code=1), db=(nil)((nil):(nil)/(nil):(nil)/???)
21804|SIGSEGV @0x73354c38 (???) (x86pc=0x7bcbad90//opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so:"/opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so/start_thread", esp=0x7298f360), for accessing 0xdeadbabe (code=2), db=0x72a00708(0x73354c00:0x73354e50/0x7bcbad90:0x7bcbae03//opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so/start_thread)
...

$  addr2line -e /usr/bin/box86 -a 0x628a85cc
0x628a85cc
/home/tony/BOX86_SRC/box86-v0.1.3/src/emu/x86run.c:857

$ addr2line -e /usr/bin/box86 -a 0x73354c38
0x73354c38
??:0

Now how do I do, need to modify the source code?Thank you for your help.

**Comment by ptitSeb** [comment]
Well, that's a crash.

The missing x86 lib `libldap_r.so` can be an issue yes.

The actual crash is the first segfault, no idea why it tries to access this address. The addr2line you run indicates it's occuring durring interpretor call, on a `rol8` instruction, which seems correct.
I'll probably need to debug this one, not sure what is happening there.
Also, there are some opcode missing on the dynarec there, because the crash is in the interpretor. Not that it would fix anything, but if you run with `BOX86_DYNAREC_LOG=1` and gives me the missing opcodes, I can add them.

**Comment by ptitSeb** [comment]
Also, try using current version to see it's already fixed (probably not, but you never know).

**Comment by Mr-HappyLI** [comment]
Hi,I run the program .

Does not add the x86 library: 
Using native(wrapped) libncurses.so.5
Using native(wrapped) libtinfo.so.5
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
0x403982: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
...
Using emulated /opt/wine/usr/local/bin/../lib/wine/ucrtbase.dll.so
Using emulated /opt/wine/usr/local/bin/../lib/wine/iphlpapi.dll.so
Using emulated /opt/wine/usr/local/bin/../lib/wine/crypt32.dll.so
Using emulated /opt/wine/usr/local/bin/../lib/wine/bcrypt.dll.so
0x409b32: Dynarec stopped because of Opcode C5 F4 57 C9 8D 0C 4A EB 0F C5 F5 75 02 C5 FD

Add the x86 library: 
....
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libcups.so.2
Using native(wrapped) libpng16.so.16
0x7a060295: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
0x796c2772: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
Warning, function gnutls_decode_rs_value not found in lib libgnutls.so.30
0x10e756dc: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
0x1127d7f3: Dynarec stopped because of Opcode C5 F4 57 C9 03 F9 EB 0F C5 F5 74 01 C5 FD D7
002c:fixme:ver:GetCurrentPackageId (0x7350ff0c (nil)): stub
0x10e88767: Dynarec stopped because of Opcode F0 0F BA 2F 1F 0F 93 C0 84 C0 0F 85 94 00 00
0x10e88767: Dynarec stopped because of Opcode F0 0F BA 2F 1F 0F 93 C0 84 C0 0F 85 94 00 00
....

**Comment by Mr-HappyLI** [comment]
Hi,I use the latest box86.(Box86 with Dynarec v0.1.5  built on Nov  4 2020 02:18:37)
Does not add the x86 library:
Box86 with Dynarec v0.1.5  built on Nov  4 2020 02:18:37
Box86 with Dynarec v0.1.5  built on Nov  4 2020 02:18:37
Box86 with Dynarec v0.1.5  built on Nov  4 2020 02:18:37
0x403982: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
0009:err:module:load_so_dll failed to load .so lib "/opt/wine/usr/local/bin/../lib/wine/wldap32.dll.so": Cannot dlopen("/opt/wine/usr/local/bin/../lib/wine/wldap32.dll.so"/0x7dd71d38, 2)

0009:err:module:import_dll Loading library WLDAP32.dll (which is needed by L"Z:\\home\\tony\\WeChat\\WeChatWin.dll") failed (error c000007a).
0x409b32: Dynarec stopped because of Opcode C5 F4 57 C9 8D 0C 4A EB 0F C5 F5 75 02 C5 FD
0009:fixme:ver:GetCurrentPackageId (0x7f85fe94 (nil)): stub

Add the x86 library:
Box86 with Dynarec v0.1.5  built on Nov  4 2020 02:18:37
Box86 with Dynarec v0.1.5  built on Nov  4 2020 02:18:37
Box86 with Dynarec v0.1.5  built on Nov  4 2020 02:18:37
0x403982: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
0x7a060295: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
0x796c2772: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
0x10e756dc: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
0x1127d7f3: Dynarec stopped because of Opcode C5 F4 57 C9 03 F9 EB 0F C5 F5 74 01 C5 FD D7
002c:fixme:ver:GetCurrentPackageId (0x728dff0c (nil)): stub
0x10e88767: Dynarec stopped because of Opcode F0 0F BA 2F 1F 0F 93 C0 84 C0 0F 85 94 00 00
0x10e88767: Dynarec stopped because of Opcode F0 0F BA 2F 1F 0F 93 C0 84 C0 0F 85 94 00 00
22197|SIGSEGV @0x628aa5cc (???) (x86pc=0x10e8876e/???:"???", esp=0x728dfeac), for accessing 0x289dea3b (code=1), db=(nil)((nil):(nil)/(nil):(nil)/???)
22197|SIGSEGV @0x728f7838 (???) (x86pc=0x7bcbad90//opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so:"/opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so/start_thread", esp=0x728df360), for accessing 0xdeadbabe (code=2), db=0x747c0b00(0x728f7800:0x728f7a50/0x7bcbad90:0x7bcbae03//opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so/start_thread)
22197|SIGSEGV @0x728f7838 (???) (x86pc=0x7bcbad90//opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so:"/opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so/start_thread", esp=0x728de814), for accessing 0xdeadbabe (code=2), db=0x747c0b00(0x728f7800:0x728f7a50/0x7bcbad90:0x7bcbae03//opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so/start_thread)
20156|SIGSEGV @0x628aa5cc (???) (x86pc=0x10e8876e/???:"???", esp=0x7f85e834), for accessing 0x94850f (code=1), db=(nil)((nil):(nil)/(nil):(nil)/???)
22197|SIGSEGV @0x728f7838 (???) (x86pc=0x7bcbad90//opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so:"/opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so/start_thread", esp=0x728ddcc8), for accessing 0xdeadbabe (code=2), db=0x747c0b00(0x728f7800:0x728f7a50/0x7bcbad90:0x7bcbae03//opt/wine/usr/local/bin/../lib/wine/ntdll.dll.so/start_thread)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x726a1000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x729647ac (???) (x86pc=0x10a982ec/???:"???", esp=0x7f85dba0), for accessing 0x72275000 (code=1), db=0x72de2290(0x72964700:0x72964878/0x10a982ec:0x10a9832a/???)
20156|SIGSEGV @0x72964718 (???) (x86pc=0x10a982ec/???:"???", esp=0x7f85dba0), for accessing 0x72695000 (code=1), db=0x72de2290(0x72964700:0x72964878/0x10a982ec:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x72681000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x72671000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x729647ac (???) (x86pc=0x10a982ec/???:"???", esp=0x7f85dba0), for accessing 0x72668000 (code=1), db=0x72de2290(0x72964700:0x72964878/0x10a982ec:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x72651000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x72641000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x72631000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x72964718 (???) (x86pc=0x10a982ec/???:"???", esp=0x7f85dba0), for accessing 0x72628000 (code=1), db=0x72de2290(0x72964700:0x72964878/0x10a982ec:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x71f71000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x71821000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x729647ac (???) (x86pc=0x10a982ec/???:"???", esp=0x7f85dba0), for accessing 0x71812000 (code=1), db=0x72de2290(0x72964700:0x72964878/0x10a982ec:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x716f1000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
20156|SIGSEGV @0x7295e984 (???) (x86pc=0x10a982d2/???:"???", esp=0x7f85dba0), for accessing 0x716e1000 (code=1), db=0x72ddd538(0x7295e900:0x7295eae4/0x10a982d2:0x10a9832a/???)
Box86 with Dynarec v0.1.5  built on Nov  4 2020 02:18:37
002e:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
002f:fixme:resource:GetGuiResources (0xc8,0): stub
0029:fixme:mountmgr:query_property Faking StorageDeviceProperty data

**Comment by Mr-HappyLI** [comment]
@ptitSeb 
0x403982: Dynarec stopped because of Opcode 0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8
0x1127d7f3: Dynarec stopped because of Opcode C5 F4 57 C9 03 F9 EB 0F C5 F5 74 01 C5 FD D7
I found the code execution place, but I'm not very familiar with the opcode. Can you help me or give me some advice to find books.
Thank you!

**Comment by ptitSeb** [comment]
Can this ticket be closed?
