### ISSUE TITLE
I want to add the corresponding operation of opcode 0f AE A9 00 Fe ff ff 8b 85 24 FA ff ff 31 D2. But I'm puzzled by the way some functions are used.

### ISSUE THREAD

**Issue by acbbghhgf** [ptitSeb/box86#247]
I want to add the corresponding operation of opcode 0f AE A9 00 Fe ff ff 8b 85 24 FA ff ff 31 D2. But I'm puzzled by the way some functions are used.
such as：
`addr = geted(dyn, addr, ninst, nextop, &ed, x1, &fixedaddress, 0, 0);`
`addr = geted(dyn, addr, ninst, nextop, &ed, x2, &fixedaddress, 0, 0);`
`addr = geted(dyn, addr, ninst, nextop, &ed, x2, &fixedaddress, 255, 0);`
`addr = geted(dyn, addr, ninst, nextop, &ed, x2, &fixedaddress, 4095, 0);`
All of them are base indexed addressing, but why is the eighth parameter 0，255，4095? How are these figures determined?

I find the missing operation of opcode, such as：XSAVE、XRSTOR、CLFLUSH。
Their corresponding operations are as follows:

XSAVE：
       The XSAVE feature set supports the saving and restoring of state components, each of which is a discrete set of
processor registers (or parts of registers). In general, each such state component corresponds to a particular CPU
feature. Such a feature is XSAVE-supported. Some XSAVE-supported features use registers in multiple XSAVEmanaged state components.
        The XSAVE instruction takes a single memory operand, which is an XSAVE area. In addition, the register pair
EDX:EAX is an implicit operand used as a state-component bitmap (see Section 13.1) called the instruction
mask. The logical-AND of XCR0 and the instruction mask is the requested-feature bitmap (RFBM) of the user
state components to be saved.

XRSTOR:
        The XRSTOR instruction takes a single memory operand, which is an XSAVE area. In addition, the register pair
EDX:EAX is an implicit operand used as a state-component bitmap (see Section 13.1) called the instruction
mask. The logical-AND of XCR0 and the instruction mask is the requested-feature bitmap (RFBM) of the user
state components to be restored.
        The following conditions cause execution of the XRSTOR instruction to generate a fault:
• If the XSAVE feature set is not enabled (CR4.OSXSAVE = 0), an invalid-opcode exception (#UD) occurs.
• If CR0.TS[bit 3] is 1, a device-not-available exception (#NM) occurs.
• If the address of the XSAVE area is not 64-byte aligned, a general-protection exception (#GP) occurs.1

CLFLUSH:
        Flushes and invalidates a memory operand and its associated cache line from all levels ofthe processor’s cache hierarchy.

Professor ptitSeb，Facing the operation of the above three instructions, what should I do?

**Comment by Mr-HappyLI** [comment]
Hello, I'm adding some opcode recently, but I'm at a loss. Can you give me some help?

**Comment by ptitSeb** [comment]
So, adding some opcode in the Dynarec?

First, be sure to look at the interpretor side before adding stuff to the Dynarec.

Now, that geted is to compute the ModR/M part when accessing a memory address. The x86 has a sofistacated way of addressing memory, with a some of up to to register with an optional shift on one of the, plus a constant. The ARM can access memory with an added constant. So ARM opcode (like LDR, STR or the byt variant) can use an offset of up to 4095 byte. Some other of nly 255 bytes, and some 1023, but ignoring the 3 lower bits... Some don't have any constant.

So the last 3 arguments of geted are there to handle that: the `&fixedaddress` is the variable that will hold the offset, the `4095` is the max value (negative value too, so it will be `-4095<=fixedaddress<=4095`) and the last one is how many lower bits are ignored (and so must be 0 in fixedvalue).

For XSAVE, the easy way would be to call a C function that do the save/restore like for FXSAVE and FXRSTOR (in `dynarec_arm_0f.c` lines 1533-1553), and so the value will be 0, as the function call doesn't handle any offset.

**Comment by Mr-HappyLI** [comment]
Hi，@ptitSeb, I want to add XGETBV and I have this opcode '0F 01 D0 89 45 F4 89 55 F8 8B 45 F4 8B 4D F8'.
Do I need to use the function got? Or use LDR directly_ Imm9 this function(in dynarec_arm_0f.c).
Thank you.

**Comment by acbbghhgf** [comment]
@ptitSeb Hi, I read that codes.

```
            switch((nextop>>3)&7) {
                case 0:                 /* FXSAVE m512byte */
                    // should save flags & all
                    // copy MMX regs...
                    for(int i=0; i<8; ++i)
                        memcpy(((void*)(ED))+32+i*16, &emu->mmx[0], sizeof(emu->mmx[0]));
                    // copy SSE regs
                    memcpy(((void*)(ED))+160, &emu->xmm[0], sizeof(emu->xmm));
                    // put also FPU regs in a reserved area...
                    for(int i=0; i<8; ++i)
                        memcpy(((void*)(ED))+416+i*8, &emu->fpu[0], sizeof(emu->fpu[0]));
                    break;
                case 1:                 /* FXRSTOR m512byte */
                    // should restore flags & all
                    // copy back MMX regs...
                    for(int i=0; i<8; ++i)
                        memcpy(&emu->mmx[i], ((void*)(ED))+32+i*16, sizeof(emu->mmx[0]));
                    // copy SSE regs
                    memcpy(&emu->xmm[0], ((void*)(ED))+160/4, sizeof(emu->xmm));
                    for(int i=0; i<8; ++i)
                        memcpy(&emu->fpu[0], ((void*)(ED))+416+i*8, sizeof(emu->fpu[0]));
```

In this way, first use `memcpy((void*)(ED)+32+i*16, &emu->mmx[0], sizeof(enu->mmx[0]);`, sure, [(ED)+32 -(ED)+512] data  through memcpy save to emu->mmx/emu->xmm . However, [(ED)+0 - (ED)+32] data ?

is that data ?  do not necessary to save it?

15 14 | 13 12 | 11 10 | 9 8 | 7 6 | 5 | 4 | 3 2 | 1 0
-- | -- | -- | -- | -- | -- | -- | -- | --
FIP[63:48] orreserved | FCS orFIP[47:32] | FIP[31:0] | FOP | Rsvd. | FTW | FSW | FCW | 0
MXCSR_MASK | MXCSR | or reserved FDP[63:48] | FDP[47:32] FDS or | FDP[31:0] | 16


I read the description of FSAVE, however I still don't understand.
I want to add XGETBV, The official description is like this: 

`run0f.h`

```
__0f_0x01:
    nextop = F8;
    switch((nextop>>3)&7){
        case 4://SMSW Ew
            ....
            ....
            break;
        default:
            switch(nextop){
                case 0xD0:   /* XGETBV EDX:EAX, XCR[ECX]   */
                    // EDX:EAX ← XCR[ECX];
                    nextop = F8;
                    GET_ED;
                    memcpy(R_EAX, (void*)(ED), sizeof(R_EAX));
                    memcpy(R_EDX, (void*)(ED)+4, sizeof(R_EDX);
                    break;
                case 0xD1: /* XSETBV  XCR[ECX], EDX:EAX*/
                    //XCR[ECX] ← EDX:EAX;
                    break;
            }
    }
    NEXT;
```

**Comment by ptitSeb** [comment]
Nope, I don't think so. The XGETBV/XSETBV use some register that are not implemented at all for now. So some handling of XCR regs need to be added first. So the `x86emu_t` structure first need to be expanded with XCR, and then some reasonable default value needs to beset on those? After that, implementating this opcode will be doable.

An easy approach would be to simply consider the XCR[x] regs to be 0, and simply return 0 to EAX and EDX on XGETBV, and ignore XSETBV. Not sure it would enough. Or maybe, according to https://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol3/o_fe12b1e2a880e0ce-81.html just return `3` and still ignore `xsetbv`

(for your 1st question about FXSAVE/FXRSTR, the opcode is partially implemented, so some part are not saved/restored at all)

**Comment by ptitSeb** [comment]
So minimum implementation would be more like:
```
           switch(nextop){
                case 0xD0:   /* XGETBV EDX:EAX, XCR[ECX]   */
                    // EDX:EAX ← XCR[ECX];
                    R_EAX = (R_ECX==0)?3:0; // should create a General protection fault for ECX!=0
                    R_EDX = 0;
                    break;
                case 0xD1: /* XSETBV  XCR[ECX], EDX:EAX*/
                    //XCR[ECX] ← EDX:EAX;
                    //ignored
                    break;
            }
```

**Comment by ptitSeb** [comment]
don't implement a dynarec version of that for now, it's not necessary

**Comment by acbbghhgf** [comment]
I'm very much obliged to you. 👍 👍 👍 
Oh, so, You are going to expand the `x86emu_t` structure with the XCR ? Is it the upcoming version?  :)
Or， These instructions that use the extended control register don't need to be considered for the time being ？
