### ISSUE TITLE
Box86 on PBP. Double SIGENV running Steam

### ISSUE THREAD

**Issue by Enne2** [ptitSeb/box86#255]
Hi Sebastien,
first of all thank you for this awesome project, it's brilliant and a pure holy grail for Gnu/Linux on ARM users. I've tested it for some native and wine-needing games like starcraft, warcraft 2 and 3, even a 32 bit old release of factorio. All of them work incredibly nice, but I get issues running Steam: after valid login, when it comes to load the Steam UI start to print DOUBLE SIGENV! continuosly, and login in window hangs 
My platform is a Pinebook Pro (as you probably know, a RK3399 machine) on Debian bullseye with a custumized kernel and an ARM64 root with a multiarch environment with also armhf and i386 repository. I'm using Panfrost driver to get native OpenGL 2.1 support. I've compiled box86 with cross compiler for armhf and installed necessary armhf libraries asked from every specific binary using armhf repository. No armhf chroot needed. I've installed Steam adding i386 architecture and installing it via dpkg using official deb file from Valve. The same procedure works good on a RPI3 (i've no RPI4) where Steam works and start downloads games, but suddendly crashes probably due the la of system memory.
I suppose you've made some hardcoded hacks to let Steam works on the specific platform of RPI, how can I help to make it also work on RK3399? Am I missing something? How can I give you more debug informations?
Matteo

**Comment by ptitSeb** [comment]
There is not much hardcoded hack for Steam, and none is specific to RPi. Only speicifc hack for Pi is for GOG Linux Installer (and I'll probably put this hack for RK3399 too soon).

As you may have noticed, there is now an RK3399 profile to build box86 directly on the board. You'll need `arm-linux-gnueabihf-gcc` (you can certainly apt install it) and you'll be able to build directly on your RK3399.
I haven't started testing Steam. It seem to be crashing indeed, even with all need lib installed (like libappindicator1 and libnm*). I'll debug it soon.

**Comment by Enne2** [comment]
Great! Earlier I've tested box86 with an armhf root on arm64 kernel. I found your note about your work on RK3399 and I immediately tried. However with the generic ARM cmake profile on an armhf root box86 works the same, also compiling it in an armhf chroot and installing files manually on arm64 root with multiarch it's a viable solution.
The GOG installer is a sad missing on PBP, it's a great news to know that you are working on it!
Keep up the good work, and sorry for the error (it's SIGEGV, now I know it is referred to a segmentation error :/ )

**Comment by ptitSeb** [comment]
Ok, I enabled the GOG Linux installer hack for RK3399, if you can try it :)

**Comment by Enne2** [comment]
You're a FOSS hero :D, however it's not working on PBP, I've pulled the git, recompiled and reinstalled but the installer has the same  behaviour 
$ wine setup_dungeon_keeper_2_1.7_\(22280\).exe 
Box86 with Dynarec v0.1.5 d833f136 built on Nov 22 2020 18:51:53
Box86 with Dynarec v0.1.5 d833f136 built on Nov 22 2020 18:51:53
Box86 with Dynarec v0.1.5 d833f136 built on Nov 22 2020 18:51:53
0009:fixme:process:SetProcessDEPPolicy (1): stub
110760|SIGBUS @0x62ba94e4 (???) (x86pc=0x403041/???:"???", esp=0x7f5fdde8), for accessing 0x7f5fde1e (code=1), db=(nil)((nil):(nil)/(nil):(nil)/???)
wine: Unhandled alignment at address 00403041 (thread 0009), starting debugger...
Box86 with Dynarec v0.1.5 d833f136 built on Nov 22 2020 18:51:53
winedbg detected, not launching it!
0009:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 8 116" (1359)
Read the Wine Developers Guide on how to set up winedbg or another debugger

And a window says "Runtime Error 255 at..."
It's the same problem of other types of installation wizard. Am I missing something?

**Comment by ptitSeb** [comment]
Ah SIGBUS. Yeah, I'm on it, I think I have a workaround. It will be pushed soon.

**Comment by ptitSeb** [comment]
And the Steam Segfault should be fixed now. Be aware that youneed to install many gtk related lib, in the armhf arch, to use steam (link libddbus-glib1, libnm, libappindicator...)

**Comment by Enne2** [comment]
**You are awesome mate! :D** 
I'll download and test some native Steam linux games tomorrow
![photo5897482782152701333](https://user-images.githubusercontent.com/6107089/99917420-71636c80-2d10-11eb-8675-f1a8bb87b86f.jpg)

Thank you Sebastien!

**Comment by ptitSeb** [comment]
Nice! Steam on a PBP :) You must be one of the first to have that! Go spread the word on the Pine64 forum also \o/

**Comment by ptitSeb** [comment]
Also, BigPicture should work :D

**Comment by ptitSeb** [comment]
Last comment: steam still doesn't quit properly, so you have to `killall -9 steam` after exiting it to really quit...

**Comment by Enne2** [comment]
Good morning Sebastien,
I've tested two game for now, Half-Life (it works with no issues) and HL2: Lost Coast (It runs good but has glitches and low video performance due to an incomplete OpenGL support of Panfrost driver, I've also noticed that glitches on light reflection with Warcraft 3 with opengl render)
However there is a Steam strange behaviour that I've also found running Steam on RPI3: when I'm downloading a games for more than 5 minute (I suppose, however this behaviour it's not related to the amount of data) box86 falls in a perpetual double SIGSEGV and everything freezes. When I force to kill steam and try  to restart it backs in a SIGSEGV loop after login. the only way to get it back to work is to delete all ~/.local/share/Steam folder and reinstall it again.
However I found a workaround: if I start steam in command line with the option to start a specific game, Steam completely bypass the Steam Client main UI and downloads the game in background. This solution avoids completely the SIGSEGV.
Maybe there is a problem with some instruction translation or library wrapping (only used by Steam main UI) causing a memory leak during download in certain conditions?
However this is a marginal problem to me, ASAP I'll start a thread on pine64 forum to spread the good news :D

**Comment by ptitSeb** [comment]
Yes, there is probably a leak but I haven't found it yet. It's pretty difficult to pinpoint were that leak could be, and I haven't found a way to track it neither.

**Comment by ptitSeb** [comment]
For the HL2:Lost Coast issue, do an apitrace capture for the mesa dev guys :)

**Comment by Enne2** [comment]
I've never used apitrace, an opportunity to learn something new :D 
Let me know about progresses on Steam, mojoinstaller and every other thing on rk3399. I will test them for you with pleasure ;)
