### ISSUE TITLE
Steam Browser

### ISSUE THREAD

**Issue by Pythonic456** [ptitSeb/box86#256]
Quick question: Do you think that the Steam Browser will ever support 32 bit again? It's quite hard to use the small mode all the time...

**Comment by ptitSeb** [comment]
No I don't think it will. Browser are not build on 32bits anymore...

Note that you can use the Big Screen mode if you prefer.

**Comment by Pythonic456** [comment]
Going Big Picture (I think that's what you meant) makes steam go fullscreen,
then plays a noise, then crashes. I have no idea why it crashes, though.

**Comment by Pythonic456** [comment]
RPi 4 B, 4G of RAM, 64Gig SD card, that's it really.
Here's the error when trying to open Big Picture:
```/data/src/common/html/chrome_ipc_client.cpp (265) : Assertion Failed: Is64BitOS()
/data/src/common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()
/data/src/common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()
mmap() failed: Cannot allocate memory
mmap() failed: Cannot allocate memory
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Input/output error
Failed to open digital audio driver Couldn't open OAL device.
/data/src/common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()
/data/src/common/friendsuihelpers.cpp (54) : Assertion Failed: Is64BitOS()
***** OUT OF MEMORY! attempted allocation size: 2097152 ****
/data/src/tier0/memstd.cpp (2448) : Fatal Assertion Failed: OUT OF MEMORY
/data/src/tier0/memstd.cpp (2448) : Fatal Assertion Failed: OUT OF MEMORY
/data/src/tier0/memstd.cpp (2448) : Fatal assert failed: /data/src/tier0/memstd.cpp, line 2448.  Application exiting.

/data/src/tier0/memstd.cpp (2448) : Fatal assert failed: /data/src/tier0/memstd.cpp, line 2448.  Application exiting.

Installing breakpad exception handler for appid(steam)/version(1603992987)
_ExitOnFatalAssert
pi@raspberrypi44g:~ $ 
```

**Comment by ptitSeb** [comment]
That OpenAL error is a bit strange.
The out of memory too, I don't have that.
what version of Mesa do you use? A 20.3 (I think) is advised, or a 21. Older 19 don't support S3TC and will not work for most things.

What is your OS?

**Comment by Pythonic456** [comment]
I'm not sure how to tell what Mesa version I use.

I use the Raspberry Pi OS 32-bit, with up-to-date software.
