### ISSUE TITLE
EZNEC 6.0

### ISSUE THREAD

**Issue by WheezyE** [ptitSeb/box86#259]
This software is pretty minor, but would be cool to have it working on Pi. I also though this might be a good error report just for bug finding.

The EZNEC 6.0 demo installs fine with or without msxml3 installed first (though the installer behaves differently in box86 if msxml3 is installed first ---- also x86 linux wine has the installer behave the same with or without msxml3 installed first, which is weird).

The program installs fine in x86 linux and on box86, and it runs fine on both, but then when trying to calculate farfield plots for antenna models, it crashes in box86 without an obvious error.  I'll try logging next.

![eznec](https://user-images.githubusercontent.com/29649598/100564647-d5d97b00-327e-11eb-9446-5b1c6eb0b995.png)

**Comment by ptitSeb** [comment]
I checked, and yes, wine internal msxml3use libxml2.so that is not wrapped yet on box86. That why it doesn't load.
I'll add libxml2 wrapping (and maybe libxslt.so too, that is optionnaly used) soon.

**Comment by WheezyE** [comment]
Awesome! 🙂 And thanks for checking into it. I’m excited to see how things go with that one wrapped

**Comment by WheezyE** [comment]
I never reported back on this thread (I think I posted in the discord) but this wrapping unfortunately didn't help the program crash during far field plot calculation.

**Comment by WheezyE** [comment]
I was on a debugging kick today and found a new opcode that pops up right when the farfield plot calculation fails:
```
Warning: Cannot dlopen("/home/pi/wine/lib/wine/msvcrt.so"/0x646c3c18, 2)
Warning, CPUID command 80000008 unsupported (ECX=00100000)
Warning, CPUID command 14 unsupported (ECX=00000000)
30885|0x68c17c: Unimplemented Opcode 66 0F D0 F3 66 0F C6 E5
```
Here's the whole log1: [eznec_log1.log](https://github.com/ptitSeb/box86/files/5745474/eznec_log1.log)

**Comment by WheezyE** [comment]
With that op code added, the far-field plot calculates now!

The near field tab (which isn’t really important) causes a crash for some reason, but I can’t find the bug yet.

Thank you! This seems to be working 🙂
