### ISSUE TITLE
Serial ports with Box86 and Wine

### ISSUE THREAD

**Issue by AxlPr** [ptitSeb/box86#262]
Hi. I'm running a Raspberry Pi 3 with the latest Raspbian OS with a recompiled kernel (3G/1G split). I've built Box86 from latest code and installed Wine from Twister OS (5.1.3). I've managed to get some programs working which is great but am having issues with one that is attempting to use a serial port. The device is a data logger which has a USB to Serial converter (PL2303).

When I run the software it can see the COM ports but connecting results in it getting stuck in what appears to be calling IOCTL_SERIAL_GET_TIMEOUTS (GetCommTimeout). Here is an extract from the Wine log with WINEDEBUG="+comm" enabled:

0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_GET_BAUD_RATE (nil) 0 0x7f5aea24 4 0x7f5ae9b8
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_GET_LINE_CONTROL (nil) 0 0x7f5aea21 3 0x7f5ae9b8
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_GET_HANDFLOW (nil) 0 0x7f5aea30 16 0x7f5ae9b8
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_GET_CHARS (nil) 0 0x7f5aea2a 6 0x7f5ae9b8
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_SET_BAUD_RATE 0x7f5aea54 4 (nil) 0 0x7f5ae9f8
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_SET_LINE_CONTROL 0x7f5aea51 3 (nil) 0 0x7f5ae9f8
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_SET_HANDFLOW 0x7f5aea60 16 (nil) 0 0x7f5ae9f8
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_SET_CHARS 0x7f5aea5a 6 (nil) 0 0x7f5ae9f8
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_GET_TIMEOUTS (nil) 0 0x7f5aea84 20 0x7f5aea08
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_SET_TIMEOUTS 0x7f5aea84 20 (nil) 0 0x7f5aea08
...
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_GET_TIMEOUTS (nil) 0 0x7f5aea84 20 0x7f5aea08
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_SET_TIMEOUTS 0x7f5aea84 20 (nil) 0 0x7f5aea08
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_GET_TIMEOUTS (nil) 0 0x7f5af180 20 0x7f5af178
0024:trace:comm:io_control 0xb4 IOCTL_SERIAL_GET_TIMEOUTS (nil) 0 0x7f5af180 20 0x7f5af178
... (repeats forever)

The software & device work fine on a Windows machine and I know people having this working with x86 Linux. So I was wondering if anyone has serial ports working with this setup (Box86 & Wine) or if it's not something currently supported. I've also tried the Pi's onboard serial port and get same issue.

Many thanks and great work!

**Comment by WheezyE** [comment]
I have no idea if this will help - and maybe you've tried this already - but I found some instructions for another program that needs com ports with wine:

> Please note that on later versions of Wine, a USB/Serial cable may automatically become COM33, so if COM1 isn’t working, try COM33 manually installing COM1 port for rig control.
>
> ONLY if COM33 doesn’t already work, otherwise skip this step. This command will make a symlink (aka, an alias or shortcut) for COM1 in the dosdevices folder, which points to the USB device – usually ttyUSB0 on linux
> 
> ln -s /dev/ttyUSB0 ~/.wine/dosdevices/com1
> 
> Now add the COM port to the windows registry.
> 
> gedit ~/.wine/system.reg
> 
> After “#arch-win32”, add the following two lines, save and exit.
> 
> [Hardware\Devicemap\Serialcomm] 1131331688
> 
> “COM1″=”COM1”

**Comment by AxlPr** [comment]
I've not had this issue with it incorrectly assigning the com ports. In fact it's working fine so when Wine starts it automatically creates the symlinks under .wine/dosdevices and adds Registry entries in system.reg, e.g.

lrwxrwxrwx 1 pi pi 10 Dec  6 09:41 com1 -> /dev/ttyS0
lrwxrwxrwx 1 pi pi 12 Dec  6 09:41 com2 -> /dev/ttyUSB0

[Hardware\Devicemap\Serialcomm]
“\Device\Serial0″=”COM1”
“\Device\Serial1″=”COM2”

Here I've enabled the onboard serial (GPIO) and attached the device with the USB to Serial converter. So this bit is working great. I've also checked the "pi" user has correct permissions, i.e. been added to "sys" and "dialout" groups. "dmesg" shows it's installed ok and running commands like "screen" shows it can connect. Also changed the power supply and usb leads to no avail.

So appears it's just the communications part which is having problems. Presumably it's something that's not supported currently but just wanted to verify.

Thanks.

**Comment by ptitSeb** [comment]
I need to check what wine is doing on that communication part. IOCTL are supported in box86, but maybe those IOCTL command need translations (different value on i386 vs ARM)?

**Comment by AxlPr** [comment]
FYI I just tried it out on a Ubuntu VM running inside VirtualBox on my Windows 10 laptop. I enabled the USB device so the VM could see it, then installed Wine (v5) and the data logging software (ZKETECH). I had to reconfigure the com ports as it actually ended up creating 33 com ports as described above. But once that was done the software was able to connect to the USB device. Interestingly the Wine log showed exactly same logs as on the Pi (IOCTL_SERIAL_GET_TIMEOUTS repeating etc). Only difference was that it could connect to the device.

**Comment by AxlPr** [comment]
Just tested a build with the code from today (29th Dec) and the USB to serial converter seems to be working now in my Windows app running under Wine 5.1.3 (TwisterOS version). I'm note sure what fix resolved the issue but happy report it's working! I've tested it on both a rpi 3 and 4. Many thanks!
