### ISSUE TITLE
VCMI x86 - not working

### ISSUE THREAD

**Issue by nru1979** [ptitSeb/box86#266]
Segmentation fault.
Might be  a decent plan B if HoMM3 is impossible to make work.
Configuration: 
Debian stretch 386 package installed vcmi and deps
PI 3B+
Raspbian Buster
256mb /var/swap
Box86 0.1.7

![2020-12-09-213448_1920x1080_scrot](https://user-images.githubusercontent.com/75307620/101684745-2c0ca200-3a67-11eb-96ea-49fd59adc6ac.png)

**Comment by ptitSeb** [comment]
Symbol `mpg123_scan` is missing and is probably not helping, I need to add it.

Can you do a `addr2line -e /usr/local/bin/box86 -a 0x6281515c` also.

**Comment by nru1979** [comment]
0x6281515c
/home/pi/box86/src/box86context.c:168

**Comment by ptitSeb** [comment]
Oh, that's odd.

Does `BOX86_JITGDB=1` works for you (I mean, it launch gdb and it's usable on that Segfault)?
I would like to the result of that command: `thread apply all bt` then. I don't understand why `context` would be NULL in `addDBFromAddressRange(...)`

**Comment by ptitSeb** [comment]
Nevermind, I can reproduce it on my side.

**Comment by nru1979** [comment]
runs the intro then crashes
![2020-12-10-175013_1920x1080_scrot](https://user-images.githubusercontent.com/75307620/101803082-70a04800-3b10-11eb-868e-3907ef8d6725.png)

**Comment by ptitSeb** [comment]
well, it goes farther. So that's technically another issue.

Your addr2line command is not good, you forget the `-e` for the exe and `-a` for the address.
Anyway, that's not much interresting here; as the crash seems to be inside libvcmi.so, in a precise C++ function, accessing some strucutr behind a null pointer probably.

**Comment by ptitSeb** [comment]
Well, what is strange is that you may be in the interpretor instead of the dynarec... So the addr2line result might still be interresting.

**Comment by nru1979** [comment]
pi@raspberrypi:~/games $ addr2line -e /usr/local/bin/box86 -a 0x62865c64
0x62865c64
/home/pi/box86/src/emu/x86run.c:1572

**Comment by nru1979** [comment]
last fix made heroes 4 so slow that it became unplayable.
vcmi intro plays very slow too. seems to be a cpu or gpu overload problem. moving mouse pointer on menu screen works fine

**Comment by ptitSeb** [comment]
the "Improve PltResolver" one? Can you check what function consume CPU the most? (using things like `sudo perf top` but "perf" is not always here for the right kernel, you may need to use `perf_*` like `perf_4.18` or some like that.

**Comment by nru1979** [comment]
This fix seems to have fixed Heroes 3 though. No more segmentation faults there so far.
However, it hurts performance extremely bad. Heroes 3 became as slow as Heroes 4 (before the patch). 
So now, VCMI --> very slow intro then crashes
H3: very slow intro then slow but stable game
H4: extremely slow, I think it is stable though. but it is so slow that it is unplayable.

**Comment by nru1979** [comment]
no perf_5.4 availlable for my buster :-( Perf 4.9 does not provide perf top seemingly

**Comment by ptitSeb** [comment]
The slowiness is with the windows version?
That's very strange. It's not a sideeffect I can explain.

Can you downgrade to previous commit -`git checkout dcbb8b29de55062945de34111edbda088d5a93d6` to make sure that commit have this effect?

**Comment by nru1979** [comment]
slowness seems to happen with everything. 
Not very familiar with git...
Does not seem to give results that way:
![2020-12-10-220737_1920x1080_scrot](https://user-images.githubusercontent.com/75307620/101830126-58422480-3b34-11eb-8d01-81ff10ba2798.png)

**Comment by ptitSeb** [comment]
That's fine. You are no on the previous commit. Just `make -j3 && sudo make install` to install that version and test.
After that, to go back to latest version, do `git checkout master` than `make -j3 && sudo make install`...

**Comment by nru1979** [comment]
vcmi still shows intro. im still on the newest commit... git pull didnt refresh my files.

**Comment by ptitSeb** [comment]
Yes it does. It just that I pushed 3 or 4 comits at the same time...
Look with the github web interface, click the "3006 commits" zone to have the list of all commits.
The one that fixed the issue is named "Initialize context as soon as possible in library (should help #265 and …"
You can see there are a few more after that... So it may no be the "last" one.

**Comment by nru1979** [comment]
OK just noticed.
Ill try 4e7e0f6aab2ccc060e19d815907d37db2138c26d and 9805ad7f3a8e5fb8cf67d8a3323af965acd0e095
I have a feeling the speed issue on windows might be linked to these 2.
might happen tomorrow though... Not sure to be awake enough to do it today.

**Comment by nru1979** [comment]
I feel im missing something: no matter the checkout I take, box86 still behaves the same.
Only the signature of the build change.
Is there a command to manually sync my directory with the checkout?

**Comment by nru1979** [comment]
ok git checkout works. I get older behaviors.
Looks like performance issue is not in the last commits. Ill try to back to the future and look for the commit which changed everything.
I keep you informed

**Comment by ptitSeb** [comment]
Maybe you have a parasite process slowy things down (check with `htop` or reboot)?
Or maybe you rebuilt without Dynarec enabled (or without the PI4 profile). Check that "with Dynarec" is mentionned when you type  `box86 --version`

**Comment by nru1979** [comment]
The problem was the user: I forgot DRPI3=1 in cmake.
Now works well. No more performance issue. I will go forward with stability tests in H3 windows and hopefully come back with a positive outcome.
Sorry for loss of time
