### ISSUE TITLE
Steam Crash

### ISSUE THREAD

**Issue by itShirb** [ptitSeb/box86#272]
I got logged into steam and turned on the "Remember Me" option, then it proceeded to close. All subsequent attempts up to now have resulted in it getting to the "Verifying installation" window and then closing. Every time it closes i hear a short buzz sound in my headphones but I'm not sure if that's related to the issue or not.

**Comment by ptitSeb** [comment]
Did you check the other tickets about steam before openning this one?

**Comment by itShirb** [comment]
I checked a few but either I missed the ones with this exact issue or there aren't any.

**Comment by itShirb** [comment]
if you could link me to a ticket that might potentially solve my issue that would be appreciated

**Comment by ptitSeb** [comment]
Did you check this one: https://github.com/ptitSeb/box86/issues/252 ?

**Comment by itShirb** [comment]
i just tried it and it still crashed. Do I need to reboot my pi for it to take effect?

**Comment by ptitSeb** [comment]
It never hurt to reboot.
Now, I'll need console log of the crash to go further, if it still crash.

**Comment by itShirb** [comment]
Oh hey it worked! Thanks!

**Comment by itShirb** [comment]
now i just need to figure out how to fix screen tearing on my pi
