### ISSUE TITLE
mmap in guest

### ISSUE THREAD

**Issue by cris8259** [ptitSeb/box86#277]
box86 support use /dev/mem and function mmap to r/w soc registers ?

**Comment by ptitSeb** [comment]
I´m not sure I understand the question, but box86 translate calls to ´mmap´ functions or access to ´/dev/mem´ from guest to host.
There is no specific transformations.

**Comment by cris8259** [comment]
i want to use /dev/mem file and mmap to access gpio registers  and other registers , in Eltechs Exagear user manual , it says "We provide limited support for /dev/mem and /proc. "  i tried to open the file  /dev/mem in exagear guest as root , it appears "Operation not permitted" ,  so i want to know box86 can achieve this ?

**Comment by ptitSeb** [comment]
Yes those operation are allowed in box86. But why would you need that? Just a reminder, OpenGL driver like mesa are wrapped, so the Native version is used directl. no need to build an x86 one to have hardware acceleration.

**Comment by cris8259** [comment]
i want to write some particular drivers , like control an gpio pin , i can access gpio register directly to achieve it ,  it is direct and efficient .  Is there some box86  .deb  package ？ i want to test it in arm64 ubuntu

**Comment by ptitSeb** [comment]
There is no .deb of box86. Installing box86 on an aarch64 system can be a bit tricky. You need 32bits subsystem. like armhf multiarch or sysroot.

**Comment by cris8259** [comment]
so i must use source code to compile and install  ?

**Comment by ptitSeb** [comment]
Go to the discord channel. you can find prebuild version or AppImage of box86 there.

**Comment by cris8259** [comment]
ok,  thank you , ptitSeb
