### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by Genius-Format** [ptitSeb/box86#281]
Hello, I need to uninstall it because zoom is completely malfunctioning on my Raspberry Pi 400 running the latest version of the Raspberry Pi OS and I cannot seem to fix it. I think that if I uninstall it then re-install it, it will hopefully help me.

### __*```SO... HOW DO YOU EVEN UNINSTALL THIS THING?!?!?!?```*__
Please reply on how you do it. It would really help.

**Comment by ptitSeb** [comment]
If you install with make, use `sudo make uninstall` to uninstall.
If  you installed zoom using pikiss or piapps. please check with the maintenair of the app.

**Comment by Aradionov366** [comment]
> If you install with make, use `sudo make uninstall` to uninstall.
> If you installed zoom using pikiss or piapps. please check with the maintenair of the app.

sudo make uninstall is dont working

**Comment by ptitSeb** [comment]
Yes it works.

How did you install box86? How do you know it's not uninstalled?

**Comment by Genius-Format** [comment]
I used Pi-Apps to install zoom. I still can see the box86 folder in the 'pi' user folder.

**Comment by ptitSeb** [comment]
I suggest you open a ticket in piapps github repo for the zoom app or the uninstall issue.

**Comment by Genius-Format** [comment]
Wait... I figured out that box86 is in the pi-apps menu, so I installed it then uninstalled it. I am now installing zoom again.

**Comment by ptitSeb** [comment]
I assume this ticket can be closed?

**Comment by Genius-Format** [comment]
yep

**Comment by Genius-Format** [comment]
# Thank You!
