### ISSUE TITLE
Build failes on rpi3b+

### ISSUE THREAD

**Issue by TheHeroCraft1579** [ptitSeb/box86#284]
Everytime i try to compile box86 it failes. Here's my console output:

Specs:

Pi Model 3B+ V1.3 
Revision           : a020d3
SoC                : BCM2837
RAM                : 1024Mb
Storage            : MicroSD
USB ports          : 4 (excluding power)
Ethernet ports     : 1
Wi-fi              : True
Bluetooth          : True
Camera ports (CSI) : 1
Display ports (DSI): 1

I'm currently running raspbian lite with a lxde desktop.

![image](https://user-images.githubusercontent.com/38401902/103205710-7a8cbe00-48fa-11eb-8d2b-2f20562872a6.png)

**Comment by ptitSeb** [comment]
don't use `make -j4`. You ran out of memory. Simply use `make` (no `-j`at all) and it should build without issue.

**Comment by ptitSeb** [comment]
Is it solved? Can I close the ticket?

**Comment by michas0602** [comment]
Have had the same issue, Option -j3 was fine with just 64Mb ram set for gpu. Without -j, plain "make" made it crash like here as all cores were used.

**Comment by ptitSeb** [comment]
What is this make? `make` is supposed to be like `make -j1`. But `make -j` will start as many thread as it can compile in parallel.

**Comment by michas0602** [comment]
Oops, my mistake, this here happened to me last (long) night while compiling Mesa with Ninja, not this project here, sorry. Not sure out of my head what plain `make` does / how many cores it utilizes...but as you already said, it could/should be changed with -j.. when too much memory is used and the process crashes.

**Comment by ptitSeb** [comment]
Ninja used "number of proc/thread"+1 IIRC to build. So that would be like `make -j5` on a Pi3/Pi4

**Comment by TheHeroCraft1579** [comment]
Ok now it worked :-)
