### ISSUE TITLE
GTA San Andreas (Works sort of)

### ISSUE THREAD

**Issue by Crazily** [ptitSeb/box86#287]
Game starts. Loads. Plays. (it's amazing it even works atall tbh)  plays outrageously poorly. I'll likely post a gif tomorrow of it. But it's like. Seconds per frame instead of frames per second. I'm happy to help by giving command line output and debug information.

**Comment by ptitSeb** [comment]
On what hardware are you running? What wine version also and OpenGL driver?

**Comment by Crazily** [comment]
I am on a raspberry pi 4 using gl4es

**Comment by ptitSeb** [comment]
Oh, using gl4es? nice.
Stiil, you should try with Mesa 20.2 directly. Also you can try 20.3, sometimes it works better, but sometimes, it crash. For now, you should avoid 21.0, it's too early.
If you are on 19.x, I suggest you try to update.

**Comment by Crazily** [comment]
How would I go about doing that?

**Comment by ptitSeb** [comment]
Come to the discord server mentionned in the README.md for more help.
(This is not directly related to box86).

**Comment by iamSlightlyWind** [comment]
> Still, you should try with Mesa 20.2 directly.

@ptitSeb if possible, could you give me a simple instruction of what to do to get mesa working, or link me to an answered issue? I can't seem to find any suggestion to get some sort of hardware acceleration.

For instance, I use a ubuntu aarch64 20.04 chroot on an android device. I compiled [mesa-turnip-kgsl](https://github.com/Grima04/mesa-turnip-kgsl) in my chroot, which upon needing to use a gui app I can just
```
export GALLIUM_DRIVER=zink
```
and start the app through xwayland. However, in [here](https://github.com/ptitSeb/box86/issues/566#issuecomment-1030580912), the reply is

> > ~# glxgears -info
> > GL_RENDERER = zink (FD640)
> >GL_VERSION = 4.6 (Compatibility Profile) Mesa 21.2.0-devel (git-49138d8349)

> So your OPENGL driver as such is working (since glxgears is shown) but 32-bit wine cannot access it.

So I guess I can't just compile it then use it with box86 3d apps

```
export GALLIUM_DRIVER=zink
box86 wine winecfg #displays the config app, but
box86 wine supertuxkart.exe #wont
```

**Comment by ptitSeb** [comment]
For box86 you need a 32bits version of mesa. so you need to build mesa for armhf (the aarch64 version will be used by box64, but not box86)

**Comment by iamSlightlyWind** [comment]
Oh, I didn't notice your immediate reply, my bad. I just looked it up, and it seems like cross compiling is no simple task. I also just tried setting up an armhf chroot using linux deploy but upon ssh-ing into it, its still reporting aarch64, which is weird:
```
$ uname -m
aarch64
```
Anyway, I guess that I should just try to set up the compiling environment for armhf directly in my aarch64 chroot according to the [meson guide](https://mesonbuild.com/Cross-compilation.html). If you however know or have written a guide specifically for cross compiling armhf mesa on aarch64 chroot, please let me know, thanks!
