### ISSUE TITLE
Atelier Sophie loads but hangs before main menu.

### ISSUE THREAD

**Issue by danificadoweel** [ptitSeb/box86#288]
System: Pi 4 2GB
BOX86: Compiled dec 29 2020.
Wine 5.15 staging

Description:
The executable starts, the gust logo show up, starts to "now loading" and it hangs right before the menu appears:
![Captura de tela_2020-12-29_11-41-50](https://user-images.githubusercontent.com/61332968/103292082-e5f29080-49cb-11eb-9492-5b529efa040b.png)
![Captura de tela_2020-12-29_11-41-13](https://user-images.githubusercontent.com/61332968/103292084-e68b2700-49cb-11eb-83d6-29e3542eee61.png)

Heres the log from right before hanging:
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glColorMaski(buf=6)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glDisableIndexed(index=6)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glColorMaski(buf=7)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glDisableIndexed(index=7)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glColorMaski(buf=4)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glDisableIndexed(index=4)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glColorMaski(buf=5)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glDisableIndexed(index=5)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glColorMaski(buf=6)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glDisableIndexed(index=6)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glColorMaski(buf=7)".
01cc:err:d3d:wined3d_debug_callback 0x1ae6398: "GL_INVALID_VALUE in glDisableIndexed(index=7)".
wine: Unhandled page fault on read access to 00000000 at address B3908696 (thread 01cc), starting debugger...
Box86 with Dynarec v0.1.9 ca1fc0ff built on Dec 29 2020 11:31:56
winedbg detected, not launching it!
01cc:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 424 640" (1359)
Read the Wine Developers Guide on how to set up winedbg or another debugger
^C0298:fixme:console:default_ctrl_handler Terminating process 1a8 on event 0

**Comment by ptitSeb** [comment]
That could be a missing OpenGL function. Can you try with LLVMpipe software rendering, to see if you have the same crash?
What mesa version are you using?

**Comment by danificadoweel** [comment]
It ran with software rendering and i am using the lastest mesa from twisterOS, i think its 20.3.

Yeah, managed to make the game run with MESA_GL_VERSION_OVERRIDE but i guess the pi is too weak to run it.
Looks like this game is a no no with the pi, maybe with some more powerful system, but it seems that box86 can run it nicely!
![screenshots](https://user-images.githubusercontent.com/61332968/103305879-07af4000-49eb-11eb-9f65-8aa7015bafe6.jpg)

Thanks, PtitSeb.
