### ISSUE TITLE
Zoom - Assertion 'cb' failed at pulse/introspect.c:340, function pa_context_get_sink_info_by_name()

### ISSUE THREAD

**Issue by q4a** [ptitSeb/box86#293]
Hi. I still have problems with Zoom on Box86 with Asus Tinker Board.
My microphone is not working with Zoom, so I read tips from here: https://github.com/ptitSeb/box86/issues/257
I'm trying to Share Computer Sound when started Share Screen:
![2020-12-30_21-16](https://user-images.githubusercontent.com/1950719/103382153-d10a2000-4ae5-11eb-91a9-b26af93d8adf.png)

But always get: Assertion 'cb' failed at pulse/introspect.c:340, function pa_context_get_sink_info_by_name().

Here is run command and default output:
```
q@tinkerboard:~/soft/zoom$ BOX86_LOG=1 BOX86_DLSYM_ERROR=1 BOX86_TRACE_FILE=trace3.txt /home/q/git/box86/build/box86 ./zoom
Debug level is 1
BOX86 Trace redirected to "trace3.txt"
Box86 with Dynarec v0.1.9 54b8522d built on Dec 30 2020 16:05:08
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: 2C:4D:54:43:33:FF][client: Linux][OS: Armbian 20.11.3 Focal][Hardware: CPU Core:4 Frenquency:1.8 G Memory size:2001MB CPU Brand:              Intel(R) Pentium(R) 4 CPU 1800MHz GPU Brand:][Req ID: ]
Linux Client Version is 5.4.2 (53391.1108)
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = XFCE;   GDMSESSION = xfce
Graphics Card Info:: 
Zoom package arch is 32bit, runing OS arch is i386
AppIconMgr::systemDesktopName log Desktop Name: xfce 
link image0 hasn't been detected!
Could not resolve property : pattern0
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
CSBConfUI::OnConfStatusChanged  UI_CMD_SHARE_READYAssertion 'cb' failed at pulse/introspect.c:340, function pa_context_get_sink_info_by_name(). Aborting.
Aborted
```

Here is trace file: [trace3.txt](https://github.com/ptitSeb/box86/files/5755781/trace3.txt)
And here is backtraces from gdb (I attached gdb to Zoom before press "Share" button): [zoom-dbg.log](https://github.com/ptitSeb/box86/files/5755789/zoom-dbg.log)

Can you check, is that assertion related to box86 or pulseaudio?

**Comment by ptitSeb** [comment]
I'll try on my side yes.

This function `pa_context_get_sink_info_by_name` seems correctly wrapped on box86, but I'll double check tomorrow and make some test on my Pi4.

**Comment by ptitSeb** [comment]
Oh, in the log I see this:
`Warning, no more slot for pulse audio module_info callback`
So yeah, that's an issue on box86 side. I'll add some slots and it should work!

**Comment by ptitSeb** [comment]
Check with this change, it should be better now.

**Comment by q4a** [comment]
Another error:
```
q@tinkerboard:~/soft/zoom$ BOX86_LOG=1 BOX86_DLSYM_ERROR=1 BOX86_TRACE_FILE=trace4.txt /home/q/git/box86/build/box86 ./zoom
Debug level is 1
BOX86 Trace redirected to "trace4.txt"
Box86 with Dynarec v0.1.9 9ff20da9 built on Dec 30 2020 22:00:25
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: 2C:4D:54:43:33:FF][client: Linux][OS: Armbian 20.11.3 Focal][Hardware: CPU Core:4 Frenquency:1.8 G Memory size:2001MB CPU Brand:              Intel(R) Pentium(R) 4 CPU 1800MHz GPU Brand:][Req ID: ]
Linux Client Version is 5.4.2 (53391.1108)
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = XFCE;   GDMSESSION = xfce
Graphics Card Info:: 
Zoom package arch is 32bit, runing OS arch is i386
AppIconMgr::systemDesktopName log Desktop Name: xfce 
link image0 hasn't been detected!
Could not resolve property : pattern0
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
CSBConfUI::OnConfStatusChanged  UI_CMD_SHARE_READYSegmentation fault
```
[trace4.txt](https://github.com/ptitSeb/box86/files/5755867/trace4.txt)
[zoom-dbg4.log](https://github.com/ptitSeb/box86/files/5755869/zoom-dbg4.log)

**Comment by ptitSeb** [comment]
Mmmm, I'll look at that tomorrow. No quick fix for this one.

**Comment by q4a** [comment]
Is there any news?

**Comment by ptitSeb** [comment]
I reproduce the issue on my side. But for now, I don't see why it segfault, or more precisely, I don't understand why the segfault is not trapped and what is happening.
I'm still working on it.

**Comment by q4a** [comment]
> I reproduce the issue on my side.
Glad to hear that. 
> I'm still working on it.
Thanks for your hard work. Merry christmas and Happy New Year!

**Comment by ptitSeb** [comment]
So, I think I found it! It was, in fact, the same issue as with #193  and the missing sound, but with a more deadly effect.
Update box86 and it should work (it worksed for me at least).

**Comment by q4a** [comment]
I got another error earlier: I just start meeting, press "Share screen" and got error:
```
q@tinkerboard:~/soft/zoom$ BOX86_LOG=1 BOX86_DLSYM_ERROR=1 BOX86_TRACE_FILE=trace5.txt /home/q/git/box86/build/box86 ./zoom
Debug level is 1
BOX86 Trace redirected to "trace5.txt"
Box86 with Dynarec v0.1.9 be7f7280 built on Dec 31 2020 16:50:53
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: 2C:4D:54:43:33:FF][client: Linux][OS: Armbian 20.11.3 Focal][Hardware: CPU Core:4 Frenquency:1.8 G Memory size:2001MB CPU Brand:              Intel(R) Pentium(R) 4 CPU 1800MHz GPU Brand:][Req ID: ]
Linux Client Version is 5.4.2 (53391.1108)
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = XFCE;   GDMSESSION = xfce
Graphics Card Info:: 
Zoom package arch is 32bit, runing OS arch is i386
AppIconMgr::systemDesktopName log Desktop Name: xfce 
link image0 hasn't been detected!
Could not resolve property : pattern0
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
CSBConfUI::OnConfStatusChanged  UI_CMD_SHARE_READYbox86: Linux/latebindingsymboltable.h:129: void* webrtc_adm_linux::LateBindingSymbolTable<SYMBOL_TABLE_SIZE, kDllName, kSymbolNames>::GetSymbol(int) const [with int SYMBOL_TABLE_SIZE = 67, const char* kDllName = ((const char*)(& webrtc_adm_linux_pulse::PulseAudioSymbolTable_kDllName)), const char* const* kSymbolNames = ((const char* const*)(& webrtc_adm_linux_pulse::PulseAudioSymbolTable_kSymbolNames))]: Assertion `IsLoaded()' failed.
Aborted
```
[trace5.txt](https://github.com/ptitSeb/box86/files/5757815/trace5.txt)

**Comment by ptitSeb** [comment]
Mmm, I don't have this error on my side. But I do have an assertion and quick exit when I try use the whiteboard. Relaunching it make it work. Random issue on my side, not easy to fix, if it's even on box86 side.

**Comment by q4a** [comment]
I tested e2df6f6c and it works now.
