### ISSUE TITLE
Unimplemented Opcode

### ISSUE THREAD

**Issue by hoat4** [ptitSeb/box86#304]
Tried running Borland C++ Builder (1997) using Wine on box86 on Raspberry Pi 4, but received this output when compiling a simple hello world application using that IDE:

Box86 with Dynarec v0.1.9 f143771b built on Jan  8 2021 20:50:15
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0050:fixme:appbar:handle_appbarmessage SHAppBarMessage(ABM_GETTASKBARPOS, hwnd=0070A104): stub
23785|0x67e0ed: Unimplemented Opcode 64 67 3B 06 00 00 74 30

Then box86 exited. 

With BOX86_DYNAREC=0 it's working correctly, but everything is very slow.

**Comment by Trass3r** [comment]
To be closed as fixed?
