### ISSUE TITLE
Fullthrottle remastered: black window (Pi 4)

### ISSUE THREAD

**Issue by warpdesign** [ptitSeb/box86#312]
I am trying to run FullThrottle remastered on a Raspberry Pi 4.

I built box86 with these params:

> -DRPI4=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo

When running the game (GOG version), I am getting a black window: only loading animation appears. Other screens stay black. The game appears to work, I can here the sound and moving the mouse triggers sound effects, but it stays black.

**Comment by ptitSeb** [comment]
FullThrottle use S3TC texture IIRC. So you need a mesa driver 20.2 or 20.3 on a PI to play it (or use gl4es if you are really stuck with 19.x). Use `glxinfo -B` to find out mesa version.

**Comment by warpdesign** [comment]
I am using mesa 19.3.2 according to glxinfo. How can I upgrade to newer mesa?

**Comment by Itai-Nelken** [comment]
@warpdesign upgrade like this:

**Install dependencies:**
```
sudo apt install git python3-pip libxcb-shm0-dev libdrm2 libdrm-dev libdrm-common bison x11-common libx11-dev libxext6 libxext-dev libxdamage-dev libxcb-glx0-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxshmfence-dev libxxf86vm-dev libxrandr-dev 
pip3 install meson
pip3 install mako
```
**Compile mesa:**
```
git clone https://gitlab.freedesktop.org/mesa/mesa.git
cd mesa
```
**change 20.2 to 20.3 if you want:**
```
git checkout 20.2
```
```
mkdir build
meson --prefix /usr -Dplatforms=x11 -Dvulkan-drivers= -Ddri-drivers= -Dgallium-drivers=v3d,kmsro,vc4,virgl -Dbuildtype=release build
ninja -C build
sudo ninja -C build install 
```

**Comment by warpdesign** [comment]
After upgrading to mesa 20.2 it works, although a bit too slow, thank you!

![image](https://user-images.githubusercontent.com/199648/104733219-a7d0cd00-573e-11eb-95a6-08fc7720e8ce.png)
