### ISSUE TITLE
foobar2000 with Wine

### ISSUE THREAD

**Issue by SpaceAgeHero** [ptitSeb/box86#314]
Hi,
foobar2000 installs fine (on TwisterOS), however just crashes when trying to start the application.
Is this anything you could look into and try to fix?
Would love to run this audio player on Raspberry Pi.

**Comment by ptitSeb** [comment]
I think it's fixed now. It worked for me (with a portable installation), but I haven't tested much.

**Comment by SpaceAgeHero** [comment]
Great. Can confirm that it launches now. Tried some audio playback and it seems fine so far.
Thanks alot!

**Comment by ptitSeb** [comment]
So ticket can be closed?

**Comment by SpaceAgeHero** [comment]
Yes, thank you
