### ISSUE TITLE
[RK3326/Mali] Renderdoc+libGLEW Hangs

### ISSUE THREAD

**Issue by JohnnyonFlame** [ptitSeb/box86#315]
Hello,

I'm trying to get box86 to run games on an RK3326 powered device using a Mali G31 GPU (ArkOS, libmali-rk-bifrost-g31-rxp0-wayland-gbm_1.7-2+deb10_armhf drivers from HardKernel), using Shovel Knight as a starting point.

Issue is, I'm getting no graphics output on Shovel Knight. I attempted to kill the Framebuffer code in GL4ES by returning from the specific calls and skipping the last glDrawArrays call when certain conditions are met (to skip a fullscreen blit), the result were garbled graphics, like if only the lower right pixel of the textures were present and nothing more, so you could see a little pixel running around in place of enemies, the player character, main menu elements, anything.

In an attempt to debug this issue, I've built Renderdoc with a quick and dirty patch to [enable headless replay](https://gist.github.com/JohnnyonFlame/0455fcd85f7c0072621ccffbfe440cb2) which looked promising enough

![image](https://user-images.githubusercontent.com/2079069/105077001-9eab6d00-5a6a-11eb-9d4d-25f464b43bcc.png)

Until it hung on glXGetProcAddressARB from libGLEW.so.1.10.

![image](https://user-images.githubusercontent.com/2079069/105075147-22178f00-5a68-11eb-9be8-22fdb0b7efb9.png)

Any ideas on how to debug the hang, or why such a thing would happen?

**Comment by ptitSeb** [comment]
I think this is more a gl4es issue than a box86.

Did you tried `LIBGL_FB=4` to use (experimental) gbm backend of gl4es?

**Comment by JohnnyonFlame** [comment]
> 
> 
> I think this is more a gl4es issue than a box86.
> 
> Did you tried `LIBGL_FB=4` to use (experimental) gbm backend of gl4es?

Thanks for the quick reply - yes, that's what I'm using to get graphics. In fact, the sdlgears running on the renderdoc output is running with GL4ES under box86 and being captured remotely by renderdoc (it's the simplest test app I could think of.)

**Comment by ptitSeb** [comment]
ShovelKnight runs fine on my side with box86+box86, but I don't have hardware configured for LIBGL_FB=4... ShovelKnight use OpenGL 2.1 with Shaders and X11 to setup the Windows IIRC...

**Comment by JohnnyonFlame** [comment]
It seems to call into the native libSDL2.0 library and setup the window/renderer there, but also calls the affected glxGetProcAddressARB function, and despite initializing it displays weird broken graphics.  I am guessing this is some sort of driver quirk because otherwise, I have copied the code related to framebuffer binding and blitting into sdlgears using an apitrace of Shovel Knight running with GL4ES as reference and it does render to the FBO correctly, and also blits the FBO to the screen correctly.

Without being able to figure out why glxGetProcAddressARB hangs when renderdoc is attached, the only alternative is slowly creating reproduction code by extract assets with a known working linux box running Shovel Knight+GL4ES and renderdoc, but I'd rather not have to do that for every single graphical issue.

**Comment by ptitSeb** [comment]
glxGetProcAddressARB is the function that gives GL pointer functions. It's a crutial one, but also a complicated one for soft like RenderDoc or APITrace...

**Comment by JohnnyonFlame** [comment]
By setting `BOX86_NOSIGSEGV=1` the gdb instance attaches properly, seems like renderdoc also adds some signal handlers, this allowed me to find the underlying issue (`eglGetPlatformDisplay` didn't exist, but renderdoc still exposed and tried to execute it despite it not being present on my system, should probably report that on renderdoc's github...).

By disabling GL/GLX hooks I managed to hook the underlying GLESv2 calls and get this:

![image](https://user-images.githubusercontent.com/2079069/105256598-cd0d7300-5b64-11eb-83d9-60bc5954c4c3.png)

Closing this issue.
