### ISSUE TITLE
Orangepi One (H3) and Thief 1/2 games errors

### ISSUE THREAD

**Issue by fl82** [ptitSeb/box86#319]
Hello,

I own a OrangePi One SBC board with the H3 SoC having the Mali-400 MP2 GPU with the latest linux-sunxi 5.10.x kernel having the opengl lima driver module functional with armbian distribution o.s. and LXDE lighter gui.
The cpu has these features:

-Processors-
SOC/Package Information
ARM Cortex-A7 MPCore r0p5 (AArch32)		: 1008,00 MHz
ARM Cortex-A7 MPCore r0p5 (AArch32)		: 1008,00 MHz
ARM Cortex-A7 MPCore r0p5 (AArch32)		: 1008,00 MHz
ARM Cortex-A7 MPCore r0p5 (AArch32)		: 1008,00 MHz
and it supports neon, vfp, vfpv3, vfpv4 and vfpd32 capabilities along others. 

Glxinfo reports this (leaving out the many extensions here):
_
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_libglvnd, GLX_EXT_no_config_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, GLX_SGIS_multisample, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, 
    GLX_SGI_make_current_read
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_INTEL_swap_event, 
    GLX_MESA_copy_sub_buffer, GLX_MESA_multithread_makecurrent, 
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_OML_swap_method, 
    GLX_OML_sync_control, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_no_error, 
    GLX_ARB_create_context_profile, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, GLX_EXT_swap_control, 
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_OML_swap_method, 
    GLX_OML_sync_control, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_video_sync
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: lima (0x13b5)
    Device: Mali400 (0xffffffff)
    Version: 20.3.2
    Accelerated: yes
    Video memory: 0MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: lima
OpenGL renderer string: Mali400
OpenGL version string: 2.1 Mesa 20.3.2
OpenGL shading language version string: 1.20_

Glxgears works perfectly at the monitor vsync freq and already tried YQuake2 to test OpenGL 1.4 renderer and it works. So I'm quite sure the OpenGl part's ok.
Now, I downloaded and compiled the yesterday zip file of the code and it built the box86 executable with the generic ARM SBC config line, then I downloaded and compiled the gl4es zip  file with the odroid suggested config line (not ES2?) and without errors I copied the resulted libGL.1.so file in the lib dir, in the x86lib dir, in the/usr/local/lib dir and everywhere I could. 
For the Wine part I found a prebuilt version of the x86 v5.13 release somewhere cause I read obviously I've to use the x86 one not the one that would come for armhf versions.

My goal would be to run a Directx6/7 game like Thief Gold and Thief 2 The Metal age on this armv7 32bit sbc board. I think it should be old an "simple" enough to run even if slow cause the Dark Engine should be based on the originale Quake one if I remember correclty and it's a 300-500Mhz x86 single cpu oriented DX6 game and I suppose this quad-core armv7 cpu might emulate the x86 cpu part at low resolution (480p or 768p). 
But when I launch the game it seems to start but begin with many d3d errors then screen becomes black like it's running but it come back to the GUI with a page fault error.
I didn't set any enviroment variables (I'm not expert on this linux part), do I have to? Also the gpu isn't recognized (lima driver) and set as Nvidia one.. could this be the reason? Or maybe I've to compile the gl4es with the ES2 config?

This is the result:
_user@orangepione:~/box86_2/box86-master$ sudo box86 /home/user/wine/bin/wine /home/user/.wine/drive_c/TGold/thief_gold/thief.exe
Box86 with Dynarec v0.2.1  built on Jan 22 2021 10:43:15
Box86 with Dynarec v0.2.1  built on Jan 22 2021 10:43:15
Box86 with Dynarec v0.2.1  built on Jan 22 2021 10:43:15
Box86 with Dynarec v0.2.1  built on Jan 22 2021 10:43:15
0024:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "lima". Returning HW_VENDOR_NVIDIA.
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "lima". Returning HW_VENDOR_NVIDIA.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0024:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
**wine: Unhandled page fault on read access to FFFFFFFF at address 10011FC9 (thread 0024),** starting debugger...
Box86 with Dynarec v0.2.1  built on Jan 22 2021 10:43:15
winedbg detected, not launching it!
0024:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 32 232" (1359)
Read the Wine Developers Guide on how to set up winedbg or another debugger
_

When I launch Thief 2 The Metal Age game sharing a similar game engine it also shows this error:

**wine: Unhandled illegal instruction at address 7BC7C69A (thread 0078)**

The newer patched Dark Engine patches permit to run the game with any o.s. using both a legacy DX6 renderer (I had great results together with an external ddraw.dll like DDrawCompat on modern Win o.s.) or the newer DX9 one that never gave problems on Wine in Linux x86/x64. Or I could even use the older executables if it's better but not supported by modern Win o.s. cause compiled for o.s. like Win 98.
I'm quite sure and tried myself time ago that these games does run perfectly on a x86 linux machines with for example an ATi video card open driver or Nvidia proprietary ones. They are very old games that would run on a Pentium MMX or Pentium 2 machine.
Any hints?

Thanks

**Comment by Heasterian** [comment]
Hi! Could you try to compile older version of lima? Sometimes new version of driver comes with regressions. Try something like 20.1/20.2 branch of main mesa repository.
