### ISSUE TITLE
Steam Quitting Hangs

### ISSUE THREAD

**Issue by ravenclaw900** [ptitSeb/box86#326]
Steam's "Remember Password” button crashes Steam on subsequent starts if `libnm0` is not installed.  Also, you can't quit Steam from the menu itself, it hangs with an illegal thread termination error.  Could you put this in your README?  For more information see https://github.com/MichaIng/DietPi/pull/3989#issuecomment-771829511.

**Comment by MichaIng** [comment]
Many thanks, but in fact I already committed the info about `libnm0` to the readme 😄: https://github.com/ptitSeb/box86/pull/325

Shall we concentrate on the logout hang with this issue? Since this is quite nasty as well and seems to be on a level where a workaround can be found.

**Comment by ravenclaw900** [comment]
Whoops, didn't see that.  Yes, let's focus on that.

**Comment by ptitSeb** [comment]
This is fixed now. Closing the ticket.
