### ISSUE TITLE
Libvirt / KVM / QEMU

### ISSUE THREAD

**Issue by c0dyhi11** [ptitSeb/box86#335]
Has anyone tried getting qemu/libvirt working with this? My use case is running a Windows 98 VM for some classic PC games.

**Comment by Itai-Nelken** [comment]
QEMU and KVM can run natively on the pi, take a look [here](https://github.com/Itai-Nelken/RPi-QEMU-VM-scripts).
its installable from apt, but its a very old version. you can use my [tool](https://github.com/Itai-Nelken/qemu2deb-RPi) to create a deb for the newest version or download premade ones from here:
armhf: https://archive.org/download/macos_921_qemu_rpi/qemu-5.2.50-armhf.deb
arm64: https://archive.org/download/macos_921_qemu_rpi/qemu_5.2.50-1_arm64.deb

**Comment by c0dyhi11** [comment]
@Itai-Nelken,

I’m aware you can install these natively on the Pi. But correct me if I’m wrong. But they can only virtualize the same CPU architecture, (ARM) but if they were packaged with box86. Wouldn’t we be able to get around this?

Or is there a way to get Qemu to emulate different CPUs? Like PowerPC, Spark, x86, or ARM?

I thought that was an issue, but maybe I’m wrong.

**Comment by Itai-Nelken** [comment]
@c0dyhi11 

you can use QEMU to emulate PPC, x86, x86_64 etc. on any architecture it runs on, that is the whole idea of QEMU.
again, take a look [here](https://github.com/Itai-Nelken/RPi-QEMU-VM-scripts)

**Comment by Itai-Nelken** [comment]
@c0dyhi11 
that is on a pi4 4gb stock clock speeds.
![image](https://raw.githubusercontent.com/Itai-Nelken/RPi-QEMU-VM-scripts/main/screenshots/2QEMUVMS.png)

**Comment by c0dyhi11** [comment]
@Itai-Nelken:
That’s awesome! I’ll need to play with this.
