### ISSUE TITLE
[Bug] Teamspeak 3 Server on Raspberry Pi 4: File Transfer supposedly crash the emulator

### ISSUE THREAD

**Issue by cyberdust2k** [ptitSeb/box86#361]
Hi,

I have set up a regular Teamspeak 3 Server v3.13.3 with default settings running on top of a self compiled build of box86 on a raspberry pi 4 4GB model, which performs basic functionality (e.g. voice) just fine, but as soon as I'm trying to use any data transfer feature (e.g. uploading avatar, uploading any file) in 95% of cases it immediately crashes, which I assume is because of box86 since the teamspeak server seems unable to create a meaningful crash log. The test log of box86 I created looks like this:

```
Debug level is 1
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Box86 with Dynarec v0.2.1 f817d06e built on Mar 11 2021 21:04:47
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 27 Env var
Looking for ./ts3server
Using emulated libts3_ssh.so
Using native(wrapped) librt.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libm.so.6
Using emulated /lib/i386-linux-gnu/libstdc++.so.6
Using emulated /lib/i386-linux-gnu/libgcc_s.so.1
Warning, CPUID command C0000000 unsupported (ECX=08db6568)
2021-03-12 23:14:07.877244|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.13.3 (2020-12-16 14:17:05)
2021-03-12 23:14:07.891272|INFO    |ServerLibPriv |   |SystemInformation: Linux 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 i686 Binary: 32bit
Using emulated libts3db_sqlite3.so
2021-03-12 23:14:07.926069|INFO    |DatabaseQuery |   |dbPlugin name:    SQLite3 plugin, Version 3, (c)TeamSpeak Systems GmbH
2021-03-12 23:14:07.927164|INFO    |DatabaseQuery |   |dbPlugin version: 3.11.1
2021-03-12 23:14:07.957700|INFO    |DatabaseQuery |   |checking database integrity (may take a while)
2021-03-12 23:14:08.430492|WARNING |Accounting    |   |Unable to open licensekey.dat, falling back to limited functionality
2021-03-12 23:14:08.448696|INFO    |Accounting    |   |Licensing Information
2021-03-12 23:14:08.449444|INFO    |Accounting    |   |licensed to       : Anonymous
```

It should be noted that a terminal output and the crated files sometimes include the cryptic message `The futex facility returned an unexpected error code.` and I'm at a loss to what could be causing this.

**How to recreate:**

1. install teamspeak 3 server as described in this guide: https://pimylifeup.com/raspberry-pi-teamspeak/ except replace Step 3 with using the default start script `./ts3server_startscript.sh start`, however, I don't think this should really matter.
2. Setup the server to the point that you can use it normally with any official Teamspeak 3 Client (I used v3.5.6)
3. right-click on your name and `set Avatar`
4. select any picture
5. observe the error `[...]:(lost file transfer connection)`

alternatively follow steps 1 and 2, then
3. right-click on voice channel, select `open file-browser`
4. click `upload file`
5. select any file
6. observe the same error as in previous step 5.

If more information is needed, i'd be happy to cooperate. If the error is related to faulty usage/installation/compilation of box86, I apologize for the inconvenience caused.

**Comment by ptitSeb** [comment]
There is nothing on the console about a crash, segfault or something? you see nothing?
if you see nothing, that probably means the stdout is redirected: use `BOX86_TRACE_FILE=trace.txt` to redirect all box86 log to `trace.txt`.

**Comment by cyberdust2k** [comment]
The tracefile seems to be even more vague as it doesn't indicate a crash at all:
```
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 27 Env var
Looking for ./ts3server
argv[1]=""
argv[2]="daemon=1"
argv[3]="pid_file=ts3server.pid"
Using emulated libts3_ssh.so
Using native(wrapped) librt.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libm.so.6
Using emulated /lib/i386-linux-gnu/libstdc++.so.6
Using emulated /lib/i386-linux-gnu/libgcc_s.so.1
```

It also still outputs `The futex facility returned an unexpected error code.` in the terminal window.

Another interesting discovery I made was that if I happen to increase the logging level to `2` it immediately crashes the server with varying messages regarding the local database, if I use the startscript shipped with the server:
```
2021-03-14 15:33:53.349874|CRITICAL|ServerLibPriv |   |Server() DatabaseError database disk image is malformed
[...]
2021-03-14 15:38:16.977391|CRITICAL|ServerLibPriv |   |Server() DatabaseError out of memory
```

using the binary directly with `./ts3server` this way however results in a endless loop after the sql database is checked. I will attach the full level 2 log here, however it's extremely big (~340MB uncompressed) and probably not of a lot of use: https://drive.google.com/file/d/1eLmHYyD_DHArqVDepiE4eCpELVwcwUZx/view?usp=sharing

That's really all I can provide I think.

**Comment by ptitSeb** [comment]
Mmm, the no message in the log is probably an endless recusirve function call that gets killed savagly because the stack gets full.
All the error message you mentionned are also interesting and need to be investigates.

I need to take some time to dig all this (and I'm a bit busy on other stuff for now).

A lest thing you can try is running the server without dynarec (using `BOX86_DYNAREC=0`) and see if this change the behaviour (it will slow things down a lot).

**Comment by cyberdust2k** [comment]
Checking in to say as of today, the current build `38a33ab` has resolved the file transfer issue, confirmed through some testing.
