### ISSUE TITLE
Running Free Steam Game, RPG MO gives a "Double SIGSEGV (code=1, pc=0x628768dc, addr=0xb63d2004)!" error.

### ISSUE THREAD

**Issue by bfready** [ptitSeb/box86#379]
This is a 32 bit Linux application.  I am attempting to run this on a Raspberry Pi 4 w/ 4 GB with Twister OS 2.0.1.

Here is the output made from BOX86_LOG=2:

Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Setting up canary (for Stack protector) at GS:0x14, value:003A4A52
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for ./nw
Read 2 Program header
Adding "./nw" as #0 in elf collection
Elf Addr(v/p)=0xc01000/0xc01000 Memsize=0xc4edc90 (align=0x1000)
Elf Stack Memsize=1048576 (align=4)
Elf TLS Memsize=0 (align=0)
Allocating 0x14e7000 memory @0xc01000 for Elf "./nw"
Allocating 0x1000 memory @0xd0ee000 for Elf "./nw"
Allocate a new X86 Emu, with EIP=(nil) and Stack=0xb64ff000/0x800000
Setup X86 Emu
Loading block #0 @0xc01000 (0x14e637f/0x14e637f)
Loading block #1 @0xd0eec90 (0x0/0x0)
Calc stack size, based on 1 elf(s)
Stack is @0xb5bff000 size=0x800000 align=0x4
Allocate a new X86 Emu, with EIP=(nil) and Stack=0xb5bff000/0x800000
Setup X86 Emu
1193|Free a X86 Emu (0x62ead218)
And now export symbols / relocation for ./nw...
Entry Point is 0x20e61d0
Start x86emu on Main
Run X86 (0x62eb3058), EIP=0x20e61d0, Stack=0xb63fe398
0x20e6dee: Calling syscall 0x5A (90) 0xb63fe37c 0x1000 0xc01000 0x20e6e14 0x14e51cc => 0x20e8000
0x20e805d: Calling syscall 0x55 (85) 0x20e8048 0xb63fd4d4 0x1000 0xb63fd4d0 0xb63fd440 => 0x14
1193|SIGSEGV @0x628768dc (???(box86/0x628768dc)) (x86pc=0x20e8225/???:"???", esp=0xb63fc904, stack=0xb5bff000:0xb63ff000 own=(nil) fp=0xb63fc940), for accessing 0xb63ff000 (code=1/prot=0), $
1193|Double SIGSEGV (code=1, pc=0x628768dc, addr=0xb63ff000)!
Calling atexit registered functions
Calling atexit registered functions
Calling fini for all loaded elfs and unload native libs
Waiting for all threads to finish before unloading box86context
1193|Free a X86 Emu (0x62eb3058)

**Comment by ptitSeb** [comment]
Steam should run fine on latest box86, so I'm closing this ticket. Feel free to re-open it if the initial issue is still present.
