### ISSUE TITLE
update docs with winetricks menu fix

### ISSUE THREAD

**Issue by paulwratt** [ptitSeb/box86#380]
[On the page about Wine & WineTricks](https://ptitseb.github.io/box86/X86WINE.html) you can add something about making a fix to the standard RPiOS WineTricks menu item to get it to run properly with Box86. The standard RPiOS Wine menu items will also work, _if_ they appear in the menu (on the latest Buster repo they dont appear, even though there are **.desktop** files present). This will be nice for those who installed Wine & WineTricks via RPiOS, before (finding &) following said tutorial, which does not install any menu items. And `/usr/local/bin/*` takes priority over the standard RPiOS installation locations, so you dont even need to uninstall them :) (I had already installed Box86 from github repo for an i386 linux binary command line tool). 

in:
`/usr/share/applications/winetricks.desktop`
change:
`Exec=winetricks --gui`
to:
`Exec=env BOX86_NOBANNER=1 winetricks --gui`

it needs to be edited with `sudo` so that it can be saved properly eg:
`sudo leafpad /usr/share/applications/winetricks.desktop`

On a side note, as a single user linux system, if you change the write access to everything in that folder, then you can save _**any**_ changes made with the **Main Menu Editor** in the **Preferences**:
`sudo chmod a+w /usr/share/applications`
`sudo chmod a+w /usr/share/applications/*`

**Comment by ptitSeb** [comment]
Can the ticket be closed now?
