### ISSUE TITLE
Starting GTA 3 through wine fails

### ISSUE THREAD

**Issue by Kakiking** [ptitSeb/box86#382]
I'm trying to run GTA 3 on my raspberry Pi 3B+ via Wine. The game is rated silver on winedb, with the version used being 4.0, so it might actually run good.
I'm using a 64Bit Kernel, and the Fake KMS GL Driver, and I have installed wine (with box86) through pi-apps. Installing the game went fine, but running it does not work. When I'm trying to run it (inside wine desktop) I get the following errors: 
[message.txt](https://github.com/ptitSeb/box86/files/6444394/message.txt)

**Comment by ptitSeb** [comment]
There is nothing that seems relevent in this message log. Try to use `BOX86_LOG=1` to get more detailled log. Also, what is your mesa version? You are using a RPi3, I don't know if it handle S3TC texture compression, wich is certainly required for GTA3. Try some  `glxinfo | grep s3tc -i` to see if you have some support.

**Comment by Kakiking** [comment]
`glxinfo | grep s3tc -i` outputs nothing, I'll look into where I can set `BOX86_LOG=1`.
I'm using mesa 20.3.4

**Comment by ptitSeb** [comment]
I don't think it will work without s3tc support.

**Comment by Kakiking** [comment]
Ok.. Then I'll look into some other games, thanks anyways.

**Comment by Kakiking** [comment]
Does the raspberry pi 4 have s3tc support?

**Comment by ptitSeb** [comment]
Yes it does, with Mesa 20+

**Comment by Kakiking** [comment]
Ok, then I'll try again when I have my pi 4 in a few weeks.
