### ISSUE TITLE
TS3 client SIGSEGV

### ISSUE THREAD

**Issue by Crypto90** [ptitSeb/box86#384]
Hi
I try to get a ts3 client running on an raspberry pi 3b using box86.
I downloaded missing i386 deb files and extracted them.
Then pointed BOX86_LD_LIBRARY_PATH to it.

Created a x86 folder and extracted the following missing i386 dependencies:
libegl1_1.1.0-1_i386.deb
libexpat1_2.2.6-2+deb10u1_i386.deb
libglvnd0_1.1.0-1_i386.deb
libnspr4_4.20-1_i386.deb
libnss3_3.42.1-1+deb10u3_i386.deb
libpci3_3.5.2-1_i386.deb

Running the client with:
```
BOX86_NOSIGSEV=1 BOX86_LOG=2 LD_LIBRARY_PATH=".:x86/lib/i386-linux-gnu:x86/usr/lib/i386-linux-gnu" xvfb-run -a ./ts3client_runscript.sh
```
As far as I got:
[box86.log](https://github.com/ptitSeb/box86/files/6470818/box86.log)
It crashes with:
```
20338|SIGSEGV @0x6a9d12d0 (???(0x6a9d12d0)) (x86pc=0x7312f794/libQt5WebEngineCore.so.5:"libQt5WebEngineCore.so.5/_ZnwjRKSt9nothrow_t", esp=0x75b8eff8, stack=0x75b8f000:0x7638f000 own=(nil) fp=(nil)), for accessing 0x75b8eff4 (code=1/prot=0), db=0x64509628(0x6a9d12c0:0x6a9d1314/0x7312f790:0x7312f7ad/libQt5WebEngineCore.so.5/_ZnwjRKSt9nothrow_t:clean, hash:379ae4eb/379ae4eb)
20338|Double SIGSEGV (code=1, pc=0x6a9d12d0, addr=0x75b8eff4)!
```

Any clue what causing this SIGSEGV?

**Comment by ptitSeb** [comment]
TS3 client wont work for now. Box86 doesn't handle ELF Symbol version  fully, and it's needed for the Qt5 libs used in it. I'll probably try to add support of this at some point in box86, but not sure when.
(note that Windows client seems to works a bit better. At least it start, but is crashy, so don't think there is a stable solution yet)

**Comment by ptitSeb** [comment]
linux ts3 client work now, but on box64 as it's a 64bits apps. So closing this ticket.

**Comment by Crypto90** [comment]
What about the x86 version of the ts3 client?
There are two versions, a x86 and a x64 client.

Would be great to get the x86 version running too.

x86 client:

https://files.teamspeak-services.com/releases/client/3.5.6/TeamSpeak3-Client-linux_x86-3.5.6.run
