### ISSUE TITLE
old HLDS_RUN not work   Global Symbol XXX not found, cannot apply R_386_PC32 &Symbol __pure_virtual not found, cannot apply R_386_32

### ISSUE THREAD

**Issue by 90999** [ptitSeb/box86#385]
https://files.ndlp.info/cstrike/linux/hlds/full/hlds_l3104.tar.gz

box86 hlds_run

[log.txt](https://github.com/ptitSeb/box86/files/6518888/log.txt)

**Comment by 90999** [comment]
qemu-i386 can work ,but box86 not

**Comment by ptitSeb** [comment]
Issue is with elfloader/librarian in box86.
I am currently working on that (on another issue), it's a bit tricky to get it right, so may tale a bit a time to fix.

**Comment by 90999** [comment]
qemu-i386 is not so good . some very old linux app(build by gcc2.8) can working in Ubuntu_i386 4-18 , but not working  in qemu-i386 on rasbian , copy different i386 linux 's lib for it , 
when cpy ubuntu4'lib&ld for it , error is  :
elocation error: libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-.so.2 
when cpy ubuntu12'lib&ld for it , error is  :
qemu: uncaught target signal 6 (Segmentation fault) - core dumped
when cpy ubuntu18'lib&ld for it , error is  :
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

can you give me some advise ? 
or i need to rebuild the 20+ years old linux with new gcc8 & linux_i386  ?

thank you

**Comment by ptitSeb** [comment]
I don't know. If ubuntu 4-18 libs create an error, it maybe that qemu on arm doesn't support that old code. those app also don't run with box86?

**Comment by 90999** [comment]
This app was build in 1999-2001 ,  it was wroking in ubuntu4-18 on i386 PC or VMWARE , 
but now I want to it working in  rpi 3-4,   it can save much power and money  
Though the arm a57 single core' s performance is 75% of PIII  cpu , and with qemu-i386 
but  enough , now i start to plan for rebuild hlds 1016 in rasbian ,
 if you have a time , you can try it ,  I hope it can help something for box86 project  

it cannot working in ARM linux with box86 or qemu-i386  , 
source code : https://files.ndlp.info/cstrike/windows/tools/HL%20Standard%20SDK%201.0.rar
hlds 1016 https://files.ndlp.info/cstrike/linux/hlds/full/hlds_l3104.tar.gz

some other app was build in 2002-2003 can working in qemu-i386 with ubuntu i386 -lib , but cannot working in box86 
source code : http://metamod.org/files/sdk/old/
hlds  11xx  https://files.ndlp.info/cstrike/linux/hlds/full/

**Comment by 90999** [comment]
now it can working too ................ 
i try all ubuntu libs , 
ubuntu 7-12 's libs file have not error ........ 
12+  qemu: uncaught target signal 6 (Segmentation fault) - core dumped 

thanks for your comments

**Comment by ptitSeb** [comment]
You got it to work? how? using ubuntu 7-12 libs with qemu?

**Comment by 90999** [comment]
yes , seems the app(1016) need the  old LIBC/DL/M &LD  from utbuntu 12 , it built in 2000 !!!  not 2012 ....
the newer app(1100+)  built in 2001+ ,  but i can working in all ubuntu version , 
 i think something different for the LIBS bewteen ubuntu 12 and 14 ... 
 i try to use qume-i386 to test it in ubuntu x64 21 , the result are the same .

**Comment by 90999** [comment]
> You got it to work? how? using ubuntu 7-12 libs with qemu?

yes , seems the app(1016) need the  old LIBC/DL/M &LD  from utbuntu 12 , it built in 2000 !!!  not 2012 ....
the newer app(1100+)  built in 2001+ ,  but i can working in all ubuntu version , 
 i think something different for the LIBS bewteen ubuntu 12 and 14 ... 
 i try to use qume-i386 to test it in ubuntu x64 21 , the result are the same .

**Comment by ptitSeb** [comment]
@90999 I think I have fixed it. You should be able to run hlds_run with box86 now (it should be faster than qemu).
