### ISSUE TITLE
Make a preferred coding style for box86

### ISSUE THREAD

**Issue by QueenPew** [ptitSeb/box86#386]
When looking at box86's source code, there are many coding styles inside many single files. This can hinder the readability of the file's code.

No worry though! If we had a preferred coding style for box86, maybe everything could be a bit more readable(citation needed).

As for pointers on how to write it,  [this fantastic coding style guidelines from Mesa](https://docs.mesa3d.org/codingstyle.html) could be helpful, or [this other fantastic coding style guidelines from GNOME](https://developer.gnome.org/programming-guidelines/stable/c-coding-style.html.en).

Bonus points: 
* Mentions of "check the surrounding code and try to imitate it.".

Thank you for your time!

**Comment by ptitSeb** [comment]
I still have issue with coding style consistency as you can see. I tend to evolve, for various reasons, and that indeed makes the code non consistant, even on part I was the only one contributing.
