### ISSUE TITLE
Chrome on Raspberry pi 4 (Not Chromium)

### ISSUE THREAD

**Issue by Tejas-Singh-py** [ptitSeb/box86#390]
### Hi PitSeb,
Actually I don't have any other computer except a raspberry pi(RPi 3B and RPi 4B 2GB{I am a 13 year old}), And I saved a few of my password on google chrome sync. But now google has removed Chrome Sync API from Chromium. Is there a way to run **Official Google Chrome** on the pi4 using wine+box86 or box86 alone. Somehow I got Google Chrome Installer( .exe ) working on the pi, with box86 and wine but chrome doesn't open. I don't know how how to compile a .deb file for Box86.  **So, Any help will be greatly appreciated** 
 
Tejas Singh YT
Youtube => @ Tejas Singh YT

**Comment by Itai-Nelken** [comment]
Why do you need a deb for box86?

**Comment by Tejas-Singh-py** [comment]
> Why do you need a deb for box86?


Hey Itai,
The container of the Chrome Installer for Debian Linux (x86) is `.deb`
[https://www.google.com/chrome/](url)

**Comment by Itai-Nelken** [comment]
You can unpack debs with `dpkg-deb -R the-deb-name.deb the-deb-name` ('the-deb-name.deb' is the deb of course and 'the-deb-name' is the name of the folder to create/use to unpack the deb to).
A deb is basically a tar archive, inside there is a `DEBIAN` folder (not always upper-case I think) containing the `control` file and a few scripts that `dpkg` runs before or after installing or uninstalling it.
inside the `control` file you will find a section called `Depends:` containing a list of the dependencies, if they are libs you might be able to use the armhf versions if they are wrapped in box86.
other than the DEBIAN folder there is a 'mirror' of the filesystem structure containing the executables/libs anything else the program needs.

so unpack the deb, install any libs you find listed in the control file (for x86 ones just find them and put them in the same folder as the executable), and try to run it with box86. I don't think it will work, and even if it did performance wouldn't be good. you should try making yourself a google api key so you can get sync back in chromium (https://www.chromium.org/developers/how-tos/api-keys).

**Comment by Tejas-Singh-py** [comment]
> You can unpack debs with `dpkg-deb -R the-deb-name.deb the-deb-name` ('the-deb-name.deb' is the deb of course and 'the-deb-name' is the name of the folder to create/use to unpack the deb to).
> A deb is basically a tar archive, inside there is a `DEBIAN` folder (not always upper-case I think) containing the `control` file and a few scripts that `dpkg` runs before or after installing or uninstalling it.
> inside the `control` file you will find a section called `Depends:` containing a list of the dependencies, if they are libs you might be able to use the armhf versions if they are wrapped in box86.
> other than the DEBIAN folder there is a 'mirror' of the filesystem structure containing the executables/libs anything else the program needs.
> 
> so unpack the deb, install any libs you find listed in the control file (for x86 ones just find them and put them in the same folder as the executable), and try to run it with box86. I don't think it will work, and even if it did performance wouldn't be good. you should try making yourself a google api key so you can get sync back in chromium (https://www.chromium.org/developers/how-tos/api-keys).

### Thanks Itai
please checkout my youtube channel and consider subscribing.
[https://www.youtube.com/channel/UCCsEfbaCHPjM0Dhx69TrJPw](url)
**Bye**
