### ISSUE TITLE
Failed to install desktop menu item Fatal error.

### ISSUE THREAD

**Issue by melon-pi** [ptitSeb/box86#394]
Hi, I am running RetroPie 4.6 on RP4B. Box86 itself installed just fine and I am able to run games like Freedom Planet that don't require an installation. 

The error only occurs on GoG installer games, like steamworld Dig or Shovel Knight. I have already tried box86 just a few days ago when I installed it on top of some version of Raspbian that came with the raspberry pie and it worked flawlessly. 

Please tell me what other information I can provide, this is the only error message I get, after which it tells me that it reverted the changes.

I did the chmod +x ./gog_steamworld_dig_2.0.0.6.sh beforehand, I tried launching the installer with sudo.

**Comment by ptitSeb** [comment]
What error message do you get???
If the install start but then at some point error out and revert, it may be because the binary is corrupted.

(also, is your box86 up to date?)

**Comment by melon-pi** [comment]
Should've formatted it better, it uses a terminal based GUI for the installer, unlike when I installed games on the rasbian that I mentioned, but it goes through the motions, accept the license, select the installation directory, toggle desktop menu icons, then installation starts with the progress bar as usual.

At the end the only message I get is "Fatal Error Failed to install desktop menu item." then "Installation incomplete, reverting changes" (or something along the lines on the second one) 

I doubt that the binaries are corrupted since it happens on 3 different games that use gog installers, all of which have worked less than a week ago on the same raspberry pi when using raspbian os. 

As for box86, I compiled and installed it yesterday using this [tutorial](https://pimylifeup.com/raspberry-pi-x86/), so it should've grabbed the latest version.

**Comment by ptitSeb** [comment]
In retropie, I don't think you have GTK libs, so the installation use console based yes. Also, unselect the "install shortcut" in the installation, as it seems you don't have infrastructure for that neither (almost no X11 in retropie IIRC).

**Comment by melon-pi** [comment]
Yes, I forgot to mention that result is the same no matter what options I check/uncheck including "install shortcut." Would it be possible to install the necessary libraries on RetroPie, or do you think it would be easier to just install regular Raspbian and install the EmulationStation front end myself? 
Either way, thanks for taking the time to help me!

**Comment by ptitSeb** [comment]
I don't know. I have never used RetroPie myself...

Many linux GoG games  can be manualy extracted using a simple "unzip" command, but it can be tricky sometimes and not always work. I have no idea why the installer would fail at the install "installing desktop menu" items if the "install desktop shortcut" is not selected. It shouldn't try to install things.
Sorry, but that all I can say about this.
Going further would require extensive logging (with `BOX86_LOG=2`), to generate a huge log file of the entire process, then try to see at the end what kind of file access fail, to maybe create the require file / folder... Or analyse the sources of mojosetup to see what it does and how that error message could be trigger (but I will not do that myself, just giving ideas to dig deeper).
