### ISSUE TITLE
Pls Add Wrapped libandroid-shmem.so

### ISSUE THREAD

**Issue by AllPlatform** [ptitSeb/box86#395]
HI
I recompile Wine with X11 For Android By NDK And Run under Box86, it works properly but most libraries Can't Wrapper to run wine like This
`Using emulated ../lib/wine/winex11.drv.so`
`Using emulated ../lib/libXext.so`
`Using emulated ../lib/libX11.so`
`Using emulated ../lib/libandroid-support.so`
`Using emulated ../lib/libxcb.so`
`Using emulated  ../lib/libXau.so`
`Using emulated ../lib/libandroid-shmem.so`

 hope you will add the Wrapped library 
`libandroid-shmem.so`
Project Here `https://github.com/termux/libandroid-shmem`
Thank You
Result
imgur.com/a/eptperj

**Comment by ptitSeb** [comment]
Why did you close the ticket?

**Comment by AllPlatform** [comment]
> Why did you close the ticket?

because I'm bad at programming or have no knowledge C
so I hope you will add the Wrapped library
`libandroid-shmem.so`

**Comment by ptitSeb** [comment]
I can, but if the ticket is closed, it means there is nothing to do on it. The ticket must be open if you expect something to happens.

**Comment by AllPlatform** [comment]
> I can, but if the ticket is closed, it means there is nothing to do on it. The ticket must be open if you expect something to happens.

thank you very much

**Comment by ptitSeb** [comment]
So, is ok now?
If it's ok, you need to close the ticket (and write a message to say it works is also nice)

**Comment by AllPlatform** [comment]
In CMakeLists.txt Line 386 `wrappedandroidshem.c`
in /box86/src/wrapped  `wrappedandroidshmem.c`
i passed
but 
`make[2]: *** No rule to make target '../src/wrapped/wrappedandroidshem_private.h', needed by '../src/wrapped/generated/functions_list.txt'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:340: CMakeFiles/WRAPPERS.dir/all] Error 2
make: *** [Makefile:95: all] Error 2`

maybe you forgot something

**Comment by ptitSeb** [comment]
Ah, yes, of course a typo :'(

I should have fixed it now.

**Comment by AllPlatform** [comment]
sorry for keeping you waiting for so long I tested it so carefully

**Comment by AllPlatform** [comment]
it worked thank you very much 
check the result here
https://youtu.be/Ww1F_-2ueJs
LOG here
[](url)
[box86wine.log](https://github.com/ptitSeb/box86/files/6681423/box86wine.log)
