### ISSUE TITLE
Please add Syscall / symbol to get runnig "plcloud software"

### ISSUE THREAD

**Issue by Exclution** [ptitSeb/box86#398]
Hi, as mnentioned in following diskussion: https://github.com/ptitSeb/box86/discussions/397
i would like to ask for adding following:

--> Error: Unsupported libc Syscall 0x148 (328)

for this i've added output of BOX_LOG=1 
[pcloud issue gtk.txt](https://github.com/ptitSeb/box86/files/6682170/pcloud.issue.gtk.txt)
and output of BOX_LOG=2
[log.txt](https://github.com/ptitSeb/box86/files/6682171/log.txt)

thanks in advance!

**Comment by Exclution** [comment]
Thanks @ptitSeb very much! I'll compiled the new version and run again `BOX86_LOG=1 ./AppRun` and got following error:

![grafik](https://user-images.githubusercontent.com/86156461/122736487-61007980-d280-11eb-98e6-a1c395ecc848.png)

See also this Text-File: 
[pcloud issue.txt](https://github.com/ptitSeb/box86/files/6685434/pcloud.issue.txt)

Should i open a new issue?

Kind regards!

**Comment by ptitSeb** [comment]
It's ok, I added the function.

**Comment by Exclution** [comment]
Hi @ptitSeb - next error:
![grafik](https://user-images.githubusercontent.com/86156461/122743103-f7d03480-d286-11eb-8177-9b3ce18862bf.png)
See also File: 
[pcloud.issue2.txt](https://github.com/ptitSeb/box86/files/6685739/pcloud.issue2.txt)

sorry for the inconvenience

**Comment by ptitSeb** [comment]
That's something else. This one will need some work, to get a correct workaround.

**Comment by Exclution** [comment]
@ptitSeb okay... can i help in any way or should i open a new issue for this one?
Thanks again!

**Comment by ptitSeb** [comment]
Better to open a new issue, as it's something completly different, and close this one as the initial subject for the ticket is solved now.
