### ISSUE TITLE
Error while trying to start pcloud software

### ISSUE THREAD

**Issue by Exclution** [ptitSeb/box86#399]
Hi @ptitSeb - can you please help:

![grafik](https://user-images.githubusercontent.com/86156461/122743103-f7d03480-d286-11eb-8177-9b3ce18862bf.png)

See also `BOX86_LOG=1` 
[pcloud.issue2.txt](https://github.com/ptitSeb/box86/files/6685739/pcloud.issue2.txt)

and `BOX86_LOG=2` snippet:
19728|0x40a1b07: Calling strlen(0x1b320("../../third_party/tcmalloc/chromium/src/tcmalloc.cc")) => return 0x00000033
19728|0x40a1b27: Calling memcpy (B62EA7D8, 0001B320, 00000033...) => return 0xB62EA7D8
 ...  =>PltResolver: Addr=0x64c62b80, Slot=1304 Return=0x40a1b7e: elf is /home/pi/Downloads/squashfs-root/pcloud (VerSym=0x532288)
            Apply Global R_386_JMP_SLOT 0x4f35404 with sym=__udivdi3(ver 7: __udivdi3@GLIBC_2.0) (0x4eba636 -> 0xb2415f10 / /lib/i386-linux-gnu/libgcc_s.so.1)
 return 0xB62EA8B7
19728|0x40a1bda: Calling memcpy (B62EA80C, B62EA8B5, 00000003...) => return 0xB62EA80C
19728|0x40a1dde: Calling strlen(0x299a6("Attempt to free invalid pointer")) => return 0x0000001F
19728|0x40a1e02: Calling memcpy (B62EA811, 000299A6, 0000001F...) => return 0xB62EA811
19728|0x40a2003: Calling memcpy (B62EA833, B62EA780, 00000008...) => return 0xB62EA833
 ...  =>PltResolver: Addr=0x64c62b80, Slot=7616 Return=0x40a1ab6: elf is /home/pi/Downloads/squashfs-root/pcloud (VerSym=0x532288)
            Apply Global R_386_JMP_SLOT 0x4f36058 with sym=write(ver 3: write@GLIBC_2.0) (0x4ebd786 -> 0x64f4a720 / (noelf))
 return 0xB62EA7D8
19728|0x40a1ab6: Calling __write (00000002, B62EA7D8, 00000065...) => return 0x00000065
19728|SIGSEGV @0xacffe664 (???(0xacffe664)) (x86pc=0x40a40e6//home/pi/Downloads/squashfs-root/pcloud:"???", esp=0xb62ea7b8, stack=0xb5aec000:0xb62ec000 own=(nil) fp=0xb62ea7a8), for accessing 0x39 (code=1/prot=0), db=0x653e7d90(0xacffe638:0xacffe694/0x40a40e0:0x40a40f1/???:clean, hash:686c3e1a/686c3e1a)
 return 0x00000001
19741|0x40213bc: Calling __clock_gettime(1, 0xb622e850) => return 0x00000000 [71837 sec 943383485 nsec]
19741|0x401bfa6: Calling recvmsg (00000003, B622C6C0, 00000000...) => return 0x00000000
 ...  =>PltResolver: Addr=0x64d21bc0, Slot=7608 Return=0x2277aa3: elf is /home/pi/Downloads/squashfs-root/pcloud (VerSym=0x532288)
            Apply Global R_386_JMP_SLOT 0x4f36054 with sym=_exit(ver 2: _exit@GLIBC_2.0) (0x4ebd776 -> 0x65009740 / (noelf))
 return 0x00000000
19741|0x2277aa3: Calling _exit (00000000, B622C8C8, 00002000...) =>

Thanks in Advance

**Comment by chills340** [comment]
tmalloc you could try `sudo apt install libtcmalloc-minimal4` not sure if it'll help but it might

**Comment by Exclution** [comment]
Nope, this did not help, but thanks, @chills340

**Comment by chills340** [comment]
in issue #400 looks like seb did a fix for libs with embedded libtccmalloc. so update BOX86 and give it another try.

**Comment by Exclution** [comment]
Thanks, @chills340 but unfortunately still the same...
![grafik](https://user-images.githubusercontent.com/86156461/123324657-5ae7f280-d537-11eb-8969-73ff09ddb6c4.png)

**Comment by Exclution** [comment]
Dear ptitSeb, im currently not using this setup anymore... but i will considerate to take a new try in the next month. 
you can close this ticket i think
thank you!
