### ISSUE TITLE
7 Billion Humans: fails to boot, missing sdl symbol strlcpy

### ISSUE THREAD

**Issue by ITotalJustice** [ptitSeb/box86#40]
Hey again. Trying to run the game "7 billion humans" results in these errors.
```
Error: Symbol SDL_utf8strlcpy not found, cannot apply R_386_JMP_SLOT @0x81720e0 (0x806e076)
PltResolver: Ofs=0x810da6d, Id=424 (IP=(nil))
```

**Comment by ptitSeb** [comment]
Ok, just pushed that one. Hopefully it will just work now (afterall, HumanRessourceMachine does work).

**Comment by ITotalJustice** [comment]
Yup fixed, plays nicely as well. Both fantastic games. Closing!
