### ISSUE TITLE
Unimplemented Opcode (FD) 0F 00 4D FC 38 45 FC 75

### ISSUE THREAD

**Issue by lab-mathias-claussen** [ptitSeb/box86#406]
During the installation of Pulsonix viewer (www.pulsonix.com) using wine the install wizzard stops with Unimplemented Opcode (FD) 0F 00 4D FC 38 45 FC 75 

Best Regards

Mathias

**Comment by djtuBIG-MaliceX** [comment]
Confirmed also getting this exact unimplemented opcode. Looks to be related to InstallShield using some instructions.
Boots but installer terminates once proceeding.

Example: Roland Sound Canvas VA v1.0.6 trial installer: https://static.roland.com/assets/media/zip/scva_win_trial.zip

**Comment by djtuBIG-MaliceX** [comment]
Can confirm 631856a has allowed InstallShield to proceed further and appears to work for SCVA. @lab-mathias-claussen recommebd updating Box86 and try again.

**Comment by lab-mathias-claussen** [comment]
I'll close this issue and reevaluate the software. If the Bug still exist a new issue against the current version will be opened.

Regards

ClaM
