### ISSUE TITLE
Steam: Missing symbols in "libgdk-x11-2.0.so.0" and segmentation faults

### ISSUE THREAD

**Issue by artdeell** [ptitSeb/box86#407]
My configuration:
 - Raspberry Pi 4 (8gb model, overclocked to 2.147 GHz)
 - Ubuntu arm64
 - dpkg architectures: armhf, arm64, i386, amd64
 - Latest version of Steam
 The issue:
   Steam crashes right after the main window appears. Log:
[steam_log.txt](https://github.com/ptitSeb/box86/files/6765450/steam_log.txt)

**Comment by artdeell** [comment]
Note: fixed by removing libcairo2:armhf package. Not a permanent solution, i think there are issues with libcairo binding or version mismatch

**Comment by ptitSeb** [comment]
Closing the ticket, steam runs fine now with latest box86. Feel free to re-open the ticket if needed.
