### ISSUE TITLE
Error loading libraries on ARM64 with schroot method

### ISSUE THREAD

**Issue by Smashman4** [ptitSeb/box86#410]
So I'm trying to run some GOG games on the Nvidia Jetson Nano, and I followed the steps to get box box86 working on it on the Armbian forum (https://forum.armbian.com/topic/16584-install-box86-on-arm64/) using the schroot method, but when I launch box86 and my game through the command line, it says there's no libraries there. I checked to make sure everything was in the right place, and it is. any reason to why it's happening?
![Screenshot from 2021-07-10 14-14-32](https://user-images.githubusercontent.com/29053081/125172861-0de85b00-e18a-11eb-9199-41096ec6215e.png)

**Comment by netthier** [comment]
Do you actually have libSDL2-2.0.so.0?
Try running `apt install libsdl2-2.0-0`

**Comment by ptitSeb** [comment]
You need `armhf` of the missing libs.

I'm closing the ticket, re-open it if you still have issues.
