### ISSUE TITLE
Pi3b box86 glibc_2.29 missing

### ISSUE THREAD

**Issue by Manolosun** [ptitSeb/box86#412]
/usr/local/bin/box86: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/box86)

this is my failure after update to latest box86 version before 2 days.

Is this problem from Box or from the Rapi?

Some solutions? would help me much.

**Comment by ptitSeb** [comment]
You are installing box86 from somewere else. I don't provided pre-compiled version box86.
You can compile box86 from source, and it will work perfectly on your system. It's not hard, look ar docs/COMPILE.md

**Comment by ptitSeb** [comment]
if box86 comes from pi-apps, please open a ticket in pi-apps github repo.

were does your version comes from?

**Comment by Itai-Nelken** [comment]
That looks like a version from pi-apps. I recently upgraded the pi that builds them to ubuntu server 64bit, and it uses a newer version of glibc...

**Comment by ptitSeb** [comment]
That's unfortunate, it seems to be spreading quite fast. PiOS (32 or 64bits) is still on glibc 2.28...

**Comment by Itai-Nelken** [comment]
I removed the newer builds to stop the problem, but I'm not sure how apt will handle this..
