### ISSUE TITLE
CC Failure Rapi3b

### ISSUE THREAD

**Issue by Manolosun** [ptitSeb/box86#413]
cc: fatal error: Getötet signal terminated program cc1
compilation terminated.
make[2]: *** [CMakeFiles/arm_pass3.dir/build.make:154: CMakeFiles/arm_pass3.dir/src/dynarec/dynarec_arm_0f.c.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
[ 32%] Built target arm_pass2
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/arm_pass3.dir/all] Fehler 2
make: *** [Makefile:163: all] Fehler 2

is that what u mean :) here some solutions?
last was make -j4

**Comment by ptitSeb** [comment]
ah, `-j4` is probably too much for a 1st build now.
try
`make && sudo make install`
it should work.

**Comment by Manolosun** [comment]
looks better 42+ %

**Comment by ptitSeb** [comment]
Yeah, it can be long the first build. It get faster on update (if you update frequently)

**Comment by ptitSeb** [comment]
Also, I have changed the COMPILE.md to remove the "-j4" on PI instructions.

**Comment by Manolosun** [comment]
did u changed the manual for compiling for rapi 3b? i just wondered ^^
thanks for support im pretty happy with it.
ts3 is pretty on rapi3b since i found box86

**Comment by ptitSeb** [comment]
Ah yes, TeamSpeak3 Server :)
