### ISSUE TITLE
Steam installation via pi-apps wont work

### ISSUE THREAD

**Issue by imstupidwithlinux** [ptitSeb/box86#421]
i tried to install steam with pi-apps, entered my account stuff, the steam guard code, my windows machine says that the pi is now available to connect to but a second later it isnt anymore and it stops or crashes idk. the weird thing is that it works flawless on other machines aka pis but not on mine it just wont start. 
[cmd_steam_log.txt](https://github.com/ptitSeb/box86/files/6864647/cmd_steam_log.txt)

i just tried it again with a clean install but still doesnt work, here a longer version
[Another try.txt](https://github.com/ptitSeb/box86/files/6864724/Another.try.txt)

**Comment by ptitSeb** [comment]
Closing the ticket. If you still have issues, check on pi-apps repo.
