### ISSUE TITLE
Portal 1 Double SIGSEGV

### ISSUE THREAD

**Issue by Firlaev-Hans** [ptitSeb/box86#426]
This is what I get when I run Portal 1 with box86 outside of Steam. The game is DRM Free and usually launches fine without Steam. The same goes for Half Life 2, which is based on the same engine, but launches just fine in box86 for me.
Full log: [log.txt](https://github.com/ptitSeb/box86/files/6894530/log.txt)
```
17693|SIGSEGV @0x628eb950 (???(/usr/local/bin/box86/0x628eb950)) (x86pc=(nil)/???:"???", esp=0xd5ad39f8, stack=0xd59d4000:0xd5ad4000 own=0xd59d4000 fp=0xdc1fc0fe), for accessing (nil) (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0)
17693|Double SIGSEGV (code=1, pc=0x628eb950, addr=(nil))!
```
```
box86: ../src/compiler/glsl_types.cpp:1134: static const glsl_type* glsl_type::get_array_instance(const glsl_type*, unsigned int, unsigned int): Assertion `glsl_type_users > 0' failed.
Aborted (core dumped)
```
Output of `addr2line -e /usr/local/bin/box86 -a 0x628eb950`:
`~/git/box86/src/emu/x86run.c:192 (discriminator 3)`

**Comment by ptitSeb** [comment]
It's a NULL function call. I assume maybe some missing wrapped OpenGL function? Use `BOX86_DLSYM_ERROR=1` to see if any functions are missing.
On what hardware are you running it?

**Comment by Firlaev-Hans** [comment]
This was on a Jetson Nano with virglrenderer as a 32 Bit graphics workaround. Both Half Life 2 and Portal 2 work this way.
But your comment made me try it again on the RockPro64 with Panfrost (where I previously didn't have any luck with Portal either) but there it worked fine. So it is indeed something with virgl and not box86 I guess.
