### ISSUE TITLE
New version of box86 is significantly slower at loading data from disk

### ISSUE THREAD

**Issue by Uncomfy** [ptitSeb/box86#428]
Hello! I've decided to update my box86 today, but after doing that, the game that I'm running (The Binding of Isaac: Afterbirth) became way slower during startup and way more laggy when going from room to room.

Old version:
```
load archives: 6910 milliseconds
preload anm2: 193 milliseconds
```

New version:
```
load archives: 41906 milliseconds
preload anm2: 2009 milliseconds
```

Old version is from Jun 1:
```
root@localhost:~/box86# git show
commit d719809440d5d4cedbe82a42a62d5d641c928de7 (HEAD -> master, origin/master, origin/HEAD)
Author: ptitSeb <sebastien.chev@gmail.com>
Date:   Tue Jun 1 11:06:45 2021 +0200

    Added some more wrapped libGL functions (help apitrace)
```

I'm running Ubuntu 18.04 in proot (Termux).

**Comment by ptitSeb** [comment]
That's a strange and huge slowdown here.
Are you sure the new version still have dynarec enabled?

Can you try to `git bisect` to find the offending commit?

(this is a Window game  right? there is no linux version of this one?)

**Comment by Uncomfy** [comment]
> Are you sure the new version still have dynarec enabled?
Yes, that was the issue, I forgot to enable dynarec during recompilation :(
Sorry for the bother and thank you!
