### ISSUE TITLE
Some problems about system call clone.

### ISSUE THREAD

**Issue by Mr-HappyLI** [ptitSeb/box86#437]
case 120:   // clone
            {
                if(!R_ECX) {
                    // allocate a new stack...
                    stack_size = 1024*1024;
                    //stack_base = malloc(stack_size); // why not 1M... (normal operation do copy on write, simpler to just copy)
                    stack_base = mmap(NULL, stack_size, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_GROWSDOWN, -1, 0);
                    // copy value from old stack to new stack
                    int size_to_copy = (uintptr_t)emu->init_stack + emu->size_stack - (R_ESP);
                    memcpy(stack_base-size_to_copy, (void*)R_ESP, size_to_copy);
                }

Hi,ptitSeb
    A segment error occurred when "memcpy" was run.

**Comment by ptitSeb** [comment]
yeah, the "clone" syscall is barely supported. I need to find a better way to emulate this one.

**Comment by ptitSeb** [comment]
Note that I have seen this syscall used in 2 cases:
1. When a segfault occured in mono/unity3d and it's used to call "gdb"
2. On program with a staticaly linked libc / libpthread: this is not supported by box86, except issues (like the clone syscall one, thta is used to create new thread by libpthread).

**Comment by Mr-HappyLI** [comment]
What I don't understand is why data should be copied to memcpy ‘stack_base-size_to_copy’.At the same time, this memory did not find a place to malloc for it.Can you help me solve this doubt？Thanks!

**Comment by ptitSeb** [comment]
It is probably wrong. I need to redo this part, it's an old one, rarely used...

**Comment by ptitSeb** [comment]
Can this ticket be closed now?
