### ISSUE TITLE
Unimplemented Opcode trying to run Soul Reaver 2

### ISSUE THREAD

**Issue by ectorhga** [ptitSeb/box86#440]
I'm using wine in combination with box86 and try to start [Legacy of Kain: Soul Reaver 2](https://www.gog.com/game/legacy_of_kain_soul_reaver_2).
I get the error message 
```12681|0x45bb54: Unimplemented Opcode (FC) 0F 0E 9B 89 75 FC EB 1C```

![20210815_230122](https://user-images.githubusercontent.com/56919853/129857381-80faaad9-aa16-40b3-9168-ca08dbe24611.jpg)

Can this be implemented into box86?
I don't know if you need further information, so please don't hesitate to ask!

**Comment by ptitSeb** [comment]
In r`src/emu/run0g.h` line 74 (after `NEXT;`), add this block:
```
        _0f_0x0E:                      /* FEMMS */
            emu->old_ip = R_EIP;
            R_EIP = ip-2;
            emit_signal(emu, SIGILL, (void*)R_EIP, 0);
            ip = R_EIP;
            if(emu->quit) goto fini;
            STEP;
            NEXT;
```

In `src/emu/x86run.c` line 107 (the one with `//0x08-0x0F` in the end, change from
```
    &&_0f_0x00, &&_0f_0x01, &&_default, &&_default, &&_default ,&&_default, &&_default, &&_default, //0x00-0x07
```
to
```
    &&_0f_0x00, &&_0f_0x01, &&_default, &&_default, &&_default ,&&_default, &&_0f_0x0E, &&_default, //0x00-0x07
````

Build & install box86 and try again, to see if this does the trick.

**Comment by ectorhga** [comment]
There is no `run0g.h`. Did you maybe mean `run0f.h`?

**Comment by ptitSeb** [comment]
Yeah, `run0f.h` sorry :(

**Comment by ptitSeb** [comment]
Awesome!
I'll add the change to box86 then :)

**Comment by ptitSeb** [comment]
If you can create an entry in the box compatibility list, that would be great :)

**Comment by ectorhga** [comment]
Sure, I can do that!
