### ISSUE TITLE
Minidoom black screen

### ISSUE THREAD

**Issue by solidstudio** [ptitSeb/box86#442]
Getting a black screen but can hear the audio

[download](https://calaverastudio.itch.io/minidoom2)

**Comment by ptitSeb** [comment]
This seems to be a GameMaker2 game. I guess the black screen is due to some Mesa issue Game use Dx10, and the conversion to OpenGL on Pi4 and on Panfrost, is not always garanteed for now. Nothing box86 can solve I'm afraid.

**Comment by ptitSeb** [comment]
I tested on my side, and miniDoom works fine with box86.

As mentionned, this is a Dx11 windows app. With Wine, it works well with DxVK (on a Radeon Rx550), but it might be difficult to get it running on a regular SBC like a Pi4 or an RK3399 based one.

Closing the ticket, as it's not a box86 issue.
