### ISSUE TITLE
Error while building: undefined reference to `cancelFillBlock'

### ISSUE THREAD

**Issue by raspiduino** [ptitSeb/box86#443]
My device is SM-A600G (Samsung Galaxy A6) and I build this with termux and Debian chroot (also tested with Ubuntu's).
I just get this warning when running `make`:
```bash
box86/src/libtools/signals.c:683:9: warning: implicit declaration of function ‘cancelFillBlock’ [-Wimplicit-function-declaration]
         cancelFillBlock();  // Segfault inside a Fillblock, just cancel it's creation, don't relock mutex
         ^~~~~~~~~~~~~~~
```

Then in the end it output:
```bash
/usr/bin/ld: CMakeFiles/box86.dir/src/libtools/signals.c.o: in function `my_box86signalhandler':
box86/src/libtools/signals.c:683: undefined reference to `cancelFillBlock`
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/box86.dir/build.make:3088: box86] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/box86.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

I can find the function `cancelFillBlock` [here](https://github.com/ptitSeb/box86/blob/ea9e9da829b1661f0acf1efc9ab8d025b6fdcf70/src/dynarec/dynablock.c#L298) in `dynablock.c` and also in `dynablock.h`.

I tried comment [line 682 and line 683](https://github.com/ptitSeb/box86/blob/ea9e9da829b1661f0acf1efc9ab8d025b6fdcf70/src/libtools/signals.c#L682) in `signals.c` and it worked, but I think this is a quick and dirty way to do that.

And ideas? Thanks in advance!

**Comment by ptitSeb** [comment]
It should be fixed, but note that you are using a build without Dynarec (I don't know if it's on purpose).

**Comment by raspiduino** [comment]
> It should be fixed, but note that you are using a build without Dynarec (I don't know if it's on purpose).

I just run `cmake` and then `make`, so maybe by default it doesn't build Dynarec. Is that correct? And how to build it with Dynarec please? Thanks!

**Comment by ptitSeb** [comment]
Well, it's detailled in docs/COMPILING.md

You can use ` ccmake` to chenge options interactively.

**Comment by raspiduino** [comment]
> Well, it's detailled in docs/COMPILING.md
> 
> You can use ` ccmake` to chenge options interactively.

Thanks! I will recompile the project now :)

**Comment by raspiduino** [comment]
Ok it works perfectly and much faster :)) Thanks for the wonderful project! I will close the issue now
