### ISSUE TITLE
box86 cant  detect when an x86 application is being run

### ISSUE THREAD

**Issue by alimiracle** [ptitSeb/box86#446]
hi
I build the box86 in my rbpi4
its ok for me
but 
it cant  detect when an x86 application is being run
for example
if I type
~ wine
its gave me this error
/lib/ld-linux.so.2: No such file or directory
but if I run the app like this
box64 /bin/wine
its run ok

**Comment by WheezyE** [comment]
Which application are you trying to run? Or are you just trying to run wine?

**Comment by alimiracle** [comment]
yes its wine
