### ISSUE TITLE
Add TEGRA X1 support like in box64 [feature request]

### ISSUE THREAD

**Issue by epicmario7133** [ptitSeb/box86#456]

**Comment by ptitSeb** [comment]
you mean add Tegra X1 build parameter or find a way to have a "plug'n play" way to build box86 on a hacked switch?

**Comment by epicmario7133** [comment]
A build parameter for jetson nano that have TEGRA X1

**Comment by Heasterian** [comment]
You can use one for RPI4, but as Jetson Nano don't have armhf libraries for GPU acceleration, it won't work out of the box. Adding option for this would be wrong as device can't work with it without correct setup. If you want to use it anyway, use this guide: https://wiki.switchroot.org/en/Linux/Emulation/Box86

If distro with GPU acceleration on armhf will appear, adding compilation for Tegra will have sense. Now it would be missleading.

**Comment by epicmario7133** [comment]
> You can use one for RPI4, but as Jetson Nano don't have armhf libraries for GPU acceleration, it won't work out of the box. Adding option for this would be wrong as device can't work with it without correct setup. If you want to use it anyway, use this guide: https://wiki.switchroot.org/en/Linux/Emulation/Box86
> 
> If distro with GPU acceleration on armhf will appear, adding compilation for Tegra will have sense. Now it would be missleading.

sorry but box86 is not working 
error:
bash: /usr/local/bin/box86: No such file or directory
when I install box 86:
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/bin/box86
-- Installing: /etc/binfmt.d/box86.conf
-- Installing: /usr/lib/i386-linux-gnu/libstdc++.so.6
-- Installing: /usr/lib/i386-linux-gnu/libstdc++.so.5
-- Installing: /usr/lib/i386-linux-gnu/libgcc_s.so.1

**Comment by Heasterian** [comment]
Looks like you are trying to start box86 in 64-bit enviorment with multiarch disabled. Best way to run box86 on Nano is in armhf chroot (with just multiarch you can break GPU acceleration in system). Guide to make chroot setup is in link that I send in previous message.

**Comment by Heasterian** [comment]
> > You can use one for RPI4, but as Jetson Nano don't have armhf libraries for GPU acceleration, it won't work out of the box. Adding option for this would be wrong as device can't work with it without correct setup. If you want to use it anyway, use this guide: https://wiki.switchroot.org/en/Linux/Emulation/Box86
> > If distro with GPU acceleration on armhf will appear, adding compilation for Tegra will have sense. Now it would be missleading.
> 
> sorry but box86 is not working
> error:
> bash: /usr/local/bin/box86: No such file or directory
> when I install box 86:
> -- Install configuration: "RelWithDebInfo"
> -- Installing: /usr/local/bin/box86
> -- Installing: /etc/binfmt.d/box86.conf
> -- Installing: /usr/lib/i386-linux-gnu/libstdc++.so.6
> -- Installing: /usr/lib/i386-linux-gnu/libstdc++.so.5
> -- Installing: /usr/lib/i386-linux-gnu/libgcc_s.so.1

Also, if you already have multiarch, you need to install libc6:armhf with apt if you are using multiarch. That should fix it.

I added some clarification about Tegras in doc about compilation.

**Comment by ptitSeb** [comment]
Can this ticket be closed now?

**Comment by epicmario7133** [comment]
yes
