### ISSUE TITLE
box86 refuses to compile on my (really old) chromebook (python syntax error?)

### ISSUE THREAD

**Issue by Tertle950** [ptitSeb/box86#457]
Make complains every time I try to build box86, but it could be CMake's fault.
```
     File "/home/tertle950/box86/rebuild_wrappers.py", line 169
       __keys__: List[T]
               ^
```
I'm using the standard compilation commands with "other Linux ARM devices". Any ideas?

**Comment by ptitSeb** [comment]
You need python 3. Something like 3.7 or 3.8 should work.

**Comment by Tertle950** [comment]
I have Python 3.5. Apt thinks it's the latest version.

**Comment by Tertle950** [comment]
I installed Python 3.8, but the issue persists. I'm assuming Make is still calling Python 3.5 and it's throwing a syntax error that 3.8 considers normal.

**Comment by ptitSeb** [comment]
Use `ccmake` to interactively change the path to the python binary.

**Comment by Tertle950** [comment]
This worked! Thank you!

For anyone in the future dealing with this:
CCMake in Apt is `cmake-curses-gui` and the Python path is hidden under Advanced mode.
