### ISSUE TITLE
Compilation instructions not clear for pi4 on 64 bits OS

### ISSUE THREAD

**Issue by thorkseng** [ptitSeb/box86#465]
Hello!

Thanks a lot for your work, and sorry if I did something wrong.

I am trying to run box86 in a Pi4/8GB with RaspianOS of 64bits.
To do this, following the compilation instructions, I have executed the following commands:
```
sudo apt install gcc-arm-linux-gnueabihf
git clone https://github.com/ptitSeb/box86
cd box86
mkdir build; cd build; cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j2
sudo make install
sudo systemctl restart systemd-binfmt
```

Everything goes fine, compiling finish without errors.
The executable is compiled, and installed on the system (I tried to compile box64 and it works perfectly).

The make install move it and create everything to work, but it does not work.
Now, when I tried to execute box86 I got the next error:
`-bash: /usr/local/bin/box86: No such file or directory`

Checking the binary compiled with "objdump -a /usr/local/bin/box86" I got this result:
`/usr/local/bin/box86:     file format elf32-littlearm`

Doing the same with box64 binary:
`/usr/local/bin/box64:     file format elf64-littleaarch64`

To fix this issue I do the next (please, let me know if it is not correct):
```
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install libc6:armhf libncurses5:armhf libstdc++6:armhf

```
Now, the box86 works fine in the machine (I tried to use it to download steamcmd and it works fine). 
Maybe can be a good point to add this to the instructions, or if there is any other way to execute the binary created.

Thanks a lot!
Regards,
Tranko.

**Comment by WheezyE** [comment]
I've add installing libc6:armhf to the box86 build instructions for aarch64 systems.  Ok to close this issue?

**Comment by ptitSeb** [comment]
Compilation (and running stuffs) on 64bits is clear now. Closing the ticket. Re-open it if needed.
