### ISSUE TITLE
Running Machinarium

### ISSUE THREAD

**Issue by Pythonic456** [ptitSeb/box86#466]
I am trying to run Machinarium.
Here is the output so far:
[allout.txt](https://github.com/ptitSeb/box86/files/7197092/allout.txt)

Seems to be missing libnss3.
It is already installed via apt.
How can I make box86 find the lib?

Thanks for any help in advance!

**Comment by ptitSeb** [comment]
Update box86, I added libnss3 wrapping last weekend.
Not sure whay I have done will be enough to run the game...

**Comment by Pythonic456** [comment]
Alright, I updated Box86. Heres the output now:
(command: `BOX86_LOG=3 box86 Machinarium &> allout.txt`)
[allout.txt](https://github.com/ptitSeb/box86/files/7198005/allout.txt)
Now it needs `libssl3`? But there is no `libssl3` in the apt repos, the latest seems to be `libssl1.1`.
Thanks!

**Comment by ptitSeb** [comment]
Ah, yeah. Probably another lib allong with libnss3. I'll see if I can wrap it soon, or at least create an empty wrapper so it load further...

**Comment by Pythonic456** [comment]
Thanks

**Comment by ptitSeb** [comment]
I tested and I got it working fine, even without that last wrapped function.
![d2000_03-780x384](https://user-images.githubusercontent.com/3250792/195155324-4e9237d7-1fd0-4037-b72b-f6042c492227.jpg)

I think this ticket can be closed.

**Comment by Pythonic456** [comment]
Great, I will check if it works on my system too tomorrow.

**Comment by Pythonic456** [comment]
Yep, seems to work now. :+1:
