### ISSUE TITLE
Latest Box86 breaks Zoom launch entirely

### ISSUE THREAD

**Issue by Botspot** [ptitSeb/box86#467]
Commands to reproduce:
```bash
wget 'https://zoom.us/client/5.4.53391.1108/zoom_i686.tar.xz'
tar -xf ~/zoom_i686.tar.xz
rm -f ~/zoom_i686.tar.xz
cd zoom
box86 zoom
```
This used to work. Issue was first spotted on [Pi-Apps issue 962](https://github.com/Botspot/pi-apps/issues/962).
Setting BOX86_LOG to `1` does not display anything of benefit.

Using an older version of Box86 (an older deb-file from @Itai-Nelken) fixes the problem, as you can see in the Pi-Apps issue I linked.

**Comment by ptitSeb** [comment]
Seems the regression was introduced with commit a110b60a2af2aef8950989393eee8a46372d8ab7
That's strange, but I'll check that and try to fix it soon.

**Comment by cycool29** [comment]
I built it again and it worked now!

**Comment by Botspot** [comment]
It's working for me too. Closing this issue.
