### ISSUE TITLE
Box86 Zoom SSO Sign-In not working

### ISSUE THREAD

**Issue by ZingyTomato** [ptitSeb/box86#468]
Once the zoom app is launched (Installed using Pi-Apps on Twister OS on a pi 4 8gb), and you enter in the SSO credentials, a browser window opens the but the sign in page never loads. Is this an issue with BOX86 or chromium itself?

**Comment by ZingyTomato** [comment]
Yeah the Sign In With Google option works. Just using a custom SSO doesn't

**Comment by Botspot** [comment]
> Just using a custom SSO doesn't

Today I located a SSO domain: msu.zoom.us
I inputted the domain like this:
![sso zoom login](https://user-images.githubusercontent.com/54716352/134718289-571bb931-6577-4902-b1a4-890233b5abcf.png)
Then I clicked **Continue**. Chromium opened and went to `https://auth.msu.edu/` like it should.

@ZingyTomato, could you try to replicate the steps I took with `msu`? What SSO domain were you trying to use?

**Comment by ZingyTomato** [comment]
Hey sorry it has taken so long to reply. I use morganstanley as the SSO. So, now the issue of the actual sign in web page not loading is fixed. However, when you enter in all your credentials and click the dialog box to open the zoom app, nothing opens.

**Comment by ptitSeb** [comment]
Is this ticket still relevent or can it be closed?
