### ISSUE TITLE
Runnning games in Raspberry pi4

### ISSUE THREAD

**Issue by actraiser30** [ptitSeb/box86#470]
Hello

its my first time installing box86 so i dont really know how to run games etc

i have dune2000 in a folder in latest raspbian buster

i tried the command:box86 DUNE2000.EXE

and i get some errors: 

not an elf file (sign=MZ)

error reading elf header of /home/pi/dune2000/DUNE2000.EXE

how can i make the game run??

thanks in advance

**Comment by ptitSeb** [comment]
That's a windows game. You need to install x86 Wine to run it. Look at [docs/WINE.md](https://github.com/ptitSeb/box86/blob/master/docs/X86WINE.md) for a tutorial on how to do it

**Comment by symbios24** [comment]
Anyway in general how do i ran a game with box86???
Is there a guide with commands supported?

**Comment by ptitSeb** [comment]
Read the README.
Once installed, with binfmt integration, just run x86 linux stuff without thinking of box86: it will be called automtically.

Can this ticket be closed now?

**Comment by ptitSeb** [comment]
You can also take a look at the box86/box64 section of this blog entry: https://box86.org/2022/03/box86-box64-vs-qemu-vs-fex-vs-rosetta2/

Closing the ticket now.
