### ISSUE TITLE
Tor-browser

### ISSUE THREAD

**Issue by buhtzz** [ptitSeb/box86#471]
I am sorry for open this as an issue. But I couldn't find a better place.

I want to run Tor-browser via box86 on a Raspberry Pi 4 with Raspberry Pi OS (based on Debian buster).

The build of box86 worked well on the Pi 4. Very nice.
I downloaded the x86 32bit linux version of tor-browser. But the start process is to complex I think.

When I do `start-tor-browser.desktop` I got thet "Tor Browser requires a CPU with SSE2 support." error. I tried to dive deeper into the tor folder structure to find out if box86 runs in the background.

```
cd ~/Downloads/tor-browser/Browser/
./firefox

Box86 with Dynarec v0.2.3 46114235 built on Sept 28 ...
Error: loading needed libs in elf ./firefox.real
```

Box86 itself runs I think. Any idea how to solve it?

**Comment by ptitSeb** [comment]
Not sure box86 can run that.
Try to use `BOX86_LOG=1 ./firefox` to have more detail on what lib is missing...

**Comment by ptitSeb** [comment]
for the `libatomic.so` missing, this lib is not wrapped, so you should grab an x86 version of that lib and copy the binary in the current folder.

For `./Browser/start-tor-browser ` doing an error with SSE2 error, that's strange. Box86 emulate SSE2 extension, so it should be detected. There must be something else going on there. I may try to run the thing at some point, to see if I can see something.

**Comment by ptitSeb** [comment]
Oh, it's a script. Ok, I see.
Well, issue is there: https://gist.github.com/Codeberg-AsGithubAlternative-buhtz/926f6c843ad43b3fd2bee63ab061bdac#file-gistfile1-txt-L99-L102
comment those lines in the script to avoid the test...

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thanks for your help. With commenting the test lines the run keeps silent without any error.
I was not able to find a lib atomic to download somewhere. And I do not want to install a virtual linux somewhere just to get this file. I think I will give up at this point.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
The ARM builds are not from a trustfull source. No option.

This issue was not about runnig tor browser on ARM64. It was about running it with box86 o ARM64.

**Comment by ptitSeb** [comment]
So, did you retry with latest box86? Shall the ticket be closed?

**Comment by buhtzz** [comment]
Thanks for asking back.
I switch to another operating system. I'm now using an original Debian (but special) image for Pi's from http://raspi.debian.net/
