### ISSUE TITLE
Winegcc gcc: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?

### ISSUE THREAD

**Issue by Deftaudio** [ptitSeb/box86#477]
Hi, I installed wine per instruction on Raspberry Pi4 and it's running perfectly. 
However winegcc is calling gcc with -m32 flag and fails to start.
Please, suggest how to fix this. 

```
# winegcc
Box86 with Dynarec v0.2.3 1955c225 built on Oct  8 2021 21:03:54
gcc: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?
gcc: fatal error: no input files
```

**Comment by ptitSeb** [comment]
why would you want to use winegcc? This is a wrapper aroung system gcc, so it will use your arm version of it. What are you trying to do?

**Comment by ptitSeb** [comment]
Can this ticket be closed? It's not an issue about box86 anymore.

**Comment by Deftaudio** [comment]
yes please

**Comment by flappix** [comment]
@Deftaudio 
Hi, did you got it managed to work? I'm also trying to use Carla to run a windows vst plugin on my Raspberry and I'm stuck at because winegcc complains about the -m32 option. Do you have any resources or any kind of tip?

Thanks a lot :)
