### ISSUE TITLE
Unable to launch zoom with latest box86 in Raspberry Pi 32 bit

### ISSUE THREAD

**Issue by cycool29** [ptitSeb/box86#478]
Commands to reproduce:
```
wget 'https://zoom.us/client/5.4.53391.1108/zoom_i686.tar.xz'
tar -xf ~/zoom_i686.tar.xz
rm -f ~/zoom_i686.tar.xz
cd zoom
box86 zoom
```
Users reported issue in pi-apps repo https://github.com/Botspot/pi-apps/issues/1038.

Tested with previous version of deb build by @Itai-Nelken on commit b30a0717 and it is working.

**Comment by Botspot** [comment]
Any updates? What is causing it this time?

**Comment by ptitSeb** [comment]
Isn't that fixed now? I think I fixed it some time ago.
