### ISSUE TITLE
Installing Steam on HoneyComb LX2K

### ISSUE THREAD

**Issue by Wooty-B** [ptitSeb/box86#481]
Hello, I tried to do as much research as I could before posting this as an issue here, but having a hard time diagnosing over the past few months and hope someone can help assist...

I am running on a SolidRun HoneyComb LX2K 64-bit ARM workstation w/ AMD Radeon Pro GPU and have had mixed results with Steam. The method I have found to work best is to set up a 32-bit chroot and installing Box86 and Steam there. Sometimes when I install it works fine for a while before breaking, while other times it's broken upon setting up the chroot. The main error I notice between a working install and broken one is with the line:

'sh: 1: /home/wooty/.local/share/Steam/ubuntu12_32/../ubuntu12_64/gldriverquery: not found'

Here is a link to the full error from terminal: https://github.com/Wooty-B/LX2K_Guide/blob/main/steam_error

Here is a link to my setup process: https://github.com/Wooty-B/LX2K_Guide/blob/main/Setup-Armhf-Chroot.md

I normally set up Box86 and Steam via Pi-Apps for ease of install, however installing Box86 and Steam manually exhibits the same results. Thanks for any input!

**Comment by Heasterian** [comment]
Looks like your set up don't define that it's 32-bit linux and that's why it's looking for 64-bit binary.

Try to start it with `setarch -L linux32 steam -no-browser` .

**Comment by ptitSeb** [comment]
Should work with latest box86 (+box64). Can this ticket be closed?

**Comment by Wooty-B** [comment]
If possible, can you briefly let me know which distro/OS/kernel you are running for your multiarch? Still having trouble getting this to work effectively as openGL package conflicts break my system. Will need to reinstall system once more and also try out Fedora as an alternative.

Would love some more information on your 64bit ARM environment to try and mimic myself, and can be closed for now while I try testing over the next few weekends. I appreciate any info as I would love to showcase Steam on ARM64 w/ a fullsize GPU and the wonders of Box86 + Box64. Thanks again for your time and effort!

**Comment by ptitSeb** [comment]
I use Debian and Armbian on my various machines. Ubuntu can works too, but I don't actively used it.

**Comment by Wooty-B** [comment]
Closing.
