### ISSUE TITLE
Fatal Error in Launching GameMaker 2

### ISSUE THREAD

**Issue by Mist-16** [ptitSeb/box86#483]
[
![image](https://user-images.githubusercontent.com/68829660/138163273-ce60bda1-ef51-4d62-a5c6-fe8b0240ab67.png)
](url)
This Error is happening when I try to Open the Game Engine.
BTW this is my first time downloading it so I have no clue whats going on,

**Comment by Mist-16** [comment]
If anyone have any insight on this Please Help

**Comment by cyberdust2k** [comment]
By the looks of it you are running Windows 10 at the moment. Are you sure your issue is related to Box86?

**Comment by Mist-16** [comment]
Thank you for helping
