### ISSUE TITLE
simcity 3000 (linux version)

### ISSUE THREAD

**Issue by jackygoule** [ptitSeb/box86#485]
Hello i want to install sc3000 with box86 .
when i run 
sh setup.sh
This installation doesn't support unknown on Linux / armv7l
so i test with:
box86 sh setup.sh
Box86 with Dynarec v0.2.3 fa4b5fe7 built on Oct 28 2021 14:24:55
Error: reading elf header of /usr/bin/dash, try to launch natively instead
Erreur de segmentation
i compile box86 with pi-kiss 
Thanks for your job.

**Comment by ptitSeb** [comment]
Is it still an issue? can this ticket be closed?

**Comment by jackygoule** [comment]
Hello, yes .But i test tomorrow again 
Thanks

**Comment by jackygoule** [comment]
Hello , the install of simcity 3000 linux version is very hard so i try with windows version .
I install wine  and box86 with pi apps.
The game seem work very well .
My little boy play with it, and if it's cool i close this.

**Comment by ptitSeb** [comment]
Good for me.
