### ISSUE TITLE
Failed to compile on Debian sid armhf chroot (selected processor does not support X)

### ISSUE THREAD

**Issue by Danct12** [ptitSeb/box86#487]
When compiling Box86 (4a7c16c3369825a810c35485e7a645eb49c353e9) inside an armhf chroot (in this case, Debian sid) on aarch64, this error shows up:

```
/tmp/box86/src/dynarec/arm_epilog.S:24: Error: selected processor does not support `vpop {d8-d15}' in ARM mode
```

By reverting 794c16644be8430c51835f19b6f028ab5b618272, the error disappears and Box86 compiles.

Build log:
```
(debian-sid)alarm@danctnix:/tmp/box86/build$ cmake .. -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo-- Found Python3: /usr/bin/python3.9 (found version "3.9.7") found components: Interpreter 
-- The C compiler identification is GNU 11.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/box86/build
(debian-sid)alarm@danctnix:/tmp/box86/build$ make -j5
Scanning dependencies of target dynarec_arm
[  0%] Built target PRINTER
[  0%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm_functions.c.o
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynarec_arm.c.o
[  1%] Built target WRAPPERS
[  1%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/arm_printer.c.o
[  2%] Building C object CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_helper.c.o
[  2%] Building ASM object CMakeFiles/dynarec_arm.dir/src/dynarec/arm_prolog.S.o
[  3%] Building ASM object CMakeFiles/dynarec_arm.dir/src/dynarec/arm_epilog.S.o
/tmp/box86/src/dynarec/arm_prolog.S: Assembler messages:
/tmp/box86/src/dynarec/arm_prolog.S:13: Error: selected processor does not support `vpush {d8-d15}' in ARM mode
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:131: CMakeFiles/dynarec_arm.dir/src/dynarec/arm_prolog.S.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/tmp/box86/src/dynarec/arm_epilog.S: Assembler messages:
/tmp/box86/src/dynarec/arm_epilog.S:15: Error: selected processor does not support `vpop {d8-d15}' in ARM mode
/tmp/box86/src/dynarec/arm_epilog.S:24: Error: selected processor does not support `vpop {d8-d15}' in ARM mode
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:144: CMakeFiles/dynarec_arm.dir/src/dynarec/arm_epilog.S.o] Error 1
[  3%] Building C object CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_emit_tests.c.o
[  3%] Building C object CMakeFiles/arm_pass2.dir/src/dynarec/dynarec_arm_emit_math.c.o
```

**Comment by ptitSeb** [comment]
What's your hardware? Choosing DYNAREC without a hardware profile  is not advised for now (I'll see if I can fix that).

**Comment by Danct12** [comment]
I'm on a PinePhone (Allwinner A64)

**Comment by Danct12** [comment]
Interestingly, trying out the referenced commit (bcdeff5217985021d59101c6504090d9c06b3b83) throws up this error:

```
cc1: error: '-mfloat-abi=hard': selected architecture lacks an FPU
cc1: error: target CPU does not support ARM mode
```

Which is untrue as the A64 has hard float instructions, here is /proc/cpuinfo
```
processor       : 3
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4
```

**Comment by ptitSeb** [comment]
You need to setup CFLAGS for your arch (use `ccmake`, it's easier). Use something like `-mcpu=cortex-a53 -mcpu=neon -mfloat-abi=hard`, it should works.

**Comment by TuxThePenguin0** [comment]
This happens on the RK3399 as well when using `-DRK3399=1`

**Comment by ptitSeb** [comment]
I have build box86 countless times on RK3399, without error. On what system are you? Is it only happening when building the Assembly files?

**Comment by TuxThePenguin0** [comment]
Fails on `arm_prolog.S` for me with a very similar vpush error to what danct is getting
Using Debian Sid

**Comment by ptitSeb** [comment]
I assume you are using chroot and not multiarch?

**Comment by TuxThePenguin0** [comment]
I'm using an arm64 lxc container with multiarch so I can use box86 and box64 in the same container

**Comment by ptitSeb** [comment]
I never had this kind of error. I assume the Debian Sid is old and default to armv6 architecture, or something like that.

Can you try to change the `CMAKE_ASM_FLAGS` (using `ccmake`) and add `-mfpu=neon` and see if it helps?

**Comment by TuxThePenguin0** [comment]
That still gives me the same error

**Comment by ptitSeb** [comment]
I don't have any system like that to test things. I have pushed a small changes, but if you already tested adding the -mfpu flags, then I guess it wont change a thing. You need to find a working parameter on you plateform. The commit https://github.com/ptitSeb/box86/commit/794c16644be8430c51835f19b6f028ab5b618272 cannot be reverted, as those d8-d15 regs needs to be saved to comply to the armhf ABI.

**Comment by TuxThePenguin0** [comment]
That most recent commit fixes the issue for me

**Comment by ptitSeb** [comment]
ah good :D 👍
