### ISSUE TITLE
Check for Python dependency / use python3 binary if available

### ISSUE THREAD

**Issue by voltagex** [ptitSeb/box86#49]
Currently, the build fails on Ubuntu 19.04 as there's no `python` binary, only `python3` by default.

```
~/src/box86/build$ make
[  1%] Generating ../src/wrapped/generated/wrapper.c, ../src/wrapped/generated/wrapper.h
/usr/bin/env: ‘python’: No such file or directory
make[2]: *** [CMakeFiles/box86.dir/build.make:112: ../src/wrapped/generated/wrapper.c] Error 127
make[1]: *** [CMakeFiles/Makefile2:72: CMakeFiles/box86.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

Would it be possible to use CMake to detect the system python and change the shebang line in rebuild_wrappers.py? The script seems to run with python3.

**Comment by ptitSeb** [comment]
Can you try with this commit 71ae77070e540debdce090000901cdca5e8dae2a that should fix the "python3" issue (I hope).

**Comment by voltagex** [comment]
Yes, that works.

**Comment by ptitSeb** [comment]
Ok, closing the issue now it's fixed.
