### ISSUE TITLE
Steam Cloud - does it work on Box86 for syncing files...?

### ISSUE THREAD

**Issue by dagleykd** [ptitSeb/box86#491]
Hi all - I guess you could classify this as an issue, but I was just curious if it were a function you guys couldn't get to work, something that just doesn't work yet, or something that isn't working right and is supposed to be....

As an example - I have Stardew Valley installed on Steam on my Win10 desktop, my Linux Mint 20.2 MATE laptop. my MX Linux 21 XFCE laptop and my Linux Mint 20.2 MATE HTPC.. Steam Cloud synchronizes my saved games to each of those devices so I can play on any of them and then the next time I play on any other device, the save has been updated so I have the same save on all those devices.

But...I have Steam installed on my newRPi 4 4GB running TwisterOS and Stardew runs quite well on it, but my saves never seem to sync from my other machines...?

Was just curious if Steam Cloud was a feature that would eventually be made to work through Steam on Box86 or whether it's just not possible or what? :)

Cheers and thanks very much for all the AMAZING hard work and the very capable program! :D

**Comment by ptitSeb** [comment]
Is steam cloud still an issue? I think it's ok now, but I'm not sure.
