### ISSUE TITLE
Could TeknoParrot work?

### ISSUE THREAD

**Issue by dorr1** [ptitSeb/box86#495]
Is it possible to play Taito Type-X arcade games on the Raspberry Pi 4 by using Box86 and Wine with the TeknoParrot compatibility layer? The specs required are high, but it could be possible.

**Comment by WheezyE** [comment]
Try it and see? Taito TypeX, like you said, is very CPU intense though. It may run slow on a Pi4, especially without graphics acceleration.

**Comment by Ruler-Dev** [comment]
Teknoparrot is a 64bit program.

**Comment by dorr1** [comment]
> Teknoparrot is a 64bit program.

So it wouldn't work on Box86, and rather require Box64 then?
