### ISSUE TITLE
Is box86 can run Linux x86 apps?

### ISSUE THREAD

**Issue by GuckTubeYT** [ptitSeb/box86#497]
Is box86 can run linux x86 apps? And how do i run linux x86 apps?

**Comment by WheezyE** [comment]
Yes, box86 is an ARM->x86 emulator for Linux. If you have a Linux x86 computer, then you don’t need box86. If you have a Windows computer, then you don’t need box86 to run Linux programs and vice-versa (just Cygwin or Wine). If you have an ARM CPU which runs Linux though, you will need box86 to run x86 Linux programs.  Box86 installation and compilation instructions can be found on the main readme page

**Comment by GuckTubeYT** [comment]
I already compile the box86, but i dont know how to open x86 linux or install x86 deb

**Comment by ptitSeb** [comment]
box86 is not VM type of emulator. You will not run an full x86 version of a Linux distrib.

Think of box86 like wine: it will use most of the library already installed on you system to run x86 apps. So "deb" will not work as-is. Prefer tgz/zip archive. Just extract the files and launch the binary as if it was an arm one (if you have installed box86 and use the binfmt integration), or use `box86 ./myapp` if you don't have system integration enabled.

**Comment by GuckTubeYT** [comment]
Oh, thanks for the information
