### ISSUE TITLE
Can a host binary file be generated

### ISSUE THREAD

**Issue by minhaozh** [ptitSeb/box86#498]
I tried to use the box86 to successfully run the example“hello x86 world!”, but I didn't see arm binary or intermediate files being generated. I can  see that x86 binary files can be run directly on arm architecture. Can I choose to generate binary files? Can one translation be reused?
Did I miss any information? Thanks a lot to help!

**Comment by ptitSeb** [comment]
Same as with box64, read `docs/COMPILE.md` to build box86.

**Comment by ptitSeb** [comment]
Can this ticket be closed?
