### ISSUE TITLE
Another question about this great project

### ISSUE THREAD

**Issue by Askmewho** [ptitSeb/box86#5]
Hi petit, could be this have any complementation with wine arm just like exagear? Didt try exagear before. But i will test this project againts everything. Its a bit sad than notaz its a bit dissapeared from the arm atmosphere. He was really kind of helping me with his binaries and wine tweaks.

Offtopic. Your jedy outcast runs grewat on the pi. It could runwith beter resolution but it demands a lot of vram
https://youtu.be/oUFC0sK8a1E

I will move on with n2 when it released. Hope than panfrost arrive soon  to that lovely arm sbc. Anholt did a great job on vc4 as you see.

**Comment by meveric** [comment]
Jedi Outcast and Jedi Academy run natively on arm.
It was made opensource and @ptitSeb  ported it years ago to OpenGL ES already. Also you can simply use gl4es also from @ptitSeb to run it as is without having to convert it to OpenGL ES.
https://forum.odroid.com/viewtopic.php?f=91&t=1718
https://forum.odroid.com/viewtopic.php?f=91&t=1756

As you can see by the date of the posts we were playing Jedi Outcast and Jedi Academy back in 2013 already in 1080p

"wine arm exagear" topic.
ExaGear did NOT use arm wine, but x86 (i386) wine. This is very important. Wine runs the binaries of the architecture it runs on. "arm" wine would only run ARM windows binaries, and that won't help you.

**Comment by Askmewho** [comment]
Ohh i forgot that of exagear!! Yes. Indeed. The question remains. We could use this projerct with wine x86?

**Comment by ptitSeb** [comment]
Wine x86 is not in my scope for Box86. Maybe it work, maybe not. I will not test it or try to make it work. There reason is that I have other plan with Wine (but it's very similar to the Hangover project, so not sure I'll do it anyway).

**Comment by Askmewho** [comment]
Ok!
