### ISSUE TITLE
Command line option test compile amd 64 [amd64]

### ISSUE THREAD

**Issue by dvdvideo1234** [ptitSeb/box86#502]
Hi, I am preparing a script to install Box86 on my [A20](https://www.olimex.com/Products/OLinuXino/A20/A20-OLinuXino-LIME2/open-source-hardware), so that I can run [UPS monitoring software](https://energy.fsp-europe.com/software/). I am doing dry run on my [x64] office laptop so it produces a bunch of warnings (skipped of course) the compillation is stuck at 1%.
```
mkdir build; cd build; cmake .. -DLD80BITS=1 -DNOALIGN=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo; make -j$(nproc)
```
When is is ready for x64, will then compile for the Allwinner A20 via:
```
sudo apt install gcc-arm-linux-gnueabihf
mkdir build; cd build; cmake .. -DA32=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo; make -j$(nproc)
```

How can I run the installer in this ticket with Box86 ?

**Comment by ptitSeb** [comment]
There is no "A32" profile in the CMakeList.txt. Your compile line will not make cmake use gcc-arm-linux-gnueabihf compiler. You need to use one of the existing profile (`RK3399`, `RPI4ARM64`, `PHYTIUM`, `SD845` or `A64`) or create you own.

Also, beware of the "-j", using a too big value may lead to a "Out Of Memory" issue while compilign for the first time.

The 1% is a python script tring to generate some code, or at least check if it needs to. Be sure you have a working Python 3.+ on your system and that it can write on source folders.

**Comment by dvdvideo1234** [comment]
Hmm trying to compile on x86 with the Windows 10 ubuntu console application:
```
make[2]: *** [CMakeFiles/box86.dir/build.make:581: CMakeFiles/box86.dir/src/emu/x86syscall.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/box86.dir/all] Error 2
make: *** [Makefile:117: all] Error 2
deyan@ddobromirov2:~/box86/build$ python3 --version
Python 3.8.5
```
Errors correspond to:
```
Error 1: vim CMakeFiles/box86.dir/build.make
src/emu/x86syscall.c.o"
        /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/box86.dir/src/emu/x86syscall.c.o   -c /home/deyan/box86/src/emu/x86syscall.c

Error 2: vim CMakeFiles/Makefile2
CMakeFiles/box86.dir/all: CMakeFiles/WRAPPERS.dir/all
        $(MAKE) -f CMakeFiles/box86.dir/build.make CMakeFiles/box86.dir/depend
        $(MAKE) -f CMakeFiles/box86.dir/build.make CMakeFiles/box86.dir/build
```

**Comment by ptitSeb** [comment]
What is the error message?

**Comment by dvdvideo1234** [comment]
Hello, @ptitSeb attaching the compiler output:
[out.txt](https://github.com/ptitSeb/box86/files/7570847/out.txt)

**Comment by ptitSeb** [comment]
Yes, the `-m32` is missing!
I'll change the COMPILE.md later to mention that.

**Comment by dvdvideo1234** [comment]
Hi, Any way I can define compilation for my A20 CPU ?

**Comment by ptitSeb** [comment]
Create another ticket and specify what you need. If you can write the typical CFLAGS for the A20, that would help.

Also, I think this ticket can be closed, I added some details on the COMPILE.md to address your issue about building box86 on amd64 plarform.

**Comment by dvdvideo1234** [comment]
Oke ;P
