### ISSUE TITLE
PlayonLinux + Wine

### ISSUE THREAD

**Issue by Pythonic456** [ptitSeb/box86#506]
I'm trying to use PlayonLinux to install a game called "Pluto Strikes Back", when installing, Wine crashes, with this traceback:
```
[POL_LoadVar_PROGRAMFILES] Message: Getting Program Files name
[POL_Wine] Message: Running wine- cmd /c echo %ProgramFiles% (Working directory : /home/pi/.PlayOnLinux/shortcuts)
[POL_Wine] Message: Notice: PlayOnLinux deliberately disables winemenubuilder. See http://www.playonlinux.com/fr/page-26-Winemenubuilder.html
/usr/local/bin/wine: line 2:  1758 Segmentation fault      setarch linux32 -L /home/pi/wine/bin/wine "$@"
[POL_Wine] Error: Wine seems to have crashed

If your program is running, just ignore this message.
[POL_Wine] Message: Wine return: 139
```
Help is much appreciated :)

**Comment by ptitSeb** [comment]
There is nothing interesting in this trace. Is Pluto Strikes Back a commercial game or a freeware I can download somewhere for testing?

**Comment by Pythonic456** [comment]
I used the PlayonLinux installer, but here is the source for that: [PlayonLinux "Pluto Strikes Back"](https://www.playonlinux.com/en/app-90-Pluto_Strikes_Back.html)
And this is the link in the installer to the game: [Game](http://www.kloonigames.com/download.php?file=pluto_r1.5.zip)
I think it is freeware as in PlayonLinux it doesn't appear with the "Commercial" filter turned on.

**Comment by ptitSeb** [comment]
Ok, Good. I'll grab this and take a look later.

**Comment by Pythonic456** [comment]
Got anywhere yet? I just checked that it runs on Linux ARM64, and yes it does, with no errors/crashes/bugs.

**Comment by ptitSeb** [comment]
You mean, it works with box64 but not with box86?

**Comment by Pythonic456** [comment]
Sorry, I meant AMD64 :/

**Comment by ptitSeb** [comment]
ah ok. Still haven't check, but will try this weekend.

**Comment by ptitSeb** [comment]
I just tried pluto on my phytium and it was working fine with Wine.

**Comment by Pythonic456** [comment]
👍 thanks for your help
