### ISSUE TITLE
It came a isuue that needs "libculr.so.4" running DST server(x86)

### ISSUE THREAD

**Issue by RaidOpe** [ptitSeb/box86#509]
I sucessfully installed and ran Steamcmd, when I countined to establish my server,Err was happend,It showed:

> Box86 with Dynarec v0.2.2 bedacef6 built on Nov 26 2021 04:55:03
> Error initializing native libcurl-gnutls.so.4 (last dlerror is libcurl-gnutls.so.4: cannot open shared object file: No such file or directory)
> Error: loading needed libs in elf ./dontstarve_dedicated_server_nullrenderer

**Comment by ptitSeb** [comment]
Install libcurl4, on debian/ubuntu/debian, use `sudo apt install libcurl4`

**Comment by RaidOpe** [comment]
> Install libcurl4, on debian/ubuntu/debian, use `sudo apt install libcurl4`

well，I installed the lib, but it still didn't work. In some tutorial , they told me , send the code 

`ln -s /usr/lib/libcurl.so.4 /home/dstserver/bin/lib32/libcurl-gnutls.so.4` (IN x86 Centos) 
For RPI OS， there is no such /usr/lib/culr *libcurl.so.4* to told *dontstarve_dedicated_server_nullrenderer* to use

**Comment by otomay** [comment]
How do you manage to run steamcmd on box86? I'm trying to setup a DST server too, but I'm stuck in the setup of steamcmd (っ˘̩╭╮˘̩)っ
I'm on ubuntu arm64 (a oracle cloud instance)

When I try to run directly with `box86 ./steamcmd.sh` it says:

```
Error: reading elf header of ./steamcmd.sh, try to launch natively instead
Segmentation fault (core dumped)
```

If I go to steamcmd/linux32/ and run with `box86 steamcmd` I got to work the first time with an error in the end:
```
[----] Update complete, launching...
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 7 items discarded.
```

The second time with no errors, but opening the log file there is a "Shutdown" in the last line:

```
[2022-02-19 19:50:56] Installing update...
[2022-02-19 19:50:56] Cleaning up...
[2022-02-19 19:50:56] Update complete, launching...
[2022-02-19 19:50:56] Shutdown
```

And all the other times it keeps with the same error:

```
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
[----] !!! Fatal Error: Failed to load steamconsole.so
```

Please help

**Comment by ptitSeb** [comment]
are you sure box86 is actually used here? I see no box86 banner in any of your logs.

**Comment by otomay** [comment]
Yes, I'm sorry. I cut the logs for avoid spamming, Idk... But I've edited the comment with the full logs

**Comment by ptitSeb** [comment]
It's better to use the shell script, but for that, you need to have box86 binfmt integration.

**Comment by otomay** [comment]
Is it possible for me to do it?

I followed this guide to install box86: https://forum.armbian.com/topic/16584-install-box86-on-arm64/

**Comment by ptitSeb** [comment]
I don't know, I never played with chroot myself, so I don't have any experiance with this, sorry.

**Comment by otomay** [comment]
I see (っ˘̩╭╮˘̩)っ Thx for your time, I'll try to chat with another guy I see in the issues section

**Comment by ptitSeb** [comment]
Closing the ticket now.

**Comment by alou-S** [comment]
@otomay used `LD_LIBRARY_PATH=$(pwd)` when launching `steamcmd`. `$(pwd)` if you are within the linux32 directory
