### ISSUE TITLE
Steam crashes on TwisterOS PBP

### ISSUE THREAD

**Issue by ravenclaw900** [ptitSeb/box86#514]
When I run steam on TwisterOS, on the Pinebook Pro, it always crashes after entering the password. There seem to be multiple possible errors:
```
Fatal IO error 11 (Resource temporarily unavailable) on X server 8a���
                                                                      ��.
```
```
src/common/framefunction.cpp (149) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[CHTTPClient::BFrameFuncHandleCompletedWorkItems] still registered
src/common/framefunction.cpp (149) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[CHTTPClient::BFrameFuncHandleCompletedWorkItems] still registered
```

**Comment by ptitSeb** [comment]
Can you retry now with latest box86, and close the ticket if it works.

**Comment by ptitSeb** [comment]
No news is good news, I guess.

Closing the ticket, feel free to re-open it if needed.

**Comment by ravenclaw900** [comment]
Sorry for forgetting about this, but my PBP runs Fedora now. I might install TwisterOS on a microSD card to test later, though.

**Comment by ptitSeb** [comment]
No problem. Create some new ticket if you have issues (I hope you are using box64 on Fedora :P )
