### ISSUE TITLE
Steam with crostini/box86

### ISSUE THREAD

**Issue by DylanAkp** [ptitSeb/box86#518]
I've successfully installed box86, ctest give me 100%
But I can't run steam
I have STEAMOS=1 and STEAM_RUNTIME=1 in my env
I've tried with a couple of linux games from itch.io without any luck
Maybe it's a real issue, maybe I'm missing something

Here is the errors : 
```
user@penguin:~/tmp$ box86 ./usr/lib/steam/bin_steam.sh

Box86 with Dynarec v0.2.5 ed8e01ea built on Dec  9 2021 15:22:49
Error: reading elf header of /home/user/tmp/usr/lib/steam/bin_steam.sh, try to launch natively instead
Segmentation fault (core dumped)

user@penguin:~/tmp$ box86 steam

Box86 with Dynarec v0.2.5 ed8e01ea built on Dec  9 2021 15:22:49
Error: reading elf header of /usr/lib/steam/bin_steam.sh, try to launch natively instead
Segmentation fault (core dumped)

user@penguin:~/tmp$ steam

steam.sh[2346]: Running Steam on debian 11 64-bit
steam.sh[2346]: STEAM_RUNTIME is enabled by the user
setup.sh[2408]: Steam runtime environment up-to-date!
steam.sh[2346]: Can't find 'steam-runtime-check-requirements', continuing anyway
/home/user/.local/share/Steam/steam.sh: line 788: /home/user/.local/share/Steam/ubuntu12_32/steam: cannot execute binary file: Exec format error

user@penguin:~/tmp$ ./usr/lib/steam/bin_steam.sh

steam.sh[2441]: Running Steam on debian 11 64-bit
steam.sh[2441]: STEAM_RUNTIME is enabled by the user
setup.sh[2503]: Steam runtime environment up-to-date!
steam.sh[2441]: Can't find 'steam-runtime-check-requirements', continuing anyway
/home/user/.local/share/Steam/steam.sh: line 788: /home/user/.local/share/Steam/ubuntu12_32/steam: cannot execute binary file: Exec format error
```
I can't find any issue with my box86 setup

**Comment by cyberdust2k** [comment]
You are running a 64-Bit Linux environment; are you also running a 64-bit version of Steam? If so, thats beyond the scope of Box86 and you need Box64 for that. If you try running a 32-bit version of Steam on your 64-bit OS you need to have a 32-bit chroot environment as the readme at "Notes about 64-bit systems" says.

**Comment by DylanAkp** [comment]
I'm pretty sure Steam doesn't provide a 32-bit version of Steam but one executable for both 64 and 32 bits.
Tried box64+box86 without success
I will try with a clean install of linux, 32 bits chroot and differents steam versions
Even if it's a success, with ChromeOS+Crostini+Box64/box86+probably proton, I doubt I will be able to run anything playable
Thank you

**Comment by ptitSeb** [comment]
I have to check steam, maybe it got broken lately (or some more native libs maybe needed). Also, 2D games might work nicely on steam. It also depends on the graphics driver a lot.

**Comment by DylanAkp** [comment]
Just tested
With snapdragon 7c and box86+box64
I'm able to run a lot of simples 64-bit linux games (what I was looking for)
I just give up steam and buy games directly from itch.io

Thank you for this amazing work

**Comment by ptitSeb** [comment]
Ah yes, DRM free on itch.io or GOG works better :)
Have fun!
(you can also use Unity3D games, depending on your driver. I could run RaceTheSun or A Short Hike for example)
