### ISSUE TITLE
Crash while trying to start Steam on Debian (RK3399 PinePhone Pro/Mobian)

### ISSUE THREAD

**Issue by CalcProgrammer1** [ptitSeb/box86#524]
Using Debian unstable and multiarch, have both box64 and box86 installed along with armhf, amd64, and i386 architecture sources enabled.  Installed Steam with apt.  Binfmts working, as tested with glxgears amd64 and i386 versions.  I go to open Steam and I get this error:

Error: Global Symbol __libc_single_threaded version 57/GLIBC_2.32 not found, cannot apply R_386_GLOB_DAT 0xf75a1914 ((nil)) in /lib/i386-linux-gnu/libstdc++.so.6

**Comment by jmeloranta** [comment]
Also seeing probably the same issue on Raspberry Pi 4 with arm64 Debian (testing):
Box86 with Dynarec v0.2.5 819cd6c3 built on Dec 18 2021 14:41:46
Error: Global Symbol __libc_single_threaded not found, cannot apply R_386_GLOB_DAT @0xf769f914 ((nil)) in /lib/i386-linux-gnu/libstdc++.so.6
box86: /home/eloranta/c/box86/src/dynarec/dynarec_arm.c:297: fillPredecessors: Assertion `p<dyn->predecessor+pred_sz' failed.

This is with up to date version from git (as of today; 12/18/2021).

**Comment by jmeloranta** [comment]
As for the second error above, it pops up with every i386 executable. So, something goes wrong in fillPredecessors() in dynarec_arm.c.

**Comment by jmeloranta** [comment]
I am seeing this also on raspberry pi 4 (debian arm64).

**Comment by jmeloranta** [comment]
Renaming /lib/i386-linux-gnu/libstdc++.so.6 to something else, gets rid of this error.

**Comment by CalcProgrammer1** [comment]
I got Steam launching by using makedeb to build Debian packages for both box86 and box64.  It is tricky as you have to edit the makepkg.conf file to set the architecture, and then I had to override the architecture environment variables to build box86 correctly.  I also had to adjust the package version in PKGBUILD to get it to build.  Then, I had to install with --force-overwrite.  I was then able to launch Steam, install all the missing dependencies, re-launch Steam, and log in.  Now my library shows empty so I can't install any games, but I think that is to be expected with the webview issues.

**Comment by ptitSeb** [comment]
You need to use the "small view" on Steam to have access to the library. For now box64 will not really execute the steamwebhelper process, so the webview is not available.

**Comment by ptitSeb** [comment]
Also, it seems the libstdc++ lib that comes with box86 is a bit outdated now and need to be refreshed.

**Comment by jmeloranta** [comment]
I am still having issues with this. Tried also getting the latest git version and recompiling.

**Comment by CalcProgrammer1** [comment]
Did you try building with makedeb?

I figured out how to use small view and was able to install a few games, but none will start for me.  I tried Half Life 2 Deathmatch, Portal, and Half Life 1.  HL2DM caused the screen to go black and then segfault, the others didn't even blank the screen.  I haven't looked too deeply into the errors yet.
