### ISSUE TITLE
Icy Tower Opcode

### ISSUE THREAD

**Issue by chills340** [ptitSeb/box86#529]
When attempting to run Icy Tower on wine staging 7.0rc2 i encountered the below opcode

23261|0x4893e0: Unimplemented Opcode (50) 66 1E 66 8C C1 66 58 66
Assertion failed: !status, file dlls/winepulse.drv/mmdevdrv.c, line 213

**Comment by ptitSeb** [comment]
Ok. That `PUSH DS` I'll add it

**Comment by chills340** [comment]
It works now, thanks a ton 
![icy tower](https://user-images.githubusercontent.com/77407293/147287154-957bff37-dffa-4107-9389-f2c9265fce33.png)

**Comment by ptitSeb** [comment]
Ah nice :) Thanks for the screenshot!
