### ISSUE TITLE
Steam issue

### ISSUE THREAD

**Issue by jmeloranta** [ptitSeb/box86#531]
I managed to get steam started in the past but now (with up to date box86) it no longer starts. The last 
 thing I see on the console is:
CAppInfoCacheReadFromDiskThread took 370 milliseconds to initialize
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
_ExitOnFatalAssert

Before that there are quite a few errors similar to:
Error: Symbol gnutls_pkcs12_verify_mac not found, cannot apply R_386_JMP_SLOT 0xe33f0104 (0x205d6) in /home/eloranta/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libnm.so.0
But I think that these were also there when steam started OK. The final errors appear only a few minutes after the initialize message.

Is anyone else seeing this or is my steam installation somehow messed up?

**Comment by Heasterian** [comment]
You are mosli likely missing some libs installed as I saw similar issues in this situation. Run Steam with `BOX86_LOG=1` environment variable and track errors about missing libs.

**Comment by jmeloranta** [comment]
OK, I tried that and I see at the end:
CAppInfoCacheReadFromDiskThread took 771 milliseconds to initialize
Error loading needed lib /home/eloranta/.local/share/Steam/steamservice.so
Warning: Cannot dlopen("/home/eloranta/.local/share/Steam/steamservice.so"/0xdc840020, 2)
Using emulated /home/eloranta/.local/share/Steam/ubuntu12_32/steamservice.so
**Error: Unsupported libc Syscall 0x160 (352)**
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
_ExitOnFatalAssert

There is lot of output but I did not at least spot immediately something that was missing. All of them were either native or emulated.

**Comment by jmeloranta** [comment]
So, does the unsupported libc syscall 0x160 (352) correspond to fallocate() ?

**Comment by jmeloranta** [comment]
OK, problem solved. I had 32bit intel wine installed, which had pulled bunch of i386 libraries with it. It seems that steam was using those and this caused the problem. Purged all i386 stuff and it works now.
