### ISSUE TITLE
(Regression) Palette errors in modded Fallout 1 and 2 when dynarec is enabled

### ISSUE THREAD

**Issue by ectorhga** [ptitSeb/box86#532]
Hi,

I'm using box/wine for a while now on my RPi4, and have noticed this problem only very recently: In both Fallout 1 (modded with [Fallout et tu](https://www.nma-fallout.com/resources/fallout-et-tu.124/) and Fallout 2 (modded with the [Restauration Project](https://www.nma-fallout.com/resources/fallout-2-restoration-project-unofficial-expansion.123/))  there are a lot of rainbow-like palette errors.

I can't say since when this is happening, but it was working before. It must have something to do with the dynarec, since when I disable it, the colors are all right. I'm updating box quite regularly, and for a lot of games the dynarec works better now (like Timeshock!, Dungeon Keeper 2 and others).

I'm willing to help out wherever I can. Like if I knew how to downgrade Box86, I could look for the last working version, maybe? Box86 is a true miracle.

https://user-images.githubusercontent.com/56919853/147413873-7728d006-c97b-47db-b642-6126e3f46d3e.mp4

**Comment by ectorhga** [comment]
I recompiled Box86 again on the weekend and the rainbow effects are gone.

**Comment by ptitSeb** [comment]
Good, thanks for the new test :)

**Comment by ectorhga** [comment]
Np! Thanks for coding Box86!
