### ISSUE TITLE
OpenArena 0.8.8 segfaults with default sound driver (but works otherwise!)

### ISSUE THREAD

**Issue by voltagex** [ptitSeb/box86#54]
Game is free at https://sourceforge.net/projects/oarena/files/openarena-0.8.8.zip/download

Everything appears to work up until openAL is loaded

```
------ Initializing Sound ------
Loading "libopenal.so.1"...
Segmentation fault
```
*However*, if you run with `./openarena.i386 +set s_useOpenAL 0` the game loads just fine! I have no way to take screenshots right now, sorry.

**Comment by ptitSeb** [comment]
Interesting.

Can you run with "BOX86_LOG=DEBUG" and see if it crash in an OpenAL call?

**Comment by voltagex** [comment]
There are 75 calls to

```
4156|0x80b01ac: Calling SDL_LoadFunction (A9037840, 081EA19A, AAA2239C...) => return 0xAAA22440
```
(but with different parameters/returns)

This zip will unpack to 90 megabytes.

[log1.zip](https://github.com/ptitSeb/box86/files/3613500/log1.zip)

**Comment by voltagex** [comment]
![2019-09-15-172056_644x512_scrot](https://user-images.githubusercontent.com/159567/64918195-6775dd80-d7de-11e9-9830-6645e6b5e5be.png)
![2019-09-15-172204_644x512_scrot](https://user-images.githubusercontent.com/159567/64918196-6775dd80-d7de-11e9-99a3-61c2b77bebd2.png)
![2019-09-15-172230_644x512_scrot](https://user-images.githubusercontent.com/159567/64918197-680e7400-d7de-11e9-8c50-2dfdadd83653.png)
![2019-09-15-171935_644x512_scrot](https://user-images.githubusercontent.com/159567/64918198-680e7400-d7de-11e9-9e61-bacfb637520c.png)
![2019-09-15-172013_644x512_scrot](https://user-images.githubusercontent.com/159567/64918199-680e7400-d7de-11e9-88a6-3815d845efdc.png)

Screenshots while I'm here.

**Comment by ptitSeb** [comment]
Oh, SDL 2 provides dlopen / dlsym functionnality with SDL_LoadObject / SDL_LoadFunction ! I completly overlooked that.
I'll do some something about that now.

**Comment by ptitSeb** [comment]
Ok, this commit 5d6a4fc068ae3b89bb26cf6f81f0d0db2f83e92c should fix the openal issue.

**Comment by voltagex** [comment]
Success!

```
------ Initializing Sound ------
Loading "libopenal.so.1"...
Using native(wrapped) libopenal.so.1
Allocated 96 sources.
OpenAL default capture device is 'ALSA Default'
AL lib: (EE) ALCcaptureAlsa_open: Could not open capture device 'default': No such file or directory
OpenAL capture device failed to open.
OpenAL info:
  Vendor:     OpenAL Community
  Version:    1.1 ALSOFT 1.19.1
  Renderer:   OpenAL Soft
  AL Extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFTX_events AL_SOFTX_filter_gain_ex AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
  ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_output_limiter ALC_SOFT_pause_device
  Device:     OpenAL Soft
Available Devices:
OpenAL Soft
Sound initialization successful.
```

**Comment by ptitSeb** [comment]
We can close the issue?

**Comment by voltagex** [comment]
Yes, thanks for this!
