### ISSUE TITLE
wine-7.0-rc4 crash on box86 latest (using debian chroot on android)

### ISSUE THREAD

**Issue by sukualam** [ptitSeb/box86#544]
I just fresh setup box86 and latest wine on my chrooted debian, when i first boot (open explorer) 
it error,

 box86: dlls/ntdll/unix/virtual.c:1742: alloc_area_in_reserved_or_between_callback: Assertion `ROUND_ADDR(intersect_start, granularity_mask) == intersect_start' failed.
Aborted

In wine 6.1x it work normally, can open .exe, but on 7 it crash instantly.

Whats wrong sir? 

os: debian bullseye armhf (via Linux Deploy)
box86: (latest commit) https://github.com/ptitSeb/box86/commit/a7d803bc82481839f3ce369cc68c9656599e06b1
wine: wine staging i386 (wine-7.0-rc4)

**Comment by polyzium** [comment]
I'm having the same problem on an aarch64 multiarch Ubuntu 20.04 proot environment with some Wine versions. None of them work.
Some of them return a "bad address" error, some of them return the error described above.

**Comment by WheezyE** [comment]
Just curious, @sukualam , are you still getting these errors after a3d2443b7075267ea6f85892d3aecb6a2ac7124f that fixed some CrossOver wine stuff?

And @polyzium Are you using Termux installed from F-Droid - that sounds like an error I was getting in an older version of proot https://github.com/termux/proot/issues/213#issue-1105221028

**Comment by polyzium** [comment]
@WheezyE
> Are you using Termux installed from F-Droid - that sounds like an error I was getting in an older version of proot
Yes I am, are you saying I should update proot with pkg?

**Comment by WheezyE** [comment]
Yeah, try updating proot and proot-distro with pkg in Termux. You might also try re-installing your Ubuntu PRoot if that doesn't work (or a Debian PRoot - I got mine working in Debian)

**Comment by sukualam** [comment]
> Yeah, try updating proot and proot-distro with pkg in Termux. You might also try re-installing your Ubuntu PRoot if that doesn't work (or a Debian PRoot - I got mine working in Debian)

What about chroot environment (linux deploy) ?

**Comment by WheezyE** [comment]
@sukualam I'm not as familiar with chroot since I don't have a rooted device.  I think that PRoot is specifically made for Termux.  Have you tried the latest box86 update again?

I'll try to test out newer versions of wine on my PRoot/Termux/Android device when I get some more time, but I'm not sure how I can test chroot on Android yet.  I might be able to set up a chroot on RPi4 later though.

**Comment by sukualam** [comment]
I compile the latest box86 commit , then try running wine-7.0-stable (i386) and now its work normal.

Its on debian bullseye armhf chroot on android 10 (linux deploy).

**Comment by WheezyE** [comment]
I was able to update to wine-devel-7.1~bullseye~1 in PRoot and can confirm that it runs with at least box86 12cc43b

**Comment by sukualam** [comment]
Its good
