### ISSUE TITLE
Wine Error on Raspbian4 :The file '/home/pi/wine/bin/wine' belongs to no guest image and there is no default guest image.

### ISSUE THREAD

**Issue by 123ABCDF11345** [ptitSeb/box86#549]
**System Information:**
```Linux raspbian 5.10.74-Release-OPENFANS+20211021-v8 #1 SMP PREEMPT Thu Oct 21 20:53:24 CST 2021 aarch64 GNU/Linux```
It's a 64bit OS for raspbian,[link here](https://github.com/openfans-community-offical/Debian-Pi-Aarch64)
**Error Message**
When I finished installing by these code
```bash
git clone https://github.com/ptitSeb/box86
cd box86
mkdir build; cd build; cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j4
sudo make install
sudo systemctl restart systemd-binfmt
cd ~
wget https://twisteros.com/wine.tgz -O ~/wine.tgz
tar -xzvf ~/wine.tgz
rm ~/wine.tgz
echo -e '#!/bin/bash\nsetarch linux32 -L '"$HOME/wine/bin/wine "'"$@"' | sudo tee -a /usr/local/bin/wine >/dev/null
sudo ln -s ~/wine/bin/wineboot /usr/local/bin/wineboot
sudo ln -s ~/wine/bin/winecfg /usr/local/bin/winecfg
sudo ln -s ~/wine/bin/wineserver /usr/local/bin/wineserver
sudo chmod +x /usr/local/bin/wine /usr/local/bin/wineboot /usr/local/bin/winecfg /usr/local/bin/wineserver
```
Then I run```wine wineboot```
However,it reported
```
The file '/home/pi/wine/bin/wine' belongs to no guest image and there is no default guest image.
```
I've searched on Internet ,but I couldn't get any helpful message,what should I do?
Thanks.

**Comment by ptitSeb** [comment]
I think your are missing the "armhf" architecture.
Use `sudo dpkg --add-architecture armhf` and a `sudo apt update` to add it.
After that, you will need to add all the needed armhf library for wine. I don't have the list, but you can start with `sudo apt install libx11-6:armhf libpulse0:armhf libgl1-armhf libxi6-armhf libxinerama1-armhf libxrandr2:armhf libxrender1:armhf libxcb1:armhf libxcb-xfixes0:armhf libxcb-winput0:armhf`
and probably a few other, but you get the idea.

**Comment by 123ABCDF11345** [comment]
Thank so much for your help,I think I can solve this problem easily by your help
