### ISSUE TITLE
actions android builds no apk file

### ISSUE THREAD

**Issue by hwanghyunseo** [ptitSeb/box86#554]
please apk files on actions on arm. not 64bit.

**Comment by WheezyE** [comment]
You may want to check in with @io12 , who has been working on the Android builds. I believe the Android CI build file is still experimental

**Comment by io12** [comment]
Hi! It doesn't build a full APK by itself, just an executable file that can run on Android. You can use it in something like Termux to run programs compiled for x86 Android on ARM Android. If we figure out how to get Wine working well enough, then we can try to package Box86 and Wine into an APK. That's what I was trying to do with https://github.com/io12/WineBox86.apk, but it's still pretty far away from building a working APK.

**Comment by bbbruni** [comment]
@io12 
**WheezyE** tries to find a Android-compliant x86 wine build to run inside box86 (PlayOnLinux build of wine doesn't seem to work correctly in proot). See https://github.com/ptitSeb/box86/issues/523#issuecomment-1010154291

**Comment by Seas0** [comment]
Yep, currently the android version is only a binary for termux or something can direct run executables, rather than a full package, also it only emulate a bionic libc interface now so don't expect any x86 Linux executables running.

**Comment by ptitSeb** [comment]
I close the ticket, it's not clear enough, and there are other Android request anyway.
