### ISSUE TITLE
GoldSource Linux games crashing after a box86 update

### ISSUE THREAD

**Issue by Raezroth** [ptitSeb/box86#559]
So... Gold Source linux games have been crashing for idk how long now. The last revision I can recall it working on was the [v0.2.4 release](https://github.com/ptitSeb/box86/releases/tag/v0.2.4)  but after [Nov 23 commit](https://github.com/ptitSeb/box86/commit/27fd1d11b8f587a9e22495eaabfc131c6d0ca5cd), which was just an update to the compile readme, I am unsure.

Edit: Forgot to specify, since the latest  Steam Runtime update only your [latest commit](https://github.com/ptitSeb/box86/commit/e31e5c1a5b254404287afdb0143a94b8ff7fcd56) will launch Steam. Since the properties menu on steam is borked (for now) It is nearly impossible to launch only the game with a specific box86 build.

 I have forked the repo to shift through the commits to get more familiar with box86 and understand what happened.

 Could you by chance look into this as well, please? I've counted 6 gold source games affected by this. 

[steam.log](https://github.com/ptitSeb/box86/files/7915918/steam.log)

**Comment by WheezyE** [comment]
Hey there! Just to help us narrow down which areas are broken, would you be able to submit specific box86 commits that cause crashes with specific games? (For example, commit aabbcc123 crashes MyGame3 v1.5, using wine 6.1 on TwisterOS, RPi4(x GB) while commits before that don’t cause the crash. Box86log.txt included here) Or some box86 logs of the crashed games?

**Comment by WheezyE** [comment]
Just a bit more info: From your steam log, it looks like you’re trying to run half-life, but can you submit some output from something like `BOX86_LOG=1 box86 halflife.sh` or whatever string you use to launch half-life?

**Comment by Raezroth** [comment]
The steam log provided was from the original half life. I will do the best I can but I am still a noob. Will be back later tonight to work on it

**Comment by Raezroth** [comment]
I launched from steam mini games list

**Comment by WheezyE** [comment]
I'm not super sure where your game is installed, but you might try `BOX86_LOG=1 ~/.steam/steam/steamapps/common/Half-Life/./hl_linux` and see if that runs half life directly and gives you any box86 logging output

**Comment by Raezroth** [comment]
I have tried different ways of launching it. I found that the changes on Nov 30 have caused this regression. 

I added ptitSeb's dprintf fix to different commits so steam launches on them, I found that 11/29/2021 build (my fork of it with the steam patch https://github.com/Raezroth/box86/tree/GoldSrc-Working) is launching gold source games. LOG HERE: [hlworking.log](https://github.com/ptitSeb/box86/files/7919691/hlworking.log)


The build from 11/30/2021 (my fork with the steam patch https://github.com/Raezroth/box86/tree/Test) however does not launch gold source games. Same output as previous steam log provided

I will revert those commits in a different branch and hope it doesn't break any of the later commits. Again Total Noob.

**Comment by ptitSeb** [comment]
Mmmm, so elfloader changes? There are 3 commit on 30th of november. I assume the regression was with 4e2f50eee7f9de7227a6986ead1b88f18deb9b89 ?
And the fix from dec. 19th is not enough for GoldSrc?

**Comment by ptitSeb** [comment]
It should be fixed now, using latest version. Can you check?

**Comment by Raezroth** [comment]
Yes, It actually did, thank you!! I passed out working on this last night, to find it fixed after waking up. ptit, you a champ.

**Comment by Raezroth** [comment]
I am deleting my fork till I run into another issue needing testting and fixing
