### ISSUE TITLE
Support for Crossover Linux

### ISSUE THREAD

**Issue by gsdefender** [ptitSeb/box86#562]
As box86 successfully runs wine, I wanted to see if Crossover Linux runs.
I fetched latest git as of now and installed it on my Raspbian 11 (armhf, LXQT desktop environment).
It turns out that the installer depends on libcursesw5. I didn't have that package on my system so I installed it.
I then tried to re-run the installer, but unfortunately it bombs out:

`[REDACTED]@[REDACTED]:~/Downloads $ setarch linux32 -L ./install-crossover-21.1.0.bin` 
`Box86 with Dynarec v0.2.5 4510b499 built on Jan 29 2022 21:05:26`
`Error: Symbol gtk_box_new not found, cannot apply R_386_JMP_SLOT 0x2b1120ec (0x1e66) in /dev/shm/mojosetup-plugin yJPhkn`
`Error: Symbol gtk_button_box_new not found, cannot apply R_386_JMP_SLOT 0x2b1120f0 (0x1e76) in /dev/shm/mojosetup-plugin-yJPhkn`
`Error: Symbol gtk_box_new not found, cannot apply R_386_JMP_SLOT 0x2b1120ec (0x1e66) in /dev/shm/mojosetup-plugin-w9o7tU`
`Error: Symbol gtk_button_box_new not found, cannot apply R_386_JMP_SLOT 0x2b1120f0 (0x1e76) in /dev/shm/mojosetup-plugin-w9o7tU`

GTK+ is installed on my system. Actually, the installer is able to show a window (attached here).

![screen](https://user-images.githubusercontent.com/1480040/151677627-f239c070-cb70-4938-ba27-f023ba22df3d.jpg)

**Comment by ptitSeb** [comment]
There are a few gtk symbol missing. Maybe just adding them would be enough? I'll try to add them later.

**Comment by gsdefender** [comment]
Hi, your commit allows the installer to run. Some user caveats:

- If you are running an incompatible kernel (i am using a raspberry pi 3 and forgot to compile a 3g/1g), a generic error is shown (unable to  create bottle). Dig deeper into crossover logs to find the real error.
- Be sure to deselect "Install Linux packages" in CrossOver preferences or you won't be able to start the installation. Ignore warnings about missing packages.
- Installation is _extremely_ slow. Maybe you're better off with a Raspberry Pi 4.
