### ISSUE TITLE
trying to install steamcmd and i keep getting this error: Error: PltReolver:

### ISSUE THREAD

**Issue by aalprince334** [ptitSeb/box86#576]
I have no idea what is the problem I followed this guild, https://pimylifeup.com/raspberry-pi-valheim-server/ :: and I ended up with this error 
my system is::
**No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal**
--
![Screenshot 2022-02-19 135930](https://user-images.githubusercontent.com/28888453/154799972-5db85977-32f1-4e67-aa54-252eb92d37ad.png)
CPU ARM64**

root@instance-20220219-1232:/home/steamcmd# ./steamcmd.sh
Box86 with Dynarec v0.2.2 bedacef6 built on Feb 19 2022 10:56:31
Redirecting stderr to '/root/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 53847 KB)...
[  0%] Downloading update (3298 of 53847 KB)...
[  6%] Downloading update (6904 of 53847 KB)...
[ 12%] Downloading update (9649 of 53847 KB)...
[ 17%] Downloading update (12132 of 53847 KB)...
[ 22%] Downloading update (14603 of 53847 KB)...
[ 27%] Downloading update (17104 of 53847 KB)...
[ 31%] Downloading update (19613 of 53847 KB)...
[ 36%] Downloading update (22410 of 53847 KB)...
[ 41%] Downloading update (24893 of 53847 KB)...
[ 46%] Downloading update (27375 of 53847 KB)...
[ 50%] Downloading update (29860 of 53847 KB)...
[ 55%] Downloading update (32334 of 53847 KB)...
[ 60%] Downloading update (35039 of 53847 KB)...
[ 65%] Downloading update (36311 of 53847 KB)...
[ 67%] Downloading update (37589 of 53847 KB)...
[ 69%] Downloading update (38963 of 53847 KB)...
[ 72%] Downloading update (40187 of 53847 KB)...
[ 74%] Downloading update (41490 of 53847 KB)...
[ 77%] Downloading update (42724 of 53847 KB)...
[ 79%] Downloading update (44061 of 53847 KB)...
[ 81%] Downloading update (45311 of 53847 KB)...
[ 84%] Downloading update (46535 of 53847 KB)...
[ 86%] Downloading update (47754 of 53847 KB)...
[ 88%] Downloading update (49103 of 53847 KB)...
[ 91%] Downloading update (50343 of 53847 KB)...
[ 93%] Downloading update (51577 of 53847 KB)...
[ 95%] Downloading update (52818 of 53847 KB)...
[ 98%] Downloading update (53847 of 53847 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
Box86 with Dynarec v0.2.2 bedacef6 built on Feb 19 2022 10:56:31
Error: PltReolver: Symbol __dprintf_chk(__dprintf_chk@GLIBC_2.8) not found, cannot apply R_386_JMP_SLOT @0xf77c8bdc (0xf71e0b26) in /home/steamcmd/linux32/steamcmd

**Comment by ptitSeb** [comment]
you are using an oold version of box86 (0.2.2), you should update to latest version, it should work there.

**Comment by aalprince334** [comment]
I did that and upgrade it to version 0.2.4 and still : 
![image](https://user-images.githubusercontent.com/28888453/154802372-31d235fc-8fa9-4ddd-ba7b-279fa5ca77da.png)

**Comment by ptitSeb** [comment]
I think you need to use current master. I have pushed the next stable yet.

**Comment by aalprince334** [comment]
> I think you need to use current master. I have pushed the next stable yet.

You mean the master branch right??

**Comment by ptitSeb** [comment]
Yep :)

**Comment by aalprince334** [comment]
> Yep :)

trying it rn.. finger cross 😥🤞

**Comment by aalprince334** [comment]
> I think you need to use current master. I have pushed the next stable yet.

working like a charm thank you so much for the help and the quick response ❤

**Comment by otomay** [comment]
Hey @aalprince334 are you using a oracle cloud instance? (it seems bc the pcname) If yes, can you point me a guide or smt about how you install the box86 and get steamcmd to run?

I'm using with chroot, but steamcmd doesn't work \:
