### ISSUE TITLE
The bug is back (wine-7.3 Staging) on debian 11 armhf chroot

### ISSUE THREAD

**Issue by sukualam** [ptitSeb/box86#580]
im using the latest commit https://github.com/ptitSeb/box86/commit/642bb357d38fc6deb59b98bcf6b312693e86646a , and running wine 7.3 staging on debian 11 armhf chroot, the crash is back (previosly was solved , like this https://github.com/ptitSeb/box86/issues/544)

wine: created the configuration directory '/home/lad/.wine'
box86: dlls/ntdll/unix/virtual.c:1742: alloc_area_in_reserved_or_between_callback: Assertion `ROUND_ADDR(intersect_start, granularity_mask) == intersect_start' failed.
0024:err:environ:run_wineboot failed to start wineboot c00000e5
wine: could not load kernel32.dll, status c0000135

**Comment by Heasterian** [comment]
It was not fixed, just some Wine builds don't have this issue (it don't really depends on version as I has two Wine 7.0 staging versions and one of them was working fine when other was crashing). Try to find Wine build on other websites that will work. I recommend Proton-GE builds, playonlinux or official ones from Wine.

**Comment by sukualam** [comment]
> It was not fixed, just some Wine builds don't have this issue (it don't really depends on version as I has two Wine 7.0 staging versions and one of them was working fine when other was crashing). Try to find Wine build on other websites that will work. I recommend Proton-GE builds, playonlinux or official ones from Wine.

i using wine from official website.

wine 7 stable work normally. but when using latest wine , always crash...

**Comment by sukualam** [comment]
on wine 7 (box86) btw how to fix control panel  when i open explorer > control panel > the add/remove program not show after i click (wine 6 just work normal)

**Comment by ptitSeb** [comment]
I have update box86 (and box64). It should work now. Please test and close the ticket.

**Comment by sukualam** [comment]
it works now..
