### ISSUE TITLE
can't install on os64 bit raspberry pi4

### ISSUE THREAD

**Issue by darkyng** [ptitSeb/box86#581]
pi@raspberrypi:~/box86/build $ cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/box86/build
pi@raspberrypi:~/box86/build $ make -j2
[  0%] Building C object CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o
[  0%] Built target WRAPPERS
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
cc: error: unrecognized command-line option ‘-mfpu=neon-fp-armv8’
cc: error: unrecognized command-line option ‘-mfloat-abi=hard’
cc: error: unrecognized command-line option ‘-marm’
make[2]: *** [CMakeFiles/dynarec_arm.dir/build.make:82: CMakeFiles/dynarec_arm.dir/src/dynarec/dynablock.c.o] Errore 1
make[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/dynarec_arm.dir/all] Errore 2
make[1]: *** Attesa per i processi non terminati....
[  0%] Built target PRINTER
make: *** [Makefile:160: all] Errore 2

please help thanks

**Comment by ptitSeb** [comment]
Please, read COMPILE.md, and also README.md, it's already all detailled there.
