### ISSUE TITLE
The sims 1

### ISSUE THREAD

**Issue by jackygoule** [ptitSeb/box86#584]
Hello i want to play the sims 1 on my pi400.
I try install with the version  download on lost treasure (auto on windows with all add ons)
The install with box86 and wine work but the game stop when it start .
I can see the launch and hear the music but stop launch.
I try with iso the sims without add on and the install don't work.
This game seem to hard for work on linux .

**Comment by jackygoule** [comment]
Ok , so i have to give it up?

**Comment by jackygoule** [comment]
Ok , so i have to give it up?
The sims 2 work on rasperry ?

**Comment by ptitSeb** [comment]
Yes, it's a Wine issue, not really a box86 one.
Sims 2 seems difficult to run too, but might work. I haven't tried.

I close this ticket, feel free to open new ticket if needed.
