### ISSUE TITLE
Why Dynarec disabled in actions-builds for Android?

### ISSUE THREAD

**Issue by CosineMath** [ptitSeb/box86#586]
I just downloaded the pre-built binary for ARM-Android from Github Actions. But I found that dynarec is disabled. Are there some technical reasons preventing us using dynarec on Android? Or just forget to include Android in configuration files?

**Comment by ptitSeb** [comment]
No specific reason. But not sure it actually build on Android because of some of the "signals.c" stuff.
Would be good to enable anyway and fix the eventual issues.
