### ISSUE TITLE
wineserver: lstat /tmp/.wine-1022: Invalid argument

### ISSUE THREAD

**Issue by sukualam** [ptitSeb/box86#587]
just build latest commit https://github.com/ptitSeb/box86/commit/298fe50dd190430271183445254eb470913efb11 and i somewhat trying to run wine-5.11 staging (i386) on chrooted debian 11 (armhf).

it fail to boot wine..

**Comment by ptitSeb** [comment]
I will need more detail about the error message and all...

**Comment by sukualam** [comment]
```
lad@localhost:~$ BOX86_LOG=1 wine explorer
Debug level is 1                                                                 Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096                                                                             Box86 with Dynarec v0.2.5 298fe50d built on Mar 12 2022 12:06:58
BOX86: Wine detected, WINEPRELOADRESERVE=""                                      BOX86_LD_LIBRARY_PATH: /home/lad/wine/opt/wine-staging/lib/
BOX86_PATH: /home/lad/wine/opt/wine-staging/bin/                                 Counted 20 Env var
Looking for wine                                                                 argv[1]="explorer"
Using native(wrapped) libdl.so.2                                                 Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/libwine.so.1
Using native(wrapped) libpthread.so.0                                            Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2                                              Using native(wrapped) librt.so.1
Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/wine/ntdll.so          Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Box86 with Dynarec v0.2.5 298fe50d built on Mar 12 2022 12:06:58                 BOX86: Wine detected, WINEPRELOADRESERVE=""
BOX86_LD_LIBRARY_PATH: /home/lad/wine/opt/wine-staging/lib/                      BOX86_PATH: /home/lad/wine/opt/wine-staging/bin/
Counted 21 Env var                                                               Looking for /home/lad/wine/opt/wine-staging/bin/wine
argv[1]="explorer"                                                               Using native(wrapped) libdl.so.2
Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/libwine.so.1           Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6                                                  Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1                                                 Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/wine/ntdll.so
Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/wine/ntdll.dll.so      Using native(wrapped) libm.so.6
Debug level is 1                                                                 Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096                                                                             Box86 with Dynarec v0.2.5 298fe50d built on Mar 12 2022 12:06:58
BOX86_LD_LIBRARY_PATH: /home/lad/wine/opt/wine-staging/lib/                      BOX86_PATH: /home/lad/wine/opt/wine-staging/bin/
Counted 21 Env var                                                               Looking for /home/lad/wine/opt/wine-staging/bin/wineserver
Using native(wrapped) libdl.so.2                                                 Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2                                              Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1                                                 wineserver: lstat /tmp/.wine-1022: Invalid argument
```

**Comment by sukualam** [comment]
lad@localhost:~$ BOX86_LOG=1 wine explorer
Debug level is 1                                                                 Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096                                                                             Box86 with Dynarec v0.2.5 298fe50d built on Mar 12 2022 12:06:58
BOX86: Wine detected, WINEPRELOADRESERVE=""                                      BOX86_LD_LIBRARY_PATH: /home/lad/wine/opt/wine-staging/lib/
BOX86_PATH: /home/lad/wine/opt/wine-staging/bin/                                 Counted 20 Env var
Looking for wine                                                                 argv[1]="explorer"
Using native(wrapped) libdl.so.2                                                 Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/libwine.so.1
Using native(wrapped) libpthread.so.0                                            Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2                                              Using native(wrapped) librt.so.1
Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/wine/ntdll.so          Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Box86 with Dynarec v0.2.5 298fe50d built on Mar 12 2022 12:06:58                 BOX86: Wine detected, WINEPRELOADRESERVE=""
BOX86_LD_LIBRARY_PATH: /home/lad/wine/opt/wine-staging/lib/                      BOX86_PATH: /home/lad/wine/opt/wine-staging/bin/
Counted 21 Env var                                                               Looking for /home/lad/wine/opt/wine-staging/bin/wine
argv[1]="explorer"                                                               Using native(wrapped) libdl.so.2
Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/libwine.so.1           Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6                                                  Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1                                                 Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/wine/ntdll.so
Using emulated /home/lad/wine/opt/wine-staging/bin/../lib/wine/ntdll.dll.so      Using native(wrapped) libm.so.6
Debug level is 1                                                                 Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096                                                                             Box86 with Dynarec v0.2.5 298fe50d built on Mar 12 2022 12:06:58
BOX86_LD_LIBRARY_PATH: /home/lad/wine/opt/wine-staging/lib/                      BOX86_PATH: /home/lad/wine/opt/wine-staging/bin/
Counted 21 Env var                                                               Looking for /home/lad/wine/opt/wine-staging/bin/wineserver
Using native(wrapped) libdl.so.2                                                 Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2                                              Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1                                                 wineserver: lstat /tmp/.wine-1022: Invalid argument

**Comment by sukualam** [comment]
![Screenshot_20220312-142944_Termux](https://user-images.githubusercontent.com/11465849/158008583-4e0dbbb1-3ba3-45b8-9e5f-9d37f0e30d48.png)

**Comment by ptitSeb** [comment]
And it was working before?

**Comment by sukualam** [comment]
I think yes, but im not sure, because i setup a new chroot, and try to build the latest box86.

Maybe i bit messing my system files?

**Comment by ptitSeb** [comment]
I haven't touched at `lstat` or any of those file access function lately. That's why I'm surprised. Also, most wine stagging version were not working before the latest changes. You can try to build older box86 version to be sure.

**Comment by sukualam** [comment]
I choose to build this commit (older) https://github.com/ptitSeb/box86/tree/eb7381457ab7874b9ae3860e1ea8fc10387c189f

and it run normal again.

**Comment by ptitSeb** [comment]
Oh, ok. So it's a regression :(
Can you do a bisect?

**Comment by sukualam** [comment]
![Screenshot_20220312-155948_Termux](https://user-images.githubusercontent.com/11465849/158011648-3f44f442-d39e-43c9-8d82-94dfa07e12b2.png)

maybe this log helps. This is the log when i running explorer normally.

**Comment by sukualam** [comment]
![Uploading Screenshot_20220312-160823_Termux.png…]()

**Comment by sukualam** [comment]
![Screenshot_20220312-160823_Termux](https://user-images.githubusercontent.com/11465849/158011773-6abf6650-6b46-4d42-b371-241a878769a1.png)

**Comment by sukualam** [comment]
If i use BOX86_LOG=2 (or 3) , the log is very long to write in here

**Comment by ptitSeb** [comment]
You have a good commit and a bad commit (current "master"), so a git bisec (like this: https://delicious-insights.com/en/posts/git-bisect/ ) would quickly find the commit that broke it.
I don't see anything that seem relevant in the logs.

**Comment by sukualam** [comment]
Oh i confused for this part. Is i must compile every commit to the newest?

is manually check can similar result like bisect?

**Comment by sukualam** [comment]
Ok let me try, i think this commit the problem since it from my report too https://github.com/ptitSeb/box86/commit/dfafce7f055e0aed616888ac17c8f32bd6609724

Actually i use commit just before that commit. 

I think need to make sure.

**Comment by sukualam** [comment]
Oh, it feel exhausting, i try build few commits, and go nowhere... i think i can't do this bisect thing.

btw, i try again the latest build, i notice it actually can run wine if .wine folder is already setup from previous commit that work. (if .wine folder is empty, it fail to run).

**Comment by sukualam** [comment]
Maybe i just use the newer wine version, like wine 6 or 7

**Comment by ptitSeb** [comment]
Using the `gisec bisect` it goes quite fast to find a regression. It's a short interval, so with like 4 compilation it should be done. Don't do random check, use the `git bisect` command. Like this (you are in the "build" folder of box86)
```
git checkout master
cd .. ; git bisect bad ; cd build
```
It will ask if you want to start bisecting. Select "Yes"
```
git checkout eb7381457ab7874b9ae3860e1ea8fc10387c189f
cd .. ; git bisect good ; cd build
```
Here, the bisect have already started, you can build
``` 
make -j2
```
And do whatever you need to install box86 (`sudo make install` ?)
and test the version
than mark the build as `good` or `bad`. For example, if good:
```
cd .. ; git bisect good ; cd build
```
And a new build is immediatly ready, just `make`, install, test and mark as good or bad until git bisect will give the exact first commit.
You can than stop the bisect process with
```
cd .. ; git bisect reset ; cd build
```

**Comment by sukualam** [comment]
I do testing builds

latest commit that still run fine is: https://github.com/ptitSeb/box86/commit/e75ca5d2ff278b0da90ce08cf20fe13d221d3392

and latest commit that broke it(actually after the that https://github.com/ptitSeb/box86/commit/e75ca5d2ff278b0da90ce08cf20fe13d221d3392 commit) is: https://github.com/ptitSeb/box86/commit/41521913d5b55e54e997d0e75a6d32d1c7edf404

**Comment by ptitSeb** [comment]
Ah, thanks for the bisec.
So that commit  still have a bug in it? I have to re-read the code, there must be a rare case I haven't thought about.

**Comment by sukualam** [comment]
this  https://github.com/ptitSeb/box86/commit/e75ca5d2ff278b0da90ce08cf20fe13d221d3392 commit is the latest that work no problem like previous commit (i delete the .wine folder too to make sure). It can setup wineprefix normally and run program normal like before (explorer.exe).

But after that (the commit after this) , it broken. I clear .wine folder again and run "wine explorer", then the error message is like this issue title.

**Comment by sukualam** [comment]
Actually it not far away from latest commit that has no this bug (just 3 commit before that)

**Comment by sukualam** [comment]
Or maybe i missing something?

**Comment by ptitSeb** [comment]
That' ok, you have identified the broken commit. I need to find the issue now.

**Comment by ptitSeb** [comment]
I couldn't reproduce your issue, but I did fix a few things. Is it working now with latest box86?

**Comment by sukualam** [comment]
![Screenshot_20220314-190516_AVNC](https://user-images.githubusercontent.com/11465849/158168781-0d96e453-baaa-4d20-8fcb-3670b91c865c.png)

It still broken

**Comment by sukualam** [comment]
I use the latest commit https://github.com/ptitSeb/box86/commit/0926c48aea8e1c2c64d6d8ebf3829dcc70dea06a

**Comment by ptitSeb** [comment]
Problem is, I don't reproduce it on my side, so I cannot debug.
Try to run with `BOX86_TRACE_FILE=stderr BOX86_LOG=1 BOX86_SHOWSEGV=1` to see more detail.

**Comment by sukualam** [comment]
I try this commit https://github.com/ptitSeb/box86/commit/4df12ee5ea0ace5e504d16893183cb725a9c54e8 and the broken is same as latest commit.


i use `BOX86_TRACE_FILE=stderr BOX86_LOG=1 BOX86_SHOWSEGV=1 ` but it seems not output relevant log (for this issue)

![IMG_20220314_193201](https://user-images.githubusercontent.com/11465849/158173217-e22119e5-1d62-45b7-b898-72eee2551e3d.jpg)

**Comment by ptitSeb** [comment]
It should works now, can you retry?

**Comment by sukualam** [comment]
Ok let me try

**Comment by sukualam** [comment]
```
lad@localhost:~$ DISPLAY=:0 wine explorer
Box86 with Dynarec v0.2.5 a1d370fc built on Mar 17 2022 18:40:13
Box86 with Dynarec v0.2.5 a1d370fc built on Mar 17 2022 18:40:13
wine: created the configuration directory '/home/lad/.wine'
Box86 with Dynarec v0.2.5 a1d370fc built on Mar 17 2022 18:40:13
err:virtual:virtual_alloc_first_teb wine: failed to map the shared user data: c0000018
0024:err:environ:run_wineboot failed to start wineboot c00000e5
Box86 with Dynarec v0.2.5 a1d370fc built on Mar 17 2022 18:40:13
003c:err:module:__wine_process_init failed to load L"C:\\windows\\system32\\wineboot.exe", error c0000018
0034:err:environ:run_wineboot failed to start wineboot c0000018
0034:err:module:__wine_process_init failed to load L"C:\\windows\\system32\\explorer.exe", error c0000018
```

Im using latest commit, and it now throw error like that. 

Is my setup wrong?

my 'wine' executable is just wrapper, the content is:
box86 wine "$@"

the 'wineboot' is:
box86 wine wineboot "$@"

the 'winecfg' is:
box86 wine winecfg "$@"

the 'wineserver' is
box86 wine wineserver "$@"

That 4 files i put on /usr/local/bin (i chmod +x too)

in my ~/.bashrc files, i add:
```
export BOX86_PATH=~/wine/opt/wine-staging/bin
export BOX86_PATH=~/wine/opt/wine-staging/lib
```

Maybe that setup broke something

**Comment by sukualam** [comment]
wine-5.11 staging

**Comment by sukualam** [comment]
I compile the latest commit, and it works now. heheh
