### ISSUE TITLE
cannot run wine on box86

### ISSUE THREAD

**Issue by edemark** [ptitSeb/box86#588]
Hi I get this error:
/wine/bin/wine: 1: Syntax error: "(" unexpected
I am trying to run wine (on box86). I have a lenovo chromebook duet so i am working in debian bullseye in crostini vm. Compiled Box86 using instruction for pi. It seems to work I can run Rochardx86 (though I get segfault entering on the first level but welcom screen, setting screen etc. works).
Followed the guide on installing wine and "installation" went on ok.
thanks

**Comment by edemark** [comment]
Hi I have just found this (already fixed) bug report so there is the answer I will try it out later today and will report back
https://bugs.chromium.org/p/chromium/issues/detail?id=1193426

**Comment by Triory** [comment]
> Hi I have just found this (already fixed) bug report so there is the answer I will try it out later today and will report back https://bugs.chromium.org/p/chromium/issues/detail?id=1193426

Did it end up working for you? I have tried using a privileged Container as mentioned in the bug report, but systemd-binfmt still wont start.

**Comment by edemark** [comment]
Hi yes sorry i should  have got back on the issue. No, it did not work for
me either.
:( it must be something related to running x86 in the virtual machine.
Mark

**Comment by Triory** [comment]
@theyseemebowlin Are you talking about Crostini or Crouton here? Because I don't understand where to run the commands, since the Crouton container doesn't have the privileges to mount that location.

**Comment by theyseemebowlin** [comment]
ah, I was talking about Crostini, sorry for the confusion

**Comment by theyseemebowlin** [comment]
now I just use the Linux beta terminal and use [this](https://github.com/NicoD-SBC/armbian-gaming) to help run wine instead, then grab the latest pre-compiled version of wine from [here](https://github.com/Kron4ek/Wine-Builds/releases), untar it, and rename it to wine.

**Comment by ptitSeb** [comment]
Bin-fmt integration is not dirrectly part of box86. So I will close this ticket.

Note that you can now run i386 bash with box86. That way, you can have a bash prompt directly in "x86 world", making the need for bin-fmt optionnal. You can have more details about that there: https://box86.org/2022/09/running-bash-with-box86-box64/
