### ISSUE TITLE
OlliOlli (Humble Bundle)

### ISSUE THREAD

**Issue by voltagex** [ptitSeb/box86#59]
Test environment: Ubuntu 19.04 x86_64 with multilib enabled. Noveau driver. Same results with software rendering.

```
warning: Corrupted shared library list: 0xa82e6e80 != 0x0
Using native(wrapped) libpng12.so.0
IMG_LoadPNG_RW failed!
Loading keys icons: 0

Thread 1 "box86" received signal SIGSEGV, Segmentation fault.
Run (emu=0xa8113d10) at /usr/src/box86/src/emu/x86run.c:629
629     /usr/src/box86/src/emu/x86run.c: No such file or directory.
(gdb) bt
#0  Run (emu=0xa8113d10) at /usr/src/box86/src/emu/x86run.c:629
#1  0xa8028dae in main (argc=<optimised out>, argv=<optimised out>, env=<optimised out>) at /usr/src/box86/src/main.c:450
```

I installed libudev1:i386 but I still get the following log:
[log.txt](https://github.com/ptitSeb/box86/files/3613793/log.txt)

**Comment by ptitSeb** [comment]
I'm guessing the game should behave better now. Can you retry with latest box86?

**Comment by voltagex** [comment]
Running the game with call to the p

```
pi@raspberrypi:~/Games/linux32 $ box86 linux32
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 47 Env var
Looking for linux32
Using native(wrapped) libGL.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libopenal.so.1
Using emulated libphysfs.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Error loading needed lib: "libstdc++.so.6"
Error: loading needed libs in elf ./linux32
```


Downloaded and extracted the .so from http://ftp.au.debian.org/debian/pool/main/g/gcc-8/libstdc++6_8.3.0-6_i386.deb

then the error was `Error loading needed lib: "libgcc_s.so.1"`, which I downloaded from http://ftp.au.debian.org/debian/pool/main/g/gcc-8/libgcc1_8.3.0-6_i386.deb

The game runs on the Pi4, a little bit slowly at 1080p but the only other thing I can see is some warnings - 
`Warning: call to partially implemented dl_iterate_phdr(0xb5694d90, 0xb6563ea8)`


Thanks!

**Comment by ptitSeb** [comment]
You know those 2 libs are now in the box86 repo? Look inside `x86lib`...

So it's working :), we can close the ticket.
