### ISSUE TITLE
cannot run hterm

### ISSUE THREAD

**Issue by Laserlicht** [ptitSeb/box86#590]
hterm (linux 32bit) don't want to start (on raspberry pi 4) 😐

https://www.der-hammer.info/pages/terminal.html

Error:

`Box86 with Dynarec v0.2.5 60078852 built on Feb  6 2022 00:07:26

Error: Global Symbol gtk_major_version not found, cannot apply R_386_GLOB_DAT @0xb6b24eb4 ((nil)) in ./hterm

Error: Global Symbol gtk_micro_version not found, cannot apply R_386_GLOB_DAT @0xb6b24f80 ((nil)) in ./hterm

Error: Global Symbol gtk_minor_version not found, cannot apply R_386_GLOB_DAT @0xb6b24f98 ((nil)) in ./hterm

Error: PltResolver: Symbol gtk_hpaned_new(ver 0: gtk_hpaned_new) not found, cannot apply R_386_JMP_SLOT 0xb6b242ec (0xb65b6616) in ./hterm`

**Comment by ptitSeb** [comment]
I have the program starting now. Note that some option menu still make it crashes.
Those issue doesn't happens when using the 64bits version on box64. Not sure If I'll be able to fix them soon (or at all), so if you can, I suggest you use the 64bits version instead.
