### ISSUE TITLE
CTD regression in Age of Empires 2 (w/bisect)

### ISSUE THREAD

**Issue by MamiyaOtaru** [ptitSeb/box86#591]
Trying to create a multiplayer game (multiplayer button, select local LAN TP/IP connection, create button) crashes.  It goes to the 'creating: please wait 15 seconds" screen, then crashes to desktop.

Git bisect says the first bad commit was https://github.com/ptitSeb/box86/commit/1717fffe8f5a3a7c67ccd6bc755ac5fc36ebba9b

output:
Box86 with Dynarec v0.2.5 c53f961e built on Mar 18 2022 17:54:17
Box86 with Dynarec v0.2.5 c53f961e built on Mar 18 2022 17:54:17
Box86 with Dynarec v0.2.5 c53f961e built on Mar 18 2022 17:54:17
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:system:SystemParametersInfoW Unimplemented action: 110 (SPI_GETSHOWIMEUI)
0024:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Broadcom". Returning HW_VENDOR_NVIDIA.
0024:fixme:d3d:wined3d_guess_card_vendor Received unrecognized GL_VENDOR "Broadcom". Returning HW_VENDOR_NVIDIA.
00d4:fixme:d3d_shader:glsl_blitter_upload_palette P8 texture loaded without a palette.
0024:fixme:system:SystemParametersInfoW Unimplemented action: 111 (SPI_SETSHOWIMEUI)
0100:fixme:winmm:MXD_GetControlDetails What should the sw-side mixer controls map to?
0100:fixme:winmm:MXD_SetControlDetails What should the sw-side mixer controls map to?
0100:fixme:winmm:MXD_SetControlDetails What should the sw-side mixer controls map to?
0100:fixme:winmm:MXD_SetControlDetails What should the sw-side mixer controls map to?
Box86 with Dynarec v0.2.5 c53f961e built on Mar 18 2022 17:54:17
Box86 with Dynarec v0.2.5 c53f961e built on Mar 18 2022 17:54:17
warning: my_XCreateIC's vasize (3) is too large, need create new call case!
free(): invalid next size (fast)
wine: Assertion failed at address 7BC7C5C0 (thread 0024), starting debugger...
Box86 with Dynarec v0.2.5 c53f961e built on Mar 18 2022 17:54:17
winedbg detected, not launching it!
0024:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 32 640" (1359)
Read the Wine Developers Guide on how to set up winedbg or another debugger

**Comment by ptitSeb** [comment]
It should be fixed now, can you test?

**Comment by MamiyaOtaru** [comment]
it's fixed :)
