### ISSUE TITLE
winetricks in aarch64 chroot fails to call wine

### ISSUE THREAD

**Issue by iamSlightlyWind** [ptitSeb/box86#599]
My chroot:
* Debian 11 Armhf
* Compiled box86 from source
* Wine binary from PlayonLinux: [https://www.playonlinux.com/wine/binaries/phoenicis/upstream-linux-x86/PlayOnLinux-wine-7.4-upstream-linux-x86.tar.gz](https://www.playonlinux.com/wine/binaries/phoenicis/upstream-linux-x86/PlayOnLinux-wine-7.4-upstream-linux-x86.tar.gz)
* [winetricks from source](https://github.com/Winetricks/winetricks/blob/master/src/winetricks)
 
wine runs fine with box86, but running `winetricks` returns:

```
------------------------------------------------------
warning: Your version of wine  is no longer supported upstream. You should upgrade to 5.x
------------------------------------------------------
Executing mkdir -p /home/slightlywind
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 24
drwxr-xr-x.  6 slightlywind slightlywind 4096 Mar 30 12:46 .
drwxr-xr-x.  4 slightlywind slightlywind 4096 Mar 30 12:51 ..
drwxr-xr-x.  6 slightlywind slightlywind 4096 Mar 30 12:46 Program Files
drwxr-xr-x.  3 slightlywind slightlywind 4096 Mar 30 12:46 ProgramData
drwxr-xr-x.  4 slightlywind slightlywind 4096 Mar 30 12:46 users
drwxr-xr-x. 19 slightlywind slightlywind 4096 Mar 30 12:46 windows

Registry info:
/home/slightlywind/.wine/system.reg:#arch=win32
/home/slightlywind/.wine/user.reg:#arch=win32
/home/slightlywind/.wine/userdef.reg:#arch=win32
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "/usr/local/bin/winetricks: 3507: wine: Exec format error"
```

```
"/usr/local/bin/winetricks: 3507: wine: Exec format error"
```
Seems like winetricks is calling wine without box86. I can't find a similar issues and it appears that other people's setup (though most prob not a chroot) works fine. If anyone have a fix for this, please let me know. In the mean time, I guess I will try to change all the call from winetricks script to box86 and see how that turns out to.

**Comment by ptitSeb** [comment]
That's a binfmt integration issue (so x86 binary are automatically using box86 to run). Not sure how you can integrate binfmt onchroot. It should be possible but there might be a trick to it. I don't have chroot experience, so I cannot help on this subject.

**Comment by iamSlightlyWind** [comment]
Thanks, now I know what to look for

**Comment by Heasterian** [comment]
@iamSlightlyWind  You need to put box86 binfmt.d config on host and restart binfmt.d on host. Than it should work.

**Comment by iamSlightlyWind** [comment]
Thanks. Unfortunately, I'm still in the process of trying to get my kernel booting, rather than actually implementing binfmt or configuring binfmt yet.

**Comment by ptitSeb** [comment]
I'm closing this ticket, as bin-fmt issue are out of scope.

Note that you can run i386 bash with box86, to workaround lack of binfmt. See here for details: https://box86.org/2022/09/running-bash-with-box86-box64/
