### ISSUE TITLE
Error while launching Processing 3.5.3 x86 32 bit using box86

### ISSUE THREAD

**Issue by JerboaWings** [ptitSeb/box86#607]
I am trying to run the x86-32bit linux version of processing3.5.3 using box86 (the arm version wont work for my project) but when i run it it says: Box86 with Dynarec v0.2.5 dc461d4d built on Apr  3 2022 00:07:32
Error: Global Symbol collector_func_load not found, cannot apply R_386_GLOB_DAT @0xb569dff4 ((nil)) in /home/pi/processing-3.5.3/java/lib/i386/server/libjvm.so
Error: PltResolver: Symbol XDefaultVisualOfScreen(ver 0: XDefaultVisualOfScreen) not found, cannot apply R_386_JMP_SLOT 0xb40f616c (0xb4097546) in /home/pi/processing-3.5.3/java/lib/i386/libsplashscreen.so
how can i fix this?

**Comment by ptitSeb** [comment]
The function has been added, you can update and try again

**Comment by ptitSeb** [comment]
@JerboaWings can this ticket be closed now?
