### ISSUE TITLE
Wine cannot run. How to solve it?

### ISSUE THREAD

**Issue by Liu-Peiming** [ptitSeb/box86#608]
**I installed wine according to the X86WINE.md documentation, but the following information appears when running the wine wineboot command:**
bash: /usr/local/bin/wine: There is no such file or directory
**How to solve it?**

**Comment by ptitSeb** [comment]
Something has gone wrong it seems
Can you do
`file /usr/local/bin/wine`
and copy/paste the result?

**Comment by Liu-Peiming** [comment]
> 

No, I just ran the "sudo ln - S ~/wine/bin/wine  /usr/local/bin/wine" command.

**Comment by ptitSeb** [comment]
I was asking you tu run that command to check what's going on.

Also, in the line you paste `sudo ln - s ~/wine/bin/wine /usr/local/bin/wine` there is a space between `-` and `s` that should not be there: `sudo ln -s ~/wine/bin/wine /usr/local/bin/wine`

**Comment by Liu-Peiming** [comment]
> I was asking you tu run that command to check what's going on.
> 
> Also, in the line you paste `sudo ln - s ~/wine/bin/wine /usr/local/bin/wine` there is a space between `-` and `s` that should not be there: `sudo ln -s ~/wine/bin/wine /usr/local/bin/wine`

Sorry, I typed it wrong. There is no space between "-" and "s".
But when I run this command, I get the following message: 
unable to create symbolic link: / usr/local/bin/wine already exists.

**Comment by ptitSeb** [comment]
Ok, than what about this one: `file /usr/local/bin/wine` that I asked initialy?

**Comment by Liu-Peiming** [comment]
> 

/usr/local/bin/wine: symbolic link to /home/pi/wine/bin/wine

**Comment by calculatortamer** [comment]
try installing libc for armhf

sudo apt install libc6:armhf
