### ISSUE TITLE
Running PAC-Man World 2 on wine returns an unimplemented OPCODE Error.

### ISSUE THREAD

**Issue by comradeblack** [ptitSeb/box86#619]
I'm running PAC-Man world 2 on my pi 400 with 4GB ram. it works fine until the level starts and then it crashes saying:

5898|0x10001384: Unimplemented Opcode (5C) 66 3E C7 46 4E FF FF 3E
6029|0x64f8e003: Unimplemented Opcode (F8) 64 60 CB F8 64 00 00 00
6030|0x64f8e003: Unimplemented Opcode (F8) 64 60 CB F8 64 00 00 00
6029|0x64f8e003: Unimplemented Opcode (F8) 64 60 CB F8 64 00 00 00
6029|0x64f8e003: Unimplemented Opcode (F8) 64 60 CB F8 64 00 00 00
6029|0x64f8e003: Unimplemented Opcode (F8) 64 60 CB F8 64 00 00 00
6217|0x64f8e003: Unimplemented Opcode (F8) 64 60 CB F8 64 00 00 00

if you run it with dynarec off it says

3778|0x10001384: Unimplemented Opcode (5C) 66 3E C7 46 4E FF FF 3E

if you want to investigate for yourself, I got it from here since it is abandonware: [https://archive.org/details/pac-man-world-2-usa-pc-no-install-drm-free](url)

Thanks in advance.

**Comment by ptitSeb** [comment]
Is it fixed now?
