### ISSUE TITLE
Crashes on startup after installing box86

### ISSUE THREAD

**Issue by KingCanute92** [ptitSeb/box86#626]
I discovered this and it's compatibility with the Raspberry Pi. I have a Raspberry Pi 400 and I followed the following website's guide:
[https://pimylifeup.com/raspberry-pi-x86/](url)

On the "Compiling the x86 Emulator on the Raspberry Pi" section on step 6 I had the error described in that second part and did "Sudo reboot". Once loaded back in, I did the command "sudo systemctl restart systemd-binfmt" which crashed the OS to a black screen. It doesn't reboot and just powering off and back on only boots up for a bit before crashing again. I did two things differently that may have caused this but, I don't know enough about Raspbian OS to know why or even how to find out why this is happening.

First thing I did was install "v0.2.6" instead of the "v0.2.2" the site suggests. 
Second thing I did was followed instructions for a 32 bit OS. I did a quick search to locate what I'm using and it said to use "uname -m) which gave the 32 bit answer. Not sure if that matters but, otherwise I followed it closely.

Issue is now, I believe my Rasbian OS is toast considering I don't know how to fix it. I may have to start over which I'm not upset about. I recently found a 128 gig I'd like to throw on it so, I don't mind. Going forward however, I'd like to ask if you can tell me what I did wrong or tell me any tips on my next install.

**Comment by ptitSeb** [comment]
box86 by itself have no reason to "toast" your OS. I checked the tutorial and I see nothing wrong with it. Box has been installed on many system (including many Pi400) with no issue. There is nothing related to the boot process with box86 installation. Maybe, the issue can simply be the SDCard that is failing?

Also, on your Pi/400, if you are willing to use RPiOS 64bits, you can follow this article I wrote some time ago: https://box86.org/2022/03/box86-box64-vs-qemu-vs-fex-vs-rosetta2/ , it contains instructions on how to install box86+box64+wine, and while the instruction is for ubuntu os, it can be applied to rpios 64bits with no issue.

**Comment by KingCanute92** [comment]
I was using the SD card that came with the $100 kit so, it's possible. I don't understand why they didn't have 64 bit on it by default. However, I'm not equipped currently with a SD card reader. So I'll have to try this later but, I will check it out when I pick up a card reader hopefully Friday. Thanks for helping anyways.
