### ISSUE TITLE
LibSDL2 error when trying to start SteamCMD  

### ISSUE THREAD

**Issue by Guztaver** [ptitSeb/box86#629]
When i try to start libSDL2 on my Oracle VPS ARM, i recive that error:
> Error initializing native libSDL2-2.0.so.0 (last dlerror is libSDL2-2.0.so.0: cannot open shared object file: No such file or directory)
Error initializing native libasound.so.2 (last dlerror is libasound.so.2: cannot open shared object file: No such file or directory)
Error initializing native libpulse-simple.so.0 (last dlerror is libpulse-simple.so.0: cannot open shared object file: No such file or directory)

But that 3 are installed in my system, and i don't found anything to solve that!

---
Box86 Verison: v0.2.3 3a7cc57f from PPA
System: Ubuntu 20.04.4 LTS 
CPU: Ampare A1
RAM: 94 GiB

**Comment by ptitSeb** [comment]
did you install the `armhf` ones? or just the `aarch64`

**Comment by Nostradanus** [comment]
`sudo apt-get install libsdl2-dev:armhf` or whatever else dependencies are missing.

**Comment by Guztaver** [comment]
> did you install the `armhf` ones? or just the `aarch64`

I just installed the `aarch64` one, don't know about the `armf`! Sorry for that, i never used ARM computer before.
Now work like a charm!

Again, thanks for this awesome project!!!
