### ISSUE TITLE
System crash when using HDMI audio on Odroid N2 and N2+ 

### ISSUE THREAD

**Issue by Mzed3D** [ptitSeb/box86#635]
Hi ptitSeb!
I have an issue with the HDMI audio output both on my N2 and my N2+ boards. The system freezes when using HDMI audio output with wine games. Everything works fine if I output audio using bluetooth headphones and the issue doesn't happen with native linux games, so it's something specific to box86 - wine. I use armbian Jammy 22.05 and I've already written about this on the armbian n2 forum. I'm trying to understand what could cause this. Do you have any idea? Thanks!

**Comment by ptitSeb** [comment]
Hi,
I don't see why it would be a box86 specific issue. But it can be an issue with pulseaudio on 32bits armhf subsystem (or alsa). Native linux games are probably aarch64 on your system, so the test is not necessarily the good one (you might need to install some games with ':armhf' in `apt install` to get the 32bits version).

**Comment by Mzed3D** [comment]
There is also no issue with 32bit native games like LIMBO or Half-Life 2. They run fine with HDMI audio output. So is something related to wine I guess..

**Comment by ptitSeb** [comment]
then it's pulse vs alsa maybe? wine might use pulse, while limbo use alsa (or sdl2-> alsa)

**Comment by Mzed3D** [comment]
I'll try to switch to alsa in wine, then.. But I'm not sure if I've already made this test. I'll tell you later

**Comment by Mzed3D** [comment]
Alsa didn't work either..

**Comment by ptitSeb** [comment]
Did you changed the version of wine your are using? Is it a regression with box86?

**Comment by Mzed3D** [comment]
I'm using wine 7.4 since when it has been released, I'm sure it was working before but I don't know when: I'm constantly recompiling box86 when there are new commits and I also like to keep wine updated.

**Comment by clort81** [comment]
Amlogic driver issue.  I have Vim3 Pro and can't use hdmi audio reliably either.  Not box86 issue.

**Comment by ptitSeb** [comment]
Oh, thanks for the information!
Maybe I can close the ticket then?

**Comment by Mzed3D** [comment]
Sure :)
