### ISSUE TITLE
Will box86/64 support android with root ?

### ISSUE THREAD

**Issue by ThieuMinh26** [ptitSeb/box86#638]

**Comment by ptitSeb** [comment]
Box86/64 are solution to translate x86/x86_64 Linux binary to arm/arm64 Linux machine.

Android is not "linux" enough by itself and needs a linux layer, like termux, to be able to run box86, and more importantly, the software ran through box.
There is no Linux -> Android transformation in box. It's not planned, but I would accept a PR about that.

**Comment by ptitSeb** [comment]
Also, seems a duplicate for #473

**Comment by ThieuMinh26** [comment]
> Box86/64 are solution to translate x86/x86_64 Linux binary to arm/arm64 Linux machine.
> 
> Android is not "linux" enough by itself and needs a linux layer, like termux, to be able to run box86, and more importantly, the software ran through box. There is no Linux -> Android transformation in box. It's not planned, but I would accept a PR about that.

so it cant run window program on android like exagear right ?

**Comment by ptitSeb** [comment]
Not directly. You need termux, and from there you can use wine/box86. This is not an android software.
