### ISSUE TITLE
Doesn't starting steam 

### ISSUE THREAD

**Issue by Votada** [ptitSeb/box86#639]
![IMG20220611033542](https://user-images.githubusercontent.com/107285595/173165615-2fadd569-0ff8-4c34-b021-07d676121d27.jpg)

**Comment by ptitSeb** [comment]
You need to install armhf x11 libs. start with `sudo app install libappindicator1:armhf` that will install a large number of needed libs.
Also, you are on a 64bits system, so can also build and install box64 to increase compatibility.

**Comment by Votada** [comment]
Install lib doesn't help

**Comment by ptitSeb** [comment]
yes it does.
The error you have is missing X11. You need libX11 for armhf.

**Comment by Votada** [comment]
I've got it

**Comment by Votada** [comment]
box64 installed. Same error

**Comment by ptitSeb** [comment]
did you install `libX11:armhf`? The switch (nvidia in general) doesn't have an armhf video driver, maybe that's the issue?

**Comment by Votada** [comment]
libx11-6 if be sure. I didn't find just libx11

**Comment by ptitSeb** [comment]
Well, I don't know, but you have x11 issue (in 32bits at least). It's not an issue with box86.
