### ISSUE TITLE
Issues on the Raspberry Pi 3B+

### ISSUE THREAD

**Issue by Stardust-kyun** [ptitSeb/box86#64]
I've been trying to get this working for a few days, and some friends with more experience coding have been helping me troubleshoot. We finally got to using the command, and now this issue pops up:
`Using default BOX86_LD_LIBRARY_PATH: ./:lib/
Using default BOX86_PATH: ./:bin/
Counted 57 Env var
Looking for /home/pi/Downloads/counter-strike-1-6.exe
Error: /home/pi/Downloads/counter-strike-1-6.exe is not an executable file`
This error has stumped us, and we have no idea where to go from here. Is there a fix for this?

**Comment by ptitSeb** [comment]
this is most likely a Windows program.
Box86 can only run Linux x86 program, sorry.

**Comment by voltagex** [comment]
@Stardust-kyun https://store.steampowered.com/app/10/CounterStrike/ lists Linux support, you'll need the Linux binary to try this.

**Comment by ptitSeb** [comment]
I close the issue, it seems irelevent. Feel free to re-open it if needed.
