### ISSUE TITLE
Symbol fstatat64/fstat64 not found

### ISSUE THREAD

**Issue by Mzed3D** [ptitSeb/box86#640]
Hi Seb! First of all, thanks for this morning commit! Did you impement fstatat64/fstat64? I compiled it and tried to run the latest version of wine (7.10) but still I got the same errors..
 
Box86 with Dynarec v0.2.7 367235db built on Jun 11 2022 16:26:44
Error: Symbol fstatat64 not found, cannot apply R_386_JMP_SLOT 0xf7490130 (0x74c6) in /home/mattia/wine/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol fstat64 not found, cannot apply R_386_JMP_SLOT 0xf7490268 (0x79a6) in /home/mattia/wine/bin/../lib/wine/i386-unix/ntdll.so
Box86 with Dynarec v0.2.7 367235db built on Jun 11 2022 16:26:44
Error: Symbol fstatat64 not found, cannot apply R_386_JMP_SLOT 0xf73f0130 (0x74c6) in /home/mattia/wine/bin/../lib/wine/i386-unix/ntdll.so
Error: Symbol fstat64 not found, cannot apply R_386_JMP_SLOT 0xf73f0268 (0x79a6) in /home/mattia/wine/bin/../lib/wine/i386-unix/ntdll.so

**Comment by ptitSeb** [comment]
I haven't wrapped those 2 yet. I'll do them soon.

**Comment by Mzed3D** [comment]
I recompiled it and tried again to launch wine 7.10 but it didn't work. It was the first time so it had to create a new wineprefix but it didn't. The output was just:

Box86 with Dynarec v0.2.7 734aa879 built on Jun 11 2022 21:29:55
Box86 with Dynarec v0.2.7 734aa879 built on Jun 11 2022 21:29:55

Here you can find a full log obtained with the command "BOX86_LOG=2 wine explorer" 
[box86log.txt](https://github.com/ptitSeb/box86/files/8884743/box86log.txt)

**Comment by Trass3r** [comment]
```

3537|0xf74ea695: Calling my_fstat64 (/usr/local/bin/box86) (00000002, F6ECFA20, 00000000...) => return 0x00000000
3537|0xf74eaae5: Calling my_stat64 (/usr/local/bin/box86) (F7546C38, F6ECFA80, 00000000...) =>3537|SIGSEGV @0x62997e94 (???(/usr/local/bin/box86/0x62997e94)) (x86pc=0x641f03fb/???:"???", esp=0xf6ecf9cc, stack=0xf66d1000:0xf6ed1000 own=(nil) fp=0xf6ecfaf8), for accessing 0x629d026c (code=2/prot=5), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0)
3537|Double SIGSEGV (code=2, pc=0x62997e94, addr=0x629d026c)!

**Comment by ptitSeb** [comment]
Is this issue still happening or can the ticket be closed. The functions have been added, so I think this ticket should be closed.

**Comment by ptitSeb** [comment]
closing, I waited long enough I think.
