### ISSUE TITLE
Steam won't open after running the install_steam.sh included in this repo

### ISSUE THREAD

**Issue by leem919** [ptitSeb/box86#656]
The installer script runs successfully, but then when I type "steam" and hit enter, I get this.
![unknown2](https://user-images.githubusercontent.com/8106607/178898752-c1ab2209-7ef7-4824-8afa-868982ca3f16.png)

**Comment by ptitSeb** [comment]
You need install `box86` also maybe.

**Comment by Itai-Nelken** [comment]
I don't think you're supposed to run steam as root.

**Comment by ptitSeb** [comment]
You are missing the "binfmt" integration. When launching steam, you should see box86 banner (that `Box86 with Dynarec v0.2.7 064eb21 built on Jul 13 2022 23:51:51` message). 
If you are on Termux, binfmt doesn't work to my knowledge, so steam cannot be run that way.
You need `binfmt` integration for box86 to be called by the system.

**Comment by ptitSeb** [comment]
Wine works fine with box86. Just don't use a version too recent. Somthing before 7.3 should be fine.

**Comment by ptitSeb** [comment]
d3d works fine, with correct driver.

**Comment by ptitSeb** [comment]
No, I have no experience with Termux.

I suppose the ticket can be closed now?

**Comment by ptitSeb** [comment]
Note that I have just pushed some changes in box86 so bash can run. Test is an i386 versionof `bash`in  `tests` folder: you can maybe try to use `box86 ../tests/bash -c /usr/local/bin/steam` to run steam. It migh work without binfmt integration. Or not, I have no idea...
