### ISSUE TITLE
Fallout 3 black sreen

### ISSUE THREAD

**Issue by olevenets2** [ptitSeb/box86#664]
Hello, Fallout 3 (Game of the Year Edition) only black screen after starting a new game. What I see in the log:

```
003f:err:d3d:wined3d_debug_callback 0x14a8af20: "GL_INVALID_VALUE in glColorMaski(buf=7)".
003f:err:d3d:wined3d_debug_callback 0x14a8af20: "GL_INVALID_VALUE in glDisableIndexed(index=7)".
0032:err:ntdll:RtlpWaitForCriticalSection section 0x1dd5394 "?" wait timed out in thread 0032, blocked by 0044, retrying (60 sec)
0032:err:ntdll:RtlpWaitForCriticalSection section 0x1dd5394 "?" wait timed out in thread 0032, blocked by 0044, retrying (60 sec)
```

Fixes?

**Comment by ptitSeb** [comment]
This is an hardware problem. Maybe you are using a Pi4? This kind of hardware only support 4 Buffers, and this games seems to use 8... Try to use updated mesa driver or mess with setup, but it's not a box issue, it's the GPU not capable of running this game.
