### ISSUE TITLE
SteamCMD not logging in

### ISSUE THREAD

**Issue by jackson-57** [ptitSeb/box86#665]
SteamCMD hangs upon logging in when running under box86.
```
Box86 with Dynarec v0.2.7 e9fcef3d built on Aug 17 2022 05:48:01
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1658944597
-- type 'quit' to exit --
Loading Steam API...OK

Steam>login anonymous

Connecting anonymously to Steam Public...
```
To reproduce the issue:
1. Follow the steps [here](https://developer.valvesoftware.com/wiki/SteamCMD) to download SteamCMD. I followed the manual instructions.
2. Run SteamCMD, let it download and extract updates, then when it gets stuck trying to launch SteamCMD, press ctrl+c and run SteamCMD again. I believe you have to do this twice. This seems to be another issue.
3. Run `login anonymous` when presented with the `Steam>` prompt.

I'm running box86 on an Oracle Cloud Ampere A1 VM, running Ubuntu 22.04 (build `2022.06.16-0`). I compiled box86 using the generic ARM command in the compilation instructions. My friend was also able to reproduce the issue using a SD845 phone.

Let me know if you need any other information. Thanks!

**Comment by Raezroth** [comment]
What Linux distro are you running???? I had this issue on Debian Bookworm. When I upgraded to Debian Sid/Experimental it started logging in again.

**Comment by jackson-57** [comment]
Interesting. I ended up making an x64 instance using the same build of Ubuntu (of course, different architecture) and SteamCMD did login properly. However, on the x64 instance I used apt to install SteamCMD instead of manually extracting the archive. Should I try uninstalling the apt package and manually extracting SteamCMD on the x64 instance to see if the same issue occurs?

**Comment by Raezroth** [comment]
What architectures where you using when it worked?

**Comment by jackson-57** [comment]
I should clarify, by x64 I mean amd64 (with multiarch enabled). SteamCMD worked there, but did not work on the arm64 instance using box86. Does that make more sense?

**Comment by Raezroth** [comment]
Try using Ubuntu Kinectic Kudu or Debian Sid

**Comment by Raezroth** [comment]
I have a guide here that sets up a Debian armhf container then makes it multiarch with arm64. It may help with some insight on running Box86/64 w/ steam. https://github.com/Raezroth/Linux-ARM-Gaming-Chroot

The packages in Ubuntu 22.04 are out of date compared to the packages targeted in the latest steam update. This issue essentially has nothing to do with Box86.

**Comment by jackson-57** [comment]
I'm not sure how the problem could be packages if it worked fine on the amd64 system (again, same build of Ubuntu). My friend tested with a Debian Sid chroot on arm64 with box86, and it didn't work there either. Besides, this issue is about SteamCMD and not Steam.

**Comment by mccleaner** [comment]
I had the same problem on 22.04, but it worked fine on 20.04 instead.

**Comment by ptitSeb** [comment]
Can this ticket be closed, it seems more like an issue related to Ubuntu 22.04 than box86.

**Comment by jackson-57** [comment]
It works fine using an x64 processor on 22.04, so I'm not sure if it's box64's fault or if it's 22.04 ARM's fault. I'd have to retest, because I haven't tried it recently.

**Comment by jackson-57** [comment]
I finally got around to testing a more modern of box86, and I can safely say this is resolved.
