### ISSUE TITLE
Steam missing symbol in arm64 chroot 

### ISSUE THREAD

**Issue by Raezroth** [ptitSeb/box86#668]
I am experimenting with an arm64 base for my chroot and ran into some missing symbols starting steam for the first time,
```
raezroth@danctnix:~$ MESA_GL_VERSION_OVERRIDE=3.2 PAN_MESA_DEBUG=gl3 steam +open steam://open/minigameslist
/home/raezroth/.local/share/Steam/steam.sh: line 124: VERSION_ID: unbound variable
/home/raezroth/.local/share/Steam/steam.sh: line 124: VERSION_ID: unbound variable
steam.sh[13990]: Running Steam on debian  64-bit
steam.sh[13990]: STEAM_RUNTIME is enabled by the user
setup.sh[14053]: Steam runtime environment up-to-date!
steam.sh[13990]: Can't find 'steam-runtime-check-requirements', continuing anyway
Box86 with Dynarec v0.2.3 3a7cc57f built on Jul  9 2021 17:31:35
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
[2022-09-05 08:55:32] Startup - updater built Nov 22 2021 22:06:59
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Looks like steam didn't shutdown cleanly, scheduling immediate update check
Error: PltReolver: Symbol pthread_rwlock_wrlock(ver 25: pthread_rwlock_wrlock@GLIBC_2.1) not found, cannot apply R_386_JMP_SLOT 0xf7a00f60 (0xf74309d6) in /home/raezroth/.local/share/Steam/ubuntu12_32/steam
Error: PltReolver: Symbol pthread_rwlock_wrlock(ver 25: pthread_rwlock_wrlock@GLIBC_2.1) not found, cannot apply R_386_JMP_SLOT 0xf7a00f60 (0xf74309d6) in /home/raezroth/.local/share/Steam/ubuntu12_32/steam
Error: PltReolver: Symbol pthread_rwlock_rdlock(ver 25: pthread_rwlock_rdlock@GLIBC_2.1) not found, cannot apply R_386_JMP_SLOT 0xf7a00f5c (0xf74309c6) in /home/raezroth/.local/share/Steam/ubuntu12_32/steam
```

**Comment by ptitSeb** [comment]
This version of box86 you are using is more than 1 year old. Please update, this symbol is wrapped.

**Comment by Raezroth** [comment]
lol that's  the binary i got from the repo. im compiling now

**Comment by ptitSeb** [comment]
what repo?

**Comment by Raezroth** [comment]
This one.

sudo wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -O /etc/apt/sources.list.d/box86.list
wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add -
sudo apt update && sudo apt install box86 -y

**Comment by Raezroth** [comment]
I was trying to streamline things in my chroot more. Though box86 has a hard time loading armhf libraries inside an arm64 based chroot, but with an armhf based chroot with arm64 added it loads the libraries fine. 

This isn't really an issue just something I noticed playing around

**Comment by Botspot** [comment]
> This one.
> 
> sudo wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -O /etc/apt/sources.list.d/box86.list wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add - sudo apt update && sudo apt install box86 -y

Strange. I also use Itai's box86 repo and it is updated every week for me.
