### ISSUE TITLE
RMS Express<->VARA: TCP connection issue in box86 >12/09/21

### ISSUE THREAD

**Issue by WheezyE** [ptitSeb/box86#673]
I've been using an older version of box86 to run RMS Express due to an issue with RMS Express not communicating to VARA over TCP correctly in any box86 builds after 12/09/21. I believe the error is due to a commit somewhere around a1aac43a-07166e59
```
12/10/21 (ed8e01ea) RMS Express talks to VARA using TCP
	*12/11/21 (a1aac43a) unrelated wine error/crash (happens in wine-devel-6.19 & wine-devel-7.1)
	*12/13/21 unrelated wine error/crash
	*12/14/21 unrelated wine error/crash
12/15/21 (07166e59) RMS Express does not talk to VARA using TCP
```

This is what RMS Express looks like when it's working with VARA (callsign KI7POL is in address bar, indicating VARA is able to be controlled by RMS Express):
![image](https://user-images.githubusercontent.com/29649598/190879546-026d23ae-d36b-435b-a990-5d97951e2f06.png)

And here's what RMS Express looks like when it's not working with VARA (callsign is not in address bar, VARA is not controlled by RMS Express - no audio plays through VARA):
![image](https://user-images.githubusercontent.com/29649598/190879584-e0c307e5-4ce0-4185-888f-23e48751fedd.png)

EDIT: I've tested many new versions of box86 but they all contain this error.

Some extra info here: https://github.com/WheezyE/Winelink/issues/41

Sorry this issue is so old. I was relying on an older box86 to run things and then took a break from the project for a long time, but there are some new features I want to implement with newer box86's now.

Thank you again!

**Comment by ptitSeb** [comment]
Is there a way for me to reproduce the issue?

**Comment by WheezyE** [comment]
There might be a couple easy ways to install things to get you to this point.
 - The easiest might be if I share my .wine folder with you privately just for testing purposes. I'll PM you a link.
 - The next easiest, might be to install wine-devel 7.1, then manually install [RMS Express](https://downloads.winlink.org/User%20Programs/Winlink_Express_install_1-7-1-0.zip) & [VARA HF](https://mega.nz/file/LDJQQTSY#X9bOfoI_s0kyFuwqe8zsVdohNEaB2dIGEDgWAIBqgTM) (source links: [1](https://downloads.winlink.org/User%20Programs/), [2](https://rosmodem.wordpress.com/)) with wine.  RMS Express requires wine-mono. VARA requires `BOX86_NOBANNER=1 winetricks -q vb6run pdh_nt4 win7 sound=alsa`. VARA has a post-install exe in its program directory that needs to be run (or else it will complain about OCX files).
 - Another way would be to use my [Winelink script](https://github.com/WheezyE/Winelink), but this installs an old box86 and reinstalls wine on Pi4 only.

For the last two options, you will need to create a free Winlink Express user account during the first run of RMS Express. You're also welcome to just use my user account for testing: I'll PM you the login/pass)

**Comment by ptitSeb** [comment]
It should be fixed now, you can try again with latest box86.

**Comment by WheezyE** [comment]
Brilliantly done! Confirmed working. Thank you very much!
