### ISSUE TITLE
Counterstrike 1.6, Half-Life, and Team Fortress Classic close after splash screen with "Error initializing native libnss3.so" (Orange Pi Zero 2)

### ISSUE THREAD

**Issue by patch6** [ptitSeb/box86#679]
The system is Ubuntu 22.04 on an Orange Pi Zero 2 (Arm64,) and the Box86 version is 0.2.7, compiled earlier today. 

After the program closes, "Error initializing native libnss3.so (last dlerror is libnss3.so: cannot open shared object file: No such file or directory)" shows in the terminal.

I've tried installing a number of libnss3.so-containing packages, but it isn't fixing this error.

I think this file is obsoleted somehow.

**Comment by ptitSeb** [comment]
if you don't find an suitable arm version of the lib from your repo (don't forget you need armhf version, so `sudo apt install libnss3:armhf`), you can use an i386 version of it, if it's simpler. Put the lib in the same folder as the binary and use `BOX86_EMULATED_LIBS=libnss3.so` env. var. to prefer the emulated version.

**Comment by patch6** [comment]
Thank you. Now it's a "Error initializing native libpng12.so.0". 

I tried installing some wayward package for it but it didn't take.

I guess it's time to play dependency wack-a-mole.

But I saw the splash screen, that was good. And I think the gpu drivers work on this.

**Comment by patch6** [comment]
Okay. I did do sudo make install but it didn't see the file there. I copied libpng12.so.0 to the game directory and did the BOX_EMULATED_LIBS bit for that, and that error doesn't pop up, but now it's crashing at "cannot dlopen <path to game dir>/chromehtml.so".

That error was appearing during the libnss3.so bit as well.

**Comment by ptitSeb** [comment]
chromehtml should be in game folder. It may be the lib or one of the dependancy taht cannot be found
use `BOX86_LOG=1` to have more details.

**Comment by patch6** [comment]
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libcups.so.2
Error loading needed lib libgcrypt.so.11
Error loading one of needed lib
Error initializing needed lib libcef.so
Error loading one of needed lib
Error initializing needed lib chromehtml.so
Error:Cannot dlopen("/home/orangepi/.local/share/Steam/steamapps/common/Half-Life/chromehtml.so"/0xf6eef400, 2)



libcef.so is in the game dir, but libgcrypt.so.11 is one of those elusive packages I can't find

I think that's the last one too

**Comment by ptitSeb** [comment]
yep, that's the one that is failing

(all thoses libs should also be found in the steam-runtime folder of a linux steam installation)

**Comment by patch6** [comment]
ok, am I looking for an armhf or an x86_64 version?

**Comment by ptitSeb** [comment]
i386 version. The ".11" version is not wrapped on box86.

**Comment by patch6** [comment]
Well, I had Team Fortress Classic running at 30 FPS, then after quit it just hung. But that's progress.

Now steam just gets stuck at "Looking for Updates."

**Comment by ptitSeb** [comment]
make sure you use the latest box86, some older versin did get stuck on steam

**Comment by patch6** [comment]
Deleting /home/*username*/.local/share/Steam/package fixes that.

But now I have a problem, where when I try to run Counterstrike 1.6 from within the menu, or from a different terminal, it does nothing.

I think it's a x86 / x64 problem? something like that

**Comment by ptitSeb** [comment]
what do you mean "nothing"? something should happens on the terminal.

**Comment by patch6** [comment]
orangepi@orangepizero2:~$ /home/orangepi/.local/share/Steam/steamapps/common/Half-Life/hl.sh -steam -game cstrike
orangepi@orangepizero2:~$ ldd /home/orangepi/.local/share/Steam/steamapps/common/Half-Life/hl_linux
	not a dynamic executable
orangepi@orangepizero2:~$ box86 /home/orangepi/.local/share/Steam/steamapps/common/Half-Life/hl_linux
Box86 with Dynarec v0.2.7 c8141c63 built on Sep 29 2022 13:20:29
Error: reading elf header of /home/orangepi/.local/share/Steam/steamapps/common/Half-Life/hl_linux, try to launch natively instead
orangepi@orangepizero2:~$

**Comment by ptitSeb** [comment]
you don't have box86 installed, or at least, the binfmt integration is not there, so box86 doesn't get called automatically when a x86 program is called.

Did you build box86 from source or are you using some prebuild / repo version?

**Comment by patch6** [comment]
I copied my box86 build from an earlier Ubuntu 22.04 OPi 2z install, didn't want to compile it again. I typed sudo make install in the build folder, but maybe that didn't do the job.

**Comment by ptitSeb** [comment]
is it a recent build?
anyway, "error reading ELF header" because you try to run a shell script, not a binary
recent version of box86 can run shell script using x86 bash, that can be loacated in the "tests" folder of box86 repo. You use "BOX86_BASH=/path/to/bash" and it will use the x86 verison of bash for shell script.
Alternatively, just restart the binfmt service with `sudo systemctl restart systemd-binfmt` if you have reboot your system since the "make install"

**Comment by patch6** [comment]
How do I use a pre-built Box86 (same OS version and chipset,) on a newly installed OS?

**Comment by ptitSeb** [comment]
> I just tried the systemd-binfmt restart and export BOX86_BASH=/bin/bash, then tried running cstrike from the command line, and nothing appeared on the terminal, including the box86 banner. So I guess box86 is installed wrong.

No! not your system bash, the x86 bash from box86 "tests" folder.



> How do I use a pre-built Box86 (same OS version and chipset,) on a newly installed OS?

there are ultiple steps done by "make install"
1. copy the box86 binary to "/usr/local/bin/"
2. copy all the "x86lib" libraries to "/usr/lib/i386-linux-gnu/"
3. register the binfmt integration copying the generated "system/box86.conf" file to "/etc/binfmt.d/"
