### ISSUE TITLE
Directx

### ISSUE THREAD

**Issue by symbios24** [ptitSeb/box86#680]
Hello there

Is it possible to include the full DirectX 9c pre-installed with box86 as the DirectX wrapper is not so accurate with many old games

Or if you cannot to put a quide how to install it in box86 ?

Thanks

**Comment by ptitSeb** [comment]
No, I cannot include that. it's too big and dependant on your wine prefix.
You can use winetricks to install stuff in wine, like  on regular x86 linux.

**Comment by symbios24** [comment]
I tried  that it failed

**Comment by ptitSeb** [comment]
I cannot include that, it's something for a wineprefix, for some specific use case, not something general.

Why winetrics failed? what was the message?

**Comment by symbios24** [comment]
I got various error messages
Is there a quide to install successful?

**Comment by ptitSeb** [comment]
there are some guide on youtube, and script to automate install (none of this by me). search for box86, there are quite a few already.

**Comment by symbios24** [comment]
I search a lot but could not find any script do you the link for it please?
Thanks

**Comment by ptitSeb** [comment]
Try this https://youtu.be/wrMPvGtxzC4
you can also find NicoD on discord in several server.

**Comment by paulwratt** [comment]
use `wine-tricks` after installing `wine`

Alternately use TwisterOS

**Comment by symbios24** [comment]
> use `wine-tricks` after installing `wine`
> 
> Alternately use TwisterOS

I tried that and getting errors in install

**Comment by ptitSeb** [comment]
I'm closing the ticket: DirectX cannot be shipped with box86.

If you have other error, please open a new ticket.
