### ISSUE TITLE
box86 compiling technical questions

### ISSUE THREAD

**Issue by WheezyE** [ptitSeb/box86#681]
Just wanted to ask a quick question about compiling box86 on aarch64 (RPi4) vs armhf (RPi4): Do both compilations result in the same file?

I know the compile steps are different (`-DRPI4=1` on armhf, `-DRPI4ARM64=1` on aarch64) and I see that a box86 executable built on aarch64 is an ELF 32-bit executable (and can run on armhf too), but I'm implementing downloads for pre-built box86 executables in my script and I was just wondering if there would be any point in hosting a version built with the `-DRPI4=1` flag and another built with the `-DRPI4ARM64=1` flag.

I also wanted to ask permission to see if it would be ok if I hosted a pre-built box86 binary on my github project page (7z including license file and readme files).

Thank you again

**Comment by ptitSeb** [comment]
both compile should give a similar binary yes, so no problem using one or the other.
I don't mind if you host pre-built binary, not issue for me.

**Comment by WheezyE** [comment]
Thank you!  Have a great day
