### ISSUE TITLE
Installing Box86 either from compile or the premade binaries breaks systemd-binfmt (unless installed as box86:armhf)

### ISSUE THREAD

**Issue by patch6** [ptitSeb/box86#682]
I've had to reinstall the OS to un-break systemd-binfmt. 

This is the error:

linux@changeme:$ sudo systemctl restart systemd-binfmt
Job for systemd-binfmt.service failed because the control process exited with error code.
See "systemctl status systemd-binfmt.service" and "journalctl -xeu systemd-binfmt.service" for details.
linux@changeme:$

**Comment by WheezyE** [comment]
I haven’t been able to reproduce this error. Which pre-made binaries are you using and what compiling steps (command-for-command) are you using?

**Comment by patch6** [comment]
Ah, I guess it's just my esoteric OS. I'm using Velvet OS on an Orange Pi Zero 2 and this happens.

I'll just be careful to use "sudo dpkg --add-architecture armhf," then "sudo apt install Box86:armhf" (after adding the repo.)
________________________________

**Comment by WheezyE** [comment]
Oh ok you’re using Itai’s repo? Would you be able to run `uname -m` and show that output too?

**Comment by patch6** [comment]
aarch64

**Comment by patch6** [comment]
linux@changeme:~$ sudo journalctl -xeu systemd-binfmt.service
Oct 06 19:47:08 changeme systemd-binfmt[1456]: Failed to add binary format: No >
Oct 06 19:47:08 changeme systemd[1]: systemd-binfmt.service: Main process exite>
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStart= process belonging to unit systemd-binfmt.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Oct 06 19:47:08 changeme systemd[1]: systemd-binfmt.service: Failed with result>
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit systemd-binfmt.service has entered the 'failed' state with result '>
Oct 06 19:47:08 changeme systemd[1]: Failed to start Set Up Additional Binary F>
░░ Subject: A start job for unit systemd-binfmt.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit systemd-binfmt.service has finished with a failure.
░░ 
░░ The job identifier is 1395 and the job result is failed.

**Comment by WheezyE** [comment]
Sometimes RPiOS 64-bit (aarch64) doesn’t see box86 and won’t run it since it’s a 32-bit (armhf) file.  This is just a guess, but I would bet that your system isn’t able to run this armhf box86 file. Then when binfmt tries to access box86 it says it can’t find the file?

I happen to be currently in the process of updating the multi-arch libraries I need for box86 armhf on aarch64 (RPiOS/Debian and Ubuntu)

**Comment by WheezyE** [comment]
Are you able to launch box86 directly? (running it from probably `~/usr/local/bin/box86`) Another guess would be that you just haven't enabled it to execute? `sudo chmod +x ~/usr/local/bin/box86`

**Comment by patch6** [comment]
the systemd-binfmt problem is due to this particular OS kernel not creating a /proc/sys/fs/binfmt_misc folder for binfmt_misc to mount to, so it breaks box86.

I think I have to compile a new OS here.

**Comment by WheezyE** [comment]
Interesting. It’s worth noting that binfmt support is just for convenience and for wine, so if you don’t need wine and don’t mind invoking box86 before running your x86 linux file, you could just not use binfmt

Also sorry if this is too simple but have you tried `sudo apt-get install binfmt-support`?

**Comment by WheezyE** [comment]
It might be worth contacting @Itai-Nelken to see if their repo could be updated with post-installs in the repo .deb’s to check for the binfmt_misc kernel module and skip/warn the user that binfmt support won’t be there in those cases

**Comment by patch6** [comment]
I can't even get it running directly. One pre-made box86 binary install on this orange pi zero 2, with the current OS, worked after I did something, wasn't even expecting it to.

**Comment by WheezyE** [comment]
I reinstalled RPiOS 64-bit on my test RPi4B and copied [a box86 binary I compiled myself](https://github.com/WheezyE/Winelink/tree/main/binaries) (known working on RPiOS 64-bit in a script I wrote) to `/usr/local/bin/`, gave box86 executable permissions (didn't install binfmt magic/mask), and can confirm that RPiOS doesn't see my box86 binary automatically.
```console
pi@raspberrypi4:/usr/local/bin $ neofetch
       _,met$$$$$gg.          pi@raspberrypi4 
    ,g$$$$$$$$$$$$$$$P.       --------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) aarch64 
 ,$$P'              `$$$.     Host: Raspberry Pi 4 Model B Rev 1.2 
',$$P       ,ggs.     `$$b:   Kernel: 5.15.61-v8+ 
`d$$'     ,$P"'   .    $$$    Uptime: 8 mins 
 $$P      d$'     ,    $$P    Packages: 1422 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4 
 $$;      Y$b._   _,d$P'      DE: LXDE 
 Y$$.    `.`"Y$$$$P"'         Theme: PiXflat [GTK3] 
 `$$b      "-.__              Icons: PiXflat [GTK3] 
  `Y$$                        Terminal: lxterminal 
   `Y$$.                      Terminal Font: Monospace 10 
     `$$b.                    CPU: BCM2835 (4) @ 1.500GHz 
       `Y$$b.                 Memory: 303MiB / 3794MiB 
          `"Y$b._
              `"""                                    
                                                      


pi@raspberrypi4:/usr/local/bin $ ls -l
total 20120
-rwxr-xr-x 1 root root 20602044 Oct  6 19:16 box86
pi@raspberrypi4:/usr/local/bin $ ./box86 
bash: ./box86: No such file or directory
```

It's been a while since I did this from scratch (I have it working in a script, but [the multiarch libraries in my script](https://github.com/WheezyE/Winelink/blob/98dee189fdc993465f06ee67edd9a3643116b0ce/install_winelink.sh#L566) are old and make my taskbar disappear). I'll work on getting the multiarch libraries set up to the point that RPiOS 64-bit sees box86:armhf.

**Comment by WheezyE** [comment]
Alright, try this:
```bash
sudo dpkg --add-architecture armhf && sudo apt update
sudo apt-get install libc6:armhf #to run box86:armhf on aarch64
```
_I also installed `sudo apt install gcc-arm-linux-gnueabihf` on my pi but I don't think that's needed for just running box86_

If you want to try installing box86 without binfmt you can also try this
```bash
#manually install an old box86 (ed8e01ea) and don't install binfmt
version="ed8e01ea_RPI4"
	    cd ~/Downloads
	    sudo rm /usr/local/bin/box86 2>/dev/null # in case box86 is already installed and running
	    wget -q https://github.com/WheezyE/Winelink/raw/main/binaries/box86_"$version".7z
	    7z x box86_"$version".7z -y -bsp0 -bso0
            #sudo cp box86_"$version"/build/system/box86.conf /etc/binfmt.d/
            sudo cp box86_"$version"/build/box86 /usr/local/bin/box86
	    sudo chmod +x /usr/local/bin/box86
	    sudo mkdir /usr/lib/i386-linux-gnu/ 2>/dev/null;
            sudo cp box86_"$version"/x86lib/* /usr/lib/i386-linux-gnu/
            #sudo systemctl restart systemd-binfmt 
```

I'll update this thread with more multiarch `:armhf` libraries for i386-wine on aarch64 when I figure out that dependency list.

**Comment by patch6** [comment]
Oh, you did it. libc6:armhf was the ticket. Thank you.

Please don't close thread until I test it on steam and such.

**Comment by patch6** [comment]
It unbreaks systemd-binfmt too.

**Comment by patch6** [comment]
Once #683 resolves and I can get into a Steam game (Team Fortress Classic), I'll say this is resolved.

**Comment by Itai-Nelken** [comment]
> It might be worth contacting @Itai-Nelken to see if their repo could be updated with pre-installs in the repo .deb’s to check for the binfmt_misc kernel module and skip/warn the user that binfmt support won’t be there in those cases

The .debs already have a postinstall script that does something similar: it tries to restart thr binfmt service, and if it fails it prints a warning.
See https://github.com/Itai-Nelken/box86-2deb-weekly-script/blob/main/run-once-box86-2deb-script.sh#L108-L113

**Comment by ptitSeb** [comment]
> Once #683 resolves and I can get into a Steam game (Team Fortress Classic), I'll say this is resolved too.

No, this ticket has nothing to do with Team Fortress Classic, and, as far as I understand, is solved and can be closed.
