### ISSUE TITLE
Steam dependency wack-a-mole

### ISSUE THREAD

**Issue by patch6** [ptitSeb/box86#683]
Ubuntu 22.04 "Velvet OS" on Orange Pi Zero 2.

Wondering where to get libgobject-2.0.so.0 that will work with Steam. 

https://github.com/ptitSeb/box86/issues/260 got Steam running upto the point of "Updating Steam", then when that finishes, a steamui.so error pops up.

BOX86_LOG=1 shows it's related to libgobject-2.0.so.0.

I'll ask for other deps as they pop up unless I can figure out how to find them myself.

**Comment by ptitSeb** [comment]
When box86 detect steam, it disable the wrapping of all gtk libs, so you will see many gtk related libs not beeing able to be loaded at first, with an error message. The i386 libs is then loaded from steam folders and the loading process should continue.

So, if you launch steam using the steal shell script, and using `STEAMOS=1` env. var.  (and also maybe `STEAM_RUNTIME=1`) steam should find all needed libs, there is no need to look for any libs

**Comment by patch6** [comment]
That sounds convenient, but when I run steam.sh it gives Exec format error issues:

linux@changeme: ~ $ BOX86_LOG=1 box86 steam
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Box86 with Dynarec v0.2.7 43190d41 built on Oct  2 2022 00:07:32
BOX86_LD_LIBRARY_PATH: /home/linux/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/:/home/linux/.local/share/Steam/ubuntu12_32/
Using default BOX86_PATH: ./:bin/
Counted 51 Env var
Looking for steam
steam detected, forcing emulated libudev and gtk
Not an ELF file (sign=#!/b)
Error: reading elf header of /usr/local/bin/steam, try to launch natively instead
steam.sh[27210]: Running Steam on ubuntu 22.04 64-bit
steam.sh[27210]: STEAM_RUNTIME is enabled by the user
setup.sh[27275]: Steam runtime environment up-to-date!
/home/linux/.local/share/Steam/steam.sh: line 421: /home/linux/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-check-requirements: cannot execute binary file: Exec format error
steam.sh[27210]: steam-runtime-check-requirements failed with an unexpected nonzero exit status. Trying to continue
/home/linux/.local/share/Steam/steam.sh: line 790: /home/linux/.local/share/Steam/ubuntu12_32/steam: cannot execute binary file: Exec format error


I've been having systemd-binfmt issues, like it's loaded and it's in a fail state, maybe that has something to do with it

**Comment by ptitSeb** [comment]
than use i386 bash, you can find a copy in box86 "tests" folder. Now I now you use a pre-build binary, so just grab `bash` from box86 github, put it somehwere and define `BOX86_BASH=/path/to/bash` env. var. Box86 will then use i386 bash to run shell script and keep control of what is going on, so steam should run.
I have created a blog entry on that here: https://box86.org/2022/09/running-bash-with-box86-box64/

**Comment by patch6** [comment]
ok, I did that and chmod +x'd the new bash. Now it does this:

linux@changeme:~$ BOX86_LOG=1 box86 steam
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using bash "/home/linux/Downloads/bash"
Box86 with Dynarec v0.2.7 43190d41 built on Oct  2 2022 00:07:32
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 49 Env var
Looking for steam
steam detected, forcing emulated libudev and gtk
Not an ELF file (sign=#!/b)
Error: reading elf header of /usr/local/bin/steam, try to launch using bash instead
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using bash "/home/linux/Downloads/bash"
Box86 with Dynarec v0.2.7 43190d41 built on Oct  2 2022 00:07:32
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 49 Env var
Looking for /home/linux/Downloads/bash
bash detected, disabling banner
argv[1]="/usr/local/bin/steam"
Rename process to "bash"
Using native(wrapped) libtinfo.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
steam.sh[1889]: Running Steam on ubuntu 22.04 64-bit
steam.sh[1889]: STEAM_RUNTIME is enabled by the user
setup.sh[1954]: Steam runtime environment up-to-date!
/home/linux/.local/share/Steam/steam.sh: line 421: /home/linux/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-check-requirements: cannot execute binary file: Exec format error
steam.sh[1889]: steam-runtime-check-requirements failed with an unexpected nonzero exit status. Trying to continue
/home/linux/.local/share/Steam/steam.sh: line 790: /home/linux/.local/share/Steam/ubuntu12_32/steam: cannot execute binary file: Exec format error
linux@changeme:~$

**Comment by patch6** [comment]
It doesn't seem to want to run box86 for steam-runtime-check-requirements or the steam binary.

**Comment by ptitSeb** [comment]
Mmm, strange. I think `steam-runtime-check-requirements` is a 64bits binary, so it should be ok, but the steam binary should be detected by box86.
I tried on my side on 32bits system and it seemed to work.

Are you on a 64bits system? and if yes, do you have box64 installed to?

**Comment by patch6** [comment]
I put box86 before the command in line 421 and line 790 and it's running now. Let's see what happens though, it's doing updates.

**Comment by ptitSeb** [comment]
Yeah, that work, but the shell script itself is part of steam, so it will be restored to its initial content at some point...

**Comment by patch6** [comment]
yeah, it failed in the same way after updating. Restored the steam.sh script.

**Comment by patch6** [comment]
just for testing's sake, I made scripts that switch steam.sh from modified to default before the hash check, and I can get in, past the update screen. But now I'm getting a window with a browser error message where the login screen should be.

Libunity.so.9 error maybe?

**Comment by patch6** [comment]
Okay, loaded a bunch of deps manually, now there's only a gldriverquery and vulkandriverquery error (Exec format error,) are these what are causing the "The Steam Browser is disabled" error?

**Comment by patch6** [comment]
The message appears when loading the login window.

**Comment by ptitSeb** [comment]
Have you read the README of box86? There is a chapter on Steam.

**Comment by patch6** [comment]
I just changed the /usr/local/bin/steam script from minibrowser to bigpicture, now it's letting me log in.

**Comment by patch6** [comment]
What worked was logging in with bigpicture, quitting, then switching to minibrowser mode. Minibrowser to login gives me the "browser is disabled" message.

**Comment by patch6** [comment]
Okay, so I've exhausted the testing of Team Fortress Classic on this device. Just hard limits keeping it ~30 fps.

Anyhow, I got Steam "working", and it's just not worth it on the Orange Pi Zero 2. Too much overhead.

Quake1 runs a treat at low res though. Can develop into that.
