### ISSUE TITLE
Box86 and Besiege

### ISSUE THREAD

**Issue by DotJARgon** [ptitSeb/box86#688]
Currently I am trying to get the steam game besiege to run on the raspberry pi 3b+. The only problem so far is that it seems to get hung up on loading up libudev-dev, which I have installed the armhf version as well, however I get the following errors:

Error loading needed lib libudev.so
Warning: cannot dlopen("libudev.so"/0x952c110, 1)
Using native(wrapped) libudev.so.1
Using libudev for joystick management

Importing game controller configs

Then it just stops there and shows only a blue screen, I am uncertain if it is using the armhf version of the lib I installed, or how to force it if it is not.

**Comment by ptitSeb** [comment]
How are you launching steam?
Steam needs to be launched with it's shell script.
Can this ticket be closed?

**Comment by DotJARgon** [comment]
Ah I see, I had installed steam and opened it via the shortcut created on the desktop! And then I set its mode to minified, I have not had time to go back and try the method you have mentioned but I will soon! And yes I think it can be closed, the rest of it should just be dependency stuff anyways.
