### ISSUE TITLE
install_steam.sh package dependency install fails in arm64 multiarch, Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by nixguru** [ptitSeb/box86#694]
Getting errors when trying to run install_steam.sh on Ubuntu 22.04.1 arm64 in with multi-arch armhf.

The script is attempting to execute the following:
`sudo apt install libc6:armhf libncurses5:armhf libsdl2*:armhf libopenal*:armhf libpng*:armhf libfontconfig*:armhf libXcomposite*:armhf libbz2-dev:armhf libXtst*:armhf # install the libraries that Steam requires`

.. which results in:

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Note, selecting 'libsdl2-net-dev:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-ttf-2.0-0:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-image-2.0-0:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-ttf-dev:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-mixer-dev:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-image-dev:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-gfx-1.0-0:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-2.0-0:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-net-2.0-0:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-gfx-dev:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-gfx-doc:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-dev:armhf' for glob 'libsdl2*'
> Note, selecting 'libsdl2-mixer-2.0-0:armhf' for glob 'libsdl2*'
> Note, selecting 'libopenal-data:armhf' for glob 'libopenal*'
> Note, selecting 'libopenal-dev:armhf' for glob 'libopenal*'
> Note, selecting 'libopenal0a:armhf' for glob 'libopenal*'
> Note, selecting 'libopenal1:armhf' for glob 'libopenal*'
> Note, selecting 'libopenal-data' instead of 'libopenal-data:armhf'
> Note, selecting 'libpnglite0:armhf' for glob 'libpng*'
> Note, selecting 'libpnglite-dev:armhf' for glob 'libpng*'
> Note, selecting 'libpng2-dev:armhf' for glob 'libpng*'
> Note, selecting 'libpng-dev:armhf' for glob 'libpng*'
> Note, selecting 'libpng16-16:armhf' for glob 'libpng*'
> Note, selecting 'libpng-tools:armhf' for glob 'libpng*'
> Note, selecting 'libfontconfig1-dev:armhf' for glob 'libfontconfig*'
> Note, selecting 'libfontconfig-dev:armhf' for glob 'libfontconfig*'
> Note, selecting 'libfontconfig1:armhf' for glob 'libfontconfig*'
> Note, selecting 'libfontconfig:armhf' for glob 'libfontconfig*'
> Note, selecting 'libfontconfig1:armhf' instead of 'libfontconfig:armhf'
> Note, selecting 'libxcomposite-dev:armhf' for glob 'libXcomposite*'
> Note, selecting 'libxcomposite1:armhf' for glob 'libXcomposite*'
> Note, selecting 'libxtst-dev:armhf' for glob 'libXtst*'
> Note, selecting 'libxtst6:armhf' for glob 'libXtst*'
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  apt : Depends: adduser but it is not going to be installed
>        Depends: gpgv or
>                 gpgv2 but it is not going to be installed or
>                 gpgv1
>        Depends: libapt-pkg6.0 (>= 2.4.6) but it is not going to be installed
>        Depends: libc6 (>= 2.34) but it is not installable
>        Depends: libgcc-s1 (>= 3.3.1) but it is not going to be installed
>        Depends: libgnutls30 (>= 3.7.0) but it is not going to be installed
>        Depends: libseccomp2 (>= 2.4.2) but it is not going to be installed
>        Depends: libstdc++6 (>= 11) but it is not going to be installed
>        Depends: libsystemd0 but it is not installable
>        Recommends: ca-certificates but it is not going to be installed
>  base-files : PreDepends: awk
>               Depends: libc6 (>= 2.34) but it is not installable
>  base-passwd : Depends: libc6 (>= 2.34) but it is not installable
>                Depends: libdebconfclient0 (>= 0.145) but it is not going to be installed
>  bash : PreDepends: libc6 (>= 2.34) but it is not installable
>         PreDepends: libtinfo6 (>= 6) but it is not going to be installed
>  bsdutils : PreDepends: libc6 (>= 2.34) but it is not installable
>             PreDepends: libsystemd0 but it is not installable
>             Recommends: bsdextrautils
>  coreutils : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed
>              PreDepends: libattr1 (>= 1:2.4.44) but it is not going to be installed
>              PreDepends: libc6 (>= 2.34) but it is not installable
>              PreDepends: libgmp10 (>= 2:6.2.1+dfsg) but it is not going to be installed
>              PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
>  dash : PreDepends: libc6 (>= 2.34) but it is not installable
>  debianutils : PreDepends: libc6 (>= 2.34) but it is not installable
>  diffutils : PreDepends: libc6 (>= 2.34) but it is not installable
>  dpkg : PreDepends: libbz2-1.0 but it is not going to be installed
>         PreDepends: libc6 (>= 2.34) but it is not installable
>         PreDepends: liblzma5 (>= 5.2.2) but it is not going to be installed
>         PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
>         PreDepends: libzstd1 (>= 1.4.0) but it is not going to be installed
>         PreDepends: zlib1g (>= 1:1.1.4) but it is not going to be installed
>  e2fsprogs : PreDepends: libblkid1 (>= 2.36) but it is not going to be installed
>              PreDepends: libc6 (>= 2.34) but it is not installable
>              PreDepends: libcom-err2 (>= 1.43.9) but it is not going to be installed
>              PreDepends: libext2fs2 (= 1.46.5-2ubuntu1.1) but it is not going to be installed
>              PreDepends: libss2 (>= 1.38) but it is not going to be installed
>              PreDepends: libuuid1 (>= 2.16) but it is not going to be installed
>              Depends: logsave
>              Recommends: e2fsprogs-l10n but it is not going to be installed
>  findutils : PreDepends: libc6 (>= 2.34) but it is not installable
>              PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
>  grep : PreDepends: libc6 (>= 2.34) but it is not installable
>         PreDepends: libpcre3 but it is not going to be installed
>  gzip : PreDepends: libc6 (>= 2.34) but it is not installable
>  hostname : PreDepends: libc6 (>= 2.34) but it is not installable
>  init : PreDepends: systemd-sysv
>  libc-bin : Depends: libc6 (> 2.35) but it is not installable
>             Depends: libc6 (< 2.36) but it is not installable
>  libcrypt1 : Depends: libc6 (>= 2.25) but it is not installable
>  libdbus-1-dev:armhf : Depends: pkg-config:armhf
>  libfontconfig-dev:armhf : Depends: pkg-config:armhf
>  libglib2.0-dev:armhf : Depends: libglib2.0-dev-bin:armhf (= 2.72.1-1)
>                         Depends: pkg-config:armhf
>  login : PreDepends: libaudit1 (>= 1:2.2.1) but it is not going to be installed
>          PreDepends: libc6 (>= 2.34) but it is not installable
>          PreDepends: libpam0g (>= 0.99.7.1) but it is not going to be installed
>          PreDepends: libpam-runtime but it is not going to be installed
>          PreDepends: libpam-modules but it is not going to be installed
>  ncurses-bin : PreDepends: libc6 (>= 2.34) but it is not installable
>                PreDepends: libtinfo6 (>= 6.3) but it is not going to be installed
>  perl-base : PreDepends: libc6 (>= 2.35) but it is not installable
>  sed : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed
>        PreDepends: libc6 (>= 2.34) but it is not installable
>        PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
>  sysvinit-utils : Depends: libc6 (>= 2.34) but it is not installable
>  tar : PreDepends: libacl1 (>= 2.2.23) but it is not going to be installed
>        PreDepends: libc6 (>= 2.34) but it is not installable
>        PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
>  util-linux : PreDepends: libaudit1 (>= 1:2.2.1) but it is not going to be installed
>               PreDepends: libblkid1 (>= 2.37.2) but it is not going to be installed
>               PreDepends: libc6 (>= 2.34) but it is not installable
>               PreDepends: libcap-ng0 (>= 0.7.9) but it is not going to be installed
>               PreDepends: libmount1 (>= 2.37.2) but it is not going to be installed
>               PreDepends: libpam0g (>= 0.99.7.1) but it is not going to be installed
>               PreDepends: libselinux1 (>= 3.1~) but it is not going to be installed
>               PreDepends: libsmartcols1 (>= 2.34) but it is not going to be installed
>               PreDepends: libsystemd0 but it is not installable
>               PreDepends: libtinfo6 (>= 6) but it is not going to be installed
>               PreDepends: libudev1 (>= 183) but it is not installable
>               PreDepends: libuuid1 (>= 2.16) but it is not going to be installed
>               PreDepends: zlib1g (>= 1:1.1.4) but it is not going to be installed
> E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
> Don't forget to compile/install Box64!
> Script complete.

There are no held packages.

/etc/apt/sources.list

> $ cat /etc/apt/sources.list | egrep -v ^\#
> 
> deb http://us.archive.ubuntu.com/ubuntu/ jammy-updates main restricted
> deb http://us.archive.ubuntu.com/ubuntu/ jammy-updates universe
> deb http://us.archive.ubuntu.com/ubuntu/ jammy-updates multiverse
> deb http://us.archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
> deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted
> deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security universe
> deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security multiverse
> deb http://us.archive.ubuntu.com/ubuntu/ jammy main universe restricted multiverse
> deb http://ports.ubuntu.com/ubuntu-ports/ jammy main universe restricted multiverse

Any suggestions?  Thank you.

**Comment by ptitSeb** [comment]
> The following packages have unmet dependencies:
> apt : Depends: adduser but it is not going to be installed
> Depends: gpgv or
> gpgv2 but it is not going to be installed or

Why are you installing `apt`? only libs should be installed.

**Comment by nixguru** [comment]
The command being executed is the same command in the script in this git repo.  `apt` is the one executing, but I can't tell you why it would be trying to install apt.  I'm wondering if the output from apt is what is confusing, in that apt may be simply pre-pending itself to the output to make it clear which commands output it is.  

`sudo apt install libc6:armhf libncurses5:armhf libsdl2*:armhf libopenal*:armhf libpng*:armhf libfontconfig*:armhf libXcomposite*:armhf libbz2-dev:armhf libXtst*:armhf`

There isn't anything in there that would be installing `apt`.

**Comment by ptitSeb** [comment]
Maybe try to install each element one by one?
The most critical is the first one anyway `libc6:armhf`

**Comment by nixguru** [comment]
This may be solved now.  For benefit of anyone that may run into the same issue, I'll explain.  While this was based on a relatively fresh install of arm64 Ubuntu 22.04.1 LTS, it appears to have been something with the configured repositories.  The message 
> "Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming."
.. made me curious if the tool to manage repositories may have mangled something.   So, I re-imaged the operating system to put it back into a pristine state, didn't touch that tool, and everything worked fine.  

When inspecting the sources.list on the freshly imaged system, it showed all uncommented sources as `http://ports.ubuntu.com/ubuntu-ports/`, which is different from above.  It appears that if you tell Ubuntu to download from "US server" from the default "Main server" selection, it changed some of them to read `http://us.archive.ubuntu.com/ubuntu/` which appears to have broken things.  So I can trace this all back to trying to change the source server location for repositories using the Ubuntu "Software & Updates" tool.
