### ISSUE TITLE
steam runtime crashing with pthread_rwlock cannot apply R_386_JMP_SLOT

### ISSUE THREAD

**Issue by nixguru** [ptitSeb/box86#696]
I'm running into an issue on a fresh install of box86 from box86 Debian repository on arm64 Ubuntu 22.04.1 LTS (running on raspberry pi 4).  So far, I have been unable to find a solution when searching.

> mikeb@rpi4:~/steam/bin$ ./steam
> steam.sh[11627]: Running Steam on ubuntu 22.04 64-bit
> steam.sh[11627]: STEAM_RUNTIME is enabled by the user
> setup.sh[11690]: Steam runtime environment up-to-date!
> steam.sh[11627]: Can't find 'steam-runtime-check-requirements', continuing anyway
> Box86 with Dynarec v0.2.3 3a7cc57f built on Jul  9 2021 17:31:35
> [2022-10-13 12:53:18] Startup - updater built Jun  7 2022 03:18:19
> ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
> Looks like steam didn't shutdown cleanly, scheduling immediate update check
> Error: PltReolver: Symbol pthread_rwlock_wrlock(ver 25: pthread_rwlock_wrlock@GLIBC_2.1) not found, cannot apply R_386_JMP_SLOT 0xf7ab4f84 (0xf74dcc56) in /home/mikeb/.local/share/Steam/ubuntu12_32/steam
> Error: PltReolver: Symbol pthread_rwlock_wrlock(ver 25: pthread_rwlock_wrlock@GLIBC_2.1) not found, cannot apply R_386_JMP_SLOT 0xf7ab4f84 (0xf74dcc56) in /home/mikeb/.local/share/Steam/ubuntu12_32/steam
> Error: PltReolver: Symbol pthread_rwlock_rdlock(ver 25: pthread_rwlock_rdlock@GLIBC_2.1) not found, cannot apply R_386_JMP_SLOT 0xf7ab4f80 (0xf74dcc46) in /home/mikeb/.local/share/Steam/ubuntu12_32/steam

The "steam didn't shutdown cleanly" is a red herring.  I've tried deleting the .crash file (which makes the message go away once), and it is just being placed there because steam crashed.  

Steam is being launched according to the install_steam.sh script, by executing ~/steam/bin/steam:

> #!/bin/bash
> export STEAMOS=1
> export STEAM_RUNTIME=1
> ~/steam/bin/steam steam://open/minigameslist

Any thoughts/suggestions?  Thank you in advance.

**Comment by ptitSeb** [comment]
You  are using a super old version of box86. I'm not sure were you get it (box86 debian repository? to my knowledge, box86 is not on official debian repo), but you better compile it from source, that way you'll have an up-to-date version.

**Comment by nixguru** [comment]
Interesting...  Here is what I did:

`sudo wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -O /etc/apt/sources.list.d/box86.list`
`wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add -`
`sudo apt update && sudo apt install box86 -y`

.. which was simply taken from the build/complication instructions:

[COMPILE.md](https://github.com/ptitSeb/box86/blob/master/docs/COMPILE.md#debian-based-linux)

I'm under the impression that this is not being updated weekly anymore and perhaps should be removed from the document?

I'll just compile everything then.  Very much appreciate your help.

**Comment by ptitSeb** [comment]
Yep, I'll check with itai if I can contact him and delete that part eventualy. Thanks for the heads up

**Comment by nixguru** [comment]
Sounds good.  Thanks again

**Comment by Itai-Nelken** [comment]
> Interesting...  Here is what I did:
> 
> `sudo wget https://itai-nelken.github.io/weekly-box86-debs/debian/box86.list -O /etc/apt/sources.list.d/box86.list`
> `wget -qO- https://itai-nelken.github.io/weekly-box86-debs/debian/KEY.gpg | sudo apt-key add -`
> `sudo apt update && sudo apt install box86 -y`
> 

I found the problem: there is an old package that has the `arch` field set to arm64.
The fix is to install `box86:armhf`.
