### ISSUE TITLE
SDL_BuildAudioCVT / SDL_ConvertAudio in SDL1

### ISSUE THREAD

**Issue by M-HT** [ptitSeb/box86#7]
Is there a reason that functions SDL_BuildAudioCVT / SDL_ConvertAudio in SDL2 are using native functions, but in SDL1 they are "implemented" using my_SDL_BuildAudioCVT / my_SDL_ConvertAudio (which just print a text that the function is unimplemented) ?

**Comment by ptitSeb** [comment]
Well, there are some filter callback in the [SDLAudio_CVT](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlaudiocvt.html) structure that will probably need some care. 
The SDL2 version should be checked too, my mistake.

**Comment by ptitSeb** [comment]
Or maybe thoses filter are for internal use only and should not be accessed externaly? It's mentioned like that on the SDL2 documentation, but it doesn't seems that clear on SDL1.
I can probably try the simple "full native" approach first, and then implement wrapping/unwrapping (à la SDLRWops) later if needed I guess.

**Comment by M-HT** [comment]
I tested two games which use SDL_BuildAudioCVT / SDL_ConvertAudio in SDL1 and they work. I also checked SDL1 sources and only internal filters are used in SDL_BuildAudioCVT.

**Comment by ptitSeb** [comment]
Sounds good!
