### ISSUE TITLE
Is there a way to install box86 on m1?

### ISSUE THREAD

**Issue by GreatHaop** [ptitSeb/box86#730]
m1 doesn’t have a armhf support, thus

**Comment by ptitSeb** [comment]
Nope, not possible.
The solution will be "box32", but it's not out (and far from beeing usable for now).

**Comment by etienne0x7C1** [comment]
Does it mean no steam support on M1 for now? with recent GPU acceleration support would be nice getting steam games running on it.

**Comment by GreatHaop** [comment]
> Does it mean no steam support on M1 for now? with recent GPU acceleration support would be nice getting steam games running on it.

This does mean that m1 doesn’t have steam now

**Comment by ptitSeb** [comment]
No box86 on M1, so no Steam as it's 32bits.
