### ISSUE TITLE
wine cannot access network with box86

### ISSUE THREAD

**Issue by sammlyu** [ptitSeb/box86#732]
I tried to use box86 with wine 32 with the following command:

wine iexplore appdb.winehq.org

my wine already put within a script with 'box86 wine' as the command to start wine 32.

But it failed and two errors are:
0138:err:secur32:process_attach Failed to load gnutls_alert_send
0138:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems

I checked to install libgnutls but I don't know what architecture I should install. I tried armhf, arm64 and i386, all failed to connect internet with iexplore.

**Comment by ptitSeb** [comment]
I think it's fixed now. Can you update box86 and try again, and close the ticket if it's fixed.

**Comment by sammlyu** [comment]
> I think it's fixed now. Can you update box86 and try again, and close the ticket if it's fixed.

I tried the latest build and it works now. Thanks a lot! I don't notice it is the issue in box86. I thought it's an issue in wine side.
