### ISSUE TITLE
How do I specify an old version of libc and libm when compiling box86

### ISSUE THREAD

**Issue by ccfxny** [ptitSeb/box86#734]
Hello, wen I make box86 on a Phytium machine,
Unable to run wine application in wine
Because wine's lib.so.6=libc-2.28.so
But when I make, the version of lbc.so in my Phytium  system was equal to =2.3.1, so the operation went wrong.
i want to ask
How do I specify an old version of libc and libm when compiling box86, for example, I use /lib/arm-linux-gnueabihf/libc.so.6

box86:  /lib/arm-linux-gnueabihf/libm,so.6: version 'GLIBC 2.29' not found 
box86:  /lib/arm-linux-gnueabihf/libc,so.6: version 'GLIBC 2.33
/box86: /lib/arm-linux-gnueabihf/libc.so.6: version 'GLIBC 2.32
/box86: /lib/arm-linux-gnueabihf/libc.so.6: version 'GLIBC 2.34

**Comment by ptitSeb** [comment]
so, you fixed your issue I guess.

**Comment by ccfxny** [comment]
> so, you fixed your issue I guess.

me changed a computer and used a lower version of gcc8 to compile, which solved the problem. I used linaro-gcc11 to compile before
Do you have a recommended gcc version available to compile with

**Comment by ptitSeb** [comment]
Not really. I use gcc8, 11 and 12 on various machine.

**Comment by ccfxny** [comment]
ok,tks
