### ISSUE TITLE
Bash in tests folder not starting properly

### ISSUE THREAD

**Issue by cabumiscool** [ptitSeb/box86#735]
I recently installed box86 in a crostini container in Chrome OS and ran the tests and they all managed to complete with box86 with no problem, but when I attempt to run bash that is inside the test folder the following is outputted:

Box86 with Dynarec v0.2.9 cb09b097 built on Dec  4 2022 01:18:35
bash: eval: line 77: syntax error near unexpected token `"/usr/bin/dircolors",'
bash: eval: line 77: `execve("/usr/bin/dircolors", 0x64d876b8["dircolors", "-b", "(nil)"...], 0x64d31ca8) is x64=0 x86=0 script=0 (my_context->envv=0xecffa4c0, environ=0x64cb0880'

I thought it was a problem with dircolors so I reinstalled coreutils and replaced it with armhf version but it stills gives the same error. Any idea on how to fix it?

**Comment by ptitSeb** [comment]
Probably something in your `~/.bashrc` that the bash version in tests doesn't like.

**Comment by cabumiscool** [comment]
You were right, that was the problem, sorry for the unrelated report

**Comment by ptitSeb** [comment]
So the ticket can be closed now?

**Comment by cabumiscool** [comment]
yes, it correctly. Thanks
