### ISSUE TITLE
Steam segfaults on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by dborel** [ptitSeb/box86#739]
I'm using Raspbian 11 updated to latest with Box86 v0.2.8 built from source (RelWithDebInfo). I ran install_steam.sh and added BOX86_BASH, BOX86_LIBRARY_PATH, and BOX86_LOG to the environment and prefixed the command with "setarch linux32 -L". It's getting fairly far in the launch, but crashes shortly after I log in with:

Using native(wrapped) ld-linux.so.2
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT 0x44cfaf08 (0x8d56)
/home/dborel/.local/share/Steam/steam.sh: line 798: 32217 Segmentation fault      "$STEAMROOT/$STEAMEXEPATH" "$@"

In gdb, the backtrace looks like this:

Thread 1 "steam" received signal SIGSEGV, Segmentation fault.
arm_lock_storeifnull () at /home/dborel/Builds/box86/src/dynarec/arm_lock_helper.S:89
89          ldrex   r2, [r0]
(gdb) bt
#0  arm_lock_storeifnull () at /home/dborel/Builds/box86/src/dynarec/arm_lock_helper.S:89
#1  0x62a2c790 in AddNewDynablock (dynablocks=dynablocks@entry=0x1, addr=addr@entry=2128120688, created=0x7eae025c, created@entry=0x7eae0254)
    at /home/dborel/Builds/box86/src/dynarec/dynablock.c:290
#2  0x62a2c8e0 in internalDBGetBlock (emu=emu@entry=0x64330118, addr=174, addr@entry=2128120688, filladdr=906383800, filladdr@entry=2128120688, create=create@entry=1, 
    current=0x78dfc500, need_lock=need_lock@entry=1) at /home/dborel/Builds/box86/src/dynarec/dynablock.c:341
#3  0x62a2cccc in DBGetBlock (emu=emu@entry=0x64330118, addr=addr@entry=2128120688, create=create@entry=1, current=0x7eae02bc, current@entry=0x7eae02b4)
    at /home/dborel/Builds/box86/src/dynarec/dynablock.c:397
#4  0x62905870 in LinkNext (emu=0x64330118, addr=2128120688, x2=<optimized out>) at /home/dborel/Builds/box86/src/dynarec/dynarec.c:49
#5  0x62a30588 in arm_next () at /home/dborel/Builds/box86/src/dynarec/arm_next.S:18
#6  0x7ed88b70 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by ptitSeb** [comment]
Can you try with latest box86 version?

**Comment by dborel** [comment]
Updated to 64f52cb, but now it crashes a little earlier (before unloading serverbrowser.so) with:

2177|SIGSEGV @0x62a37bc8 (???(/home/dborel/.local/share/Steam/ubuntu12_32/steam/0x62a37bc8)) (x86pc=0x7e684300//home/dborel/.local/share/Steam/ubuntu12_32/serverbrowser.so:"???", esp=0x2ca338fc, stack=0x2c23b000:0x2ca3b000 own=(nil) fp=0x2ca33b58), for accessing 0x16944 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0)
ESP-0x10:0x7e677e17 ESP-0x0c:0x38f0dcf4 ESP-0x08:0x38f0dcf4 ESP-0x04:0x38f0dcf4
ESP+0x00:0x40020030 ESP+0x04:0x00000004 ESP+0x08:0x2ca398f0 ESP+0x0c:0x2ca39904

**Comment by dborel** [comment]
I was able to get steam running by installing all of the libraries box86 was trying to wrap. In my case, the following were missing: libxinerama1 libxi6 libxrandr2 libxcursor1 libxcomposite1 libpng16-16 libturbojpeg0 libselinux1 libxtst6 pulseaudio libdbus-1-3 libsndfile1 libogg0 libvorbis0a libopenal1 libsm6 libice6 libgnutls30 libgmp10 libxss1 libsdl2-2.0-0
