### ISSUE TITLE
Super Hexagon (Weak symbol and segfault)

### ISSUE THREAD

**Issue by JORGETECH** [ptitSeb/box86#74]
Trying to run Super Hexagon (x86 version) triggers some weak symbol warnings and a segmentation fault:

> jorgetech@orangepizero:~/box86/build$ LD_LIBRARY_PATH=/usr/local/lib/gl4es/ BOX86_LD_LIBRARY_PATH=/home/jorgetech/superhexagon/x86/ ./box86 /home/jorgetech/superhexagon/x86/superhexagon.x86 
BOX86_LD_LIBRARY_PATH: /home/jorgetech/superhexagon/x86/
Using default BOX86_PATH: ./:bin/
Counted 63 Env var
Looking for /home/jorgetech/superhexagon/x86/superhexagon.x86
LIBGL: Initialising gl4es
LIBGL: v1.1.3 built on Nov 28 2019 13:33:44
LIBGL: Using GLES 2.0 backend
LIBGL: loaded: libGLESv2.so
LIBGL: loaded: libEGL.so
LIBGL: Using GLES 2.0 backend
LIBGL: Error while gathering supported extension (eglInitialize: EGL_BAD_DISPLAY), default to none
LIBGL: Targeting OpenGL 2.0
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/home/jorgetech/box86/build
Using native(wrapped) libGL.so.1
Using native(wrapped) libGLU.so.1
Using emulated /home/jorgetech/superhexagon/x86/libglut.so.3
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libXi.so.6
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/jorgetech/superhexagon/x86/libGLEW.so.1.6
Using native(wrapped) libopenal.so.1
Using native(wrapped) libvorbisfile.so.3
Using emulated /home/jorgetech/superhexagon/x86/libstdc++.so.6
Using emulated /home/jorgetech/superhexagon/x86/libgcc_s.so.1
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT @0xb4db0bcc (0x6b580)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_386_JMP_SLOT @0xb4db0eb0 (0x6c110)
Segmentation fault

More detailed logs are attached.
[debug.log](https://github.com/ptitSeb/box86/files/3903231/debug.log)
[dump.log](https://github.com/ptitSeb/box86/files/3903233/dump.log)

**Comment by ptitSeb** [comment]
I'm unsure wich version of SuperHexxagon you are using, but my version (comming from HumbleBundle) doesn't use libglut but SDL2. I guess your version is older.

I'm unsure SuperHexxagon handle beeing launched from outside its root folder, so maybe try to cd in `/home/jorgetech/superhexagon/` before launching. Also, gl4es seems to not be able to create any context, so I assumed you used some ssh to launch it and forgot to export `DISPLAY=:0`
But I don't think any of this explain your crash.
It works on my side, it start with no issue. But I do have some sound/ogg issue in game. I probably have some bug in libogg wrapper that I need to fix.

Can you try to send me a gdb backtrace? Also a trace with `BOX86_DYNAREC_LOG=3` to have generated code.
And also, you can check how it run with the interpretor only with `BOX86_DYNAREC=0`

**Comment by ptitSeb** [comment]
Can I close this ticket?

**Comment by JORGETECH** [comment]
I will close the issue myself (so I can re-open it if needed) since I lost track and I need to recreate my testing setup. Maybe I'll test it again in the following days, but I don't promise anything.
