### ISSUE TITLE
Unimplemented Opcode (00) F2 0F 7D C9 0F 29 8C

### ISSUE THREAD

**Issue by 1322579329** [ptitSeb/box86#744]
When i run wine in box86, some windows program crash, box86 log is Unimplemented Opcode (00) F2 0F 7D C9 0F 29 8C，
try to fix https://github.com/1322579329/box86/commit/34069d48e9b493e82542abaa03aa6e9a9ff6d24e. Program works well, I'm not good at opcode problem. I don't sure it's a right fix.

**Comment by ptitSeb** [comment]
This is not the correct code. I'll fix this in a few moment.

**Comment by ptitSeb** [comment]
Ok, Added proper code for this opcde.
