### ISSUE TITLE
Steam will not start on Odroid XU4

### ISSUE THREAD

**Issue by aaron9412** [ptitSeb/box86#749]
Hi, 

My name is Aaron; I'm trying to set up a fresh install of an Odroid XU4 with Ubuntu Mate and box86 to run Steam. I can't get it to run. 

I see a libgl error, I will look into that as best I can.

Methods:
- Installed Ubuntu Mate 22.04-5.4 20220522 image (I can link if needed) on SD.
- sudo apt update
- sudo apt upgrade
- sudo apt update
- ...install git, cmake
- ...git clone box86
- ...run instructions (copy paste from github) to make odroid build
- sudo make install
- ./install-steam.sh
- double click "steam" in usr/bin

Results:

Update is run (gui for update loads) followed by open terminal with the following output. No login gui for steam. Tried starting chromium then starting steam script in case it was a login issue, no luck. Please advise and let me know if more info is needed. Happy to help.

Output:

steam.sh[3127]: Running Steam on ubuntu 22.04 32-bit
steam.sh[3127]: STEAM_RUNTIME is enabled by the user
setup.sh[3192]: Steam runtime environment up-to-date!
steam.sh[3127]: Steam client's requirements are satisfied
Box86 with Dynarec v0.2.9 2b247838 built on Jan  8 2023 21:15:40
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
[2023-01-08 21:46:48] Startup - updater built Dec 15 2022 21:26:49
[2023-01-08 21:46:48] Startup - Steam Client launched with: '/home/odroid/.local/share/Steam/ubuntu12_32/steam' '-noreactlogin' 'steam://open/minigameslist'
libGL error: failed to create dri screen
libGL error: failed to load driver: exynos
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-01-08 21:46:49] Loading cached metrics from disk (/home/odroid/.local/share/Steam/package/steam_client_metrics.bin)
[2023-01-08 21:46:49] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-01-08 21:46:49] Using the following download hosts for Public, Realm steamglobal
[2023-01-08 21:46:49] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-01-08 21:46:49] Checking for update on startup
[2023-01-08 21:46:49] Checking for available updates...
[2023-01-08 21:46:49] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
[2023-01-08 21:46:49] Manifest download: send request
[2023-01-08 21:46:49] Manifest download: waiting for download to finish
[2023-01-08 21:46:49] Manifest download: finished
[2023-01-08 21:46:49] Download skipped: /client/steam_client_ubuntu12 version 1671236931, installed version 1671236931, existing pending version 0
[2023-01-08 21:46:49] Nothing to do
[2023-01-08 21:46:49] Verifying installation...
[2023-01-08 21:46:49] Performing checksum verification of executable files

Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  804
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  806
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  808
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  810
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  812
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  814
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  816
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  818
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  820
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  822
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  824
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  826
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  828
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  830
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  832
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  834
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  836
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  838
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  18 (X_ChangeProperty)
Resource id in failed request:  0x3400008
Serial number of failed request:  840
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  18 (X_ChangeProperty)
Resource id in failed request:  0x3400008
Serial number of failed request:  844
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  12 (X_ConfigureWindow)
Resource id in failed request:  0x3400008
Serial number of failed request:  845
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  846
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  848
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  850
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  852
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  854
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  856
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  858
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  860
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  862
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  864
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  866
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  868
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  870
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  872
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  874
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  876
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  878
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  880
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  882
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  884
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  886
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  888
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  890
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  892
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  894
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  896
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  898
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  900
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  902
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  904
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  906
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  908
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  910
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  912
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  914
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  916
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  918
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  920
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  922
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  924
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  926
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  928
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  930
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  932
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  934
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  936
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  938
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  940
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  942
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  944
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  12 (X_ConfigureWindow)
Resource id in failed request:  0x3400008
Serial number of failed request:  946
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request:  150
Resource id in failed request:  0x3400005
Serial number of failed request:  947
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request:  55 (X_CreateGC)
Resource id in failed request:  0x3400005
Serial number of failed request:  948
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadGC (invalid GC parameter)
Major opcode of failed request:  60 (X_FreeGC)
Resource id in failed request:  0x3400011
Serial number of failed request:  949
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request:  14 (X_GetGeometry)
Resource id in failed request:  0x3400005
Serial number of failed request:  950
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400005
Serial number of failed request:  951
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  GLXBadDrawable
Major opcode of failed request:  150
Serial number of failed request:  953
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request:  150
Resource id in failed request:  0x3400008
Serial number of failed request:  954
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request:  55 (X_CreateGC)
Resource id in failed request:  0x3400008
Serial number of failed request:  955
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadGC (invalid GC parameter)
Major opcode of failed request:  60 (X_FreeGC)
Resource id in failed request:  0x3400012
Serial number of failed request:  956
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
Major opcode of failed request:  14 (X_GetGeometry)
Resource id in failed request:  0x3400008
Serial number of failed request:  957
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  3 (X_GetWindowAttributes)
Resource id in failed request:  0x3400008
Serial number of failed request:  958
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  GLXBadDrawable
Major opcode of failed request:  150
Serial number of failed request:  960
xerror_handler: X failed, continuing
Box86 with Dynarec v0.2.9 2b247838 built on Jan  8 2023 21:15:40
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
[2023-01-08 21:49:11] Background update loop checking for update. . .
[2023-01-08 21:49:11] Checking for available updates...
[2023-01-08 21:49:11] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
[2023-01-08 21:49:11] Manifest download: send request
[2023-01-08 21:49:11] Manifest download: waiting for download to finish
[2023-01-08 21:49:11] Manifest download: finished
[2023-01-08 21:49:11] Download skipped by HTTP 304 Not Modified
[2023-01-08 21:49:11] Nothing to do

**Comment by ptitSeb** [comment]
You have X11/OpenGL issue yes. Is this a bistro using Wayland? Steam needs X11, and some OpenGL (not ES) drivers.

**Comment by cantalupo555** [comment]
`orangepi@orangepi5:~$ steam`
`/usr/local/bin/steam: line 5: /home/orangepi/steam/bin/steam: No such file or directory`

`orangepi@orangepi5:~$ ls -lh /usr/local/bin/steam`
`-rwxr-xr-x 1 root root 141 Jan  9 06:03 /usr/local/bin/steam`

What must be the problem?

**Comment by ptitSeb** [comment]
Box86 is not installed, or at least systems binfmt needs to be restarted

**Comment by aaron9412** [comment]
Oh boy am I not going to know how to do that.

(Thanks for your time ptitSeb and MastaG anyway. Yall do some great work.)

I looked into libreelec and botocera but it looks like neither of them will be easy to get box86 on, so no steam.
I read through the thread and I have installed MastaG's Fedora 36 workstation image to test.
Saw chewwitt's kernel, I assume it has the patches.
I don't know if chewwitt's kernel is built for a specific OS. I will try to install cmake and install it on (in?) Fedora first, (try)..
If it doesn't include the driver, I guess some other step after to make/install the panfrost driver.
Also, since the gnome on xorg will not load in Fedora 36, maybe some other step to allow X11 calls.

You can take a guess how that is going to go though... : ) Out of my league here.
Thanks again though!

**Comment by ptitSeb** [comment]
So X11/OpenGL issue here. Nothing specific to box86 I'm afraid. Closing the ticket.
