### ISSUE TITLE
LabVIEW launch error Symbol XrmStringToQuark not found

### ISSUE THREAD

**Issue by Botspot** [ptitSeb/box86#751]
I am trying to run an old 32-bit version of LabVIEW on my Pi4. See https://wiki.ubuntu.com/LabVIEW and https://github.com/lenartj/labview
Progress went fairly well but I'm not sure how to proceed with this latest error.
This was the output:
```
$ BOX86_LOG=1 BOX86_LD_LIBRARY_PATH="./:lib/:lib32/:x86/:i686/:$PWD/libs" ./merged/usr/local/lv61/labview
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Cores:4
Warning, unsupported BOX86_LD_PRELOAD=libX11.so.6 for [sof-bin] in /etc/box86.box86rcParams database has 20 entries
Box86 with Dynarec v0.2.9 2b247838 built on Jan  8 2023 01:14:47
BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/:/tmp/labview/libs/
Using default BOX86_PATH: ./:bin/
Counted 52 Env var
Looking for ./merged/usr/local/lv61/labview
Rename process to "labview"
Using emulated /tmp/labview/libs/libLVMesaGL.so.3
Using native(wrapped) libX11.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) libXext.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Error: PltResolver: Symbol XrmStringToQuark(ver 0: XrmStringToQuark) not found, cannot apply R_386_JMP_SLOT 0x894bef0 (0x81459c6) in /tmp/labview/merged/usr/local/lv61/labview
```
And here are the commands to reproduce it. As nothing is interactive, you can paste them all into a bash terminal at once.
```
IFS=$'\n'
sudo apt install -y alien fakeroot

mkdir /tmp/labview
cd /tmp/labview
wget ftp://ftp.heise.de/pub/ct/spezial/labviewlinux.zip
unzip labviewlinux.zip

#extract rpm files
mkdir extract
cd extract
fakeroot alien --scripts --target=all -s ../LabVIEW61Linux/*.rpm

#combine them into 'merged' folder
mkdir ../merged
for i in $(find -maxdepth 1 -type d | grep -v '\./LabVIEW61Linux\|merged\|^\.$') ;do cp -a "$i/." ../merged ;done
cd ..

#make folder of libs
mkdir libs
libs="$(find ./merged/usr/local -name '*.so*')"
for lib in $libs ;do sudo cp -f "$lib" ./libs ;done

#run
BOX86_LOG=1 BOX86_LD_LIBRARY_PATH="./:lib/:lib32/:x86/:i686/:$PWD/libs" ./merged/usr/local/lv61/labview
```

My investigations uncovered the following facts:
- `libx11-6` provides the `XrmStringToQuark` symbol.
- `libx11-6` is installed on my system and is located at `/usr/lib/arm-linux-gnueabihf/libX11.so.6`.
- Box86 does issue a strange warning about libX11.so.6 in its early launch output.
    `Warning, unsupported BOX86_LD_PRELOAD=libX11.so.6 for [sof-bin] in /etc/box86.box86rcParams database has 20 entries`
    I am not sure if that is related.
- I tried removing these two lines from `/etc/box86.box86rc`:
    ```
    [sof-bin]
    BOX86_LD_PRELOAD=libX11.so.6
    ```
    This removed the "`Warning, unsupported BOX86_LD_PRELOAD`" error on box86 launch, but all other output stayed the same.
- I have tried reinstalling the `libx11-6` package but it made no difference.

Thank you in advance for any help or advice. One of my university classes will be using LabVIEW in a month or two, so it would be great if I got it running on ARM.

**Comment by ptitSeb** [comment]
Ok, it seems to works now for me. At least I could start a blank program and put random object on the design. Didn't tried a working design or loading an example, so some symbols might still be missing. But for now, it looked good.

**Comment by Botspot** [comment]
> Ok, it seems to works now for me. At least I could start a blank program and put random object on the design. Didn't tried a working design or loading an example, so some symbols might still be missing. But for now, it looked good.

Same here. Thank you for the quick fix.

The goal here is to use LabView to communicate with a Lego robotics kit over USB. @ptitSeb, does Box86 support programs that use USB communication? Is it likely to work without any workarounds?

**Comment by Botspot** [comment]
I have noticed one bug. When trying to "Open VI" from the first window dialog, the files listed are incorrect.
![image](https://user-images.githubusercontent.com/54716352/213576648-77f8ce3b-099b-4f43-bbad-7001fe7238c5.png)
But this is a known issue with LabVIEW. The [suggested solution](https://wiki.ubuntu.com/LabVIEW) is to download [this file](https://wiki.ubuntu.com/LabVIEW?action=AttachFile&do=view&target=spd_readdir.so) and put it in LD_PRELOAD.

I attempted to do the same thing. After placing that new spd_readdir.so file in /tmp/labview/libs, I ran LabVIEW with this new command:
```
BOX86_LD_PRELOAD=/tmp/labview/libs/spd_readdir.so BOX86_LOG=1 BOX86_LD_LIBRARY_PATH="./:lib/:lib32/:x86/:i686/:$PWD/libs" ./merged/usr/local/lv61/labview
```
Box86 seems to succeed in loading spd_readdir.so, because it says:
```
BOX86 try to Preload /tmp/labview/libs/spd_readdir.so
#and later
Using emulated /tmp/labview/libs/spd_readdir.so
```
However, nothing changes in the file-selection window. Could you take a look at this, @ptitSeb?
If your /tmp directory got cleared out since you tested LabView last time, here is the full list of commands to run in order to reach where I am right now.
```
IFS=$'\n'
sudo apt install -y alien fakeroot

mkdir /tmp/labview
cd /tmp/labview
wget ftp://ftp.heise.de/pub/ct/spezial/labviewlinux.zip
unzip labviewlinux.zip

#extract rpm files
mkdir extract
cd extract
fakeroot alien --scripts --target=all -s ../LabVIEW61Linux/*.rpm

#combine them into 'merged' folder
mkdir ../merged
for i in $(find -maxdepth 1 -type d | grep -v '\./LabVIEW61Linux\|merged\|^\.$') ;do cp -a "$i/." ../merged ;done
cd ..

#make folder of libs
mkdir libs
libs="$(find ./merged/usr/local -name '*.so*')"
for lib in $libs ;do sudo cp -f "$lib" ./libs ;done
wget -O /tmp/labview/libs/spd_readdir.so https://wiki.ubuntu.com/LabVIEW?action=AttachFile&do=get&target=spd_readdir.so

#run
BOX86_LD_PRELOAD=/tmp/labview/libs/spd_readdir.so BOX86_LOG=1 BOX86_LD_LIBRARY_PATH="./:lib/:lib32/:x86/:i686/:$PWD/libs" ./merged/usr/local/lv61/labview
```

**Comment by ptitSeb** [comment]
Ok, I think I have it working now. I could browse the folders and open stuffs and it seems to works.

(note thta the downloaded `spd_readdir.so` was 0-sized after the script. Not sure what went wrong and I just downloaded the file using chrome to get the file. Maybe it's nothing, maybe not, I leave that to you to debug)

**Comment by ptitSeb** [comment]
Note the some (at least 1) example  crashes labview. I have confirmed it also crashes on a regular x86 PC, so it's not box86 specific.
After some debugging, what is happening is that at the beggining of `MapDigitalPlots__FPPUciP7ObjListT2PPP16MultiPlotDataRecG6TDIterPUciiiPiiT10_` function, a local is created (with a simple `0x0832b0ae: lea    -0x48(%ebp),%eax`) and `__18DigitalDataWrapperPUcG6TDIter` is called with that pointer. Issue is field `+0x2c` is initialized to 0 (like all other field) but then never set to any other value. But this field (that is a pointer) is then used later in a `SkipTypeDefPtr__FG6TDIter` call and will crash, trying to get `NULL + 0x2` value.

**Comment by Botspot** [comment]
Is there additional debug to see when box86 fails to load a needed lib?
```
Error initializing needed lib xlvkde.so
```
I ask this because I get a SEGFAULT when clicking a particular button in any LabVIEW project, and the stack trace says something about xlvkde.so.
![Screenshot from 2023-01-22 08-23-08](https://user-images.githubusercontent.com/54716352/213920904-47359f76-b744-4bc2-b3c4-3e368af3a28a.png)
```
Error: PltResolver: Symbol XFillArcs(ver 0: XFillArcs) not found, cannot apply R_386_JMP_SLOT 0x894bc38 (0x8144ee6) in /tmp/labview/merged/usr/local/lv61/labview
17427|SIGSEGV @0xedb7ff8c (???(0xedb7ff8c)) (x86pc=0xf7d48ce4//tmp/labview/merged/usr/local/lv61/resource/xlvkde.so:"/tmp/labview/merged/usr/local/lv61/resource/xlvkde.so/__do_global_dtors_aux + 58", esp=0xf70a9b38, stack=0xf68ab000:0xf70ab000 own=(nil) fp=0xf70a9bf0), for accessing 0xdfd4 (code=1/prot=0), db=0x654bb480(0xedb7ff80:0xedb8000c/0xf7d48cde:0xf7d48cfb//tmp/labview/merged/usr/local/lv61/resource/xlvkde.so/__do_global_dtors_aux + 58:clean, hash:6a3af890/6a3af890)
EAX:0x00000000 ECX:0x00000000 EDX:0x0000dfd4 EBX:0xf7d50fd8 
ESP:0xf70a9b38 EBP:0xf70a9b40 ESI:0xf70a9ba0 EDI:0x00000002 
ESP-0x10:0x08890878 ESP-0x0c:0x654b8b78 ESP-0x08:0xf70a9b40 ESP-0x04:0x0814607a
ESP+0x00:0xf70a9b58 ESP+0x04:0xf7d50fd8 ESP+0x08:0xf70a9b4c ESP+0x0c:0xf7d4ec25
Segmentation fault
```
I am not sure if this "Show VI Hierarchy" button is necessary for what I will be doing with LabVIEW, but it is strange in any case, as the `xlvkde.so` lib exists in three places.
```
$ find -name 'xlvkde.so'
./extract/labview61-app-6.1/usr/local/lv61/resource/xlvkde.so
./merged/usr/local/lv61/resource/xlvkde.so
./libs/xlvkde.so
```
Is there a good resource to learn debugging skills? I think the ability to watch functions crash inside a program is a useful skill to have.

**Comment by ptitSeb** [comment]
The source of the error is probably just `Error: PltResolver: Symbol XFillArcs...`
I'll add that function.

**Comment by ptitSeb** [comment]
Juste added the function, the menu seems to be working fine now.

**Comment by Botspot** [comment]
OK at this stage I do not predict much more testing can occur until my class begins to use LabVIEW. It is possible that once we start using it, more problems will appear. But for now I do not know anything else to try.

@ptitSeb, would you like for this issue to be closed for now?

**Comment by ptitSeb** [comment]
Yeah, I think this one can be closed. Open a new one if something new happens while using it.

**Comment by Botspot** [comment]
OK.
