### ISSUE TITLE
New steam big picture mode crashes on launch

### ISSUE THREAD

**Issue by theofficialgman** [ptitSeb/box86#757]
The old big picture mode has been fully removed. the new big picture mode has not worked (ever since it was added in beta)

Error output is as follow at the end
```
20122|SIGSEGV @0xa6cefa94 (???(0xa6cefa94)) (x86pc=0xe4efb22b//home/user/.local/share/Steam/ubuntu12_32/steamui.so:"/home/user/.local/share/Steam/ubuntu12_32/steamui.so + 0x6b3222", esp=0xf2860d64, stack=0xf206d000:0xf286d000 own=(nil) fp=0xf2860cc8), for accessing (nil) (code=1/prot=0), db=0x7b89e550(0xa6cefa88:0xa6cefae4/0xe4efb222:0xe4efb239//home/user/.local/share/Steam/ubuntu12_32/steamui.so + 0x6b3222:clean, hash:6a5b59f1/6a5b59f1)
EAX:0xe60c4bc0 ECX:0x00000000 EDX:0xe15c6df8 EBX:0xe60aafa8 
ESP:0xf2860d64 EBP:0xf2860f78 ESI:0xe60c4bc0 EDI:0x00000000 
ESP-0x10:0xe60aafa8 ESP-0x0c:0xe60c4bc0 ESP-0x08:0xe4efb222 ESP-0x04:0xe60c4bc0
ESP+0x00:0xf2860e58 ESP+0x04:0xe598a73b ESP+0x08:0xe4efb1dc ESP+0x0c:0x75bec8b0
20122|Double SIGSEGV (code=1, pc=0xa6cefa94, addr=(nil))!
```

I know this isn't enough for debugging but should be very easy to replicate on your end

**Comment by ptitSeb** [comment]
Yes, I can reproduce on my side. I'll probably need time for that one, debugging steam is always complicated.

**Comment by ptitSeb** [comment]
BigPicture doesn't crash anymore for me, but it doesn't work as it use steamwebhelper, and this one is still not working on box64.

**Comment by yi-yunseok** [comment]
Hopefully solve this.

**Comment by ptitSeb** [comment]
Box64 is now running steamwebhelper correctly, including the BigPicture mode. But, you need lots of RAM for that, and 4GB only system will not work. 
You need latest box64 and box86 and it should work.

Can you check so this ticket can be closed.

**Comment by theofficialgman** [comment]
closing as fixed.
