### ISSUE TITLE
Steam Install Issues / disabled binfmt_misc kernel support

### ISSUE THREAD

**Issue by Takiiiiiiii** [ptitSeb/box86#761]
I'm running into issues with the Steam install script that I can't solve. After compiling Box86 and Box64 and running the steam install script, I get the following printout in the terminal by executing 'steam' :
![1](https://user-images.githubusercontent.com/43725718/219899914-a48c2828-ca01-4748-9add-1c625330fa6c.JPG)

It seems like the steam binary is not executing with Box86, so I executed it manually and it started the initial update process:
![2](https://user-images.githubusercontent.com/43725718/219900066-6d4f3237-940a-4c83-a5b4-3f1e1a3ff7ca.JPG)

The update completes and I am still unable to launch steam using the command steam, so I  repeat the previous step and I get a fatal error: `Failed to load steamui.so - dlerror(): Cannot dlopen("steamui.so"/0x64913970, 2)`
![4](https://user-images.githubusercontent.com/43725718/219900182-43089ceb-7d33-4892-9bc6-49cd78079ae6.JPG)

It seems like this install is supposed to be straightforward, so I'm not sure what is causing this current issue.

**Comment by cantalupo555** [comment]
You can try to use the already compiled .deb packages.

https://github.com/ptitSeb/box64/blob/main/docs/COMPILE.md
https://github.com/ptitSeb/box86/blob/master/docs/COMPILE.md
https://github.com/ptitSeb/box86/blob/master/docs/X86WINE.md

I also installed wine and winetricks.

**Comment by ptitSeb** [comment]
@Takiiiiiiii you need to restart your system after box86/box64 installation, or at least restart the binfmt service.

Anyway, steam will not work for now because of some internal changes (on steam side), unless you use the `steam_chrome` branch of box64. If you have no idea what I am talking about, then just wait untill box64 officialy support steamwebhelper or you'll have just a blank screen instead of the login dialog box (see #760 )

**Comment by Takiiiiiiii** [comment]
It was like this after numerous reboots. I actually tried to get this working on a bunch of boards and wasn't able to get around this issue. I almost wouldn't mind if I managed to get to the blank login screen.

**Comment by ptitSeb** [comment]
So, you are using Termux on a phone @Takiiiiiiii ?
This doesn't support binfmt, so you need to use `BOX64_BASH` and run the steam shell script using box64.

**Comment by Takiiiiiiii** [comment]
No, I've been doing compatibility testing on a few RK3588 boards. I planned to start adding game reports for a lot of stuff to your other repo, but a lot of things that I own need Steam for verification. If I use the steam_chrome branch, can I run games with box86 while box64 runs the client for DRM?

**Comment by ptitSeb** [comment]
If you have box86 & box64 (`steam_chrome` branch) both installed and working on your system, yes, you run steam and launch steam game

**Comment by Takiiiiiiii** [comment]
@ptitSeb 
Alright, I've gone ahead and started a fresh server image of Ubuntu 22.04 on the Khadas Edge2. I installed a DE and the latest panfork driver. I then compiled box86 from source and compiled the steam_chrome branch from source. Installed wine86 and made sure it was functional by using wine winecfg to do the initial install. I also installed winetricks.

I then went into the box86 folder from my git clone and ran your steam install script. After the script was done, I tried to launch steam from the terminal with `steam` but it failed. 
![box2](https://user-images.githubusercontent.com/43725718/220191404-dc13ddb4-df6d-4db8-99b2-01a3e697ccdf.JPG)

I got around this on my other two boards by entering this into terminal: `box86 [path to box86 bash script] steam`

I saw a video that you did about the new steam_chrome branch and you did not do this, so I decided to poke around and I changed the steam.sh script to an executable and I did the same for `/home/khadas/.local/share/Steam/ubuntu12_32/steam`
![box3](https://user-images.githubusercontent.com/43725718/220191997-dd25f46f-f188-4260-a285-f47f0df21b67.JPG)
![box1](https://user-images.githubusercontent.com/43725718/220192020-66570544-d337-462f-b96b-c156f39d99e2.JPG)

Doing all of that allowed the steam client to fully update (I've always been able to get to this point).

After doing all of that, I still get the `dlerror(): Cannot dlopen("steamui.so"/0x655466f0, 2)` error message. :[

![box4](https://user-images.githubusercontent.com/43725718/220192401-148dcc9d-d27b-40b8-bf58-99ca53328e51.JPG)

Do you have any idea what is causing this?

**Comment by Takiiiiiiii** [comment]
If I try to launch steam without using` box64 steam`, I get this error:
```
khadas@Khadas:~$ steam
steam.sh[53327]: Running Steam on ubuntu 22.04 64-bit
steam.sh[53327]: STEAM_RUNTIME is enabled by the user
setup.sh[53393]: Steam runtime environment up-to-date!
/home/khadas/.local/share/Steam/steam.sh: line 421: /home/khadas/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-check-requirements: cannot execute binary file: Exec format error
steam.sh[53327]: steam-runtime-check-requirements failed with an unexpected nonzero exit status. Trying to continue
/home/khadas/.local/share/Steam/steam.sh: line 792: /home/khadas/.local/share/Steam/ubuntu12_32/steam: cannot execute binary file: Exec format error
khadas@Khadas:~$
```

**Comment by ptitSeb** [comment]
You are still missing binfmt integration. just `steam` should run. What happens is the x86_64 software is not detected and box64 is not automaticaly launched, and so it just fail.
Did you `sudo make install` the box64 install too? and did you restart the binfmt service?
If you build box64 from sources in your home, running `~/box64/tests/test01` should work. It's useless to go further if this doesn't work.

**Comment by Takiiiiiiii** [comment]
Yes, I used sudo make install for box64. As for the binfmt, I rebooted the system after installing Box86/64. I based my builds for both of those on what this script does: https://github.com/NicoD-SBC/armbian-gaming/blob/main/armbian-gaming.sh

As for the test01, I cannot run it by entering only that command in the terminal. I need to put box64 before it. After that, I can see the hello message.

Here's doing make install for box64:
`khadas@Khadas:~/box64$ cd build
khadas@Khadas:~/box64/build$ sudo make install
[sudo] password for khadas:
[  2%] Built target dynarec_native
[  2%] Built target WRAPPERS
[  9%] Built target native_pass0
[ 16%] Built target native_pass1
[ 23%] Built target native_pass2
[ 30%] Built target native_pass3
[ 31%] Built target dynarec
[100%] Built target box64
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/bin/box64
-- Up-to-date: /etc/binfmt.d/box64.conf
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libstdc++.so.5
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libstdc++.so.6
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
-- Up-to-date: /usr/lib/x86_64-linux-gnu/libpng12.so.0
-- Up-to-date: /etc/box64.box64rc
`

Here's the output of the other command:
`khadas@Khadas:~/box64/build$ sudo systemctl restart systemd-binfmt
Job for systemd-binfmt.service failed because the control process exited with error code.
See "systemctl status systemd-binfmt.service" and "journalctl -xeu systemd-binfmt.service" for details.

khadas@Khadas:~/box64/build$ systemctl status systemd-binfmt.service
× systemd-binfmt.service - Set Up Additional Binary Formats
     Loaded: loaded (/lib/systemd/system/systemd-binfmt.service; static)
     Active: failed (Result: exit-code) since Mon 2023-02-20 21:53:49 UTC; 27s ago
       Docs: man:systemd-binfmt.service(8)
             man:binfmt.d(5)
             https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html
             https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
    Process: 5570 ExecStart=/lib/systemd/systemd-binfmt (code=exited, status=1/FAILURE)
   Main PID: 5570 (code=exited, status=1/FAILURE)
        CPU: 11ms

Feb 20 21:53:49 Khadas systemd[1]: Starting Set Up Additional Binary Formats...
Feb 20 21:53:49 Khadas systemd-binfmt[5570]: Failed to add binary format: No such file or directory
Feb 20 21:53:49 Khadas systemd-binfmt[5570]: Failed to add binary format: No such file or directory
Feb 20 21:53:49 Khadas systemd[1]: systemd-binfmt.service: Main process exited, code=exited, status=1/FAILURE
Feb 20 21:53:49 Khadas systemd[1]: systemd-binfmt.service: Failed with result 'exit-code'.
Feb 20 21:53:49 Khadas systemd[1]: Failed to start Set Up Additional Binary Formats.

khadas@Khadas:~/box64/build$ journalctl -xeu systemd-binfmt.service
░░ The unit systemd-binfmt.service has entered the 'failed' state with result 'exit-code'.
Feb 20 21:43:13 Khadas systemd[1]: Failed to start Set Up Additional Binary Formats.
░░ Subject: A start job for unit systemd-binfmt.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit systemd-binfmt.service has finished with a failure.
░░
░░ The job identifier is 2494 and the job result is failed.
Feb 20 21:53:49 Khadas systemd[1]: Starting Set Up Additional Binary Formats...
░░ Subject: A start job for unit systemd-binfmt.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit systemd-binfmt.service has begun execution.
░░
░░ The job identifier is 2984.
Feb 20 21:53:49 Khadas systemd-binfmt[5570]: Failed to add binary format: No such file or directory
Feb 20 21:53:49 Khadas systemd-binfmt[5570]: Failed to add binary format: No such file or directory
Feb 20 21:53:49 Khadas systemd[1]: systemd-binfmt.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStart= process belonging to unit systemd-binfmt.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Feb 20 21:53:49 Khadas systemd[1]: systemd-binfmt.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit systemd-binfmt.service has entered the 'failed' state with result 'exit-code'.
Feb 20 21:53:49 Khadas systemd[1]: Failed to start Set Up Additional Binary Formats.
░░ Subject: A start job for unit systemd-binfmt.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit systemd-binfmt.service has finished with a failure.
░░
░░ The job identifier is 2984 and the job result is failed.
lines 56-96/96 (END)

`

I was using -DRK3399=1, but I wanted to use the 3588 one that was added to the COMPILE.md page. Here's that printout:

`khadas@Khadas:~/box64/build$ cmake .. -DRK3588=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
-- Configuring done
-- Generating done
-- Build files have been written to: /home/khadas/box64/build
khadas@Khadas:~/box64/build$ make -j4
Scanning dependencies of target dynarec_native
Consolidate compiler generated dependencies of target dynarec_native
[  0%] Built target WRAPPERS
[  2%] Built target dynarec_native
Consolidate compiler generated dependencies of target native_pass1
Consolidate compiler generated dependencies of target native_pass2
Consolidate compiler generated dependencies of target native_pass0
Consolidate compiler generated dependencies of target native_pass3
[  9%] Built target native_pass2
[ 16%] Built target native_pass0
[ 23%] Built target native_pass1
[ 30%] Built target native_pass3
[ 31%] Built target dynarec
Consolidate compiler generated dependencies of target box64
[100%] Built target box64
`

I did the `sudo make install` command, followed by the `sudo systemctl restart systemd-binfmt` command that doesn't work. I then rebooted and tried to do test01 and I cannot do it without having box64 before the path.

```
khadas@Khadas:~$ ~/box64/tests/test01
-bash: /home/khadas/box64/tests/test01: cannot execute binary file: Exec format error
khadas@Khadas:~$ ^C
khadas@Khadas:~$ box64 ~/box64/tests/test01
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:8
Params database has 15 entries
Box64 with Dynarec v0.2.1 fb5ac9c4 built on Feb 20 2023 19:38:14
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 27 Env var
Looking for /home/khadas/box64/tests/test01
Rename process to "test01"
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Hello x86_64 World!
```

**Comment by Takiiiiiiii** [comment]
`update-binfmts --display` shows box64 and box86 as disabled. I cannot enable them with the option.

![binfmts](https://user-images.githubusercontent.com/43725718/220208758-43cda9db-7129-43f6-bdbc-238a2da4701a.JPG)

**Comment by Takiiiiiiii** [comment]
I don't know if this is another red herring, but my binfmt_misc module is missing from my stock kernel:


![](https://cdn.discordapp.com/attachments/878848947748237443/1077458988876177408/image.png)


![](https://cdn.discordapp.com/attachments/878848947748237443/1077459230719746158/image.png)

**Comment by Takiiiiiiii** [comment]
@ptitSeb 

Recompiling only the kernel module didn't work, so I just did the entire kernel. I now have working binfmt_misc for a bunch of entries (many qemu ones that were installed during the kernel building process & python 3).

However, I cannot enable box86 or box64. I've tried to rebuild them to see if that changed anything and it doesn't. Any ideas?

`khadas@Khadas:~$ sudo update-binfmts --display box64.conf
[sudo] password for khadas:
box64.conf (disabled):
     package = box64
        type = magic
      offset = 0
       magic = \x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff                    \xff\xff
        mask =
 interpreter = /usr/local/bin/box64
    detector =
khadas@Khadas:~$ sudo update-binfmts --enable box64.conf
update-binfmts: warning: unable to close /proc/sys/fs/binfmt_misc/register: Invalid argument
update-binfmts: exiting due to previous errors
`

**Comment by Takiiiiiiii** [comment]
Here's the view. It keeps looking steamwebhelper.sh errors before giving up and restarting the same messages.
![Uploading almost.JPG…]()

**Comment by ptitSeb** [comment]
Oh, yes, qemu and box86/box64 conflict on the binfmt side. I don't advise installing both.

**Comment by Takiiiiiiii** [comment]
![image](https://user-images.githubusercontent.com/43725718/220469766-2f334114-9fac-4bd8-b7eb-3366340290fd.png)
I think this is as far as I can get without changes to the steam branch. I'm now as far as #760

**Comment by cantalupo555** [comment]
> ![image](https://user-images.githubusercontent.com/43725718/220469766-2f334114-9fac-4bd8-b7eb-3366340290fd.png) I think this is as far as I can get without changes to the steam branch. I'm now as far as #760
> 
> There's a lot of activity from `renderer_crash` while this is loading. Took about 2 minutes to get to this error screen.

I got the same result.

**Comment by Takiiiiiiii** [comment]
@ptitSeb 

I found a temporary solution to this issue. I installed FEX and tested the full Steam client for about a day or so with the auto-login option enabled. I had an assumption that box64 would skip over the troubling area using this mode, but I needed to verify. I removed FEX from update-binfmts (this is required), and I was able to launch steam with box64 steam in the terminal. To my surprise, the mini Steam client loaded up as it is the default option at this point. I am able to run games directly from Steam now. 

Not an ideal solution since it involves installing a conflicting emulator, but it works.
@cantalupo555

**Comment by cantalupo555** [comment]
@Takiiiiiiii 

How can I get to the same result?

**Comment by ptitSeb** [comment]
@Takiiiiiiii and now you ahve a system where nothing works it seems. I don't call taht a solution.

**Comment by Takiiiiiiii** [comment]
> @Takiiiiiiii and now you have a system where nothing works it seems. I don't call that a solution.

No, everything works. I can use FEX and box64/86 at the same time. I found this solution on a hunch.

**Comment by ptitSeb** [comment]
It sems you are not interested in fix box64, so the ticket is closed.

**Comment by Takiiiiiiii** [comment]
> It sems you are not interested in fix box64, so the ticket is closed.

??? I spent 5 days trying to solve this problem. I wouldn't say I am not interested in fixing box64. The problem is that you don't have hardware that exhibits the issues we are having with RK3588 boards.

**Comment by Takiiiiiiii** [comment]
> and I spent 1 year on steamwebhelper issue.
> 
> I'm also working on this on Discord channel with someone that have the same begavior. I still don't understand where it comes from, because on my Odroid N2 freshly flashed with Armbian, I didn't reproduce the issue myself. But a work around like that will not help fixing the issue, and, in your case, the problem is solved. So yes, I close the ticket, because there is nothing more to say here, it works for you now.


I would have gladly donated hardware or had companies give you free boards. I have duplicates of a bunch of RK3588 boards and I don't need them all.

**Comment by ptitSeb** [comment]
I have a Radxa RK3588, it should be enough thanks. What OS image did you used, I can start by that.

**Comment by cantalupo555** [comment]
> I have a Radxa RK3588, it should be enough thanks. What OS image did you used, I can start by that.

Armbian 22.11 Jammy Gnome
https://www.armbian.com/orangepi-5/

**Comment by cantalupo555** [comment]
> Ok, will start with that. I'm using Rock 5, but that should be really the same as long as steam goes

Yes, it shouldn't change anything.

**Comment by Takiiiiiiii** [comment]
> I have a Radxa RK3588, it should be enough thanks. What OS image did you used, I can start by that.

Ubuntu 22.04 with Panfork drivers. AFAIK, box doesn't work with the Rockchip blob drivers (unless one of you were able to get it working).

**Comment by ptitSeb** [comment]
It should work with gl4es, but panfork is probably a better option for steam.

**Comment by cantalupo555** [comment]
> Ubuntu 22.04 with Panfork drivers. AFAIK, box doesn't work with the Rockchip blob drivers (unless one of you were able to get it working).

I use this driver for Armbian.
![](https://i.imgur.com/j9V5DSU.png)

**Comment by ptitSeb** [comment]
I can reproduce the issue on my rk3588 with armbian (while I coulnd't on Armbian on an N2). I can investigate now.

**Comment by ptitSeb** [comment]
I pushed a workaround on box64 branch for those interrested. It should works now.

**Comment by cantalupo555** [comment]
> I pushed a workaround on box64 branch for those interrested. It should works now.

Problem solved, I am now able to login to steam.
Thanks you!

**Comment by Takiiiiiiii** [comment]
@ptitSeb Great work! Will it ever be possible to get Big Picture supported?

**Comment by ptitSeb** [comment]
FYI, I have updated box64. It is now compatible with steamwebhelper, and also run the BigPicture.
I have updated the README of box86 with the info.

Also, I saw your video @Takiiiiiiii . There is a lot of work on it, that's for sure, with a lot of game used. I would suggest you try Armbian instead of the default vendor OS. Armbian is well maintained, up-to-date, you can find support on  Discord/IRC, and binfmt is enable by default. You can also easily find some ppe for Panfork.

**Comment by Takiiiiiiii** [comment]
I'll try it now. The boards that I used in that video don't have an Armbian build, so I didn't have any other choice :\

I'm using a NanoPi R6S right now on Armbian. It has some other challenges that I didn't have to deal with before. I think some of the panfork dependencies for 32bit GL are broken with the 2/28 build files. It will complain that there is no g610-firmware:armhf when you try to install libgl1-mesa-dri:armhf. Without that, you don't have libGL.so.1

**Comment by Takiiiiiiii** [comment]
The only bypass that I had was to copy my entire /usr/lib/armhf folder from my working SBC to the NanoPi. I have tested BigPicture. It works, but it doesn't feel like the UI is accelerated. It's still a big step.

**Comment by ptitSeb** [comment]
Yeah, it's not super smooth, I have to analyse what's going on, but I was focussed on compatibility to get things working. I'll analyse later if I see something about speed (like opcode missing from the dynarec...)

**Comment by Takiiiiiiii** [comment]
I'm planning to make another video showing what it looks like at this point.

**Comment by ptitSeb** [comment]
Sounds good.
It seems there is a package dependancies yeah, hopefully it will be fixed soon.

FYI, I have "Heroic launcher" running also, with box86+box64 (simply using the AppImage). That alows easy download and play of games from GOG and Epic store.

**Comment by Takiiiiiiii** [comment]
@ptitSeb Do you have a Discord server for box/can you make one?

**Comment by ptitSeb** [comment]
I don't have a Discord server for box. I'm present on a few Discord server with a specific box channel (like Armbian or Radxa), but yeah, you can create one, no problem, and I'll join.
