### ISSUE TITLE
Error during installation on make command after 29%

### ISSUE THREAD

**Issue by Alefunshow** [ptitSeb/box86#769]
![image](https://user-images.githubusercontent.com/38226690/221345971-266c6c6e-d568-4100-9b60-673d1b6c3489.png)

Hi, every time that I try the make command it stop at 29% with this error.
I've tried the "make -j2" the "make -j3" the "make -j$(nproc)" but all three still not building.

I'm using a RPI 3B.

**Comment by Alefunshow** [comment]
![image](https://user-images.githubusercontent.com/38226690/221345971-266c6c6e-d568-4100-9b60-673d1b6c3489.png)

Hi, every time that I try the make command it stop at 29% with this error.
I've tried the "make -j2" the "make -j3" the "make -j$(nproc)" but all three still not building.

I'm using a RPI 3B.

**Comment by ptitSeb** [comment]
Just use `make` without any `-j` You are running out of memory while compiling...

**Comment by Alefunshow** [comment]
Thank you very much!

**Comment by ptitSeb** [comment]
So it worked? the ticket can be closed?
