### ISSUE TITLE
Psychonauts fails to load libstdc++.so.6 on Chroot

### ISSUE THREAD

**Issue by Fancy2209** [ptitSeb/box86#772]
Running Ubuntu 22.04 trough Termux
[Psylog.log](https://github.com/ptitSeb/box86/files/10911680/Psylog.log)

**Comment by ptitSeb** [comment]
there is a copy libstdc++.so.6 in box86. So it should be availble if you build and install box86 according to the COMPILE.md.

**Comment by Fancy2209** [comment]
> there is a copy libstdc++.so.6 in box86. So it should be availble if you build and install box86 according to the COMPILE.md.

Oh, i did compile box86 and do a make install, but I guess that I need to use BOX86_LD_PRELOAD on the lib?

**Comment by ptitSeb** [comment]
Did you install in a specific folder?
box86 goes look for standard folder for the x86 libs, but if it's installed in a specific location, you'll need to use `BOX86_LD_LIBRARY_PATH` yes (or `LD_LIBRARY_PATH`, it will also be checked)

**Comment by Fancy2209** [comment]
Did a make install again and now it works!
