### ISSUE TITLE
Failed to run some program on Android (Termux)

### ISSUE THREAD

**Issue by CosineMath** [ptitSeb/box86#782]
I just write this program
```C

typedef unsigned size_t;
typedef unsigned ssize_t;

#define noinline __attribute__ ((noinline))

noinline ssize_t sys_write(int fd, void* buf, size_t count) {
    asm("push ebx");
    asm("mov eax, 0x4");
    asm("mov ebx, DWORD PTR [esp + 0x8]");
    asm("mov ecx, DWORD PTR [esp + 0xc]");
    asm("mov edx, DWORD PTR [esp + 0x10]");
    asm("int 0x80");
    asm("pop ebx");
    asm("ret");
}

noinline void sys_exit(int status) {
    asm("mov eax, 0x1");
    asm("mov ebx, DWORD PTR [esp + 0x4]");
    asm("int 0x80");
    asm("ret");
}

noinline void sys_enosys(void* addr) {
    asm("push ebx");
    asm("mov eax, 1024");
    asm("mov ebx, DWORD PTR [esp + 0x8]");
    asm("int 0x80");
    asm("pop ebx");
    asm("ret");
}

unsigned counter = 0;

noinline unsigned fibonacci(unsigned n) {
    counter++;
    if (n <= 1) {
        return n;
    }
    return fibonacci(n - 1) + fibonacci(n - 2);
}

noinline void println_int(unsigned i) {
    char buf[12];
    for (int i = 0; i < sizeof(buf); i++) {
        buf[i] = '0';
    }
    char *ptr = buf + sizeof(buf) - 1;
    *ptr = '\n';
    ptr--;
    do {
        *ptr = '0' + i % 10;
        ptr--;
        i /= 10;
    } while (i != 0);
    sys_write(1, buf, sizeof(buf));
}

noinline int main() {
    sys_enosys(fibonacci);
    for (unsigned i = 0; i < 40; i++) {
        unsigned f = fibonacci(i);
        println_int(f);
    }
    println_int(counter);
    return 0;
}

noinline void _start() {
    int ret = main();
    sys_exit(ret);
}

```

Compiled with `i686-linux-gnu-gcc nolibc-compile.c -o nolibc-compile -fPIE -O2 -masm=intel -nostdlib -Wl,--no-dynamic-linker`

And then run with box86: `termux-box86/usr/bin/box86 nolibc-compile`

But box86 print nothing (The Fibonacci numbers are expected).

I donwload the *.deb from Termux, and manually extract it.

**Comment by CosineMath** [comment]
[nolibc-compile.tar.gz](https://github.com/ptitSeb/box86/files/10950417/nolibc-compile.tar.gz)

This is the binary program I compiled.

**Comment by ptitSeb** [comment]
The `sys_enosys` syscall is not supported by box86. What is it supposed to do?

**Comment by CosineMath** [comment]
I think for syscall not supported should just return `-ENOSYS` and do nothing, not terminate the program.

**Comment by ptitSeb** [comment]
Yes, it's like that on box64, I must have forgotten to do this on box86.
But still, I find no documentation on this syscall, should I implement it? What's its name and what is it supposed to do?

**Comment by CosineMath** [comment]
Of course not. It is not a real syscall (as function name sys_enosys() says), just for test.

**Comment by ptitSeb** [comment]
Ah ok. well, it's the correct behaviour now.
