### ISSUE TITLE
FreeLibrary name conflict

### ISSUE THREAD

**Issue by mittorn** [ptitSeb/box86#79]
FreeLibrary conflicts with win32 FreeLibrary function. Maybe choose different name? Even if box86 will not be ported to win32, it conflicts with win32 implementations in same binary

**Comment by ptitSeb** [comment]
Ok, I'll find another name for this one.

**Comment by ptitSeb** [comment]
Ok, solved.

**Comment by mittorn** [comment]
I thought there are better names, but ok :)
