### ISSUE TITLE
Wine can not open winodw on rpi4(aarch64) through vnc

### ISSUE THREAD

**Issue by YuriSizuku** [ptitSeb/box86#791]
Both winecfg and wine notepad can not open a valid window.  
When I resize the window after wine notepad,  this window shows nothing and can not input any thing in the window. 

![QQ图片20230321132537](https://user-images.githubusercontent.com/15275959/226517212-e79c5162-3a61-4d18-b898-6a6eaf886c37.png)

![QQ图片20230321133027](https://user-images.githubusercontent.com/15275959/226517646-4b2b7e5f-a341-405b-ac61-1c3570142a73.png)

**Comment by ptitSeb** [comment]
What system are you using, what Wine version are you using?

Look at the error message, you are missing tons of armhf libs, like freetype, Xinerama, Xrender...

Install all those missing libs (armhf version, not arm64 if you are on a 64bits OS)

**Comment by YuriSizuku** [comment]
> What system are you using, what Wine version are you using?
> 
> Look at the error message, you are missing tons of armhf libs, like freetype, Xinerama, Xrender...
> 
> Install all those missing libs (armhf version, not arm64 if you are on a 64bits OS)

My rpi is pi os arm64 and wine is 8.0 stable. 
Thank you for your reply. At first I thought it was the vnc problem.
When I try to install the armhf libs, now the wine works well! 

``` shell 
sudo dpkg --add-architecture armhf && sudo apt-get update # enable multi-arch
sudo apt-get install -y libasound2:armhf libc6:armhf libglib2.0-0:armhf libgphoto2-6:armhf libgphoto2-port12:armhf \
    libgstreamer-plugins-base1.0-0:armhf libgstreamer1.0-0:armhf libldap-2.4-2:armhf libopenal1:armhf libpcap0.8:armhf \
    libpulse0:armhf libsane1:armhf libudev1:armhf libusb-1.0-0:armhf libvkd3d1:armhf libx11-6:armhf libxext6:armhf \
    libasound2-plugins:armhf ocl-icd-libopencl1:armhf libncurses6:armhf libncurses5:armhf libcap2-bin:armhf libcups2:armhf \
    libdbus-1-3:armhf libfontconfig1:armhf libfreetype6:armhf libglu1-mesa:armhf libglu1:armhf libgnutls30:armhf \
    libgssapi-krb5-2:armhf libkrb5-3:armhf libodbc1:armhf libosmesa6:armhf libsdl2-2.0-0:armhf libv4l-0:armhf \
    libxcomposite1:armhf libxcursor1:armhf libxfixes3:armhf libxi6:armhf libxinerama1:armhf libxrandr2:armhf \
    libxrender1:armhf libxxf86vm1 libc6:armhf libcap2-bin:armhf # to run wine-i386 through box86:armhf on aarch64
```

**Comment by ptitSeb** [comment]
excelent, thanks for the list of libs
