### ISSUE TITLE
Steam not working in chroot

### ISSUE THREAD

**Issue by Ilya114** [ptitSeb/box86#797]
Android 13 (Arrow OS), POCO X3 Pro, box86 0.3.1, box64 0.2.3 (Installed from repository), chroot system is Ubuntu 22.04 with multiarch
![зображення](https://user-images.githubusercontent.com/93242944/227745141-8fe5a0b7-1d78-4098-9a04-dc10606a0e2a.png)

**Comment by ptitSeb** [comment]
You are probably missing binfmt integration.

Use BOX64_BASH env. var, to point to an x86_64 version of bash (availbale in box64 repo) and use box64 to launch steam script,it should works better.

**Comment by Ilya114** [comment]
![зображення](https://user-images.githubusercontent.com/93242944/227758666-36f77baf-341e-4db4-8a59-5051d1d5d290.png)
Seems same.

**Comment by ptitSeb** [comment]
You haven't setup BOX64_BASH correctly. Look at https://box86.org/2022/09/running-bash-with-box86-box64/ for more details.

**Comment by Ilya114** [comment]
> You haven't setup BOX64_BASH correctly. Look at https://box86.org/2022/09/running-bash-with-box86-box64/ for more details.

I tried export BOX64_BASH=~/box64/tests/bash then box64 steam

**Comment by ptitSeb** [comment]
Well somethng seems wrong becuase the script complaint about not finding `steam-runtime-check-requirements` but this one should be run with box64 iirc (it will exit immediatly, but it should be found).

**Comment by ptitSeb** [comment]
You'll need to run with `BOX86_LOG=1` and you'll need a way to copy/paste more log than with a screenshot.

**Comment by Ilya114** [comment]
[log (2).txt](https://github.com/ptitSeb/box86/files/11070982/log.2.txt)

**Comment by ptitSeb** [comment]
You need `box64` also for steam. `box86` alone is not enough.

**Comment by Ilya114** [comment]
box64 already installed
![зображення](https://user-images.githubusercontent.com/93242944/227761399-9020aa5b-2fc9-42bc-9ba2-b46b6390bd77.png)

**Comment by ptitSeb** [comment]
Then setup `BOX64_BASH` and run steam with `box64`, not `box86`.

**Comment by Ilya114** [comment]
![зображення](https://user-images.githubusercontent.com/93242944/227761756-c1d27463-b4f1-42f0-a0c8-380170a9c88c.png)
(He says what binary format is wrong)

**Comment by ptitSeb** [comment]
You forgot to setup `BOX64_BASH=~/box64/tests/bash`

**Comment by Ilya114** [comment]
![зображення](https://user-images.githubusercontent.com/93242944/227761969-64d89355-aa23-4826-8547-ede66e1c1acc.png)

**Comment by ptitSeb** [comment]
still need `BOX86_LOG=1`

**Comment by Ilya114** [comment]
[log (3).txt](https://github.com/ptitSeb/box86/files/11071046/log.3.txt)
With `BOX64_LOG=1`

**Comment by ptitSeb** [comment]
No, I needed `BOX86_LOG=1`, not `BOX64_LOG=1` (it's already 1 by default)

**Comment by Ilya114** [comment]
BOX86_LOG=1 with box86 or box64? Because if i start box64, BOX86_LOG=1 not work. box86 with BOX86_LOG=1 in attached file:
[log (4).txt](https://github.com/ptitSeb/box86/files/11071090/log.4.txt)

**Comment by ptitSeb** [comment]
`BOX86_LOG=1 BOX64_BASH=~/box64/tests/bash box64 ./steam`

**Comment by Ilya114** [comment]
[log (5).txt](https://github.com/ptitSeb/box86/files/11071119/log.5.txt)

**Comment by ptitSeb** [comment]
I think your proot or whatever you are using is missing some needed syscall. The messages `src/tier0/threadtools.cpp (2377) : Assertion Failed: Function not implemented` should not happens, but are not box86/box64 fault.

**Comment by Ilya114** [comment]
I`m using chroot

**Comment by ptitSeb** [comment]
I don't know what you are using, because you never detailed your configuration. The point is: this is not a box86/box64 issue. It's a termux or whatever you are using to provide a Linux environement that doesn't simulate well enough Linux.
So, i'll close that ticket as I cannot do anything here.
