### ISSUE TITLE
Problem with callbacks

### ISSUE THREAD

**Issue by M-HT** [ptitSeb/box86#8]
Here's an example of problematic scenario with callbacks:
* SDL_OpenAudio is called with callback which uses AddCallback to add a new callback
* inside the callback function the code calls qsort which uses AddSharedCallback to add a new shared callback and then uses FreeCallback to remove the shared callback
* since qsort callback is shared, it uses the same emu as callback from SDL_OpenAudio, so removing the shared callback also removes the callback from SDL_OpenAudio
* further calls to SDL_OpenAudio callback print the text `Warning, Callback not found?!` instead of calling the callback

**Comment by ptitSeb** [comment]
The `FreeCallback` on a Shared callback should not free the emu. I'll check that, thanks!

**Comment by ptitSeb** [comment]
Commit 0398803f1b70a02253063c3e1e53518f3d7628da should have fixed it.

**Comment by M-HT** [comment]
I tested it and the problem is fixed (at least in described scenario).

**Comment by ptitSeb** [comment]
Nice, thanks for testing.
