### ISSUE TITLE
Box86 in docker works on arm linux, not on arm macos

### ISSUE THREAD

**Issue by jacobmichels** [ptitSeb/box86#806]
When I run the `box86` command in a container running on my mac host, I get `bash: /usr/local/bin/box86: cannot execute binary file: Exec format error`. The same image running on an arm64 ubuntu cloud vm is able to start and run box86 just fine. I'm not a docker expert, but I would've expected the containers to behave identically no matter the host OS. Below is the Dockerfile for the offending image. I built the image on the linux VM, then imported it onto my mac.

This dockerfile is not mine, I found it [here](https://github.com/Weilbyte/box).
```
FROM debian:bullseye-slim as build

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --yes --no-install-recommends git python3 build-essential cmake ca-certificates && \
    apt-get install --yes --no-install-recommends gcc-arm-linux-gnueabihf libc6-dev-armhf-cross libc6:armhf libstdc++6:armhf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN git clone https://github.com/ptitSeb/box86.git; mkdir /box86/build && \
    git clone https://github.com/ptitSeb/box64.git; mkdir /box64/build

WORKDIR /box86/build
RUN cmake .. -DRPI4ARM64=1 -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo && \
    make && \
    make install DESTDIR=/tmp/install

WORKDIR /box64/build
RUN cmake .. -DRPI4ARM64=1 -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo && \
    make && \
    make install DESTDIR=/tmp/install

FROM debian:bullseye-slim

COPY --from=build /tmp/install /

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --yes --no-install-recommends libc6:armhf libstdc++6:armhf && \
    apt-get -y autoremove && \
    apt-get clean autoclean && \
    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists

ENTRYPOINT ["box86"]
```

I don't need a solution, I'm just looking for a reason as to why this wouldn't work. Thanks in advance.

**Comment by ptitSeb** [comment]
If it's a mac M1, they don't support arm 32bits and will not run box86, so I suppose that the reason.

**Comment by jacobmichels** [comment]
That makes sense. Thank you!
