### ISSUE TITLE
box86 down?, box64 still respond

### ISSUE THREAD

**Issue by ikhoeyZX** [ptitSeb/box86#818]

**Comment by ikhoeyZX** [comment]
Hi, i cant download box86 version, box64 can be downloaded and installed

![Screenshot_20230430_030531_Termux](https://user-images.githubusercontent.com/79812109/235320075-6fe3b9c2-2aab-4180-8d2a-44e14a4e87c0.png)
![Screenshot_20230430_030546_Firefox Nightly](https://user-images.githubusercontent.com/79812109/235320079-764ae825-a0e4-4974-bf31-0b3bd4fbee30.png)

**Comment by ptitSeb** [comment]
This is not the correct repo to open this ticket.
I don't handle the packaging of box86 or box64 in a .deb.

Go there https://github.com/Itai-Nelken/weekly-box86-debs to open an issue.
