### ISSUE TITLE
Missing symbols in SDL2

### ISSUE THREAD

**Issue by Waterkonijn** [ptitSeb/box86#836]
Hello, upon trying to run an AGS game, it fails to start due to missing symbols with this error

`Error: PltResolver: Symbol SDL_strtokr(ver 0: SDL_strtokr) not found, cannot apply R_386_JMP_SLOT 0x846d5fc (0x80faf26) in /mnt/share/Beyond The Edge Of Owlsgard/data/ags32`

Is it possible to have this added?

**Comment by ptitSeb** [comment]
I have added the symbol. But note that you might need a fairly recent native SDL2 build to have it.

**Comment by ptitSeb** [comment]
Ok, I pushed that function too.

**Comment by ptitSeb** [comment]
Added too.
