### ISSUE TITLE
Compiling on Arch Linux (aarch64)

### ISSUE THREAD

**Issue by Sucharek233** [ptitSeb/box86#839]
I've been trying to compile box86 on arch for the past few days with no success. Well, just a little. I managed to get it compiled for armhf, but not for aarch64.

I'm compiling this on a qemu aarch64 virtual machine.

For armhf compilation I installed `arm-linux-gnueabihf-gcc` and `arm-linux-gnueabihf-glibc`. For arm64, I didn't find any packages, so I downloaded some from [here](https://developer.arm.com/downloads/-/gnu-a) (specifically `gcc-arm-10.3-2021.07-aarch64-aarch64-none-elf.tar.xz`).

Then I ran `export CC=arm-linux-gnueabihf-gcc` and `export CXX=arm-linux-gnueabihf-g++` to specify what compilers it's supposed to use. The build worked and it works on armhf. When I tried to run it on the vm (aarch64), it says `cannot execute binary file`. I asked chatgpt how to cross compile and it said I should type in `export CC_ARM64=/path/to/toolchain/aarch64-none-elf-gcc` and `export CXX_ARM64=/path/to/toolchain/aarch64-none-elf-g++` and add `CFLAGS="-march=aarch64" CXXFLAGS="-march=aarch64"` to the make command. I ran it again and it seemed that nothing has changed. And yes, I still can't run it on aarch64.

Also, adding `-DARM64=1` to cmake doesn't work.

How can I compile it for aarch64?

**Comment by ptitSeb** [comment]
No you cannot.

As mentionned in the README.md, box86 is a 32bits app exclusivly, and can only be build for 32bits system.

**Comment by Sucharek233** [comment]
Oh, ok. Thanks for your response.
