### ISSUE TITLE
Portal 2 propulsion gel not working properly

### ISSUE THREAD

**Issue by Huggo2** [ptitSeb/box86#848]
Used box86 in Android, Termux chroot with Ubuntu 22.04

Game: Portal 2 (Steam version using wine, tried many different versions)

Expected behavior: when the player is on orange gel, his speed will increase

What actually happens: nothing. But if you move the camera when player is standing on orange gel, speed will be changed. If move camera horizontally very fast, speed may increase too much that shouldn't happen normally. BOX86_DYNAREC_FASTROUND=0 doesn't help
I hope you can reproduce this because it's a very strange problem

**Comment by Huggo2** [comment]
If using BOX86_DYNAREC=0, game works very slow as expected (1-2fps), but gel works fine

**Comment by ptitSeb** [comment]
Ok,I'll have to play the game long enough to get to the point were the orange gel is available. I have probably some save with that... I'll ceck later.

**Comment by Huggo2** [comment]
Oh, you can type "map sp_a3_speed_ramp" in console for example

**Comment by ptitSeb** [comment]
Ok, should be fixed now, you can update box86 and try again.

**Comment by Huggo2** [comment]
Confirmed,it's fixed
