### ISSUE TITLE
Project - PolentaOS 

### ISSUE THREAD

**Issue by sassos14** [ptitSeb/box86#850]
I'm building this OS in python 3, there's so much to code and there will exist two versions one with GUI and the other it's just a terminal, the difficult thing is the repositories since i need to build a pc to storage all my files  and other projects too

**Comment by ptitSeb** [comment]
I'm sorry, but I don't not understand if it's a ticket with an issue or advertisement for your project?

**Comment by sassos14** [comment]
> I'm sorry, but I do not understand if it's a ticket with an issue or advertisement for your project?

i'm going to post any errors i don't understand in the future don't worry

**Comment by Hacker1245** [comment]
> > I'm sorry, but I do not understand if it's a ticket with an issue or advertisement for your project?
> 
> i'm going to post any errors i don't understand in the future don't worry

You do know this is a bug tracker for the box86 project right?

**Comment by sassos14** [comment]
> > > I'm sorry, but I do not understand if it's a ticket with an issue or advertisement for your project?
> > 
> > i'm going to post any errors i don't understand in the future don't worry
> 
> You do know this is a bug tracker for the box86 project right?

The thing is tjat some errores i can't fix it and i need help in fixing my code

**Comment by ptitSeb** [comment]
> > > > I'm sorry, but I do not understand if it's a ticket with an issue or advertisement for your project?
> > > 
> > > 
> > > i'm going to post any errors i don't understand in the future don't worry
> > 
> > 
> > You do know this is a bug tracker for the box86 project right?
> 
> The thing is tjat some errores i can't fix it and i need help in fixing my code

Is this related to box86????

**Comment by sassos14** [comment]
> > > > > I'm sorry, but I do not understand if it's a ticket with an issue or advertisement for your project?
> > > > 
> > > > 
> > > > i'm going to post any errors i don't understand in the future don't worry
> > > 
> > > 
> > > You do know this is a bug tracker for the box86 project right?
> > 
> > The thing is tjat some errores i can't fix it and i need help in fixing my code
> 
> Is this related to box86????

My OS is related to linux at least, i think you could say that

**Comment by Hacker1245** [comment]
> > > > > > I'm sorry, but I do not understand if it's a ticket with an issue or advertisement for your project?
> > > > > 
> > > > > 
> > > > > i'm going to post any errors i don't understand in the future don't worry
> > > > 
> > > > 
> > > > You do know this is a bug tracker for the box86 project right?
> > > 
> > > 
> > > The thing is tjat some errores i can't fix it and i need help in fixing my code
> > 
> > 
> > Is this related to box86????
> 
> My OS is related to linux at least, i think you could say that

dude, this isn't some place to ask for help with your project, there are plenty of other places for that, this isn't one.

**Comment by ptitSeb** [comment]
Closing this, as it doesn't seems related to box86 in any way.

Feel free to open a new ticket if you have actual issues with box86.
