### ISSUE TITLE
Running on raspberry pi os (64bit)failed.

### ISSUE THREAD

**Issue by kanerty** [ptitSeb/box86#853]
*English is not my native language; please excuse typing errors.

I want to install box86 by Pi-Apps, but I can't install its dependencie: libc6:armhf
(In fact, there are still many dependencies, here is an example)
If I install libc6:armhf, then he will prompt:
`0 software packages have been upgraded, 6 software packages have been newly installed, and 1998 software packages have to be uninstalled, and 0 software packages have not been upgraded.`

This will obviously destroy my system. I tried bing and looked at the documents but it didn't solve the problem.

I have tried
```
sudo dpkg --add-architecture armhf
sudo apt update
sudo apt install libc6:armhf
```
But still asked me to uninstall 1998 software packages.

Even if it is compiled and installed, box86 will not run.When I tried to run box86, he said: There is no such file or directory.But box86 really lies in /usr/local/bin, next to box64 (box64 can run).

What should I do?

==========
Device info:
Raspberry pi 4b 8G
Raspberry pi OS 64bit(desktop)

==========

**Comment by ptitSeb** [comment]
This is an OS issue, not really a box86 issue. I'm not sure why install libc6:armhf would uninstall 1998 packages. Last time I used RPiOS 64bits, I had no issue install base package. I notices some conflict with a few development packages, but nothing that prevented me to run box86. 
You should ask on RPi forum maybe?

**Comment by kanerty** [comment]
Actually, I asked, and he asked me to install libc6-dev-armhf-cross or libc6-armhf-cross, but it didn't work.I sincerely hope that you can check my terminal records:
[![asciicast](https://asciinema.org/a/rdZuNWvWnGOhNfXSLmbzUhecc.svg)](https://asciinema.org/a/rdZuNWvWnGOhNfXSLmbzUhecc)

**Comment by ptitSeb** [comment]
Yeah, looks like everything gets uninstalled, so you cannot do that.

I have no idea what's going on. Maybe you have more apt source, and the armhf version is not the same source as the aarh64 one? Cannot really help here, system is not my specialty.

**Comment by kanerty** [comment]
> Yeah, looks like everything gets uninstalled, so you cannot do that.
> 
> I have no idea what's going on. Maybe you have more apt source, and the armhf version is not the same source as the aarh64 one? Cannot really help here, system is not my specialty.

Well, thank you,I will continue to look for solutions.
Have a nice day. (‵▽′)/
