### ISSUE TITLE
Unimplemented Opcode (FF) 64 88 07 BD A4 15 57 65

### ISSUE THREAD

**Issue by DevikinD** [ptitSeb/box86#857]
Without dynarec
`31673|0x6a9c246: Unimplemented Opcode (FF) 64 88 07 BD A4 15 57 65`

With dynarec
`2345|0x110043: Unimplemented Opcode (6E) 65 20 62 75 69 6C 74 69`

**Comment by ptitSeb** [comment]
I have added those 2 opcodes to box86. You can update and try again.
