### ISSUE TITLE
Wrap OpenSLES functions

### ISSUE THREAD

**Issue by kawanakaiku** [ptitSeb/box86#879]
I tried to create a wrapper for ```OpenSLES```, but couldn't figure out how to wrap functions inside a struct such as ```SLObjectItf_->RegisterCallback```. 
Is it possible to wrap this library?

The functions can be found at this link: [OpenSLES.h](https://android.googlesource.com/platform/system/media/+/gingerbread/opensles/include/SLES/OpenSLES.h).

**Comment by ptitSeb** [comment]
Yeah, that API is not that simple, bacause that structure `SLObjectItf_` (or `SLObjectItf` taht is a pointer to that structure). Needs special care, as all the filed needs some callback function.

It's a complex task, wrapping this libs. I suggest you take a look at `wrappedpulse.c` nad some of the simpler one, like `wrappedlzma.c` and `wrappedxml2.c` to have a better idea of what wrapping that structure might means.

**Comment by kawanakaiku** [comment]
Thank you for giving examples. They look very complicated, but I will try that when I have time.
