### ISSUE TITLE
libncurses5:armhf doesnt work on my side..

### ISSUE THREAD

**Issue by DarkevilPT** [ptitSeb/box86#880]
Probably its because of openfyde sand boxing maybe its just me... idk about others but if others can then this can be deleted... this libncurses5:armhf fails to be found to be installed which .. stops the script. (its probably just on me).

**Comment by ptitSeb** [comment]
So, you are talking about `insteall_steam.sh` script?

**Comment by DarkevilPT** [comment]
> So, you are talking about `insteall_steam.sh` script?

Yes box86 install_steam.sh

**Comment by ptitSeb** [comment]
and `libncurses5:armhf` failed as "not found"? You are using Debian containerized in openfyde? What debian version is it?

**Comment by DarkevilPT** [comment]
> and `libncurses5:armhf` failed as "not found"? You are using Debian containerized in openfyde? What debian version is it?

![image](https://github.com/ptitSeb/box86/assets/3583885/1eba4806-6256-47d4-bf0b-daadd12f3c95)
![image](https://github.com/ptitSeb/box86/assets/3583885/1796e442-b896-4ed9-a041-6684aabceab5)

With both distros within LXC containers none finds it. I wonder if on a regular ubuntu it does..

**Comment by ptitSeb** [comment]
I have removed the libncurses5 and put an extra install line for it, so it's ok if it fails.
The ticket can be closed now I think.
