### ISSUE TITLE
Not reading ELF header correctly on PowerPC?

### ISSUE THREAD

**Issue by MightyAlex200** [ptitSeb/box86#883]
I'm trying to use box86 to run i386 Linux programs on my Wii U (which has a 32 bit PPC processor). I have my Wii U running Debian Sid, and box86 compiles and runs just fine, but when I try to use it to run an i386 program, it shoots out this:
```
Not an Executable (768)
```
That error message comes from here, where it tries to read the ELF header of the executable:
https://github.com/ptitSeb/box86/blob/0d64ab09bb2c0508d3080dc4281fb1b3ff697046/src/elfs/elfparser.c#L94-L97
If I try commenting out the check, it stops on the next check, then the next, etc.

This happened with the executable I was originally trying to run, but it also errors out at the same point when I try running other executables. 
Here is a zip file containing the i386 `ls` binary from Debian Stable coreutils, so you can hopefully replicate this if you have a 32 bit PPC system. [ls.zip](https://github.com/ptitSeb/box86/files/13260101/ls.zip)

**Comment by ptitSeb** [comment]
Box86 needs a Little Endian system to function properly. I'm pretty sure th Wii U PPC is BigEndian.

**Comment by MightyAlex200** [comment]
Ah, didn't realize it had to be LE. No workaround then?

**Comment by ptitSeb** [comment]
No, no workaround because of the base concept on box86 that is the wrapping of libraries. The core idea behind box86 is to call native function instead of emulating everything. So having BE support would mean needing to wrap each starture and everything in every call.

Sorry, but that's not box86 use case.

**Comment by MightyAlex200** [comment]
Alright, makes sense! Thanks for the quick response :)

**Comment by Fancy2209** [comment]
> No, no workaround because of the base concept on box86 that is the wrapping of libraries. The core idea behind box86 is to call native function instead of emulating everything. So having BE support would mean needing to wrap each starture and everything in every call.
> 
> Sorry, but that's not box86 use case.

Would it be impossible to implement something like the syscall translator the QEMU Userspace Emulator uses to circumvent this issue?

**Comment by ptitSeb** [comment]
> > No, no workaround because of the base concept on box86 that is the wrapping of libraries. The core idea behind box86 is to call native function instead of emulating everything. So having BE support would mean needing to wrap each starture and everything in every call.
> > Sorry, but that's not box86 use case.
> 
> So implement something like the syscall translator the QEMU Userspace Emulator uses to circumvent this issue is out of the projects scope?

Box86 also tranlate syscall, and that's not the root of the issue. Box86 cannot work on different endianness architecture than the one being emulated. There are too many shortcut around that (that make box86 fast).
