### ISSUE TITLE
How can I use x86 .deb file with box86?

### ISSUE THREAD

**Issue by sruafly425** [ptitSeb/box86#89]
I can use x86 binaries well with boxx86(That's awesome!). But when I install x86 .deb file(like x86 wine) dependency error occur. How can I correct these error and execute binary file well?

**Comment by ptitSeb** [comment]
To have x86 dependancies automatically installed, you need to have some x86 repo in you apt list. While it should be, in theory, possible, I'm unsure what could be a practical way to achieve that. I did some experimentation and it didn't work, but I'm not a debian expert.

Also, note that, for now, Wine is not supported in box86. I plan to work on that at some point, but there are a few (important) things to do to get it to start...

**Comment by RussianNeuroMancer** [comment]
> I plan to work on that at some point

You mean integration of [WINE Hangover](https://github.com/AndreRH/hangover) into box86 or something new?

**Comment by ptitSeb** [comment]
Something new probably.

**Comment by Maccraft123** [comment]
I have my laptop set up so it can run seamlessly
Run dpkg --add-architecture i386
Then add i386 to sources.list and do apt update.
With binfmt configured for box86 you can now run any x86 program downloaded from repos.

**Comment by ptitSeb** [comment]
Wine can be used now, but not the deb pacakge, just grab some prebuilt tgz, there are plenty of them.
