### ISSUE TITLE
Compile error on Pandora

### ISSUE THREAD

**Issue by farox1** [ptitSeb/box86#90]
Hi
i have an error compiling box86 directly on Pandora.
Seems related to latest libc changes.

`[ 45%] Building C object CMakeFiles/box86.dir/src/wrapped/wrappedlibc.c.o
/media/toshi32/code/box86-dynarec/src/wrapped/wrappedlibc.c: In function ���my_prlimit64���:
/media/toshi32/code/box86-dynarec/src/wrapped/wrappedlibc.c:1339:13: error: ���__NR_prlimit64��� undeclared (first use in this function); did you mean ���my_prlimit64���?
     syscall(__NR_prlimit64, pid, res, new_rlim, old_rlim);
             ^~~~~~~~~~~~~~
             my_prlimit64
/media/toshi32/code/box86-dynarec/src/wrapped/wrappedlibc.c:1339:13: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/box86.dir/build.make:622: CMakeFiles/box86.dir/src/wrapped/wrappedlibc.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/box86.dir/all] Error 2
make: *** [Makefile:141: all] Error 2`

Thanks

**Comment by ptitSeb** [comment]
Should be fixed, but I let you check and close the issue if it's ok (or put the next error if there are still some).

**Comment by farox1** [comment]
Yes it's fixed. Thanks
