### ISSUE TITLE
Error initializing native libXpm.so.4 (and libtinfo.so.5)

### ISSUE THREAD

**Issue by iamcxds** [ptitSeb/box86#913]
When I try to run a game with x86
```
Box86 with Dynarec v0.3.4 f1912283 built on Dec 17 2023 01:03:33
Error initializing native libXpm.so.4 (last dlerror is libXpm.so.4: cannot open shared object file: No such file or directory)
Error initializing native libtinfo.so.5 (last dlerror is libtinfo.so.5: cannot open shared object file: No such file or directory)

```
But I actually installed everything. After checking the library file, I found `libXpm.so.4` is a symbolic link to `libXpm.so.4.11.0` (similar for `libtinfo.so.5`). I don't know if that caused the problem.

**Comment by ptitSeb** [comment]
This is box86, so the libs have to be the 32bits version.

**Comment by iamcxds** [comment]
I solved the problem, by `apt-get install libxpm4:armhf`, by reinstalling libs in 32bits.
