### ISSUE TITLE
Compile error on Pi5

### ISSUE THREAD

**Issue by yi-yunseok** [ptitSeb/box86#918]
Both of `-DRPI4ARM64=1` and `-DARM64=1`,

`No rule to make target '/box86/src/dynarec/arm_printer.c', needed by 'CMakeFiles/dynarec_arm.dir/src/dynarec/arm_printer.c.o'. Stop.
[CMakeFiles/Makefile2:154: CMakefiles/dynarec_arm_dir/all] error 2`

**Comment by ptitSeb** [comment]
That file `src/dynarec/arm_printer.c` is part of box86 repo, I suspect your clone is damaged, try to re-clone or check for missing files.

**Comment by rajdakin** [comment]
I don't think the issue is with the cloning (`/box86` is a suspicious path). What I suspect is that your repo is in a weird place that makes cmake not work. Where did you clone the repo (the output of `pwd`)?

**Comment by yi-yunseok** [comment]
It seems there was a problem with the disk during cloning.

Don't mind!
