### ISSUE TITLE
Segmentation fault on Pi5

### ISSUE THREAD

**Issue by yi-yunseok** [ptitSeb/box86#919]
Finished compile and install but I can't run Box86. Terminal shows `Segmentation fault`. Any help?

**Comment by ptitSeb** [comment]
You'll need to put more logs. Also, are you on 16K or 4K pagesize?

**Comment by yi-yunseok** [comment]
16k, where is the log?

**Comment by ptitSeb** [comment]
Box86 does not support non 4K pagesize for now.

**Comment by yi-yunseok** [comment]
Okay, thanks!
