### ISSUE TITLE
Just cause 2 won't launch

### ISSUE THREAD

**Issue by hisham2630** [ptitSeb/box86#922]
Hello when i try to launch just cause 2 its just won't launch there's no error dialog from the game.

```
0x3f0004d112: Dynarec stopped because of Opcode 48 0F AE A9 C0 00 00 00 4C 89 D8 8B 91 94 00
0x3f0004d027: Dynarec stopped because of Opcode 48 0F C7 A1 C0 00 00 00 EB 12 48 0F AE A1 C0 ( => /data/data/com.termux/files/usr/glibc/wine-ge-custom-8-25/bin/../lib64/wine/x86_64-unix/ntdll.so:__wine_syscall_dispatcher_prolog_end + 166)
0x3f0004d065: Dynarec stopped because of Opcode F3 48 0F AE D6 EB 13 BF 02 10 00 00 B8 9E 00 ( => /data/data/com.termux/files/usr/glibc/wine-ge-custom-8-25/bin/../lib64/wine/x86_64-unix/ntdll.so:__wine_syscall_dispatcher_prolog_end + 228)
0x3f0004d112: Dynarec stopped because of Opcode 48 0F AE A9 C0 00 00 00 4C 89 D8 8B 91 94 00


0x1003c516: Dynarec stopped @ dynarec0F0 (/data/data/com.termux/files/home/box86-master/src/dynarec/dynarec_arm_0f.c:2773) because of Opcode 0F 01 D0 89 45 EC 89 55 F0 8B 45 EC 8B 4D F0
0x41123e: Dynarec stopped @ dynarec0F0 (/data/data/com.termux/files/home/box86-master/src/dynarec/dynarec_arm_0f.c:2773) because of Opcode 0F 01 D0 89 45 EC 89 55 F0 8B 45 EC 8B 4D F0

0164:err:module:LdrInitializeThunk "steam_api.dll" failed to initialize, aborting
0164:err:module:LdrInitializeThunk Initializing dlls for L"D:\\Games\\Just Cause 2\\JustCause2.exe" failed, status c0000142


```

**Comment by ptitSeb** [comment]
Was it running before or did it just never worked?

**Comment by hisham2630** [comment]
> Was it running before or did it just never worked?

was working before

**Comment by hisham2630** [comment]
can you add missing opcodes

**Comment by ptitSeb** [comment]
> can you add missing opcodes

That's not the source of the issue. Those looks like opcodes not executed anyway. Also also, this is 64bits and box64 (look at the address of the missing opcodes).

**Comment by hisham2630** [comment]
> > can you add missing opcodes
> 
> That's not the source of the issue. Those looks like opcodes not executed anyway. Also also, this is 64bits and box64 (look at the address of the missing opcodes).

![Screenshot_2024-01-18-10-18-55-084_com termux](https://github.com/ptitSeb/box86/assets/35382590/2d6fdf8a-ecd4-4c4a-9a27-c03ab55d00e4)

**Comment by ptitSeb** [comment]
That doesn't change the fact that the missing dynarec opcodes are from a 64bits process (wine stuffs).

To go back to Just Cause 2, can you do gi bisect to find what box86 commit broke it?

**Comment by hisham2630** [comment]
> That doesn't change the fact that the missing dynarec opcodes are from a 64bits process (wine stuffs).
> 
> To go back to Just Cause 2, can you do gi bisect to find what box86 commit broke it?

sorry game was not working due to corrupted steam_api.dll file
i reinstalled the game and it worked, but there's some flickering and some other graphics glitches it's maybe the turnip driver problem
anyway thanks, you can close the issues.


are you interested in add support to another games
like when game won't open or work i just share the logs and opcodes?

**Comment by ptitSeb** [comment]
> 
> are you interested in add support to another games like when game won't open or work i just share the logs and opcodes?

Yes, but the missing Dynarec opcode are not usefull for fix issue. They are usefull only for optimizing speed for something that works.
To make good report, try put as much info as possible, using LOG=1, ROLLING_LOG=1 maybe, SHOWBT=1 and SHOWSEGV=1.
