### ISSUE TITLE
What about Oddworld new'n tasty ?

### ISSUE THREAD

**Issue by enderhobrine** [ptitSeb/box86#95]
Hi, I am about to buy the remake of Abe's Odyssey (Oddworld new'n tasty), but I don't know if it works on the pi. I bought several games on GOG like Undertale and they all ran on my pi, but I prefer not taking any risks...

**Comment by ptitSeb** [comment]
Oddworld new'n tasty is not really working for now. It's a Unity game, so it will probably be supported at some point, but not yet: it starts but eventually crashes.

**Comment by enderhobrine** [comment]
It crashes even with minimal resolution ?

**Comment by ptitSeb** [comment]
I don't know. I have done minimal test on this game, and haven't tried any debugging yet...

**Comment by enderhobrine** [comment]
Ok, I'll buy it and tell you. Thanks !

**Comment by Askmewho** [comment]
The game start, slowly, and it crash.. I had only successfully tested one mono based game, clarc. It will need more time even if it works later (we don't know if the shader model/opengl requirements will be meet on opengl 2.1)

**Comment by enderhobrine** [comment]
Ow, ok. So what about The Witcher II ? I really need a game to play during this period... If the pi can't run The Witcher II, do you know good games that it can run ?

**Comment by ptitSeb** [comment]
Nope, The Witcher II doesn't work for now (it use some custom wine wrapper that doesn't work in box86 for now).

You can play The Bard's Tale (https://www.gog.com/game/the_bards_tale or https://www.humblebundle.com/store/the-bards-tale ) that is currently running fine (look here: https://youtu.be/5U-mGExcUsI?t=1764 )

**Comment by enderhobrine** [comment]
I saw the video and I think I'll buy hyper light drifter. Also, I didn't see any video of terraria running on pi, but with box86 I think it can run ?

**Comment by ptitSeb** [comment]
Nope, not for now, there are some issue with terraria. I think PILab will do a video when it's eventually working. But for now, it crashes at load with box86.

**Comment by enderhobrine** [comment]
Uhhh ok.
