### ISSUE TITLE
Wine cannot create window

### ISSUE THREAD

**Issue by 1640675651** [ptitSeb/box86#985]
System: Raspberry Pi 3b, Raspberry Pi OS bookworm 64bit.
Installed box86, box64 and wine. 
wine explorer gives:
```
Box86 with Dynarec v0.3.7 c5bccdf3 built on Jul 27 2024 15:58:43
Error: Symbol __shmctl64 not found, cannot apply R_386_JMP_SLOT 0x60874218 (0x7896) in /home/zhz/wine/lib/wine/i386-unix/winex11.so
Error: relocating Plt symbols in elf winex11.so
00fc:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00fc:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
```

But wine64 explorer works fine. Tried wine-stable-9.0.0.0, wine-stable-8.0.2 and wine-devel-7.2.2. Same behavior.

**Comment by ptitSeb** [comment]
You should grab wine binary from some build CI, like krone4lk or PlayOnLinux...
I'll check to add that symbol, but I'm pretty sure there will be many other after this one.

**Comment by ptitSeb** [comment]
Function added.

**Comment by 1640675651** [comment]
Confirm Kron4ek's version worked. Thank you.
