### ISSUE TITLE
Hotline Miami crash

### ISSUE THREAD

**Issue by enderhobrine** [ptitSeb/box86#99]
Hey, Hotline Miami runs very well on latest box86, but while I was playing, the game suddently crashed at about 1h-1h30 of non-stop playing. Do you think it's a box86 issue or it's just that the cpu was overactive ?

**Comment by ptitSeb** [comment]
I hope you had a save not far before the crash...
I you can replay and go past the point of previous crash, than it could be the Pi overheating or some memory leak in box86 or Hotline miami (or the mesa?).

If it crash at the same point, then it's probably a box86 bug.

**Comment by enderhobrine** [comment]
It didn't crash, I guess my pi was overheating, but I have a active cooling...

**Comment by enderhobrine** [comment]
So the game doesn't crash anymore, I consider the problem solved. Can't wait to see steam working on the pi !
