### ISSUE TITLE
Infinite Loop on SteamCMD Checking for Update.

### ISSUE THREAD

**Issue by redkwind** [ptitSeb/box86#990]
**Hardware:** Orange Pi 5  and Orange Pi 5 B
**OS:** Ubuntu 24.04 LTS Desktop ([Joshua's](https://github.com/Joshua-Riek/ubuntu-rockchip/releases))
**SteamCMD:** From this [link]( https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz)

Description:
After installing from prebuilts or compiling box86 and box64 myself, i downloaded steamcmd to a folder.
When running it for the first time i get the following output and gets stuck at 0% forever. I left it running overnight but didn't help.
It doesn't give me any error or anything to go by.
The steam logs don't show anything either other than the same output from console.

>  red@red-desktop:~/steamcmd$ box86 ./steamcmd.sh
> Box86 with Dynarec v0.3.7 9811f140 built on Aug  6 2024 14:04:49
> Error: reading elf header of /home/red/steamcmd/steamcmd.sh, trying to launch natively instead
> Box86 with Dynarec v0.3.7 9811f140 built on Aug  6 2024 14:04:49
> Redirecting stderr to '/home/red/Steam/logs/stderr.txt'
> ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
> [  0%] Checking for available update...

(As a side note... it works with FEXEmu so im guessing the issue is with box then?)

**Comment by Cannibaal** [comment]
so i got the same loop happening but for me is both on box and FEX, do you have any ideas on how to solve this?
