### ISSUE TITLE
[Question] Error occurred while installing steam on KylinOS showing __dprintf_chk not found

### ISSUE THREAD

**Issue by rong-xiaoli** [ptitSeb/box86#991]
安装Box86和Box64都还好，没报错。但是双击steam桌面图标的时候，有个弹窗要我装些deb包。
我在Kali上装过steam，在上面关闭这个弹窗是没有影响的，所以我估计安装这些包没必要、
然后有个弹窗高所我缺失`libc.so.6`。
所以我就按照这篇：
https://github.com/ptitSeb/box86/blob/9811f140ce8faa5f12fc224afb5eda39cde85a09/docs/README_CN.md?plain=1#L100
编辑了`.bashrc`，添加了两行：
```plain text
export STEAMOS=1
export STEAM_RUNTIME=1
```
在注销然后重启之后，我开了个命令行然后执行了`steam`，过程一样，还是提示安装deb包，缺少库文件`libc.so.6`。
我想问有没有什么地方我做错了或者之类的，以及我如何修正。
感谢帮助！

home-made translation below: 
Installation of both Box86 and Box64 are fine, no errors have been found. But as I double click the steam icon, a pop up window shows that I should install some packages. 
I guess it isn't needed so I closed that window, as I've installed steam on Kali, closing that pop up window have no affection on running steam. 
And another pop up window says that missing library `libc.so.6`. 
Accroding to this tutorial: 

https://github.com/ptitSeb/box86/blob/9811f140ce8faa5f12fc224afb5eda39cde85a09/docs/README_CN.md?plain=1#L100

So I edited `.bashrc`, added 
```plain text
export STEAMOS=1
export STEAM_RUNTIME=1
```
After logging out and loggin in, I start a shell and executed `steam`. The same process and the same pop up saying no `libc.so.6` found. 
I would like to ask if there is anything wrong in my operation, and how to fix it. 
Thanks for help! 

Edit: forgot to post log. Here it is:
```plain text
steam.sh[13212]: Running Steam on kylin V10 64-bit
steam.sh[13212]: STEAM_RUNTIME is enabled by the user
setup.sh[13278]: Steam runtime environment up-to-date!
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 PageSize:4096 Running on Unknown CPU with 8 Cores
Will use Hardware counter measured at 48.0 MHz emulating 3.0 GHz
Params database has 87 entries
Box64 with Dynarec v0.3.1 2a076366 built on Aug 10 2024 14:29:04
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 77 Env var
BOX64 LIB PATH: /home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/:/lib/aarch64-linux-gnu/:/usr/lib/aarch64-linux-gnu/libfakeroot/:/usr/lib/kysdk/kysdk-base/:/usr/libs/kysdk/applications/:/usr/local/lib/:/lib/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/lib/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/:./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/bin/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/:/home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/usr/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/
Looking for /home/[USER]/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger
argv[1]="--exec-fallback"
argv[2]="--filename=console-linux.txt"
argv[3]="-t"
argv[4]="steam"
Rename process to "srt-logger"
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
steam.sh[13212]: Steam client's requirements are satisfied
Box86 with Dynarec v0.2.3 162e0a1a built on Nov  9 2021 09:46:09
Error: PltReolver: Symbol __dprintf_chk(ver 26: __dprintf_chk@GLIBC_2.8) not found, cannot apply R_386_JMP_SLOT 0xf7785b48 (0xf70e8316) in /home/[USER]/.local/share/Steam/ubuntu12_32/steam
```

**Comment by ptitSeb** [comment]
You realise your box86 is super old: `Box86 with Dynarec v0.2.3 162e0a1a built on Nov  9 2021 09:46:09`. You are missing more than 3 years of developpement! Update box86 first.

**Comment by rong-xiaoli** [comment]
> You realise your box86 is super old: `Box86 with Dynarec v0.2.3 162e0a1a built on Nov 9 2021 09:46:09`. You are missing more than 3 years of developpement! Update box86 first.

Wow so it's the version's fault. Thanks! I'll try fix it soon.

**Comment by rong-xiaoli** [comment]
May I ask what method should I use to update Box86? I installed it by directly clone the master branch and followed this: 
https://github.com/kamehame-ha/steamcmd-on-arm64/blob/a19a56e7ab44633bec842990b7f51e98c6f224ed/README.md?plain=1#L26-L45

**Comment by ptitSeb** [comment]
cd to the "build" folder then do
```bash
git pull
make -j3
sudo make install
```
And it should update.
Check also box64 if it needs update, as it's needed for steam to work.

**Comment by rong-xiaoli** [comment]
> cd to the "build" folder then do
> 
> ```shell
> git pull
> make -j3
> sudo make install
> ```
> 
> And it should update. Check also box64 if it needs update, as it's needed for steam to work.

I've done `git pull` today at about 1 pm and I've double-checked that the repo on my computer is newest. 
![image](https://github.com/user-attachments/assets/6aedeb64-f9c4-4065-ab76-b1d51f75e4b0)
The `已经是最新的` means already the newest in Chinese. 

Sorry for troubling you for such a long time, and thank you again for helping me.

**Comment by ptitSeb** [comment]
and you did the the other 2 commands? what `box86 --version` gives you?

also, also, from the box86 folder, do `cat .git/config` to be sure it's a clone from upstream and not some outdated fork.

**Comment by rong-xiaoli** [comment]
> and you did the the other 2 commands? 

I did again that 2 commands. 
still, 
![image](https://github.com/user-attachments/assets/97e8c57c-bb31-4bf2-885f-8ed80f71aa24)
and for sure, I ran `git log -1`
and I got this:
![image](https://github.com/user-attachments/assets/300fa7be-0a8c-4bbc-84bd-340b18b190be)


> what box86 --version gives you?

This command gave me this: 
![image](https://github.com/user-attachments/assets/e83e6526-e782-498d-b828-d4eecfd31d08)

**Comment by ptitSeb** [comment]
Ah, so you have 2 version of box86 on your system it seems. You have a very old copy  along with the latest version. You should search for that old copy to delete it...

**Comment by rong-xiaoli** [comment]
Okay, so I guess I need to locate the box86 by `whereis box86`?

**Comment by ptitSeb** [comment]
yeah, the one from whereis is the one found when just running `box86` wich is the latest version.
do `export` to see what BOX64 / BOX86 environement variable you have. The box86 you are looking for might be in the same foler as `box64`, wich might not be in `/usr/local/bin`

**Comment by rong-xiaoli** [comment]
OK. I ran this command: `env | grep BOX`, and I got nothing. 
Runing `env` alone got this:
![image](https://github.com/user-attachments/assets/7acdcc99-cd10-469e-8d43-0e9283107d77)
![image](https://github.com/user-attachments/assets/6e915e0a-e772-45a0-a79e-fadcf01e7586)

**Comment by ptitSeb** [comment]
From box86 folder, try to do `../tests/test01` to see what box86 is triggered.

**Comment by rong-xiaoli** [comment]
You mean the source code part?
It ran this: 
![image](https://github.com/user-attachments/assets/b4d4405e-92c4-406e-b3dd-18072536f616)

**Comment by ptitSeb** [comment]
Maybe you should just restart the binfmt integration, with `sudo systemctl restart systemd-binfmt` (as described in COMPILE.md)

**Comment by rong-xiaoli** [comment]
> Maybe you should just restart the binfmt integration, with `sudo systemctl restart systemd-binfmt` (as described in COMPILE.md)

OK thanks. I'll try on Monday UTC+8.

**Comment by rong-xiaoli** [comment]
Close this issue as done.
