### ISSUE TITLE
Segmentation fault  while launching Valheim Server + BepinEX

### ISSUE THREAD

**Issue by redkwind** [ptitSeb/box86#992]
I was trying to launch a modded Valheim server and i keep getting segmentation fault errors.
I have successfully managed to run the server without any mods and it works fine, however if i try to use the ./start_server_bepinex.sh  method i get a segmentation fault and maybe a core dump wich i have no idea where to find or how to read.

Hardware: Orange Pi 5B  16GB  256 emmc
OS: Ubuntu 24.04 Desktop 2.3.0  ([Joshua's](https://github.com/Joshua-Riek/ubuntu-rockchip/releases))

> red@red-desktop:~/valheimserver$ ./start_server_bepinex.sh
> Starting server PRESS CTRL-C to exit
> ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libdoorstop_x64.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
>  PageSize:4096 Running on - - - - - - - - - - - - - - - - with 8 Cores
> Will use Hardware counter measured at 24.0 MHz emulating 3.0 GHz
> Params database has 87 entries
> Box64 with Dynarec v0.3.1 2a076366 built on Aug 10 2024 06:20:06
> BOX64: Detected 48bits at least of address space
> Counted 33 Env var
> BOX64 trying to Preload libdoorstop_x64.so
> BOX64 LIB PATH: ./linux64/:./doorstop_libs/:./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
> BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/
> Looking for ./valheim_server.x86_64
> argv[1]="-name"
> argv[2]="My server"
> argv[3]="-port"
> argv[4]="2456"
> argv[5]="-world"
> argv[6]="Dedicated"
> argv[7]="-password"
> argv[8]="secret"
> Rename process to "valheim_server.x86_64"
> Using emulated ./doorstop_libs/libdoorstop_x64.so
> Using native(wrapped) libc.so.6
> Using native(wrapped) ld-linux-x86-64.so.2
> Using native(wrapped) libpthread.so.0
> Using native(wrapped) libdl.so.2
> Using native(wrapped) libutil.so.1
> Using native(wrapped) librt.so.1
> Using native(wrapped) libbsd.so.0
> Using emulated UnityPlayer.so
> Using native(wrapped) libm.so.6
> Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
> Found UnityPlayer, hooking into it instead
> 13980|SIGSEGV @0xffffad943ca4 (???(0xffffad943ca4)) (x64pc=0x7fff00003fd7/"./doorstop_libs/libdoorstop_x64.so/check_rel + 0x24", rsp=0xffffae46f090, stack=0xffffadc70000:0xffffae470000 own=(nil) fp=0xffffae46f180), for accessing 0x159128 (code=1/prot=0), db=0xffffadb4f7f8(0xffffad943c80:0xffffad943e80/0x7fff00003fb3:0x7fff0000408b/./doorstop_libs/libdoorstop_x64.so/check_rel:clean, hash:23d9e017/23d9e017) handler=(nil)
> RAX:0x0000000000159120 RCX:0x0000ffffae46f160 RDX:0x0000000000000007 RBX:0x0000000000000000
> RSP:0x0000ffffae46f090 RBP:0x0000ffffae46f0d0 RSI:0x0000000000159120 RDI:0x00000000483a4e80
>  R8:0x0000ffffae46f168  R9:0x0000000000000000 R10:0x0000000000000000 R11:0x0000000000000000
> R12:0x0000000000000000 R13:0x0000000000000000 R14:0x0000000000000000 R15:0x0000000000000000
> ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053
> RSP-0x20:0x0000000000000000 RSP-0x18:0x0000000000000000 RSP-0x10:0x0000000000000000 RSP-0x08:0x0000000000000000
> RSP+0x00:0x0000000000000000 RSP+0x08:0x0000ffffae46f168 RSP+0x10:0x0000ffffae46f160 RSP+0x18:0x0000000000000007
> Segmentation fault (core dumped)

**Comment by ptitSeb** [comment]
Pretty sure this ticket should be in box64 repo and not here. Also, there is already a ticket (at least) on that subject on box64 repo, please check there.

**Comment by redkwind** [comment]
> Pretty sure this ticket should be in box64 repo and not here. Also, there is already a ticket (at least) on that subject on box64 repo, please check there.

will do, thank you.
